import type { Commodity } from '../../../shared/src/types/world'

// ============================================================================
// Commodités (biens échangeables) — An 1000
// ============================================================================
// baseValue : valeur relative (1 = valeur d'un boisseau de blé)
// weight    : poids relatif (1 = léger/facile à transporter, 10 = lourd/encombrant)
// ============================================================================

export const commodities: Commodity[] = [
	// --- Nourriture ---
	{
		id: 'com_wheat',
		name: 'Blé',
		category: 'food',
		baseValue: 1,
		weight: 5,
		perishable: true,
	},
	{
		id: 'com_rice',
		name: 'Riz',
		category: 'food',
		baseValue: 1.2,
		weight: 5,
		perishable: true,
	},
	{
		id: 'com_millet',
		name: 'Millet',
		category: 'food',
		baseValue: 0.8,
		weight: 5,
		perishable: true,
	},
	{
		id: 'com_barley',
		name: 'Orge',
		category: 'food',
		baseValue: 0.9,
		weight: 5,
		perishable: true,
	},
	{
		id: 'com_maize',
		name: 'Maïs',
		category: 'food',
		baseValue: 1,
		weight: 5,
		perishable: true,
	},
	{
		id: 'com_fish',
		name: 'Poisson',
		category: 'food',
		baseValue: 1.5,
		weight: 4,
		perishable: true,
	},
	{
		id: 'com_dried_fish',
		name: 'Poisson séché',
		category: 'food',
		baseValue: 3,
		weight: 2,
		perishable: false,
	},
	{
		id: 'com_salt',
		name: 'Sel',
		category: 'food',
		baseValue: 8,
		weight: 6,
		perishable: false,
	},
	{
		id: 'com_olive_oil',
		name: "Huile d'olive",
		category: 'food',
		baseValue: 5,
		weight: 7,
		perishable: false,
	},
	{
		id: 'com_wine',
		name: 'Vin',
		category: 'food',
		baseValue: 6,
		weight: 8,
		perishable: false,
	},
	{
		id: 'com_dates',
		name: 'Dattes',
		category: 'food',
		baseValue: 3,
		weight: 3,
		perishable: true,
	},
	{
		id: 'com_honey',
		name: 'Miel',
		category: 'food',
		baseValue: 7,
		weight: 6,
		perishable: false,
	},
	{
		id: 'com_tea',
		name: 'Thé',
		category: 'food',
		baseValue: 15,
		weight: 1,
		perishable: false,
	},

	// --- Bétail ---
	{
		id: 'com_cattle',
		name: 'Bœuf / Bétail',
		category: 'livestock',
		baseValue: 20,
		weight: 10,
		perishable: false,
	},
	{
		id: 'com_horses',
		name: 'Chevaux',
		category: 'livestock',
		baseValue: 50,
		weight: 10,
		perishable: false,
	},
	{
		id: 'com_sheep',
		name: 'Moutons',
		category: 'livestock',
		baseValue: 8,
		weight: 6,
		perishable: false,
	},
	{
		id: 'com_camels',
		name: 'Chameaux',
		category: 'livestock',
		baseValue: 40,
		weight: 10,
		perishable: false,
	},

	// --- Matières premières ---
	{
		id: 'com_iron_ore',
		name: 'Minerai de fer',
		category: 'raw_material',
		baseValue: 4,
		weight: 9,
		perishable: false,
	},
	{
		id: 'com_copper_ore',
		name: 'Minerai de cuivre',
		category: 'raw_material',
		baseValue: 5,
		weight: 9,
		perishable: false,
	},
	{
		id: 'com_tin',
		name: 'Étain',
		category: 'raw_material',
		baseValue: 7,
		weight: 8,
		perishable: false,
	},
	{
		id: 'com_timber',
		name: "Bois d'œuvre",
		category: 'raw_material',
		baseValue: 3,
		weight: 10,
		perishable: false,
	},
	{
		id: 'com_stone',
		name: 'Pierre de taille',
		category: 'raw_material',
		baseValue: 2,
		weight: 10,
		perishable: false,
	},
	{
		id: 'com_cotton',
		name: 'Coton brut',
		category: 'raw_material',
		baseValue: 6,
		weight: 3,
		perishable: false,
	},
	{
		id: 'com_wool',
		name: 'Laine',
		category: 'raw_material',
		baseValue: 5,
		weight: 3,
		perishable: false,
	},
	{
		id: 'com_leather',
		name: 'Cuir',
		category: 'raw_material',
		baseValue: 6,
		weight: 4,
		perishable: false,
	},
	{
		id: 'com_clay',
		name: 'Argile',
		category: 'raw_material',
		baseValue: 1,
		weight: 8,
		perishable: false,
	},
	{
		id: 'com_furs',
		name: 'Fourrures',
		category: 'raw_material',
		baseValue: 15,
		weight: 2,
		perishable: false,
	},

	// --- Biens de luxe ---
	{
		id: 'com_gold',
		name: 'Or',
		category: 'luxury',
		baseValue: 500,
		weight: 8,
		perishable: false,
	},
	{
		id: 'com_silver',
		name: 'Argent (métal)',
		category: 'luxury',
		baseValue: 100,
		weight: 7,
		perishable: false,
	},
	{
		id: 'com_gems',
		name: 'Pierres précieuses',
		category: 'luxury',
		baseValue: 300,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_silk',
		name: 'Soie',
		category: 'luxury',
		baseValue: 80,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_spices',
		name: 'Épices',
		category: 'luxury',
		baseValue: 60,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_incense',
		name: 'Encens et myrrhe',
		category: 'luxury',
		baseValue: 40,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_ivory',
		name: 'Ivoire',
		category: 'luxury',
		baseValue: 70,
		weight: 5,
		perishable: false,
	},
	{
		id: 'com_amber',
		name: 'Ambre',
		category: 'luxury',
		baseValue: 45,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_lapis_lazuli',
		name: 'Lapis-lazuli',
		category: 'luxury',
		baseValue: 55,
		weight: 2,
		perishable: false,
	},
	{
		id: 'com_pearls',
		name: 'Perles',
		category: 'luxury',
		baseValue: 120,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_dyes',
		name: 'Teintures (pourpre, indigo)',
		category: 'luxury',
		baseValue: 35,
		weight: 2,
		perishable: false,
	},

	// --- Biens manufacturés ---
	{
		id: 'com_weapons',
		name: 'Armes forgées',
		category: 'manufactured',
		baseValue: 25,
		weight: 7,
		perishable: false,
	},
	{
		id: 'com_armor',
		name: 'Armures',
		category: 'manufactured',
		baseValue: 40,
		weight: 8,
		perishable: false,
	},
	{
		id: 'com_textiles',
		name: 'Textiles (tissus)',
		category: 'manufactured',
		baseValue: 10,
		weight: 3,
		perishable: false,
	},
	{
		id: 'com_pottery_goods',
		name: 'Poterie et céramique',
		category: 'manufactured',
		baseValue: 5,
		weight: 6,
		perishable: false,
	},
	{
		id: 'com_porcelain',
		name: 'Porcelaine',
		category: 'manufactured',
		baseValue: 50,
		weight: 5,
		perishable: false,
	},
	{
		id: 'com_glass',
		name: 'Verrerie',
		category: 'manufactured',
		baseValue: 20,
		weight: 5,
		perishable: false,
	},
	{
		id: 'com_paper',
		name: 'Papier',
		category: 'manufactured',
		baseValue: 12,
		weight: 2,
		perishable: false,
	},
	{
		id: 'com_books',
		name: 'Livres et manuscrits',
		category: 'manufactured',
		baseValue: 100,
		weight: 3,
		perishable: false,
	},
	// --- Commodités additionnelles ---
	{
		id: 'com_coffee',
		name: 'Café',
		category: 'food',
		baseValue: 15,
		weight: 3,
		perishable: false,
	},
	{
		id: 'com_dried_salmon',
		name: 'Saumon séché',
		category: 'food',
		baseValue: 3,
		weight: 4,
		perishable: true,
	},
	{
		id: 'com_grain',
		name: 'Céréales (mélange)',
		category: 'food',
		baseValue: 1,
		weight: 5,
		perishable: true,
	},
	{
		id: 'com_livestock',
		name: 'Bétail vivant',
		category: 'food',
		baseValue: 8,
		weight: 10,
		perishable: false,
	},
	{
		id: 'com_palm_oil',
		name: 'Huile de palme',
		category: 'food',
		baseValue: 4,
		weight: 6,
		perishable: true,
	},
	{
		id: 'com_emeralds',
		name: 'Émeraudes',
		category: 'luxury',
		baseValue: 200,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_jewelry',
		name: 'Bijoux',
		category: 'luxury',
		baseValue: 120,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_obsidian',
		name: 'Obsidienne',
		category: 'raw',
		baseValue: 10,
		weight: 5,
		perishable: false,
	},
	{
		id: 'com_shells',
		name: 'Coquillages (monnaie)',
		category: 'luxury',
		baseValue: 5,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_slaves',
		name: 'Esclaves',
		category: 'raw',
		baseValue: 50,
		weight: 10,
		perishable: false,
	},
	{
		id: 'com_tropical_wood',
		name: 'Bois tropical',
		category: 'raw',
		baseValue: 8,
		weight: 8,
		perishable: false,
	},
	{
		id: 'com_turquoise',
		name: 'Turquoise',
		category: 'luxury',
		baseValue: 80,
		weight: 1,
		perishable: false,
	},
	{
		id: 'com_iron_goods',
		name: 'Articles en fer',
		category: 'manufactured',
		baseValue: 15,
		weight: 7,
		perishable: false,
	},
]
