import type { ConstructionRecipe } from '../../../shared/src/types/world'

export const constructionRecipes: ConstructionRecipe[] = [
	// ========================================================================
	// ROUTES
	// ========================================================================
	{
		id: 'recipe_dirt_road',
		type: 'road',
		tier: 'basic',
		name: 'Chemin de terre',
		description:
			'Piste aménagée par damage et débroussaillage, praticable par chariots en saison sèche.',
		requiredTechs: [],
		resourceCosts: [{ resource: 'wood', quantity: 5 }],
		laborForce: 20,
		durationMonths: 2,
		maintenanceCostPerYear: 2,
		minSocialClass: 'minor_noble',
		allowedTerrains: ['plain', 'steppe', 'hill', 'forest'],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'mountain'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 6,
		strategicValueOnComplete: 3,
		notes:
			"Les routes non pavées représentent l'essentiel du réseau routier médiéval.",
	},
	{
		id: 'recipe_paved_road',
		type: 'road',
		tier: 'improved',
		name: 'Route pavée',
		description:
			'Chaussée en pierre taillée avec fondations drainées, inspirée des techniques romaines.',
		requiredTechs: ['tech_road_building', 'tech_stone_masonry'],
		resourceCosts: [
			{ resource: 'stone', quantity: 30 },
			{ resource: 'wood', quantity: 5 },
		],
		laborForce: 80,
		durationMonths: 8,
		maintenanceCostPerYear: 5,
		minSocialClass: 'noble',
		allowedTerrains: ['plain', 'steppe', 'hill', 'coast'],
		forbiddenTerrains: [
			'ocean',
			'sea',
			'lake',
			'ice',
			'mountain',
			'swamp',
			'jungle',
		],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 7,
		notes:
			"Les voies romaines restent les meilleures routes d'Europe occidentale en l'an 1000.",
	},
	{
		id: 'recipe_imperial_highway',
		type: 'road',
		tier: 'advanced',
		name: 'Route impériale',
		description:
			"Grand axe routier avec relais, bornes milliaires et entretien organisé par l'État.",
		requiredTechs: [
			'tech_road_building',
			'tech_stone_masonry',
			'tech_bureaucracy',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 60 },
			{ resource: 'iron', quantity: 10 },
			{ resource: 'wood', quantity: 15 },
		],
		laborForce: 200,
		durationMonths: 18,
		maintenanceCostPerYear: 12,
		minSocialClass: 'noble',
		allowedTerrains: ['plain', 'steppe', 'hill'],
		forbiddenTerrains: [
			'ocean',
			'sea',
			'lake',
			'ice',
			'mountain',
			'swamp',
			'jungle',
			'desert',
		],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 10,
		strategicValueOnComplete: 9,
		notes:
			'Réseau type Tang, Byzantin ou Romain. Requiert une administration centralisée.',
	},

	// ========================================================================
	// PONTS
	// ========================================================================
	{
		id: 'recipe_wooden_bridge',
		type: 'bridge',
		tier: 'basic',
		name: 'Pont en bois',
		description:
			'Pont à poutres et pilotis en bois, courant pour franchir rivières et ruisseaux.',
		requiredTechs: ['tech_basic_construction'],
		resourceCosts: [{ resource: 'wood', quantity: 20 }],
		laborForce: 15,
		durationMonths: 3,
		maintenanceCostPerYear: 4,
		minSocialClass: 'minor_noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'ice'],
		requiresCoast: false,
		requiresRiver: true,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 5,
		notes:
			'Structure la plus répandue au Moyen Âge, vulnérable aux crues et au feu.',
	},
	{
		id: 'recipe_stone_bridge',
		type: 'bridge',
		tier: 'improved',
		name: 'Pont en pierre',
		description:
			'Pont à arches en pierre de taille avec culées maçonnées. Durable plusieurs siècles.',
		requiredTechs: [
			'tech_bridge_building',
			'tech_stone_masonry',
			'tech_arch_vault',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 50 },
			{ resource: 'wood', quantity: 10 },
			{ resource: 'iron', quantity: 5 },
		],
		laborForce: 60,
		durationMonths: 18,
		maintenanceCostPerYear: 3,
		minSocialClass: 'noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'ice'],
		requiresCoast: false,
		requiresRiver: true,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 8,
		notes:
			'Le Pont du Gard, le Ponte Vecchio — les ponts en pierre traversent les siècles.',
	},

	// ========================================================================
	// PORTS
	// ========================================================================
	{
		id: 'recipe_fishing_wharf',
		type: 'port',
		tier: 'basic',
		name: 'Débarcadère de pêche',
		description:
			"Quai rudimentaire en bois permettant l'accostage de barques et petits navires.",
		requiredTechs: ['tech_basic_construction'],
		resourceCosts: [
			{ resource: 'wood', quantity: 25 },
			{ resource: 'iron', quantity: 3 },
		],
		laborForce: 20,
		durationMonths: 4,
		maintenanceCostPerYear: 3,
		minSocialClass: 'merchant',
		allowedTerrains: ['coast'],
		forbiddenTerrains: [],
		requiresCoast: true,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 4,
		notes: "La plupart des villages côtiers disposent d'un simple débarcadère.",
	},
	{
		id: 'recipe_trade_port',
		type: 'port',
		tier: 'improved',
		name: 'Port de commerce',
		description:
			'Bassin protégé avec quais en pierre, entrepôts et grues à treuil.',
		requiredTechs: [
			'tech_basic_construction',
			'tech_stone_masonry',
			'tech_basic_trade',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 50 },
			{ resource: 'wood', quantity: 40 },
			{ resource: 'iron', quantity: 15 },
		],
		laborForce: 100,
		durationMonths: 18,
		maintenanceCostPerYear: 10,
		minSocialClass: 'noble',
		allowedTerrains: ['coast'],
		forbiddenTerrains: [],
		requiresCoast: true,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 8,
		strategicValueOnComplete: 8,
		notes:
			'Venise, Constantinople, Guangzhou — les grands ports sont moteurs du commerce mondial.',
	},
	{
		id: 'recipe_naval_port',
		type: 'port',
		tier: 'advanced',
		name: 'Arsenal naval',
		description:
			'Chantier naval fortifié avec cales sèches, ateliers de construction et docks militaires.',
		requiredTechs: [
			'tech_basic_construction',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_basic_sailing',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 80 },
			{ resource: 'wood', quantity: 60 },
			{ resource: 'iron', quantity: 30 },
		],
		laborForce: 200,
		durationMonths: 30,
		maintenanceCostPerYear: 20,
		minSocialClass: 'noble',
		allowedTerrains: ['coast'],
		forbiddenTerrains: [],
		requiresCoast: true,
		requiresRiver: false,
		minYear: 800,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 10,
		notes:
			"L'Arsenale di Venezia est la plus grande structure industrielle d'Europe médiévale.",
	},

	// ========================================================================
	// AQUEDUCS
	// ========================================================================
	{
		id: 'recipe_basic_aqueduct',
		type: 'aqueduct',
		tier: 'basic',
		name: "Canal d'adduction",
		description:
			"Canal ouvert en terre battue pour acheminer l'eau depuis une source proche.",
		requiredTechs: ['tech_irrigation'],
		resourceCosts: [
			{ resource: 'wood', quantity: 10 },
			{ resource: 'stone', quantity: 5 },
		],
		laborForce: 30,
		durationMonths: 4,
		maintenanceCostPerYear: 3,
		minSocialClass: 'minor_noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'desert'],
		requiresCoast: false,
		requiresRiver: true,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 6,
		strategicValueOnComplete: 5,
		notes:
			"Systèmes d'irrigation simples présents dans toutes les civilisations agraires.",
	},
	{
		id: 'recipe_stone_aqueduct',
		type: 'aqueduct',
		tier: 'improved',
		name: 'Aqueduc en pierre',
		description:
			"Aqueduc maçonné avec arches, capable de franchir vallées et de transporter l'eau sur de longues distances.",
		requiredTechs: ['tech_aqueduct', 'tech_stone_masonry', 'tech_arch_vault'],
		resourceCosts: [
			{ resource: 'stone', quantity: 80 },
			{ resource: 'wood', quantity: 15 },
			{ resource: 'iron', quantity: 5 },
		],
		laborForce: 120,
		durationMonths: 24,
		maintenanceCostPerYear: 6,
		minSocialClass: 'noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 8,
		notes:
			"Les aqueducs romains restent fonctionnels en l'an 1000 dans certaines régions.",
	},

	// ========================================================================
	// CANAUX
	// ========================================================================
	{
		id: 'recipe_irrigation_canal',
		type: 'canal',
		tier: 'basic',
		name: "Canal d'irrigation",
		description:
			"Fossé creusé et consolidé pour distribuer l'eau des rivières vers les champs.",
		requiredTechs: ['tech_irrigation'],
		resourceCosts: [{ resource: 'wood', quantity: 10 }],
		laborForce: 40,
		durationMonths: 4,
		maintenanceCostPerYear: 3,
		minSocialClass: 'minor_noble',
		allowedTerrains: ['plain', 'steppe'],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'mountain'],
		requiresCoast: false,
		requiresRiver: true,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 6,
		strategicValueOnComplete: 5,
		notes:
			'Les canaux du Nil, du Tigre-Euphrate et du Yangtsé nourrissent des millions de personnes.',
	},
	{
		id: 'recipe_navigation_canal',
		type: 'canal',
		tier: 'improved',
		name: 'Canal navigable',
		description:
			'Canal maçonné assez large et profond pour le passage de barges commerciales.',
		requiredTechs: [
			'tech_irrigation',
			'tech_stone_masonry',
			'tech_basic_trade',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 40 },
			{ resource: 'wood', quantity: 20 },
			{ resource: 'iron', quantity: 5 },
		],
		laborForce: 150,
		durationMonths: 24,
		maintenanceCostPerYear: 8,
		minSocialClass: 'noble',
		allowedTerrains: ['plain'],
		forbiddenTerrains: [
			'ocean',
			'sea',
			'lake',
			'ice',
			'mountain',
			'hill',
			'desert',
		],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 8,
		strategicValueOnComplete: 8,
		notes:
			'Le Grand Canal de Chine (Sui/Tang) est le plus grand ouvrage hydraulique du monde médiéval.',
	},

	// ========================================================================
	// MURAILLES
	// ========================================================================
	{
		id: 'recipe_wooden_palisade',
		type: 'wall',
		tier: 'basic',
		name: 'Palissade en bois',
		description:
			'Enceinte de pieux pointus et de terre battue, suffisante contre les raids légers.',
		requiredTechs: ['tech_basic_construction'],
		resourceCosts: [{ resource: 'wood', quantity: 30 }],
		laborForce: 30,
		durationMonths: 3,
		maintenanceCostPerYear: 4,
		minSocialClass: 'minor_noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 4,
		notes:
			"Défense standard des bourgs et villages fortifiés d'Europe du Nord.",
	},
	{
		id: 'recipe_stone_wall',
		type: 'wall',
		tier: 'improved',
		name: 'Rempart en pierre',
		description:
			'Muraille de pierre avec chemin de ronde, merlons et tours de flanquement.',
		requiredTechs: ['tech_fortification', 'tech_stone_masonry'],
		resourceCosts: [
			{ resource: 'stone', quantity: 80 },
			{ resource: 'wood', quantity: 10 },
			{ resource: 'iron', quantity: 10 },
		],
		laborForce: 100,
		durationMonths: 18,
		maintenanceCostPerYear: 6,
		minSocialClass: 'noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 8,
		notes:
			'Les murailles de Constantinople résistent aux sièges depuis le Ve siècle.',
	},
	{
		id: 'recipe_great_wall',
		type: 'wall',
		tier: 'monumental',
		name: 'Grande muraille',
		description:
			"Fortification colossale s'étendant sur des centaines de kilomètres, avec tours de guet et garnisons.",
		requiredTechs: [
			'tech_fortification',
			'tech_stone_masonry',
			'tech_bureaucracy',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 200 },
			{ resource: 'wood', quantity: 40 },
			{ resource: 'iron', quantity: 30 },
		],
		laborForce: 1000,
		durationMonths: 120,
		maintenanceCostPerYear: 30,
		minSocialClass: 'noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 10,
		strategicValueOnComplete: 10,
		notes:
			"La Grande Muraille de Chine, les limes romains — projets de défense à l'échelle civilisationnelle.",
	},

	// ========================================================================
	// FORTERESSES
	// ========================================================================
	{
		id: 'recipe_hillfort',
		type: 'fortress',
		tier: 'basic',
		name: 'Fort de colline',
		description:
			'Position fortifiée sur une hauteur naturelle, avec fossés et remparts de terre.',
		requiredTechs: ['tech_basic_construction'],
		resourceCosts: [
			{ resource: 'wood', quantity: 25 },
			{ resource: 'stone', quantity: 10 },
		],
		laborForce: 40,
		durationMonths: 6,
		maintenanceCostPerYear: 4,
		minSocialClass: 'minor_noble',
		allowedTerrains: ['hill', 'mountain'],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 6,
		notes:
			'Les mottes castrales et hillforts sont la fortification de base en Europe.',
	},
	{
		id: 'recipe_stone_castle',
		type: 'fortress',
		tier: 'improved',
		name: 'Château fort',
		description:
			'Forteresse en pierre avec donjon, courtines, douves et pont-levis.',
		requiredTechs: [
			'tech_fortification',
			'tech_stone_masonry',
			'tech_arch_vault',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 100 },
			{ resource: 'wood', quantity: 30 },
			{ resource: 'iron', quantity: 20 },
		],
		laborForce: 150,
		durationMonths: 36,
		maintenanceCostPerYear: 10,
		minSocialClass: 'noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'swamp'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 900,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 9,
		notes:
			"L'âge des châteaux forts commence au Xe siècle en Europe occidentale.",
	},
	{
		id: 'recipe_citadel',
		type: 'fortress',
		tier: 'advanced',
		name: 'Citadelle',
		description:
			'Complexe fortifié massif avec enceintes concentriques, garnison permanente et réserves.',
		requiredTechs: [
			'tech_fortification',
			'tech_stone_masonry',
			'tech_arch_vault',
			'tech_siege_warfare',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 150 },
			{ resource: 'wood', quantity: 40 },
			{ resource: 'iron', quantity: 30 },
			{ resource: 'marble', quantity: 10 },
		],
		laborForce: 300,
		durationMonths: 48,
		maintenanceCostPerYear: 18,
		minSocialClass: 'noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'swamp', 'jungle'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 800,
		maxYear: null,
		conditionOnComplete: 10,
		strategicValueOnComplete: 10,
		notes:
			"Le Krak des Chevaliers, l'Alhambra, le Palais impérial de Constantinople.",
	},

	// ========================================================================
	// MARCHÉS
	// ========================================================================
	{
		id: 'recipe_village_market',
		type: 'market',
		tier: 'basic',
		name: 'Marché de village',
		description:
			'Place de marché en plein air avec étals en bois et enclos pour le bétail.',
		requiredTechs: ['tech_basic_trade'],
		resourceCosts: [{ resource: 'wood', quantity: 15 }],
		laborForce: 10,
		durationMonths: 2,
		maintenanceCostPerYear: 2,
		minSocialClass: 'merchant',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 4,
		notes:
			'Le marché hebdomadaire est le cœur économique de tout bourg médiéval.',
	},
	{
		id: 'recipe_covered_market',
		type: 'market',
		tier: 'improved',
		name: 'Halle couverte',
		description:
			'Marché couvert permanent en pierre et bois, avec entrepôts attenants.',
		requiredTechs: [
			'tech_basic_trade',
			'tech_basic_construction',
			'tech_guilds',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 30 },
			{ resource: 'wood', quantity: 25 },
			{ resource: 'iron', quantity: 5 },
		],
		laborForce: 40,
		durationMonths: 8,
		maintenanceCostPerYear: 5,
		minSocialClass: 'merchant',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 8,
		strategicValueOnComplete: 6,
		notes: 'Les souks de Bagdad, les fondouks du Caire, les halles de Bruges.',
	},
	{
		id: 'recipe_grand_bazaar',
		type: 'market',
		tier: 'advanced',
		name: 'Grand bazar',
		description:
			'Complexe commercial monumental avec voûtes, caravansérails et bureaux de change.',
		requiredTechs: [
			'tech_basic_trade',
			'tech_stone_masonry',
			'tech_arch_vault',
			'tech_banking_basic',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 70 },
			{ resource: 'wood', quantity: 30 },
			{ resource: 'iron', quantity: 10 },
			{ resource: 'marble', quantity: 10 },
		],
		laborForce: 100,
		durationMonths: 24,
		maintenanceCostPerYear: 12,
		minSocialClass: 'noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 9,
		notes:
			"Le Grand Bazar d'Istanbul (fondé en 1461) deviendra le plus grand marché couvert du monde.",
	},

	// ========================================================================
	// GRENIERS
	// ========================================================================
	{
		id: 'recipe_wooden_granary',
		type: 'granary',
		tier: 'basic',
		name: 'Grenier en bois',
		description:
			"Bâtiment surélevé en bois pour stocker céréales et protéger contre l'humidité et les rongeurs.",
		requiredTechs: ['tech_basic_agriculture'],
		resourceCosts: [{ resource: 'wood', quantity: 15 }],
		laborForce: 10,
		durationMonths: 2,
		maintenanceCostPerYear: 2,
		minSocialClass: 'minor_noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'swamp'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 4,
		notes:
			'Stockage essentiel pour survivre aux mauvaises récoltes et aux hivers.',
	},
	{
		id: 'recipe_stone_granary',
		type: 'granary',
		tier: 'improved',
		name: 'Grenier fortifié',
		description:
			"Entrepôt en pierre avec ventilation, capable de stocker d'importantes réserves pour la cité.",
		requiredTechs: ['tech_basic_agriculture', 'tech_stone_masonry'],
		resourceCosts: [
			{ resource: 'stone', quantity: 30 },
			{ resource: 'wood', quantity: 10 },
			{ resource: 'iron', quantity: 5 },
		],
		laborForce: 30,
		durationMonths: 6,
		maintenanceCostPerYear: 3,
		minSocialClass: 'noble',
		allowedTerrains: [],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'swamp'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 7,
		notes:
			'Les horrea romains et les greniers impériaux chinois assurent la stabilité des empires.',
	},

	// ========================================================================
	// MINES
	// ========================================================================
	{
		id: 'recipe_surface_mine',
		type: 'mine',
		tier: 'basic',
		name: 'Mine à ciel ouvert',
		description:
			"Extraction en surface par tranchées et fosses, nécessitant peu d'équipement.",
		requiredTechs: ['tech_copper_working'],
		resourceCosts: [
			{ resource: 'wood', quantity: 20 },
			{ resource: 'iron', quantity: 5 },
		],
		laborForce: 30,
		durationMonths: 4,
		maintenanceCostPerYear: 4,
		minSocialClass: 'minor_noble',
		allowedTerrains: ['hill', 'mountain'],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'swamp'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 6,
		notes: "Les mines de surface sont exploitées depuis l'Âge du Bronze.",
	},
	{
		id: 'recipe_deep_mine',
		type: 'mine',
		tier: 'improved',
		name: 'Mine profonde',
		description:
			"Galeries souterraines avec boisage, ventilation et drainage, permettant d'atteindre des filons profonds.",
		requiredTechs: ['tech_iron_working', 'tech_basic_construction'],
		resourceCosts: [
			{ resource: 'wood', quantity: 40 },
			{ resource: 'iron', quantity: 15 },
		],
		laborForce: 60,
		durationMonths: 10,
		maintenanceCostPerYear: 8,
		minSocialClass: 'noble',
		allowedTerrains: ['hill', 'mountain'],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'swamp'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 8,
		strategicValueOnComplete: 8,
		notes:
			"Les mines d'argent de Rammelsberg (Harz) enrichissent le Saint-Empire dès le Xe siècle.",
	},

	// ========================================================================
	// IRRIGATION
	// ========================================================================
	{
		id: 'recipe_basic_irrigation',
		type: 'irrigation',
		tier: 'basic',
		name: "Réseau d'irrigation simple",
		description:
			"Système de fossés et de vannes distribuant l'eau de rivière vers les parcelles agricoles.",
		requiredTechs: ['tech_irrigation'],
		resourceCosts: [{ resource: 'wood', quantity: 10 }],
		laborForce: 25,
		durationMonths: 3,
		maintenanceCostPerYear: 3,
		minSocialClass: 'minor_noble',
		allowedTerrains: ['plain', 'steppe'],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'mountain', 'desert'],
		requiresCoast: false,
		requiresRiver: true,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 5,
		notes:
			"Les systèmes d'irrigation de Mésopotamie et d'Égypte datent de 5000 ans.",
	},
	{
		id: 'recipe_qanat',
		type: 'irrigation',
		tier: 'improved',
		name: 'Qanat / Foggaras',
		description:
			'Galeries souterraines captant les eaux de nappes phréatiques et les acheminant par gravité.',
		requiredTechs: ['tech_irrigation', 'tech_basic_construction'],
		resourceCosts: [
			{ resource: 'stone', quantity: 20 },
			{ resource: 'wood', quantity: 15 },
		],
		laborForce: 50,
		durationMonths: 12,
		maintenanceCostPerYear: 4,
		minSocialClass: 'noble',
		allowedTerrains: ['plain', 'desert', 'steppe', 'hill'],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'swamp'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 8,
		strategicValueOnComplete: 8,
		notes:
			"Les qanats perses permettent l'agriculture en zone aride. Technologie diffusée jusqu'en Espagne.",
	},
	{
		id: 'recipe_terrace_irrigation',
		type: 'irrigation',
		tier: 'advanced',
		name: 'Terrasses irriguées',
		description:
			'Culture en terrasses avec canaux intégrés, retenant sol et eau sur les pentes.',
		requiredTechs: ['tech_irrigation', 'tech_terracing'],
		resourceCosts: [
			{ resource: 'stone', quantity: 30 },
			{ resource: 'wood', quantity: 10 },
		],
		laborForce: 60,
		durationMonths: 12,
		maintenanceCostPerYear: 4,
		minSocialClass: 'minor_noble',
		allowedTerrains: ['hill', 'mountain'],
		forbiddenTerrains: ['ocean', 'sea', 'lake', 'ice', 'plain', 'desert'],
		requiresCoast: false,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 8,
		strategicValueOnComplete: 7,
		notes: "Les rizières en terrasses d'Asie du Sud-Est et les andenes incas.",
	},

	// ========================================================================
	// PHARES
	// ========================================================================
	{
		id: 'recipe_beacon_tower',
		type: 'lighthouse',
		tier: 'basic',
		name: 'Tour à feu',
		description:
			'Tour en bois ou pierre avec brasero au sommet pour guider les navires.',
		requiredTechs: ['tech_basic_construction', 'tech_basic_sailing'],
		resourceCosts: [
			{ resource: 'stone', quantity: 15 },
			{ resource: 'wood', quantity: 10 },
		],
		laborForce: 15,
		durationMonths: 4,
		maintenanceCostPerYear: 3,
		minSocialClass: 'minor_noble',
		allowedTerrains: ['coast'],
		forbiddenTerrains: [],
		requiresCoast: true,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 7,
		strategicValueOnComplete: 5,
		notes:
			"Des tours à feu existent sur les côtes méditerranéennes depuis l'Antiquité.",
	},
	{
		id: 'recipe_stone_lighthouse',
		type: 'lighthouse',
		tier: 'improved',
		name: 'Phare en pierre',
		description:
			'Tour haute en maçonnerie avec lanterne permanente, visible à plusieurs lieues.',
		requiredTechs: [
			'tech_stone_masonry',
			'tech_basic_sailing',
			'tech_glass_making',
		],
		resourceCosts: [
			{ resource: 'stone', quantity: 50 },
			{ resource: 'wood', quantity: 10 },
			{ resource: 'iron', quantity: 10 },
		],
		laborForce: 40,
		durationMonths: 12,
		maintenanceCostPerYear: 5,
		minSocialClass: 'noble',
		allowedTerrains: ['coast'],
		forbiddenTerrains: [],
		requiresCoast: true,
		requiresRiver: false,
		minYear: 0,
		maxYear: null,
		conditionOnComplete: 9,
		strategicValueOnComplete: 7,
		notes:
			"Le phare d'Alexandrie, merveille du monde antique, inspire encore les constructions de l'an 1000.",
	},
]
