import type { CulturalNamePool } from '../../../shared/src/types/world'

// ============================================================================
// Pools de noms par aire culturelle — An 1000
// ============================================================================
// Chaque pool fournit ~20-30 prénoms + ~10-15 noms de famille
// pour générer des NPCs cohérents avec la culture et l'époque.
// Sources : onomastique historique médiévale, anthroponymie comparée.
// ============================================================================

export const culturalNamePools: CulturalNamePool[] = [
	// ========================================================================
	// EUROPE OCCIDENTALE (roman / franc / ibérique)
	// ========================================================================
	{
		id: 'area_western_europe',
		name: 'Europe occidentale (roman/franc)',
		nationIds: [
			'nat_france',
			'nat_leon',
			'nat_navarre',
			'nat_papal',
			'nat_venice',
			'nat_croatia',
		],
		maleFirstNames: [
			'Hugues',
			'Robert',
			'Guillaume',
			'Raoul',
			'Geoffroi',
			'Baudouin',
			'Arnaud',
			'Bérenger',
			'Foulques',
			'Thibaut',
			'Eudes',
			'Géraud',
			'Adémar',
			'Renaud',
			'Lothaire',
			'Gui',
			'Aimeri',
			'Sancho',
			'García',
			'Ramiro',
			'Fernando',
			'Ordoño',
			'Alfonso',
			'Pietro',
			'Giovanni',
			'Marco',
		],
		femaleFirstNames: [
			'Adélaïde',
			'Berthe',
			'Constance',
			'Ermengarde',
			'Gerberge',
			'Hildegarde',
			'Mahaut',
			'Pétronille',
			'Richilde',
			'Théodora',
			'Urraca',
			'Elvira',
			'Sancha',
			'Toda',
			'Jimena',
			'Béatrice',
			'Mathilde',
			'Blanche',
			'Agnès',
			'Emma',
		],
		surnames: [
			'de Toulouse',
			'de Blois',
			'de Poitiers',
			'de Barcelone',
			'de Bourgogne',
			'de Lombardie',
			'de Gascogne',
			'de Champagne',
			'de Provence',
			'de Flandre',
			'de León',
			'de Castille',
			'de Navarre',
			'Orsini',
			'Frangipane',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Duc', 'Comte', 'Vicomte', 'Marquis', 'Prince', 'Roi'],
				female: [
					'Duchesse',
					'Comtesse',
					'Vicomtesse',
					'Marquise',
					'Princesse',
					'Reine',
				],
			},
			{
				socialClass: 'clergy',
				male: ['Évêque', 'Abbé', 'Prieur', 'Cardinal', 'Archevêque'],
				female: ['Abbesse', 'Prieure'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Sire', 'Seigneur', 'Chevalier', 'Baron'],
				female: ['Dame', 'Baronne'],
			},
			{
				socialClass: 'merchant',
				male: ['Maître'],
				female: ['Maîtresse'],
			},
			{
				socialClass: 'peasant',
				male: [],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			"Patronymes topographiques (de + lieu). Les paysans n'ont souvent qu'un prénom + surnom de métier ou physique (Jean le Roux, Pierre le Forgeron).",
	},

	// ========================================================================
	// GERMANIQUE (Saint-Empire, Pologne, Hongrie)
	// ========================================================================
	{
		id: 'area_germanic',
		name: 'Europe germanique (HRE, Pologne, Hongrie)',
		nationIds: ['nat_hre', 'nat_poland', 'nat_hungary'],
		maleFirstNames: [
			'Otto',
			'Heinrich',
			'Konrad',
			'Friedrich',
			'Ludwig',
			'Adalbert',
			'Bernhard',
			'Ekkehard',
			'Gero',
			'Hermann',
			'Burkhard',
			'Werner',
			'Welf',
			'Dietrich',
			'Ulrich',
			'Siegfried',
			'Markward',
			'Bolesław',
			'Mieszko',
			'Kazimierz',
			'Władysław',
			'István',
			'Géza',
			'László',
			'Béla',
		],
		femaleFirstNames: [
			'Theophanu',
			'Kunigunde',
			'Gisela',
			'Hedwig',
			'Mathilde',
			'Richenza',
			'Adelheid',
			'Irmingard',
			'Gertrude',
			'Judith',
			'Liutgard',
			'Oda',
			'Dobrawa',
			'Świętosława',
			'Sarolta',
			'Agatha',
			'Ida',
			'Bertha',
			'Sophie',
			'Anastasia',
		],
		surnames: [
			'von Sachsen',
			'von Bayern',
			'von Schwaben',
			'von Franken',
			'von Lothringen',
			'von Kärnten',
			'von Meißen',
			'von Wettin',
			'von Habsburg',
			'von Salier',
			'Piast',
			'Árpád',
			'Přemyslid',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Kaiser', 'König', 'Herzog', 'Markgraf', 'Pfalzgraf', 'Fürst'],
				female: ['Kaiserin', 'Königin', 'Herzogin', 'Markgräfin', 'Fürstin'],
			},
			{
				socialClass: 'clergy',
				male: ['Erzbischof', 'Bischof', 'Abt'],
				female: ['Äbtissin'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Graf', 'Ritter', 'Freiherr'],
				female: ['Gräfin', 'Freifrau'],
			},
			{
				socialClass: 'merchant',
				male: ['Meister'],
				female: ['Meisterin'],
			},
			{
				socialClass: 'peasant',
				male: [],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			'Noms dynastiques forts (Ottoniens, Piasts, Árpáds). Patronymes topographiques (von + lieu). Le peuple utilise prénoms + surnoms professionnels (Schmidt, Müller).',
	},

	// ========================================================================
	// NORSE / SCANDINAVE
	// ========================================================================
	{
		id: 'area_norse',
		name: 'Scandinavie (Norse)',
		nationIds: ['nat_denmark', 'nat_norway', 'nat_sweden'],
		maleFirstNames: [
			'Harald',
			'Svein',
			'Olaf',
			'Erik',
			'Knut',
			'Leif',
			'Bjorn',
			'Sigurd',
			'Thorstein',
			'Gunnar',
			'Ragnar',
			'Ingvar',
			'Halfdan',
			'Hákon',
			'Magnus',
			'Torvald',
			'Ulf',
			'Rolf',
			'Arne',
			'Ketil',
			'Thorfinn',
			'Styrbjörn',
			'Anund',
			'Skuli',
		],
		femaleFirstNames: [
			'Freydis',
			'Sigrid',
			'Astrid',
			'Gudrun',
			'Ingrid',
			'Hildur',
			'Thyra',
			'Ragnhild',
			'Aud',
			'Gunnhild',
			'Helga',
			'Thordis',
			'Aslög',
			'Solveig',
			'Gyda',
			'Jorunn',
			'Vigdis',
			'Yrsa',
			'Brynhild',
			'Liv',
		],
		surnames: [
			'-sson',
			'-sdóttir',
			'Hárfagri (aux beaux cheveux)',
			'Blåtand (Dent bleue)',
			'Digre (le Gros)',
			'Tryggvason',
			'Haraldsson',
			'Eiriksson',
			'Sigurdsson',
			'Olafsson',
			'Sveinson',
			'Magnusson',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Konung', 'Jarl'],
				female: ['Drottning'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Hersir', 'Lendmann', 'Hövding'],
				female: [],
			},
			{
				socialClass: 'merchant',
				male: ['Kaupmaðr'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Karl', 'Bóndi'],
				female: ['Húsfreyja'],
			},
		],
		namingConvention: 'given_patronymic',
		notes:
			'Patronymique pur : Erik fils de Harald = Erik Haraldsson. Les femmes : Sigrid fille de Harald = Sigrid Haraldsdóttir. Surnoms descriptifs fréquents (le Hardi, Dent de fer, etc.).',
	},

	// ========================================================================
	// ANGLO-SAXON
	// ========================================================================
	{
		id: 'area_anglo_saxon',
		name: 'Angleterre & Écosse',
		nationIds: ['nat_england', 'nat_scotland'],
		maleFirstNames: [
			'Æthelred',
			'Eadmund',
			'Eadgar',
			'Godwin',
			'Leofric',
			'Wulfstan',
			'Byrhtno\u00f0',
			'Ælfred',
			'Oswald',
			'Dunstan',
			'Siward',
			'Morcar',
			'Tostig',
			'Thorkell',
			'Eadric',
			'Edwin',
			'Harold',
			'Kenneth',
			'Malcolm',
			'Duncan',
			'Macbeth',
			'Gruoch',
			'Crinan',
			'Findlaech',
		],
		femaleFirstNames: [
			'Ælfgifu',
			'Ealdgyth',
			'Wulfhild',
			'Godgifu',
			'Ælfthryth',
			'Eadgyth',
			'Hild',
			'Cwenthryth',
			'Wynflæd',
			'Leofgyth',
			'Maud',
			'Margaret',
			'Emma',
			'Gruoch',
			'Bethóc',
			'Donada',
		],
		surnames: [
			'of Wessex',
			'of Mercia',
			'of Northumbria',
			'of East Anglia',
			'of Alba',
			'of Moray',
			'of Lothian',
			'of Atholl',
			'mac Alpin',
			'mac Donnchada',
			'mac Findlaech',
			'mac Máel Coluim',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Cyning (King)', 'Ealdorman', 'Earl', 'Rí (King)'],
				female: ['Cwen (Queen)', 'Hlæfdige (Lady)'],
			},
			{
				socialClass: 'clergy',
				male: ['Archbishop', 'Bishop', 'Abbot'],
				female: ['Abbess'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Thegn', 'Mormaer', 'Toísech'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Ceorl'],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			'Angleterre : noms vieil-anglais + influence danoise (Thorkell, Harold). Écosse : noms gaéliques + patronymique mac (fils de). Bynames topographiques (of Wessex, of Moray).',
	},

	// ========================================================================
	// SLAVE ORIENTAL (Rus' de Kiev, Bulgarie de la Volga)
	// ========================================================================
	{
		id: 'area_slavic',
		name: "Slaves orientaux (Rus' de Kiev)",
		nationIds: ['nat_kievan_rus', 'nat_volga_bulgaria'],
		maleFirstNames: [
			'Vladimir',
			'Yaroslav',
			'Sviatoslav',
			'Mstislav',
			'Boris',
			'Gleb',
			'Iziaslav',
			'Vsevolod',
			'Igor',
			'Oleg',
			'Sviatopolk',
			'Rostislav',
			'Dobrynya',
			'Ilya',
			'Aliosha',
			'Vassili',
			'Fedor',
			'Ivan',
			'Gavriil',
			'Dmitri',
		],
		femaleFirstNames: [
			'Olga',
			'Rogneda',
			'Anna',
			'Predslava',
			'Mstislava',
			'Dobrava',
			'Yaroslavna',
			'Eupraxia',
			'Maria',
			'Anastasia',
			'Irina',
			'Ludmila',
			'Fevronia',
			'Evdokia',
			'Agafia',
			'Vasilisa',
		],
		surnames: [
			'Riurikides',
			'Vladimirovitch',
			'Yaroslavitch',
			'Sviatoslavitch',
			'Mstislavitch',
			'Igorevitch',
			'Olegvitch',
			'Vsevolodovitch',
			'Rostislavitch',
			'Borisovitch',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Veliki Kniaz (Grand-Prince)', 'Kniaz (Prince)'],
				female: ['Kniaginia (Princesse)'],
			},
			{
				socialClass: 'clergy',
				male: ['Mitropolit (Métropolite)', 'Igumen (Abbé)', 'Episkop (Évêque)'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Boyar', 'Voïvode', 'Druzhina (Compagnon)'],
				female: ['Boyarynia'],
			},
			{
				socialClass: 'merchant',
				male: ['Gost (Marchand)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Smerd'],
				female: [],
			},
		],
		namingConvention: 'given_patronymic',
		notes:
			'Patronymique en -ovitch/-evitch (fils de) ou -ovna/-evna (fille de). Vladimir fils de Sviatoslav = Vladimir Sviatoslavitch. Noms chrétiens et slaves coexistent après le baptême de 988.',
	},

	// ========================================================================
	// BYZANTIN
	// ========================================================================
	{
		id: 'area_byzantine',
		name: 'Empire byzantin',
		nationIds: ['nat_byzantine'],
		maleFirstNames: [
			'Basileios',
			'Konstantinos',
			'Romanos',
			'Nikephoros',
			'Ioannes',
			'Michael',
			'Alexios',
			'Theodoros',
			'Georgios',
			'Stephanos',
			'Leon',
			'Andronikos',
			'Isaakios',
			'Demetrios',
			'Manuel',
			'Philippos',
			'Gregorios',
			'Eustathios',
			'Symeon',
			'Bardas',
		],
		femaleFirstNames: [
			'Theodora',
			'Zoe',
			'Eudokia',
			'Irene',
			'Anna',
			'Maria',
			'Helena',
			'Sophia',
			'Theophano',
			'Anastasia',
			'Pulcheria',
			'Athenais',
			'Kassia',
			'Eulogia',
			'Simonis',
			'Thomais',
		],
		surnames: [
			'Komnenos',
			'Doukas',
			'Phokas',
			'Skleros',
			'Monomachos',
			'Palaiologos',
			'Kantakouzenos',
			'Laskaris',
			'Angelos',
			'Botaneiates',
			'Diogenes',
			'Argyros',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Basileus (Empereur)', 'Despotès', 'Sebastokrator', 'Caesar'],
				female: ['Basilissa (Impératrice)', 'Despoina', 'Augusta'],
			},
			{
				socialClass: 'clergy',
				male: ['Patriarches', 'Metropolites', 'Archimandrite', 'Higoumene'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Strategos', 'Doux', 'Katepano', 'Protospatharios'],
				female: [],
			},
			{
				socialClass: 'merchant',
				male: ['Emporos'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: [],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			'Noms grecs antiques + chrétiens. Noms de famille aristocratiques forts. Le système de titres est très élaboré avec une hiérarchie byzantine complexe.',
	},

	// ========================================================================
	// ARABE (Fatimides, Cordoue, Bouyides)
	// ========================================================================
	{
		id: 'area_arabic',
		name: 'Monde arabe',
		nationIds: ['nat_fatimid', 'nat_cordoba', 'nat_buyid'],
		maleFirstNames: [
			'Ahmad',
			'Muhammad',
			'Ali',
			'Hassan',
			'Hussein',
			'Omar',
			'Othman',
			'Khalid',
			'Tariq',
			'Yusuf',
			'Ibrahim',
			'Ismail',
			'Hakim',
			'Mansur',
			'Muizz',
			'Aziz',
			'Rashid',
			'Said',
			'Walid',
			'Hisham',
			'Abd al-Rahman',
			'Abd al-Malik',
			'Nizar',
			'Jawhar',
		],
		femaleFirstNames: [
			'Fatima',
			'Aisha',
			'Khadija',
			'Zaynab',
			'Maryam',
			'Sitt al-Mulk',
			'Lubna',
			'Wallada',
			'Shajara',
			'Hurra',
			'Asma',
			'Rayhana',
			'Safiyya',
			'Ruqayya',
			'Halima',
			'Layla',
		],
		surnames: [
			'ibn Ahmad',
			'ibn Ali',
			'ibn Muhammad',
			'ibn Yusuf',
			'ibn Ibrahim',
			'al-Hakim',
			'al-Mansur',
			'al-Rashid',
			"al-Mu'izz",
			'al-Aziz',
			'al-Andalusi',
			'al-Qurtubi',
			'al-Misri',
			'al-Baghdadi',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Khalifa (Calife)',
					'Sultan',
					'Émir',
					'Wali (Gouverneur)',
					'Malik (Roi)',
				],
				female: ['Malika (Reine)', 'Sitt (Dame)'],
			},
			{
				socialClass: 'clergy',
				male: ['Qadi (Juge)', 'Imam', 'Mufti', 'Sheikh', 'Ulema'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Hajib (Chambellan)', 'Vizir', "Qa'id (Commandant)"],
				female: [],
			},
			{
				socialClass: 'merchant',
				male: ['Tajir (Marchand)', 'Sayrafī (Changeur)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Fellah'],
				female: [],
			},
		],
		namingConvention: 'given_ibn_father',
		notes:
			"Système nasab : prénom + ibn (fils de) + nom du père + nisba (origine). Ex: Ahmad ibn Muhammad al-Baghdadi. La kunya (Abu/Umm + nom d'enfant) est aussi très courante. Les femmes : bint (fille de).",
	},

	// ========================================================================
	// PERSAN / IRANIEN (Ghaznavides)
	// ========================================================================
	{
		id: 'area_persian',
		name: 'Monde persan (Ghaznavides)',
		nationIds: ['nat_ghaznavid'],
		maleFirstNames: [
			'Mahmud',
			'Masud',
			'Ferdowsi',
			'Khosrau',
			'Bahram',
			'Darius',
			'Cyrus',
			'Rostam',
			'Sohrab',
			'Kaveh',
			'Ardashir',
			'Shapur',
			'Ismail',
			'Nuh',
			'Nasr',
			'Sabuktigin',
			'Toghrul',
			'Alp',
			'Firuz',
			'Reza',
		],
		femaleFirstNames: [
			'Shirin',
			'Gohar',
			'Mahin',
			'Parvaneh',
			'Yasamin',
			'Laleh',
			'Golnar',
			'Setareh',
			'Anahita',
			'Faranak',
			'Rudabeh',
			'Tahmineh',
			'Mandaneh',
			'Pourandokht',
			'Zarin',
			'Mahvash',
		],
		surnames: [
			'Ghaznavid',
			'Samanid',
			'Buyid',
			'Saffarid',
			'Tahirid',
			'Barmakid',
			'Farrukhi',
			'Balkhi',
			'Tusi',
			'Khorasani',
			'Sistani',
			'Shirazi',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Shah', 'Shahanshah', 'Sultan', 'Émir', 'Khagan'],
				female: ['Shahbanu', 'Khatun'],
			},
			{
				socialClass: 'clergy',
				male: ['Mobed (Prêtre zoroastrien)', 'Sheikh', 'Imam'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Sipahsalar (Général)', 'Dihqan (Seigneur local)', 'Amir'],
				female: [],
			},
			{
				socialClass: 'merchant',
				male: ['Bazargan'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: [],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			'Nisbas géographiques (-i : Tusi = de Tus, Balkhi = de Balkh). Tradition shahnameh (noms héroïques). Les dynasties turco-persanes mélangent onomastique turque et persane.',
	},

	// ========================================================================
	// TURCIQUE (Karakhanides)
	// ========================================================================
	{
		id: 'area_turkic',
		name: 'Turcs (Karakhanides)',
		nationIds: ['nat_karakhanid'],
		maleFirstNames: [
			'Ilek',
			'Bughra',
			'Qadir',
			'Arslan',
			'Toghrul',
			'Alp',
			'Bilge',
			'Kül',
			'Bars',
			'Tengri',
			'Yusuf',
			'Harun',
			'Satuk',
			'Musa',
			'Sulayman',
			'Nasr',
			'Ahmad',
			'Oghuz',
			'Seljuk',
			'Tughtigin',
		],
		femaleFirstNames: [
			'Terken',
			'Khatun',
			'Aysha',
			'Ülkü',
			'Turandokht',
			'Altunyarug',
			'Begüm',
			'Çiçek',
			'Gülçiçek',
			'Fatima',
			'Maryam',
			'Safiye',
			'Bilge',
			'Umay',
			'Bolgan',
			'Könchek',
		],
		surnames: [
			'Khan',
			'Khagan',
			'Ilek',
			'Qarakhanid',
			'Bogra',
			'Tamghach',
			'Arslan',
			'Toghrul',
			'Oghuz',
			'Seljukid',
			'Qadir',
			'Bughra',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Khagan', 'Khan', 'Ilek', 'Beg', 'Tegin'],
				female: ['Khatun', 'Begüm'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Bey', 'Atabeg', 'Sipahsalar'],
				female: [],
			},
			{
				socialClass: 'merchant',
				male: ['Saudagar'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: [],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			'Noms turco-islamiques. Titres turcs (Khan, Beg) + influence arabo-persane après la conversion. Surnoms animaliers fréquents (Arslan=lion, Bars=panthère, Toghrul=faucon).',
	},

	// ========================================================================
	// CAUCASIEN (Géorgie, Arménie)
	// ========================================================================
	{
		id: 'area_caucasian',
		name: 'Caucase (Géorgie, Arménie)',
		nationIds: ['nat_georgia', 'nat_armenia'],
		maleFirstNames: [
			'Bagrat',
			'Giorgi',
			'David',
			'Demetre',
			'Tamar',
			'Konstantine',
			'Ashot',
			'Gagik',
			'Smbat',
			'Hovhannes',
			'Tigran',
			'Grigor',
			'Levon',
			'Nerses',
			'Varazdat',
			'Gurgen',
			'Kakha',
			'Tornike',
			'Liparit',
			'Ivane',
		],
		femaleFirstNames: [
			'Mariam',
			'Tamar',
			'Gurandukht',
			'Shushanik',
			'Nana',
			'Ketevan',
			'Rusudan',
			'Borena',
			'Khosrovanush',
			'Katranide',
			'Hripsime',
			'Gayane',
			'Anahit',
			'Satenik',
			'Ashkhen',
			'Parandzem',
		],
		surnames: [
			'Bagrationi',
			'Bagratuni',
			'Artsruni',
			'Orbeli',
			'Zakaryan',
			'Mamikonian',
			'Pahlavuni',
			'Klarjeti',
			'Kakheti',
			'Siunia',
			'Toreli',
			'Mkhargrdzeli',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Mepe (Roi-Géorgie)',
					'Taguvor (Roi-Arménie)',
					'Eristavi (Duc)',
					'Ishkhan (Prince)',
				],
				female: ['Dedopali (Reine-Géorgie)', 'Tikin (Princesse-Arménie)'],
			},
			{
				socialClass: 'clergy',
				male: ['Catholicos', 'Eparkhose (Évêque)', 'Vardapet (Docteur)'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Aznauri (Chevalier)', 'Nakharar (Baron)', 'Sparapet (Général)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Shinakan'],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			'Noms dynastiques forts (Bagrationi/Bagratuni). Influence chrétienne ancienne. Les noms de famille arméniens se terminent en -yan/-ian, les géorgiens en -shvili/-dze.',
	},

	// ========================================================================
	// AFRIQUE DE L'EST (Éthiopie, Swahili, Makuria)
	// ========================================================================
	{
		id: 'area_east_african',
		name: "Afrique de l'Est",
		nationIds: ['nat_ethiopia', 'nat_swahili_cities', 'nat_makuria'],
		maleFirstNames: [
			'Yekuno',
			'Gebre',
			'Tekle',
			'Lalibela',
			'Menelik',
			'Kaleb',
			'Ezana',
			'Merkurios',
			'Dawit',
			'Solomon',
			'Ali',
			'Muhammad',
			'Hassan',
			'Omar',
			'Sulaiman',
			'Yusuf',
			'Raphael',
			'Georgios',
			'Petros',
			'Qalidurut',
		],
		femaleFirstNames: [
			'Gudit',
			'Makeda',
			'Eleni',
			'Mentewab',
			'Sabla',
			'Zewditu',
			'Taytu',
			'Maryam',
			'Aster',
			'Birtukan',
			'Fatima',
			'Amina',
			'Halima',
			'Zainab',
			'Safiya',
			'Aisha',
		],
		surnames: [
			'Zagwe',
			'Solomonid',
			'ibn Sulaiman',
			'ibn Ali',
			'wa Kilwa',
			'wa Mogadishu',
			'wa Mombasa',
			'wa Lamu',
			'Tekle Haymanot',
			'Gebre Meskel',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Negus (Roi)',
					'Negusa Nagast (Roi des rois)',
					'Sultan',
					'Sheikh',
				],
				female: ['Nigiste (Reine)', 'Sultana'],
			},
			{
				socialClass: 'clergy',
				male: ['Abuna (Patriarche)', 'Memhir (Maître)', 'Qadi'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Ras', 'Dejazmatch', 'Fitawrari'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: [],
				female: [],
			},
		],
		namingConvention: 'given_patronymic',
		notes:
			'Éthiopie : pas de nom de famille traditionnel — prénom + prénom du père. Swahili : système arabe (ibn/bint) mélangé avec noms bantous. Makuria : noms nubiens chrétiens + coptes.',
	},

	// ========================================================================
	// AFRIQUE DE L'OUEST (Ghana, Kanem, Yoruba, Igbo)
	// ========================================================================
	{
		id: 'area_west_african',
		name: "Afrique de l'Ouest",
		nationIds: [
			'nat_ghana',
			'nat_kanem',
			'nat_yoruba',
			'nat_igbo',
			'nat_tuareg',
		],
		maleFirstNames: [
			'Tunka',
			'Manin',
			'Soumaba',
			'Kaya',
			'Magha',
			'Basi',
			'Oduduwa',
			'Oranmiyan',
			'Ajaka',
			'Sango',
			'Obatala',
			'Idris',
			'Dunama',
			'Hummay',
			'Sefu',
			'Nri',
			'Eze',
			'Obi',
			'Amanirenas',
			'Tin-Hinan',
			'Amenokal',
			'Amayas',
			'Yuba',
			'Aksil',
		],
		femaleFirstNames: [
			'Aminata',
			'Fanta',
			'Awa',
			'Nana',
			'Moremi',
			'Iyalode',
			'Oduduwa',
			'Amina',
			'Magajiya',
			'Sarraounia',
			'Taguelmust',
			'Dassine',
			'Ada',
			'Nkechi',
			'Ngozi',
			'Nneka',
		],
		surnames: [
			'Cissé',
			'Sissako',
			'Wagadu',
			'Soninké',
			'Kanuri',
			'Sefuwa',
			'Zarma',
			'Mandinka',
			'Yoruba',
			'Hausa',
			'Kel Ahaggar',
			'Kel Aïr',
			'Ifè',
			'Nri',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Ghana (Roi-titre)',
					'Mai (Roi-Kanem)',
					'Ooni (Roi-Ifè)',
					'Eze (Roi-Igbo)',
					'Amenokal (Chef touareg)',
				],
				female: ['Iyalode (Mère de la cité)', 'Magajiya (Reine)'],
			},
			{
				socialClass: 'clergy',
				male: ['Babalawo (Prêtre-Ifá)', 'Imam', 'Marabout'],
				female: ['Iyaloricha (Prêtresse)'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Kaya-Magha (Prince)', 'Galadima', 'Oloye'],
				female: [],
			},
			{
				socialClass: 'merchant',
				male: ['Juula (Marchand dioula)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: [],
				female: [],
			},
		],
		namingConvention: 'given_tribal',
		notes:
			"Noms souvent liés au jour de naissance (Akan) ou au clan totémique. Les Touaregs utilisent un patronymique berbère (ag = fils de). Les noms Yoruba sont souvent théophores (Sangotola = Sango m'a élevé).",
	},

	// ========================================================================
	// AFRIQUE AUSTRALE (Zimbabwe, San, Mbuti)
	// ========================================================================
	{
		id: 'area_south_african',
		name: 'Afrique australe & centrale',
		nationIds: ['nat_zimbabwe', 'nat_san', 'nat_mbuti'],
		maleFirstNames: [
			'Mutota',
			'Matope',
			'Changamire',
			'Nyatsimba',
			'Dombashava',
			'Chaminuka',
			'Musikavanhu',
			'Njelele',
			'Kwame',
			'Kofi',
			'Kaggen',
			'Tsui-Goab',
			'Mantis',
			'Eland',
			'Kenge',
			'Makubasi',
			'Efu',
			'Nkumbi',
			'Apakumandura',
			'Ndura',
		],
		femaleFirstNames: [
			'Nehanda',
			'Ambuya',
			'Mbuya',
			'Nyamhika',
			'Shona',
			'Tafara',
			'Rudo',
			'Tapiwa',
			'Nandi',
			'Modjadji',
			'Nobantu',
			'Thandiwe',
			'Balekimito',
			'Kacaleba',
			'Maipe',
			'Asofi',
		],
		surnames: [
			'Rozwi',
			'Karanga',
			'Kalanga',
			'Shona',
			'Mbuti',
			'Ituri',
			'San',
			'Khoi',
			'Twa',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Mambo (Roi-Shona)', 'Mwene (Chef)'],
				female: ['Nehanda (Reine-esprit)'],
			},
			{
				socialClass: 'any',
				male: ["N'anga (Guérisseur)", 'Svikiro (Médium spirite)'],
				female: ['Mbuya (Ancienne)'],
			},
		],
		namingConvention: 'given_clan',
		notes:
			'Zimbabwe : noms shotiques liés aux totems claniques (Soko=singe, Shumba=lion). San : noms descriptifs courts, souvent liés à la nature. Mbuti : noms liés à la forêt. Pas de noms de famille au sens occidental.',
	},

	// ========================================================================
	// CHINOIS
	// ========================================================================
	{
		id: 'area_chinese',
		name: 'Monde chinois (Song, Liao)',
		nationIds: ['nat_song', 'nat_liao'],
		maleFirstNames: [
			'Zhenzong',
			'Renzong',
			'Taizu',
			'Taizong',
			'Shenzong',
			'Huizong',
			'Qinzong',
			'Yuanhao',
			'Weizheng',
			'Mingde',
			'Zongyuan',
			'Wenzhong',
			'Zhongyan',
			'Xiangru',
			'Tingzhao',
			'Junyi',
			'Dezhao',
			'Shidao',
			'Yelü',
			'Longxu',
		],
		femaleFirstNames: [
			'Liangdi',
			'Yingtian',
			'Mingde',
			'Zhangxian',
			'Zhenyi',
			'Xuanren',
			'Xiao',
			'Yanyan',
			'Huilan',
			'Wanqing',
			'Qingzhao',
			'Huan',
			'Ruolan',
			'Yuzhen',
			'Miaoxian',
			'Cihui',
		],
		surnames: [
			'Zhao',
			'Li',
			'Wang',
			'Zhang',
			'Liu',
			'Chen',
			'Yang',
			'Huang',
			'Zhou',
			'Wu',
			'Sun',
			'Zhu',
			'Lin',
			'Song',
			'Fan',
			'Sima',
			'Ouyang',
			'Su',
			'Yelü',
			'Xiao',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Huangdi (Empereur)',
					'Wang (Prince/Roi)',
					'Gong (Duc)',
					'Hou (Marquis)',
				],
				female: [
					'Huanghou (Impératrice)',
					'Guifei (Consort impériale)',
					'Gongzhu (Princesse)',
				],
			},
			{
				socialClass: 'clergy',
				male: ['Fangzhang (Abbé bouddhiste)', 'Daoshi (Prêtre taoïste)'],
				female: ['Nüni (Nonne bouddhiste)', 'Nüdaoshi (Prêtresse taoïste)'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Daren (Excellence)', 'Langjun (Seigneur)'],
				female: ['Furen (Dame)', 'Niangniang'],
			},
			{
				socialClass: 'merchant',
				male: ['Yuanwai (Notable)', 'Shangren (Marchand)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Nongfu'],
				female: [],
			},
		],
		namingConvention: 'surname_given',
		notes:
			'Nom de famille AVANT le prénom (Zhao Zhenzong, pas Zhenzong Zhao). Le prénom est souvent composé de 2 caractères. Les Liao/Khitans utilisent des noms Yelü (clan impérial) et Xiao (clan consort).',
	},

	// ========================================================================
	// CORÉEN (Goryeo)
	// ========================================================================
	{
		id: 'area_korean',
		name: 'Corée (Goryeo)',
		nationIds: ['nat_goryeo'],
		maleFirstNames: [
			'Seongjong',
			'Mokjong',
			'Hyeonjong',
			'Gwangjong',
			'Gyeongjong',
			'Wang',
			'Choe',
			'Seo',
			'Jeong',
			'Gang',
			'Gam',
			'Seung',
			'Bo',
			'Won',
			'Ui',
			'Gyu',
			'Taejo',
			'Dongsu',
			'Hyeonbo',
			'Jikgyeom',
		],
		femaleFirstNames: [
			'Heonae',
			'Gyeonghwa',
			'Seonui',
			'Wonseong',
			'Daemok',
			'Heonjeong',
			'Munhwa',
			'Anjeong',
			'Wonyeong',
			'Seongyeol',
			'Insuk',
			'Myeongbok',
			'Hwangbo',
			'Sunhwa',
			'Jinseong',
			'Sukbin',
		],
		surnames: [
			'Wang',
			'Kim',
			'Yi',
			'Park',
			'Choe',
			'Jeong',
			'Yun',
			'Seo',
			'Han',
			'Gang',
			'Hwangbo',
			'Hae',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Wang (Roi)', 'Taeja (Prince héritier)', 'Gun (Prince)'],
				female: ['Wangbi (Reine)', 'Gongju (Princesse)'],
			},
			{
				socialClass: 'clergy',
				male: [
					'Guksa (Précepteur national)',
					'Wangsa (Précepteur royal)',
					'Seunim (Moine)',
				],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Yangban (Aristocrate lettré)', 'Daegam (Excellence)'],
				female: ['Buin (Dame)'],
			},
			{
				socialClass: 'peasant',
				male: ['Yangmin (Roturier)'],
				female: [],
			},
		],
		namingConvention: 'surname_given',
		notes:
			'Nom de famille avant le prénom (Wang Seongjong). Les clans sont identifiés par le bon (origine géographique) : Kim de Gyeongju ≠ Kim de Gimhae. Très peu de noms de famille différents (quelques dizaines).',
	},

	// ========================================================================
	// JAPONAIS (Heian)
	// ========================================================================
	{
		id: 'area_japanese',
		name: 'Japon (époque Heian)',
		nationIds: ['nat_japan'],
		maleFirstNames: [
			'Michinaga',
			'Korechika',
			'Sanesuke',
			'Kinto',
			'Yukinari',
			'Tadanobu',
			'Yoshinobu',
			'Norimichi',
			'Yorimichi',
			'Murasaki',
			'Akimitsu',
			'Takaie',
			'Kintsune',
			'Morosuke',
			'Saneyori',
			'Tamemitsu',
			'Naritoki',
			'Yasusuke',
			'Tsunefusa',
			'Sukemasa',
		],
		femaleFirstNames: [
			'Shikibu',
			'Shonagon',
			'Akazome',
			'Izumi',
			'Kodaiin',
			'Rinshi',
			'Ishi',
			'Shōshi',
			'Kenshi',
			'Ishi',
			'Meishi',
			'Teishi',
			'Senshi',
			'Junshi',
			'Takako',
			'Yasuko',
		],
		surnames: [
			'Fujiwara',
			'Minamoto',
			'Taira',
			'Sugawara',
			'Tachibana',
			'Abe',
			'Oe',
			'Kamo',
			'Ki',
			'Nakahara',
			'Otomo',
			'Saionji',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Tenno (Empereur)',
					'Kampaku (Régent)',
					'Sadaijin (Ministre de gauche)',
					'Udaijin (Ministre de droite)',
				],
				female: [
					'Kogo (Impératrice)',
					'Chugu (Consort)',
					"Nyogo (Dame d'honneur)",
				],
			},
			{
				socialClass: 'clergy',
				male: [
					'Sojo (Grand prêtre bouddhiste)',
					'Kannushi (Prêtre shinto)',
					'Hoshi (Moine)',
				],
				female: ['Bikuni (Nonne)'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Dainagon', 'Chunagon', 'Shonagon', 'Kurodo'],
				female: ['Tsubone (Dame de la cour)'],
			},
			{
				socialClass: 'peasant',
				male: [],
				female: [],
			},
		],
		namingConvention: 'surname_given',
		notes:
			"Nom de clan avant le prénom (Fujiwara no Michinaga). La particule 'no' lie clan et prénom. L'époque Heian est dominée par le clan Fujiwara. Les femmes de lettres sont souvent connues par leur rang de cour, pas leur vrai nom.",
	},

	// ========================================================================
	// ASIE DU SUD-EST (Khmer, Dai Viet, Srivijaya)
	// ========================================================================
	{
		id: 'area_southeast_asian',
		name: 'Asie du Sud-Est',
		nationIds: ['nat_khmer', 'nat_dai_viet', 'nat_srivijaya'],
		maleFirstNames: [
			'Suryavarman',
			'Jayavarman',
			'Udayadityavarman',
			'Harshavarman',
			'Rajendravarman',
			'Yasovarman',
			'Lê',
			'Hoàn',
			'Long',
			'Đĩnh',
			'Phụng',
			'Khánh',
			'Sri',
			'Vijaya',
			'Sangrama',
			'Maravijayattungga',
			'Chulamanivarmadeva',
			'Dharmasetu',
			'Balaputradewa',
			'Dapunta',
		],
		femaleFirstNames: [
			'Indradevi',
			'Jayarajadevi',
			'Kambujarajalakshmi',
			'Dương',
			'Lý',
			'Trần',
			'Ỷ',
			'Thuận',
			'Sri Tribhuvana',
			'Pramodavardhani',
			'Tara',
			'Dewi',
			'Paramesvari',
			'Suhita',
			'Ratna',
			'Padma',
		],
		surnames: [
			'-varman (protégé de)',
			'Lê',
			'Lý',
			'Ngô',
			'Đinh',
			'Trần',
			'Sailendra',
			'Srivijaya',
			'Majapahit',
			'Mataram',
			'Champa',
			'Dvaravati',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Devaraja (Roi-dieu)',
					'Vua (Roi-Viet)',
					'Maharaja',
					'Chakravartin',
				],
				female: ['Devi (Reine)', 'Hoàng hậu (Impératrice-Viet)'],
			},
			{
				socialClass: 'clergy',
				male: [
					'Brahmane',
					'Bhikkhu (Moine bouddhiste)',
					'Purohita (Grand prêtre)',
				],
				female: ['Bhikkhuni (Nonne)'],
			},
			{
				socialClass: 'minor_noble',
				male: [
					'Pon (Seigneur-Khmer)',
					'Mratan (Noble)',
					'Quan (Mandarin-Viet)',
				],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Anak (Sujet)'],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			'Khmers : noms sanskrits en -varman (protégé de). Vietnamiens : nom de famille + prénom (Lê Hoàn). Malais : noms sanskrits-malais. Forte influence indienne (noms théophores hindous/bouddhistes).',
	},

	// ========================================================================
	// INDIEN (Chola, Chalukya, Pala)
	// ========================================================================
	{
		id: 'area_indian',
		name: 'Sous-continent indien',
		nationIds: ['nat_chola', 'nat_chalukya', 'nat_pala'],
		maleFirstNames: [
			'Rajaraja',
			'Rajendra',
			'Kulottunga',
			'Vikramaditya',
			'Jayasimha',
			'Somesvara',
			'Tailapa',
			'Mahipala',
			'Dharmapala',
			'Devapala',
			'Gopala',
			'Nayapala',
			'Vigrahapala',
			'Madanapala',
			'Paramara',
			'Bhoja',
			'Munja',
			'Rajyapala',
			'Gangeyadeva',
			'Lakshmanasena',
		],
		femaleFirstNames: [
			'Sembiyan',
			'Kundavai',
			'Lokamahadevi',
			'Trailokyamahadevi',
			'Akkadevi',
			'Lakshmidevi',
			'Chandralekha',
			'Vijayamahadevi',
			'Kulavantidevī',
			'Devasena',
			'Padmavati',
			'Kamaladevi',
			'Rajlakshmi',
			'Sarasvatidevi',
			'Sundari',
			'Mahadevi',
		],
		surnames: [
			'Chola',
			'Chalukya',
			'Pala',
			'Rashtrakuta',
			'Paramara',
			'Chandella',
			'Pratihara',
			'Gahadavala',
			'Sena',
			'Kadamba',
			'Hoysala',
			'Pandya',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Maharaja (Grand roi)',
					'Raja (Roi)',
					'Maharajadhiraja (Roi des rois)',
					'Samrat (Empereur)',
				],
				female: ['Maharani (Grande reine)', 'Rani (Reine)', 'Devi (Déesse)'],
			},
			{
				socialClass: 'clergy',
				male: ['Brahmane', 'Acharya (Maître)', 'Guru', 'Swami'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: [
					'Nayaka (Gouverneur)',
					'Senapati (Général)',
					'Dandanayaka (Commandant)',
				],
				female: [],
			},
			{
				socialClass: 'merchant',
				male: ['Shreshthi (Grand marchand)', 'Vanik'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Ryot'],
				female: [],
			},
		],
		namingConvention: 'given_surname',
		notes:
			'Noms sanskrits dynastiques. Les suffixes -deva (dieu), -pala (protecteur), -varman (armure), -sena (armée) sont fréquents. Le système des castes influence fortement les noms disponibles par classe sociale.',
	},

	// ========================================================================
	// TIBÉTAIN
	// ========================================================================
	{
		id: 'area_tibetan',
		name: 'Tibet',
		nationIds: ['nat_tibet'],
		maleFirstNames: [
			'Trisong',
			'Langdarma',
			'Yeshe',
			'Rinchen',
			'Palden',
			'Dorje',
			'Tenzin',
			'Ngawang',
			'Lobsang',
			'Jamyang',
			'Kunga',
			'Drakpa',
			'Sonam',
			'Phagpa',
			'Changchub',
			'Nyima',
			'Sangye',
			'Chogyel',
			'Tsewang',
			'Namgyal',
		],
		femaleFirstNames: [
			'Dolma',
			'Tara',
			'Lhamo',
			'Pema',
			'Dechen',
			'Yangzom',
			'Tsering',
			'Wangmo',
			'Choden',
			'Kelsang',
			'Dawa',
			'Norzom',
			'Sonam',
			'Rigzin',
			'Yeshe',
			'Sangye',
		],
		surnames: [
			'Yarlung',
			'Rlangs',
			'Dro',
			'Sba',
			'Mchims',
			'Gnubs',
			'Khyungpo',
			'Bro',
			'Dbas',
			'Lha',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Tsenpo (Empereur)', 'Gyelpo (Roi)', 'Depa (Gouverneur)'],
				female: ['Gyalmo (Reine)'],
			},
			{
				socialClass: 'clergy',
				male: ['Rinpoche', 'Lama', 'Geshe', 'Tulku', 'Khenpo (Abbé)'],
				female: ['Ani (Nonne)', 'Jetsunma'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Dpon (Seigneur)', 'Nangso (Chambellan)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Miwa'],
				female: [],
			},
		],
		namingConvention: 'given_only',
		notes:
			"Les Tibétains n'ont traditionnellement pas de nom de famille au sens occidental. Les noms sont donnés par un lama, souvent composés de 2 syllabes bouddhistes. Le nom de clan (rus) existe mais est moins utilisé que le prénom.",
	},

	// ========================================================================
	// MÉSOAMÉRICAIN (Toltèques, Mayas, Mississippiens)
	// ========================================================================
	{
		id: 'area_mesoamerican',
		name: 'Mésoamérique',
		nationIds: ['nat_toltec', 'nat_maya_states', 'nat_mississippian'],
		maleFirstNames: [
			'Ce Acatl',
			'Topiltzin',
			'Huemac',
			'Mixcoatl',
			'Tlahuicole',
			'Quetzalcoatl',
			'Nezahualcoyotl',
			'Itzamna',
			'Kukulkan',
			"K'inich",
			'Pakal',
			'Yax',
			'Bahlam',
			'Chan',
			'Chaak',
			'Ukit',
			'Tajoom',
			'Great Sun',
			'Tattooed Serpent',
			'Old Hair',
		],
		femaleFirstNames: [
			'Xochitl',
			'Cihuacoatl',
			'Chalchiuhtlicue',
			'Ixchel',
			'Lady Xoc',
			'Lady Six Sky',
			"Lady K'abel",
			'Wac Chanil',
			'Ix Mutal',
			'Lady Sak Kuk',
			"Tz'akbu Ajaw",
			'Lady Olnal',
			'White Deer',
			'Corn Mother',
			'Shell Woman',
			'Cloud Dancer',
		],
		surnames: [
			'Tolteca',
			'Tula',
			'Colhua',
			'Tepanec',
			"K'uhul Ajaw",
			'Tikal',
			'Calakmul',
			'Copán',
			'Palenque',
			'Uxmal',
			'Chichén',
			'Cahokia',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Tlatoani (Souverain)',
					"K'uhul Ajaw (Seigneur divin-Maya)",
					'Halach Uinik (Vrai homme)',
					'Great Sun',
				],
				female: [
					'Cihuacoatl (Femme serpent)',
					'Kaloomte (Reine guerrière)',
					'Ix Ajaw (Dame)',
				],
			},
			{
				socialClass: 'clergy',
				male: [
					'Tlamacazqui (Prêtre-Nahua)',
					"Ah K'in (Prêtre-Maya)",
					'Chilam (Prophète)',
				],
				female: ['Cihuatlamacazqui (Prêtresse)'],
			},
			{
				socialClass: 'minor_noble',
				male: [
					'Tecuhtli (Seigneur)',
					'Batab (Gouverneur-Maya)',
					'Sahal (Noble-Maya)',
					'Cuauhtli (Guerrier-Aigle)',
					'Ocelotl (Guerrier-Jaguar)',
				],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Macehualli (Roturier)'],
				female: [],
			},
		],
		namingConvention: 'given_clan',
		notes:
			'Nahuas : noms calendriques + nom de guerre (Ce Acatl = 1-Roseau jour de naissance). Mayas : glyphes-emblèmes dynastiques + noms théophores. Les noms mississippiens sont descriptifs et cérémoniels.',
	},

	// ========================================================================
	// ANDIN (Wari/Pré-Inca, Chimú, Muisca)
	// ========================================================================
	{
		id: 'area_andean',
		name: 'Monde andin',
		nationIds: ['nat_wari', 'nat_chimu', 'nat_muisca'],
		maleFirstNames: [
			'Tacaynamo',
			'Nancenpinco',
			'Minchancaman',
			'Huari',
			'Pachacamac',
			'Viracocha',
			'Sinchi',
			'Tupac',
			'Roca',
			'Capac',
			'Lloque',
			'Mayta',
			'Yahuar',
			'Inca',
			'Nemequene',
			'Tisquesusa',
			'Saguamanchica',
			'Michúa',
			'Hunzahúa',
			'Goranchacha',
		],
		femaleFirstNames: [
			'Mama Ocllo',
			'Mama Quilla',
			'Pachamama',
			'Coya',
			'Curi',
			'Chimpu',
			'Anawarque',
			'Raurawa',
			'Higuemota',
			'Bachué',
			'Chía',
			'Fura',
			'Nencatacoa',
			'Güecha',
			'Arachne',
			'Menca',
		],
		surnames: [
			'Chimú',
			'Wari',
			'Tiwanaku',
			'Sicán',
			'Lambayeque',
			'Ayllu',
			'Muisca',
			'Zipa',
			'Zaque',
			'Iraca',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Chimú Capac (Grand seigneur)',
					'Hatun Kuraka (Grand chef)',
					'Zipa (Roi-Muisca)',
					'Zaque (Roi-Muisca nord)',
				],
				female: ['Coya (Reine)', 'Ñusta (Princesse)'],
			},
			{
				socialClass: 'clergy',
				male: ['Willaq Umu (Grand prêtre)', 'Jeque (Prêtre-Muisca)'],
				female: ['Acllas (Vierges du soleil)'],
			},
			{
				socialClass: 'minor_noble',
				male: [
					'Kuraka (Seigneur local)',
					'Kamachiq (Administrateur)',
					'Güecha (Guerrier-Muisca)',
				],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Hatun Runa (Homme commun)'],
				female: [],
			},
		],
		namingConvention: 'given_clan',
		notes:
			"Noms quechua/aymara pour la zone andine. Noms muisca (chibcha) pour la Colombie. Souvent uniques + rattachement à l'ayllu (communauté). Les souverains portent des noms-titres sacrés.",
	},

	// ========================================================================
	// AMÉRIQUE DU NORD (Puebloans, Haida, Hohokam, etc.)
	// ========================================================================
	{
		id: 'area_north_american',
		name: 'Amérique du Nord autochtone',
		nationIds: [
			'nat_puebloans',
			'nat_haida',
			'nat_hohokam',
			'nat_dene',
			'nat_mikmaq',
			'nat_beothuk',
		],
		maleFirstNames: [
			'Standing Bear',
			'Running Deer',
			'Sky Eagle',
			'Red Cloud',
			'Strong Bow',
			'White Wolf',
			'Thunder Voice',
			'Raven Wing',
			'Cedar Man',
			'Salmon Boy',
			'Tall Pine',
			'Stone Carver',
			'Morning Star',
			'River Walker',
			'Corn Planter',
			'Flint Knapper',
			'Cloud Watcher',
			'Wind Singer',
			'Fire Keeper',
			'Moon Hunter',
		],
		femaleFirstNames: [
			'Corn Woman',
			'Shell Flower',
			'Morning Dew',
			'Blue Sky',
			'White Feather',
			'Moon Shadow',
			'River Song',
			'Cedar Root',
			'Turquoise Girl',
			'Spider Woman',
			'Rain Bringer',
			'Star Gazer',
			'Willow Bark',
			'Snow Bird',
			'Sage Blossom',
			'Basket Weaver',
		],
		surnames: [
			'Pueblo Bonito',
			'Chaco',
			'Mesa Verde',
			'Haida Gwaii',
			'Tsimshian',
			'Tlingit',
			'Hohokam',
			'Mogollon',
			'Athabascan',
			"Mi'kma'ki",
			'Beothuk',
			'Snuneymuxw',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Chief', 'Head Chief', 'War Chief', 'Village Leader'],
				female: ['Clan Mother', 'Village Mother'],
			},
			{
				socialClass: 'clergy',
				male: ['Medicine Man', 'Shaman', 'Storyteller', 'Dream Speaker'],
				female: ['Medicine Woman', 'Spirit Keeper'],
			},
			{
				socialClass: 'any',
				male: ['Elder', 'Hunter', 'Warrior', 'Carver'],
				female: ['Elder', 'Weaver', 'Potter', 'Healer'],
			},
		],
		namingConvention: 'given_only',
		notes:
			"Noms descriptifs liés à la nature, aux visions ou aux événements de vie. Les noms changent au cours de la vie (nom d'enfant → nom d'adulte → nom d'ancien). Les clans totémiques (Haida : Aigle/Corbeau) déterminent l'appartenance.",
	},

	// ========================================================================
	// AMAZONIEN / SUD-AMÉRICAIN (Guaraní, Mapuche)
	// ========================================================================
	{
		id: 'area_amazonian',
		name: 'Amérique du Sud (Guaraní, Mapuche)',
		nationIds: ['nat_guarani', 'nat_mapuche'],
		maleFirstNames: [
			'Tupã',
			'Ñamandu',
			'Arasy',
			'Kuarahy',
			'Jasy',
			'Tume',
			'Arandú',
			'Guaicurú',
			'Teyú',
			'Karai',
			'Lautaro',
			'Caupolicán',
			'Colocolo',
			'Galvarino',
			'Pelantaro',
			'Leftraru',
			'Michimalongo',
			'Toqui',
			'Lientur',
			'Butapichón',
		],
		femaleFirstNames: [
			'Jasy',
			'Arasy',
			'Kuñataí',
			'Ñasaindy',
			'Mbyja',
			'Tajy',
			'Guajaki',
			'Iracema',
			'Fresia',
			'Guacolda',
			'Janequeo',
			'Tegualda',
			'Rayen',
			'Millaray',
			'Sayen',
			'Ayelen',
		],
		surnames: [
			'Guaraní',
			'Tupi',
			'Chiriguano',
			'Avá',
			'Mbyá',
			'Mapuche',
			'Reche',
			'Huilliche',
			'Pehuenche',
			'Picunche',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Tuvichá (Chef-Guaraní)',
					'Toqui (Chef de guerre-Mapuche)',
					'Lonco (Chef de paix)',
				],
				female: ['Machí (Chamane-Mapuche)'],
			},
			{
				socialClass: 'clergy',
				male: [
					'Paí (Chamane-Guaraní)',
					'Ñanderu (Père spirituel)',
					'Kalku (Sorcier-Mapuche)',
				],
				female: ['Machí (Chamane)'],
			},
			{
				socialClass: 'any',
				male: ['Koanga (Guerrier)'],
				female: [],
			},
		],
		namingConvention: 'given_tribal',
		notes:
			'Guaraní : noms liés aux esprits de la nature (Tupã=tonnerre, Jasy=lune). Mapuche : noms décrivant des qualités ou la nature (Lautaro=traro rapide, Rayen=fleur). Noms secrets + noms publics.',
	},

	// ========================================================================
	// POLYNÉSIEN (Tonga, Fidji, Chamorro)
	// ========================================================================
	{
		id: 'area_polynesian',
		name: 'Océanie (Polynésie, Mélanésie, Micronésie)',
		nationIds: ['nat_tui_tonga', 'nat_fiji', 'nat_chamorro', 'nat_hawaii'],
		maleFirstNames: [
			"Tu'itatui",
			'Takalaua',
			"Kau'ulufonua",
			'Havea',
			'Momo',
			"Tele'a",
			"Fakanaana'a",
			'Ratu',
			'Vuniwaqa',
			'Cakobau',
			'Tanoa',
			'Varani',
			'Quipuha',
			'Hurao',
			"Mata'pang",
			'Gadao',
			'Maui',
			'Tane',
			'Tangaroa',
			'Lono',
		],
		femaleFirstNames: [
			'Hina',
			'Sina',
			'Nafanua',
			'Salamasina',
			'Hinauri',
			'Adi',
			'Bulou',
			'Litia',
			'Mere',
			'Luisa',
			"Maga'håga",
			'Maria',
			"Fo'ou",
			'Lahi',
			'Toa',
			'Moana',
		],
		surnames: [
			"Tu'i Tonga",
			"Ha'a Takalaua",
			"Ha'a Moheofo",
			'Tui Nayau',
			'Tui Viti',
			'Roko Tui',
			"Maga'låhi",
			"Maga'håga",
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					"Tu'i (Roi sacré)",
					'Ratu (Chef-Fidji)',
					"Maga'låhi (Chef-Chamorro)",
				],
				female: [
					'Tamahā (Reine sacrée-Tonga)',
					'Adi (Dame-Fidji)',
					"Maga'håga (Cheftaine-Chamorro)",
				],
			},
			{
				socialClass: 'clergy',
				male: [
					'Taula (Prêtre-Tonga)',
					'Bete (Prêtre-Fidji)',
					'Makahna (Chamane)',
				],
				female: ['Tobonga (Prêtresse)'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Matāpule (Orateur cérémoniel)', 'Buli (Chef de district)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ["Tu'a (Roturier)"],
				female: [],
			},
		],
		namingConvention: 'given_clan',
		notes:
			'Noms souvent liés aux dieux et héros mythiques (Maui, Tangaroa). Hiérarchie stricte : les noms royaux sont tapu (sacrés). Patronymique + titre de rang. Les Chamorro ont un système matrilinéaire.',
	},

	// ========================================================================
	// PAPOUAN
	// ========================================================================
	{
		id: 'area_papuan',
		name: 'Nouvelle-Guinée (peuples papous)',
		nationIds: ['nat_papuan'],
		maleFirstNames: [
			'Ongka',
			'Kawelka',
			'Ndika',
			'Minembi',
			'Tipuka',
			'Kengeke',
			'Komapi',
			'Manga',
			'Wurup',
			'Ketan',
			'Moka',
			'Ru',
			'Pena',
			'Wia',
			'Ndamba',
			'Kuri',
		],
		femaleFirstNames: [
			'Amb',
			'Mbo',
			'Mendi',
			'Roga',
			'Wena',
			'Penga',
			'Pukl',
			'Mang',
			'Kolta',
			'Wöi',
			'Manga',
			'Rimbu',
		],
		surnames: [
			'Melpa',
			'Hagen',
			'Huli',
			'Dani',
			'Asmat',
			'Sepik',
			'Chimbu',
			'Enga',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Big Man (Chef par prestige)'],
				female: [],
			},
			{
				socialClass: 'clergy',
				male: ['Spirit Man', 'Dream Interpreter'],
				female: ['Spirit Woman'],
			},
			{
				socialClass: 'any',
				male: ['Warrior', 'Trade Partner'],
				female: [],
			},
		],
		namingConvention: 'given_clan',
		notes:
			"Système Big Man : le leader n'hérite pas du pouvoir, il le gagne par la redistribution de richesses (cochons, coquillages). Noms liés au clan + surnom d'exploit. Très grande diversité linguistique (800+ langues).",
	},

	// ========================================================================
	// ARCTIQUE (Thulé/proto-Inuit, Dorset, Sami, Tchouktches)
	// ========================================================================
	{
		id: 'area_arctic',
		name: 'Peuples arctiques',
		nationIds: ['nat_thule', 'nat_dorset', 'nat_sami', 'nat_chukchi'],
		maleFirstNames: [
			'Qilak',
			'Siku',
			'Nanuq',
			'Tulugaq',
			'Amaruq',
			'Tatkret',
			'Kiviuq',
			'Atanarjuat',
			'Sila',
			'Tuurngaq',
			'Ailo',
			'Jovnna',
			'Niillas',
			'Ánde',
			'Gáhtte',
			'Risten',
			'Umky',
			'Kymytval',
			'Tymnev',
			"Val'gyrgin",
		],
		femaleFirstNames: [
			'Sedna',
			'Arnaq',
			'Pinga',
			'Maliina',
			'Siku',
			'Nuliajuk',
			'Tigua',
			'Niviarsiaq',
			'Máret',
			'Sáhká',
			'Risten',
			'Rávdná',
			'Elle',
			"Tyneril'o",
			'Omrytkot',
			'Giivamrav',
		],
		surnames: [
			'Thulé',
			'Inupiaq',
			'Yupik',
			'Dorset',
			'Sámi',
			'Chukchi',
			'Koryak',
			'Tuniit',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					"Isumataaq (Celui dont on suit l'avis)",
					'Siida-isit (Chef de campement-Sami)',
				],
				female: [],
			},
			{
				socialClass: 'clergy',
				male: [
					'Angakkuq (Chamane-Inuit)',
					'Noaidi (Chamane-Sami)',
					"Ene'nil'in (Chamane-Chukchi)",
				],
				female: ['Angakkuq (Chamane-Inuit)', 'Noaidi (Chamane-Sami)'],
			},
			{
				socialClass: 'any',
				male: ['Hunter', 'Umiak Captain'],
				female: ['Seamstress', 'Healer'],
			},
		],
		namingConvention: 'given_only',
		notes:
			'Noms liés aux esprits animaux et aux forces naturelles. Tradition de "soulname" : on donne le nom d\'un ancêtre décédé (l\'âme du nom vit dans le nouveau-né). Les Sami utilisent des noms nordiques + sami.',
	},

	// ========================================================================
	// AÏNOU (Hokkaido)
	// ========================================================================
	{
		id: 'area_ainu',
		name: 'Aïnous (Hokkaido)',
		nationIds: ['nat_ainu'],
		maleFirstNames: [
			'Shakushain',
			'Koshamain',
			'Samkusainu',
			'Menashunkur',
			'Haukase',
			'Tsukinoe',
			'Shutain',
			'Tashiro',
			'Onibishi',
			'Tottari',
			'Ikotoi',
			'Nitaru',
			'Kamuinu',
			'Retar',
			'Isekari',
			'Ekashipe',
		],
		femaleFirstNames: [
			'Chikap',
			'Pirka',
			'Rera',
			'Huci',
			'Matnepo',
			'Nonno',
			'Resu',
			'Ashiri',
			'Kewtum',
			'Sirar',
			'Nupuri',
			'Yairese',
		],
		surnames: [
			'Ainu',
			'Kotan',
			'Pirka',
			'Kamui',
			'Mosir',
			'Saru',
			'Ishikari',
			'Tokachi',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Ekashi (Ancien/Chef de village)'],
				female: ['Huci (Ancienne)'],
			},
			{
				socialClass: 'clergy',
				male: ['Tusukur (Chamane)'],
				female: ['Tusukur (Chamane)'],
			},
			{
				socialClass: 'any',
				male: ['Nisgur (Chasseur)', 'Kotan-kor-kur (Maître du village)'],
				female: [],
			},
		],
		namingConvention: 'given_only',
		notes:
			"Les Aïnous n'utilisent traditionnellement pas de noms de famille. Noms liés à la nature et aux kamui (esprits). Les enfants reçoivent un nom temporaire, puis un nom définitif à l'adolescence. Tabou de prononcer le vrai nom — on utilise des surnoms.",
	},

	// ========================================================================
	// ABORIGÈNE AUSTRALIEN
	// ========================================================================
	{
		id: 'area_aboriginal',
		name: 'Nations aborigènes australiennes',
		nationIds: ['nat_aboriginal'],
		maleFirstNames: [
			'Baiame',
			'Daramulum',
			'Bunjil',
			'Tiddalik',
			'Wayambeh',
			'Yhi',
			'Biami',
			'Nurunderi',
			'Murrundi',
			'Kangaroo',
			'Wombat',
			'Emu',
			'Goanna',
			'Pelican',
			'Eagle Hawk',
			'Crow',
		],
		femaleFirstNames: [
			'Yhi',
			'Birrahgnooloo',
			'Julunggul',
			'Wala',
			'Kunapipi',
			'Djanggawul',
			'Melatji',
			'Wawalak',
			'Eingana',
			'Warramurrungunji',
			'Moon',
			'Star',
		],
		surnames: [
			'Yolngu',
			'Aranda',
			'Warlpiri',
			'Pitjantjatjara',
			'Ngarrindjeri',
			'Kaurna',
			'Gamilaroi',
			'Wiradjuri',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Elder'],
				female: ['Elder'],
			},
			{
				socialClass: 'clergy',
				male: ['Songman', 'Clever Man', 'Law Man'],
				female: ['Clever Woman', 'Law Woman'],
			},
			{
				socialClass: 'any',
				male: ['Hunter', 'Tracker'],
				female: ['Gatherer', 'Healer'],
			},
		],
		namingConvention: 'given_only',
		notes:
			"Les vrais noms sont souvent secrets/sacrés. Les noms publics sont des surnoms ou des noms de Dreamtime (Temps du Rêve). Tabou de prononcer le nom d'un défunt — on change alors les mots similaires dans la langue.",
	},

	// ========================================================================
	// MALGACHE
	// ========================================================================
	{
		id: 'area_malagasy',
		name: 'Madagascar',
		nationIds: ['nat_malagasy'],
		maleFirstNames: [
			'Andriamanitra',
			'Andriambahoaka',
			'Ralambo',
			'Andrianjaka',
			'Rafohy',
			'Rangita',
			'Andrianampoinimerina',
			'Radama',
			'Ratsimilaho',
			'Ramboasalama',
			'Andriamanelo',
			'Rabiby',
			'Andriantompokoindrindra',
			'Razakatsitakatrandriana',
			'Ralaimahatody',
			'Andriandahifotsy',
		],
		femaleFirstNames: [
			'Ranavalona',
			'Rasalimo',
			'Rasoherina',
			'Rabodo',
			'Ramavo',
			'Raketaka',
			'Rafotsy',
			'Ranaivo',
			'Ramaitsoanala',
			'Ratsimandresy',
			'Razafitrimo',
			'Voninahitsy',
		],
		surnames: [
			'Merina',
			'Betsileo',
			'Betsimisaraka',
			'Sakalava',
			'Antandroy',
			'Antaimoro',
			'Mahafaly',
			'Vazimba',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Andriana (Noble)', 'Mpanjaka (Roi)'],
				female: ['Andriambavy (Princesse)', 'Mpanjakavavy (Reine)'],
			},
			{
				socialClass: 'clergy',
				male: ['Ombiasy (Devin-guérisseur)', 'Mpanandro (Astrologue)'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Hova (Notable libre)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Andevo'],
				female: [],
			},
		],
		namingConvention: 'given_only',
		notes:
			'Noms très longs, souvent composés de phrases entières. Préfixe Ra- (commun/respect) ou Andria- (noble). Peuples austronésiens + influences bantoues et arabes. Le fady (tabou) interdit certains noms.',
	},

	// ========================================================================
	// GUANCHE (Canaries)
	// ========================================================================
	{
		id: 'area_guanche',
		name: 'Guanches (îles Canaries)',
		nationIds: ['nat_guanche'],
		maleFirstNames: [
			'Tenerife',
			'Doramas',
			'Bentejuí',
			'Bencomo',
			'Adeje',
			'Anaterve',
			'Pelinor',
			'Acaimo',
			'Tegueste',
			'Beneharo',
			'Adjona',
			'Pelicar',
			'Ichasagua',
			'Guetón',
			'Atbitocazpe',
			'Tagoter',
		],
		femaleFirstNames: [
			'Dácil',
			'Guayarmina',
			'Tenesoya',
			'Cathaysa',
			'Ramagua',
			'Andamana',
			'Abenchara',
			'Tibiabin',
			'Ico',
			'Acerina',
			'Chaxiraxi',
			'Arminda',
		],
		surnames: [
			'Mencey',
			'Guanarteme',
			'Faicán',
			'Canarii',
			'Maxorata',
			'Bimbache',
		],
		titles: [
			{
				socialClass: 'noble',
				male: ['Mencey (Roi-Tenerife)', 'Guanarteme (Roi-Gran Canaria)'],
				female: ['Guayarmina (Princesse)'],
			},
			{
				socialClass: 'clergy',
				male: ['Faicán (Grand prêtre)', 'Guadameñe (Prêtre)'],
				female: ['Harimaguada (Prêtresse)'],
			},
			{
				socialClass: 'minor_noble',
				male: ['Achimencey (Noble)'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Achicaxna'],
				female: [],
			},
		],
		namingConvention: 'given_only',
		notes:
			'Peuple berbère isolé. Noms pré-hispaniques reconstitués à partir des chroniques espagnoles. Chaque île avait son propre dialecte et ses propres noms. Le menceyato (royaume) était la structure politique de Tenerife.',
	},

	// ========================================================================
	// BERBÈRE / TOUAREG (complémentaire à l'Afrique de l'Ouest)
	// ========================================================================
	{
		id: 'area_berber',
		name: 'Monde berbère (Sanhadja/Touaregs)',
		nationIds: [], // nat_tuareg est déjà dans area_west_african — ce pool sert de complément berbère
		maleFirstNames: [
			'Tin-Hinan',
			'Amenokal',
			'Amayas',
			'Aksil',
			'Yuba',
			'Masinissa',
			'Jugurtha',
			'Koceila',
			'Kahina',
			'Tariq',
			'Buluggin',
			'Ziri',
			'Hammad',
			'Muqran',
			'Yaghmurasen',
			'Gaia',
			'Micipsa',
			'Takfarinas',
			'Aderfi',
			'Agellid',
		],
		femaleFirstNames: [
			'Kahina',
			'Tin-Hinan',
			'Dihya',
			'Tiziri',
			'Tafukt',
			'Tamimunt',
			'Tawenza',
			'Tilelli',
			'Taninna',
			'Tayri',
			'Wardia',
			'Tasa',
		],
		surnames: [
			'ag Aman',
			'ag Ataram',
			'ag Elher',
			'ult Amayas',
			'Kel Ahaggar',
			'Kel Aïr',
			'Kel Adrar',
			'Sanhadja',
			'Zirid',
			'Hammadid',
		],
		titles: [
			{
				socialClass: 'noble',
				male: [
					'Amenokal (Chef suprême)',
					'Agellid (Roi)',
					'Amghar (Chef de tribu)',
				],
				female: ['Tamenokalt (Cheftaine)'],
			},
			{
				socialClass: 'clergy',
				male: ['Ineslemen (Marabout)', 'Amrabeḍ'],
				female: [],
			},
			{
				socialClass: 'minor_noble',
				male: ['Imajeghen (Noble-Touareg)', 'Ettebel'],
				female: [],
			},
			{
				socialClass: 'peasant',
				male: ['Imghad (Tributaire)'],
				female: [],
			},
		],
		namingConvention: 'given_ibn_father',
		notes:
			"Patronymique : ag (fils de) / ult (fille de). Les Touaregs sont matrilinéaires pour l'héritage. Noms amazighs + influence arabe post-islamisation. L'amenokal est élu par les nobles, pas héréditaire.",
	},
]
