import type { RegionEcology } from '../../../shared/src/types/world'

// ============================================================================
// Écologie régionale — An 1000
// ============================================================================
// Chaque entrée correspond à une ClimateRegion (via regionId).
// forestCoverage : ratio 0-1
// biodiversity / humanImpact : 0-10
// ============================================================================

export const ecologyData: RegionEcology[] = [
	// ========================================================================
	// EUROPE TEMPÉRÉE
	// ========================================================================
	{
		regionId: 'clim_temperate_europe',
		dominantFlora: [
			'chêne',
			'hêtre',
			'frêne',
			'orme',
			'tilleul',
			'noisetier',
			'blé',
			'seigle',
			'orge',
			'avoine',
			'lin',
			'chanvre',
		],
		dominantFauna: [
			'loup',
			'ours_brun',
			'cerf',
			'sanglier',
			'renard',
			'aigle_royal',
			'aurochs',
			'bison_européen',
			'castor',
			'loutre',
		],
		domesticatedAnimals: [
			'cheval',
			'bœuf',
			'porc',
			'mouton',
			'chèvre',
			'poule',
			'oie',
			'chien',
		],
		domesticatedPlants: [
			'blé',
			'seigle',
			'orge',
			'avoine',
			'lin',
			'chou',
			'navet',
			'fève',
			'vigne',
		],
		forestCoverage: 0.65,
		biodiversity: 6,
		humanImpact: 4,
	},

	// ========================================================================
	// MÉDITERRANÉE
	// ========================================================================
	{
		regionId: 'clim_mediterranean',
		dominantFlora: [
			'olivier',
			'chêne_vert',
			'pin_maritime',
			'cyprès',
			'laurier',
			'maquis',
			'garrigue',
			'vigne',
			'figuier',
			'amandier',
		],
		dominantFauna: [
			'loup_ibérique',
			'lynx',
			'aigle_impérial',
			'dauphin',
			'tortue_marine',
			'flamant_rose',
			'thon',
			'sardine',
		],
		domesticatedAnimals: [
			'cheval',
			'âne',
			'mouton',
			'chèvre',
			'bœuf',
			'poule',
			'abeille',
		],
		domesticatedPlants: [
			'blé',
			'olivier',
			'vigne',
			'figuier',
			'amandier',
			'citronnier',
			'oranger',
		],
		forestCoverage: 0.35,
		biodiversity: 7,
		humanImpact: 6, // déforestation ancienne (Antiquité)
	},

	// ========================================================================
	// SUBARCTIQUE (Scandinavie, Islande)
	// ========================================================================
	{
		regionId: 'clim_subarctic',
		dominantFlora: [
			'épicéa',
			'pin_sylvestre',
			'bouleau',
			'saule_arctique',
			'mousse',
			'lichen',
			'myrtille',
			'airelle',
		],
		dominantFauna: [
			'ours_polaire',
			'renne',
			'élan',
			'loup',
			'glouton',
			'renard_arctique',
			'harfang_des_neiges',
			'morse',
			'baleine',
			'saumon',
			'morue',
		],
		domesticatedAnimals: [
			'cheval_islandais',
			'mouton',
			'chèvre',
			'chien',
			'renne',
		],
		domesticatedPlants: ['orge', 'avoine'], // agriculture très limitée
		forestCoverage: 0.4,
		biodiversity: 4,
		humanImpact: 1,
	},

	// ========================================================================
	// EUROPE ORIENTALE CONTINENTALE
	// ========================================================================
	{
		regionId: 'clim_continental_east_europe',
		dominantFlora: [
			'chêne',
			'bouleau',
			'pin',
			'sapin',
			'tilleul',
			'steppe_herbeuse',
			'seigle',
			'blé',
		],
		dominantFauna: [
			'loup',
			'ours_brun',
			'bison_européen',
			'cerf',
			'élan',
			'castor',
			'loutre',
			'esturgeon',
			'aigle_des_steppes',
		],
		domesticatedAnimals: [
			'cheval',
			'bœuf',
			'porc',
			'mouton',
			'chèvre',
			'chien',
			'abeille',
		],
		domesticatedPlants: [
			'seigle',
			'blé',
			'orge',
			'millet',
			'lin',
			'navet',
			'chou',
		],
		forestCoverage: 0.6,
		biodiversity: 6,
		humanImpact: 2,
	},

	// ========================================================================
	// MOYEN-ORIENT ARIDE
	// ========================================================================
	{
		regionId: 'clim_arid_mideast',
		dominantFlora: [
			'palmier_dattier',
			'tamaris',
			'acacia',
			'jujubier',
			'roseaux',
			'pistachier',
			'grenadier',
		],
		dominantFauna: [
			'gazelle',
			'oryx',
			'hyène_rayée',
			'chacal',
			'vautour',
			'scorpion',
			'cobra',
			'faucon',
		],
		domesticatedAnimals: [
			'chameau',
			'cheval_arabe',
			'âne',
			'mouton',
			'chèvre',
			'faucon',
		],
		domesticatedPlants: [
			'blé',
			'orge',
			'datte',
			'grenade',
			'safran',
			'coton',
			'canne_à_sucre',
		],
		forestCoverage: 0.05,
		biodiversity: 4,
		humanImpact: 5, // irrigation ancienne, déforestation historique
	},

	// ========================================================================
	// SAHARA
	// ========================================================================
	{
		regionId: 'clim_saharan',
		dominantFlora: ['palmier_dattier', 'acacia', 'tamaris', 'euphorbe'],
		dominantFauna: [
			'fennec',
			'addax',
			'gazelle_dorcas',
			'vipère_à_cornes',
			'scorpion',
			'vautour_fauve',
			'dromadaire_sauvage',
		],
		domesticatedAnimals: ['dromadaire', 'chèvre'],
		domesticatedPlants: ['datte', 'mil'], // oasis uniquement
		forestCoverage: 0.01,
		biodiversity: 2,
		humanImpact: 1,
	},

	// ========================================================================
	// VALLÉE DU NIL
	// ========================================================================
	{
		regionId: 'clim_nile_valley',
		dominantFlora: [
			'papyrus',
			'lotus',
			'palmier_dattier',
			'acacia_nilotique',
			'tamaris',
			'sycomore',
			'blé',
			'lin',
		],
		dominantFauna: [
			'crocodile_du_nil',
			'hippopotame',
			'ibis',
			'aigrette',
			'perche_du_nil',
			'cobra_égyptien',
			'vautour',
		],
		domesticatedAnimals: [
			'âne',
			'bœuf',
			'mouton',
			'chèvre',
			'pigeon',
			'abeille',
		],
		domesticatedPlants: [
			'blé',
			'orge',
			'lin',
			'papyrus',
			'palmier_dattier',
			'lentille',
			'oignon',
		],
		forestCoverage: 0.05,
		biodiversity: 5,
		humanImpact: 7, // 5000 ans d'agriculture intensive
	},

	// ========================================================================
	// STEPPE D'ASIE CENTRALE
	// ========================================================================
	{
		regionId: 'clim_central_asia_steppe',
		dominantFlora: [
			'herbe_des_steppes',
			'artemisia',
			'saxaoul',
			'peuplier_de_l_euphrate',
		],
		dominantFauna: [
			'cheval_de_przewalski',
			'saïga',
			'loup_des_steppes',
			'aigle_royal',
			'marmotte',
			'hamster',
			'vautour',
			'renard_corsac',
		],
		domesticatedAnimals: [
			'cheval',
			'mouton',
			'chèvre',
			'chameau_de_bactriane',
			'yak',
			'chien',
		],
		domesticatedPlants: ['blé', 'orge', 'millet', 'coton'], // culture dans les oasis
		forestCoverage: 0.05,
		biodiversity: 4,
		humanImpact: 2, // nomadisme faible impact
	},

	// ========================================================================
	// PLATEAU TIBÉTAIN
	// ========================================================================
	{
		regionId: 'clim_tibetan_plateau',
		dominantFlora: [
			'prairie_alpine',
			'rhododendron',
			'genévrier',
			'mousse',
			'orge_du_tibet',
		],
		dominantFauna: [
			'yak_sauvage',
			'antilope_du_tibet',
			'léopard_des_neiges',
			'grue_à_cou_noir',
			'pika',
			'loup_du_tibet',
			'ours_brun_du_tibet',
		],
		domesticatedAnimals: [
			'yak',
			'mouton',
			'chèvre',
			'cheval_du_tibet',
			'chien_de_mastiff',
		],
		domesticatedPlants: ['orge', 'navet'], // très peu de culture possible
		forestCoverage: 0.05,
		biodiversity: 4,
		humanImpact: 1,
	},

	// ========================================================================
	// ASIE DE L'EST (zone de mousson)
	// ========================================================================
	{
		regionId: 'clim_east_asia',
		dominantFlora: [
			'bambou',
			'pin',
			'ginkgo',
			'camphrier',
			'mûrier',
			'riz',
			'thé',
			'soja',
			'lotus',
		],
		dominantFauna: [
			'tigre_de_chine',
			'panda_géant',
			'grue_du_japon',
			'daim_sika',
			'pangolin',
			'macaque',
			'carpe',
			'silure',
			'aigle',
		],
		domesticatedAnimals: [
			'buffle_d_eau',
			'porc',
			'poule',
			'canard',
			'ver_à_soie',
			'chien',
			'cheval',
		],
		domesticatedPlants: [
			'riz',
			'millet',
			'soja',
			'thé',
			'mûrier',
			'bambou',
			'lotus',
			'litchi',
			'abricot',
		],
		forestCoverage: 0.45,
		biodiversity: 9,
		humanImpact: 6, // riziculture intensive, déforestation Song
	},

	// ========================================================================
	// STEPPE D'ASIE DE L'EST (Mongolie, Mandchourie)
	// ========================================================================
	{
		regionId: 'clim_east_asia_steppe',
		dominantFlora: ['herbe_des_steppes', 'armoise', 'mélèze', 'bouleau'],
		dominantFauna: [
			'loup',
			'cheval_de_przewalski',
			'gazelle_de_mongolie',
			'marmotte',
			'aigle_royal',
			'grue_de_sibérie',
			'cerf_de_sibérie',
		],
		domesticatedAnimals: [
			'cheval',
			'mouton',
			'chèvre',
			'chameau_de_bactriane',
			'bœuf',
			'chien',
		],
		domesticatedPlants: ['millet'], // quasi-exclusivement pastoral
		forestCoverage: 0.1,
		biodiversity: 4,
		humanImpact: 1,
	},

	// ========================================================================
	// ASIE DU SUD-EST
	// ========================================================================
	{
		regionId: 'clim_southeast_asia',
		dominantFlora: [
			'teck',
			'bambou',
			'palmier',
			'cocotier',
			'bananier',
			'poivrier',
			'muscadier',
			'giroflier',
			'riz',
			'sagoutier',
		],
		dominantFauna: [
			'tigre',
			'éléphant_d_asie',
			'rhinocéros_de_java',
			'orang_outan',
			'python',
			'dragon_de_komodo',
			'calao',
			'raie_manta',
		],
		domesticatedAnimals: [
			'buffle_d_eau',
			'porc',
			'poule',
			'canard',
			'éléphant',
		],
		domesticatedPlants: [
			'riz',
			'coco',
			'banane',
			'poivre',
			'muscade',
			'girofle',
			'canne_à_sucre',
			'sagou',
		],
		forestCoverage: 0.8,
		biodiversity: 10,
		humanImpact: 2,
	},

	// ========================================================================
	// ASIE DU SUD (sous-continent indien)
	// ========================================================================
	{
		regionId: 'clim_south_asia',
		dominantFlora: [
			'teck',
			'banian',
			'cocotier',
			'bambou',
			'santal',
			'riz',
			'coton',
			'canne_à_sucre',
			'poivrier',
			'curcuma',
		],
		dominantFauna: [
			'tigre_du_bengale',
			'éléphant_d_asie',
			'rhinocéros_indien',
			'paon',
			'cobra_royal',
			'léopard',
			'macaque',
			'gavial',
		],
		domesticatedAnimals: [
			'buffle_d_eau',
			'zébu',
			'éléphant',
			'chèvre',
			'mouton',
			'poule',
			'chien',
		],
		domesticatedPlants: [
			'riz',
			'blé',
			'coton',
			'canne_à_sucre',
			'poivre',
			'curcuma',
			'manguier',
			'bananier',
			'jute',
		],
		forestCoverage: 0.5,
		biodiversity: 9,
		humanImpact: 5,
	},

	// ========================================================================
	// AFRIQUE TROPICALE
	// ========================================================================
	{
		regionId: 'clim_tropical_africa',
		dominantFlora: [
			'baobab',
			'iroko',
			'palmier_à_huile',
			'karité',
			'acajou',
			'sorgho',
			'millet',
			'igname',
			'kola',
		],
		dominantFauna: [
			'lion',
			'éléphant_d_afrique',
			'gorille',
			'hippopotame',
			'girafe',
			'zèbre',
			'rhinocéros_noir',
			'autruche',
			'crocodile',
			'python_royal',
		],
		domesticatedAnimals: [
			'zébu',
			'chèvre',
			'mouton',
			'âne',
			'poule_de_guinée',
			'chien',
		],
		domesticatedPlants: [
			'sorgho',
			'millet',
			'igname',
			'palmier_à_huile',
			'kola',
			'café',
		],
		forestCoverage: 0.6,
		biodiversity: 10,
		humanImpact: 2,
	},

	// ========================================================================
	// SAHEL
	// ========================================================================
	{
		regionId: 'clim_sahel',
		dominantFlora: [
			'baobab',
			'acacia_sahélienne',
			'tamarinier',
			'mil',
			'karité',
			'néré',
		],
		dominantFauna: [
			'lion',
			'hyène',
			'chacal',
			'autruche',
			'gazelle',
			'vautour',
			'scorpion',
			'varan',
		],
		domesticatedAnimals: [
			'dromadaire',
			'zébu',
			'chèvre',
			'mouton',
			'cheval',
			'âne',
		],
		domesticatedPlants: ['mil', 'sorgho', 'niébé', 'arachide'],
		forestCoverage: 0.1,
		biodiversity: 4,
		humanImpact: 3,
	},

	// ========================================================================
	// HAUTS-PLATEAUX D'AFRIQUE DE L'EST
	// ========================================================================
	{
		regionId: 'clim_east_africa_highland',
		dominantFlora: [
			'genévrier_d_afrique',
			'bambou_de_montagne',
			'lobélie_géante',
			'teff',
			'enset',
			'caféier',
		],
		dominantFauna: [
			'gélada',
			'loup_d_éthiopie',
			'nyala_de_montagne',
			'léopard',
			'aigle_de_verreaux',
			'ibis',
			'flamant',
		],
		domesticatedAnimals: [
			'zébu',
			'mouton',
			'chèvre',
			'âne',
			'cheval',
			'abeille',
		],
		domesticatedPlants: ['teff', 'enset', 'orge', 'café', 'sorgho'],
		forestCoverage: 0.35,
		biodiversity: 7,
		humanImpact: 3,
	},

	// ========================================================================
	// MÉSOAMÉRIQUE
	// ========================================================================
	{
		regionId: 'clim_mesoamerica',
		dominantFlora: [
			'ceiba',
			'acajou',
			'cactus',
			'agave',
			'maïs',
			'haricot',
			'courge',
			'cacaoyer',
			'vanillier',
			'avocatier',
		],
		dominantFauna: [
			'jaguar',
			'puma',
			'quetzal',
			'ara',
			'serpent_à_sonnettes',
			'iguane',
			'tapir',
			'singe_hurleur',
			'dindon_sauvage',
		],
		domesticatedAnimals: ['dindon', 'chien'], // pas de grands mammifères domestiqués
		domesticatedPlants: [
			'maïs',
			'haricot',
			'courge',
			'cacao',
			'piment',
			'amarante',
			'tomate',
			'vanille',
			'agave',
		],
		forestCoverage: 0.6,
		biodiversity: 9,
		humanImpact: 4, // défrichement maya en déclin
	},

	// ========================================================================
	// VALLÉE DU MISSISSIPPI
	// ========================================================================
	{
		regionId: 'clim_mississippi_valley',
		dominantFlora: [
			'chêne',
			'érable',
			'noyer',
			'cyprès_chauve',
			'peuplier',
			'maïs',
			'tournesol',
			'courge',
		],
		dominantFauna: [
			'bison',
			'cerf_de_virginie',
			'ours_noir',
			'dindon_sauvage',
			'aigle_à_tête_blanche',
			'poisson_chat',
			'alligator',
			'castor',
			'loutre',
		],
		domesticatedAnimals: ['chien'], // pas de bétail domestiqué
		domesticatedPlants: ['maïs', 'haricot', 'courge', 'tournesol', 'tabac'],
		forestCoverage: 0.7,
		biodiversity: 7,
		humanImpact: 2,
	},

	// ========================================================================
	// HAUTS-PLATEAUX ANDINS
	// ========================================================================
	{
		regionId: 'clim_andes_highland',
		dominantFlora: [
			'pomme_de_terre',
			'quinoa',
			'kiwicha',
			'polylepis',
			'ichu',
			'puya_raimondii',
			'coca',
		],
		dominantFauna: [
			'condor',
			'lama_sauvage',
			'vigogne',
			'viscache',
			'puma',
			'renard_andin',
			'chinchilla',
		],
		domesticatedAnimals: ['lama', 'alpaga', 'cochon_d_inde', 'chien'],
		domesticatedPlants: [
			'pomme_de_terre',
			'quinoa',
			'maïs',
			'coca',
			'kiwicha',
			'oca',
		],
		forestCoverage: 0.1,
		biodiversity: 6,
		humanImpact: 4, // terrasses Wari
	},

	// ========================================================================
	// JAPON
	// ========================================================================
	{
		regionId: 'clim_japan',
		dominantFlora: [
			'cryptoméria',
			'pin_japonais',
			'érable_japonais',
			'bambou',
			'cerisier',
			'riz',
			'mûrier',
			'thé',
		],
		dominantFauna: [
			'macaque_japonais',
			'cerf_sika',
			'ours_noir_d_asie',
			'grue_du_japon',
			'tanuki',
			'thon',
			'saumon',
			'aigle',
		],
		domesticatedAnimals: ['cheval', 'bœuf', 'poule', 'ver_à_soie', 'chien'],
		domesticatedPlants: [
			'riz',
			'millet',
			'soja',
			'thé',
			'mûrier',
			'daikon',
			'prune',
		],
		forestCoverage: 0.7,
		biodiversity: 7,
		humanImpact: 4,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================
	{
		regionId: 'clim_southwest_north_america',
		dominantFlora: [
			'pin_ponderosa',
			'genévrier',
			'cactus_saguaro',
			'yucca',
			'sauge',
			'maïs',
			'courge',
			'haricot',
		],
		dominantFauna: [
			'bison',
			'cerf_mulet',
			'coyote',
			'serpent_à_sonnettes',
			'dindon',
			'aigle_royal',
			'lièvre',
			'puma',
		],
		domesticatedAnimals: ['dindon', 'chien'],
		domesticatedPlants: ['maïs', 'courge', 'haricot', 'coton', 'tournesol'],
		forestCoverage: 0.15,
		biodiversity: 5,
		humanImpact: 3,
	},
	{
		regionId: 'clim_pacific_northwest',
		dominantFlora: [
			'cèdre_rouge',
			'sapin_de_douglas',
			'épicéa_de_sitka',
			'pruche',
			'fougère',
			'mousse',
			'baie_de_salal',
			'if_du_pacifique',
		],
		dominantFauna: [
			'saumon_du_pacifique',
			'orque',
			'ours_noir',
			'ours_grizzly',
			'aigle_chauve',
			'phoque',
			'loutre_de_mer',
			'cerf_de_sitka',
		],
		domesticatedAnimals: ['chien'],
		domesticatedPlants: [],
		forestCoverage: 0.85,
		biodiversity: 8,
		humanImpact: 1,
	},
	{
		regionId: 'clim_arctic',
		dominantFlora: [
			'lichen',
			'mousse_arctique',
			'saule_nain',
			'herbe_arctique',
			'pavot_arctique',
		],
		dominantFauna: [
			'phoque_annelé',
			'morse',
			'baleine_boréale',
			'caribou',
			'ours_polaire',
			'renard_arctique',
			'lièvre_arctique',
			'narval',
		],
		domesticatedAnimals: ['chien_de_traîneau'],
		domesticatedPlants: [],
		forestCoverage: 0.0,
		biodiversity: 3,
		humanImpact: 0,
	},
	{
		regionId: 'clim_polynesia',
		dominantFlora: [
			'cocotier',
			'arbre_à_pain',
			'pandanus',
			'taro',
			'igname',
			'bananier',
			'kava',
			'hibiscus',
		],
		dominantFauna: [
			'tortue_verte',
			'thon',
			'bonite',
			'requin',
			'frégate',
			'pigeon_impérial',
			'gecko',
			'crabe_cocotier',
		],
		domesticatedAnimals: ['porc', 'poule', 'chien'],
		domesticatedPlants: [
			'taro',
			'igname',
			'arbre_à_pain',
			'cocotier',
			'banane',
			'patate_douce',
		],
		forestCoverage: 0.6,
		biodiversity: 5,
		humanImpact: 3,
	},
	{
		regionId: 'clim_australia',
		dominantFlora: [
			'eucalyptus',
			'acacia',
			'melaleuca',
			'spinifex',
			'baobab_australien',
			'banksia',
			'herbe_de_mitchell',
		],
		dominantFauna: [
			'kangourou',
			'émeu',
			'wombat',
			'koala',
			'dingo',
			'crocodile_marin',
			'varanidé',
			'casoar',
		],
		domesticatedAnimals: ['dingo'],
		domesticatedPlants: [],
		forestCoverage: 0.2,
		biodiversity: 8,
		humanImpact: 1,
	},
	{
		regionId: 'clim_lapland',
		dominantFlora: [
			'bouleau_nain',
			'saule_polaire',
			'lichen_de_renne',
			'mousse',
			'myrtille',
			'pin_sylvestre',
			'épicéa',
		],
		dominantFauna: [
			'renne',
			'élan',
			'glouton',
			'lynx',
			'renard_arctique',
			'ours_brun',
			'saumon',
			'lagopède',
		],
		domesticatedAnimals: ['renne', 'chien'],
		domesticatedPlants: [],
		forestCoverage: 0.3,
		biodiversity: 4,
		humanImpact: 1,
	},
	{
		regionId: 'clim_south_america_temperate',
		dominantFlora: [
			'araucaria',
			'hêtre_austral',
			'lenga',
			'nalca',
			'fuchsia',
			'copihue',
			'bambou_chilien',
		],
		dominantFauna: [
			'condor',
			'puma',
			'guanaco',
			'pudú',
			'huemul',
			'renard_culpeo',
			'flamant',
			'manchot_de_humboldt',
		],
		domesticatedAnimals: ['lama', 'alpaga', 'chien'],
		domesticatedPlants: [
			'pomme_de_terre',
			'maïs',
			'quinoa',
			'piment',
			'fraise_blanche',
		],
		forestCoverage: 0.5,
		biodiversity: 7,
		humanImpact: 2,
	},
	{
		regionId: 'clim_madagascar',
		dominantFlora: [
			'baobab',
			'ravinala',
			'palissandre',
			'ylang_ylang',
			'orchidée',
			'raphia',
			'riz',
			'vanille_sauvage',
		],
		dominantFauna: [
			'lémurien',
			'fossane',
			'caméléon',
			'aye_aye',
			'tortue_radiée',
			'crocodile_du_nil',
			'gecko',
			'oiseau_éléphant',
		],
		domesticatedAnimals: ['zébu', 'poule', 'chien'],
		domesticatedPlants: ['riz', 'manioc', 'banane', 'igname', 'taro'],
		forestCoverage: 0.65,
		biodiversity: 10, // endémisme exceptionnel
		humanImpact: 2,
	},

	// ========================================================================
	// ÉCOLOGIE — TIER 2 & 3
	// ========================================================================
	{
		regionId: 'clim_peruvian_coast',
		dominantFlora: ['cactus', 'algarrobo', 'huarango', 'tillandsia', 'sapote'],
		dominantFauna: [
			'pélican',
			'otarie',
			'condor',
			'pingouin_de_humboldt',
			'lézard',
			'anchois',
		],
		domesticatedAnimals: ['lama', 'alpaga', 'cobaye', 'canard_musqué'],
		domesticatedPlants: ['maïs', 'haricot', 'courge', 'coton', 'piment'],
		forestCoverage: 0.05,
		biodiversity: 5,
		humanImpact: 4,
	},
	{
		regionId: 'clim_colombian_highlands',
		dominantFlora: [
			'chêne_andin',
			'frailejón',
			'orchidée',
			'palmier_de_cire',
			'fougère_arborescente',
		],
		dominantFauna: [
			'condor',
			'ours_à_lunettes',
			'tapir_de_montagne',
			'colibri',
			'jaguar',
			'grenouille_dorée',
		],
		domesticatedAnimals: ['cobaye', 'chien'],
		domesticatedPlants: ['maïs', 'pomme_de_terre', 'quinoa', 'haricot', 'coca'],
		forestCoverage: 0.6,
		biodiversity: 9,
		humanImpact: 2,
	},
	{
		regionId: 'clim_south_american_subtropical',
		dominantFlora: [
			'araucaria',
			'yerba_maté',
			'palmier',
			'jacaranda',
			'lapacho',
			'fougère',
		],
		dominantFauna: [
			'jaguar',
			'tapir',
			'capybara',
			'caïman',
			'toucan',
			'perroquet',
			'anaconda',
		],
		domesticatedAnimals: ['chien'],
		domesticatedPlants: [
			'manioc',
			'maïs',
			'patate_douce',
			'yerba_maté',
			'cacahuète',
		],
		forestCoverage: 0.7,
		biodiversity: 9,
		humanImpact: 2,
	},
	{
		regionId: 'clim_hawaii',
		dominantFlora: [
			'koa',
			'ohia_lehua',
			'taro',
			'cocotier',
			'santal',
			'fougère_arborescente',
		],
		dominantFauna: [
			'nene_oie',
			'phoque_moine',
			'tortue_verte',
			'po_ouli',
			'chauve_souris',
		],
		domesticatedAnimals: ['porc', 'poule', 'chien'],
		domesticatedPlants: [
			'taro',
			'patate_douce',
			'noix_de_coco',
			'banane',
			'igname',
		],
		forestCoverage: 0.7,
		biodiversity: 8,
		humanImpact: 3,
	},
	{
		regionId: 'clim_hokkaido',
		dominantFlora: [
			'bouleau',
			'sapin_du_japon',
			'chêne',
			'bambou_nain',
			'lavande',
		],
		dominantFauna: [
			'ours_brun',
			'cerf_sika',
			'renard_roux',
			'saumon',
			'grue_du_japon',
			'aigle_de_steller',
		],
		domesticatedAnimals: ['chien'],
		domesticatedPlants: ['millet', 'racines_sauvages'],
		forestCoverage: 0.65,
		biodiversity: 7,
		humanImpact: 2,
	},
	{
		regionId: 'clim_upper_nile',
		dominantFlora: [
			'acacia',
			'doum_palmier',
			'papyrus',
			'tamaris',
			'balanites',
		],
		dominantFauna: [
			'crocodile_du_nil',
			'hippopotame',
			'ibis',
			'gazelle',
			'vautour',
			'tilapia',
		],
		domesticatedAnimals: ['âne', 'chèvre', 'bœuf', 'chien'],
		domesticatedPlants: ['mil', 'sorgho', 'dattes', 'lentilles', 'blé'],
		forestCoverage: 0.1,
		biodiversity: 5,
		humanImpact: 4,
	},
	{
		regionId: 'clim_central_sahara',
		dominantFlora: ['acacia', 'tamaris', 'calotropis', 'euphorbe'],
		dominantFauna: [
			'fennec',
			'gazelle_dorcas',
			'addax',
			'vipère_des_sables',
			'scorpion',
			'autruche',
		],
		domesticatedAnimals: ['dromadaire', 'chèvre', 'chien'],
		domesticatedPlants: ['dattes', 'mil'],
		forestCoverage: 0.01,
		biodiversity: 3,
		humanImpact: 1,
	},
	{
		regionId: 'clim_caucasus',
		dominantFlora: [
			'chêne',
			'hêtre',
			'épicéa',
			'rhododendron',
			'vigne_sauvage',
			'buis',
		],
		dominantFauna: [
			'ours_brun',
			'loup',
			'bouquetin',
			'aigle_royal',
			'lynx',
			'chamois',
		],
		domesticatedAnimals: ['mouton', 'chèvre', 'bœuf', 'cheval', 'chien'],
		domesticatedPlants: ['blé', 'orge', 'vigne', 'noix', 'grenade', 'pomme'],
		forestCoverage: 0.5,
		biodiversity: 8,
		humanImpact: 4,
	},
	{
		regionId: 'clim_northeast_america',
		dominantFlora: ['épinette', 'bouleau', 'érable', 'sapin_baumier', 'bleuet'],
		dominantFauna: [
			'orignal',
			'ours_noir',
			'castor',
			'saumon',
			'homard',
			'phoque',
			'caribou',
		],
		domesticatedAnimals: ['chien'],
		domesticatedPlants: ['maïs', 'courge', 'tournesol'],
		forestCoverage: 0.75,
		biodiversity: 6,
		humanImpact: 1,
	},
	{
		regionId: 'clim_new_guinea',
		dominantFlora: [
			'pandanus',
			'sagoutier',
			'fougère_arborescente',
			'dipterocarpacée',
			'orchidée',
			'bananier',
		],
		dominantFauna: [
			'oiseau_de_paradis',
			'casoar',
			'wallaby',
			'python',
			'crocodile',
			'cuscus',
		],
		domesticatedAnimals: ['porc', 'chien'],
		domesticatedPlants: ['patate_douce', 'taro', 'sagou', 'banane', 'igname'],
		forestCoverage: 0.85,
		biodiversity: 10,
		humanImpact: 2,
	},
	{
		regionId: 'clim_fiji',
		dominantFlora: ['cocotier', 'mangrove', 'acajou', 'pandanus', 'fougère'],
		dominantFauna: [
			'iguane_fidjien',
			'roussette',
			'tortue_imbriquée',
			'perroquet',
			'serpent_de_mer',
		],
		domesticatedAnimals: ['porc', 'poule'],
		domesticatedPlants: [
			'taro',
			'igname',
			'noix_de_coco',
			'banane',
			'fruit_à_pain',
		],
		forestCoverage: 0.6,
		biodiversity: 7,
		humanImpact: 3,
	},
	{
		regionId: 'clim_mariana_islands',
		dominantFlora: ['cocotier', 'pandanus', 'ifit', 'cycas', 'fruit_à_pain'],
		dominantFauna: [
			'roussette_des_mariannes',
			'lézard_moniteur',
			'tortue_verte',
			'bernard_l_hermite',
		],
		domesticatedAnimals: ['porc', 'poule'],
		domesticatedPlants: ['riz_sauvage', 'taro', 'noix_de_coco', 'fruit_à_pain'],
		forestCoverage: 0.5,
		biodiversity: 5,
		humanImpact: 3,
	},
	{
		regionId: 'clim_canary_islands',
		dominantFlora: [
			'dragonnier',
			'laurier_des_canaries',
			'palmier_des_canaries',
			'euphorbe',
			'pin_canarien',
		],
		dominantFauna: [
			'lézard_géant',
			'pinson_des_canaries',
			'tortue',
			'roussette',
		],
		domesticatedAnimals: ['chèvre', 'mouton', 'chien'],
		domesticatedPlants: ['orge', 'figuier', 'dattier'],
		forestCoverage: 0.25,
		biodiversity: 6,
		humanImpact: 3,
	},
	{
		regionId: 'clim_kalahari',
		dominantFlora: [
			'acacia',
			'melon_tsamma',
			'hoodia',
			'baobab',
			'herbe_kalahari',
		],
		dominantFauna: [
			'lion',
			'guépard',
			'springbok',
			'suricate',
			'autruche',
			'oryx',
			'hyène',
		],
		domesticatedAnimals: [],
		domesticatedPlants: [],
		forestCoverage: 0.1,
		biodiversity: 6,
		humanImpact: 1,
	},
	{
		regionId: 'clim_congo_rainforest',
		dominantFlora: [
			'acajou',
			'ébène',
			'iroko',
			'palmier_à_huile',
			'fougère_arborescente',
			'orchidée',
		],
		dominantFauna: [
			'gorille',
			'okapi',
			'éléphant_de_forêt',
			'léopard',
			'bonobo',
			'pangolin',
			'perroquet_gris',
		],
		domesticatedAnimals: ['chien'],
		domesticatedPlants: ['igname', 'banane_plantain', 'palmier_à_huile'],
		forestCoverage: 0.95,
		biodiversity: 10,
		humanImpact: 1,
	},
	{
		regionId: 'clim_chukotka',
		dominantFlora: [
			'mousse',
			'lichen',
			'saule_arctique',
			'linaigrette',
			'saxifrage',
		],
		dominantFauna: [
			'morse',
			'baleine_boréale',
			'ours_polaire',
			'renne',
			'renard_arctique',
			'phoque',
			'harfang_des_neiges',
		],
		domesticatedAnimals: ['renne', 'chien'],
		domesticatedPlants: [],
		forestCoverage: 0.02,
		biodiversity: 4,
		humanImpact: 1,
	},
	{
		regionId: 'clim_subarctic_canada',
		dominantFlora: [
			'épinette_noire',
			'bouleau',
			'tremble',
			'mousse',
			'lichen',
			'bleuet',
		],
		dominantFauna: [
			'caribou',
			'orignal',
			'loup',
			'ours_noir',
			'castor',
			'lynx',
			'harfang_des_neiges',
		],
		domesticatedAnimals: ['chien'],
		domesticatedPlants: [],
		forestCoverage: 0.4,
		biodiversity: 5,
		humanImpact: 1,
	},
]
