import type { NationCulture } from '../../../shared/src/types/world'

// ============================================================================
// Cultures par nation — An 1000
// ============================================================================

export const nationCultures: NationCulture[] = [
	// ========================================================================
	// EUROPE OCCIDENTALE
	// ========================================================================
	{
		nationId: 'nat_hre',
		architecturalStyle: 'romanesque',
		culturalTraits: ['martial', 'pious', 'feudal', 'literary'],
		festivals: ['Noël', 'Pâques', 'foires impériales', 'tournois'],
		artForms: [
			'manuscript_illumination',
			'stone_carving',
			'choir_music',
			'metalwork',
		],
		cuisineStaples: ['blé', 'seigle', 'porc', 'bière', 'chou', 'fromage'],
		clothing: ['tunique en laine', 'braies', 'manteau en fourrure', 'capuchon'],
		socialCustoms: [
			'hommage féodal',
			'ordalie',
			'mariage chrétien',
			'funérailles ecclésiastiques',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_france',
		architecturalStyle: 'romanesque',
		culturalTraits: ['pious', 'feudal', 'courtly', 'literary'],
		festivals: ['Noël', 'Pâques', 'foire de Saint-Denis', 'fête des Rois'],
		artForms: [
			'manuscript_illumination',
			'troubadour_poetry',
			'stone_carving',
			'tapestry',
		],
		cuisineStaples: ['blé', 'vin', 'fromage', 'porc', 'boeuf', 'poisson'],
		clothing: ['tunique longue', 'bliaut', 'manteau', 'voile (femmes)'],
		socialCustoms: [
			'hommage féodal',
			'troubadours',
			'mariage chrétien',
			'pèlerinage',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_england',
		architecturalStyle: 'romanesque',
		culturalTraits: ['martial', 'mercantile', 'pious', 'seafaring'],
		festivals: ['Noël', 'Pâques', 'moissons', 'assemblée du witan'],
		artForms: [
			'manuscript_illumination',
			'embroidery',
			'metalwork',
			'stone_cross_carving',
		],
		cuisineStaples: ['blé', 'orge', 'mouton', 'poisson', 'bière', 'miel'],
		clothing: ['tunique en laine', 'manteau', 'broches anglo-saxonnes'],
		socialCustoms: ['witan', 'ordalie', 'wergild', 'fêtes de moissons'],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_scotland',
		architecturalStyle: 'romanesque',
		culturalTraits: ['martial', 'oral_tradition', 'clan_based'],
		festivals: ['Samhain', 'Beltane', 'Noël', 'fête de saint André'],
		artForms: ['stone_cross_carving', 'oral_poetry', 'metalwork', 'harp_music'],
		cuisineStaples: ['orge', 'avoine', 'mouton', 'poisson', 'gibier'],
		clothing: ['tunique en laine', 'brat (manteau)', 'léine (chemise longue)'],
		socialCustoms: [
			'loyauté clanique',
			'hospitalité sacrée',
			'bardes',
			'concours de force',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_papal',
		architecturalStyle: 'romanesque',
		culturalTraits: ['pious', 'literary', 'bureaucratic', 'artistic'],
		festivals: ['Noël', 'Pâques', 'fêtes des saints', 'conclave'],
		artForms: [
			'manuscript_illumination',
			'mosaic',
			'fresco',
			'gregorian_chant',
		],
		cuisineStaples: ['blé', 'vin', "huile d'olive", 'poisson', 'légumes'],
		clothing: ['habits ecclésiastiques', 'dalmatique', 'chasuble', 'soutane'],
		socialCustoms: ['messe quotidienne', 'pèlerinage', 'aumône', 'communion'],
		culturalPrestige: 9,
	},
	{
		nationId: 'nat_venice',
		architecturalStyle: 'byzantine',
		culturalTraits: ['mercantile', 'seafaring', 'cosmopolitan', 'artistic'],
		festivals: [
			'mariage avec la mer',
			'carnaval',
			'fête de saint Marc',
			'régate',
		],
		artForms: ['mosaic', 'glassblowing', 'shipbuilding', 'painting'],
		cuisineStaples: ['poisson', 'riz', 'blé', 'épices', 'vin', 'sel'],
		clothing: ['robe vénitienne', 'dalmatique', 'brocart', 'bijoux en verre'],
		socialCustoms: [
			'élection du doge',
			'guildes marchandes',
			'commerce maritime',
			'diplomatie',
		],
		culturalPrestige: 7,
	},

	// ========================================================================
	// IBÉRIE
	// ========================================================================
	{
		nationId: 'nat_leon',
		architecturalStyle: 'romanesque',
		culturalTraits: ['martial', 'pious', 'reconquista', 'pastoral'],
		festivals: ['Saint-Jacques', 'Noël', 'Pâques', 'foires'],
		artForms: ['stone_carving', 'manuscript_illumination', 'metalwork'],
		cuisineStaples: ['blé', 'mouton', 'vin', 'porc', 'fromage'],
		clothing: ['tunique en laine', 'manteau', 'capuche'],
		socialCustoms: [
			'pèlerinage de Compostelle',
			'reconquista',
			'mariage chrétien',
		],
		culturalPrestige: 4,
	},
	{
		nationId: 'nat_navarre',
		architecturalStyle: 'romanesque',
		culturalTraits: ['martial', 'pastoral', 'pious'],
		festivals: ['Noël', 'Pâques', 'fêtes de montagne'],
		artForms: ['stone_carving', 'metalwork', 'folk_music'],
		cuisineStaples: ['blé', 'mouton', 'fromage', 'vin', 'porc'],
		clothing: ['tunique en laine', 'béret', 'ceinture de cuir'],
		socialCustoms: ['assemblées locales', 'droits coutumiers', 'transhumance'],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_cordoba',
		architecturalStyle: 'islamic',
		culturalTraits: [
			'literary',
			'mercantile',
			'cosmopolitan',
			'artistic',
			'scholarly',
		],
		festivals: ['Aïd al-Fitr', 'Aïd al-Adha', 'Mawlid', 'moussem'],
		artForms: [
			'calligraphy',
			'geometric_mosaic',
			'arabesques',
			'poetry',
			'architecture',
		],
		cuisineStaples: [
			'blé',
			'riz',
			'agneau',
			"huile d'olive",
			'fruits secs',
			'épices',
		],
		clothing: ['djellaba', 'turban', 'soie brodée', 'babouches'],
		socialCustoms: [
			'hammam',
			'souk',
			'hospitalité',
			'récitation du Coran',
			'mariage islamique',
		],
		culturalPrestige: 9,
	},

	// ========================================================================
	// SCANDINAVIE
	// ========================================================================
	{
		nationId: 'nat_denmark',
		architecturalStyle: 'norse',
		culturalTraits: ['martial', 'seafaring', 'oral_tradition', 'mercantile'],
		festivals: ['Jul (Yule)', 'Althing', 'fête de moissons', 'blót'],
		artForms: [
			'woodcarving',
			'metalwork',
			'rune_inscription',
			'skaldic_poetry',
		],
		cuisineStaples: ['poisson', 'orge', 'porc', 'bière', 'miel', 'baies'],
		clothing: [
			'tunique en laine',
			'manteau en fourrure',
			'bottes en cuir',
			'broches vikings',
		],
		socialCustoms: [
			'thing (assemblée)',
			'sagas',
			'serment de sang',
			'funérailles par barque',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_norway',
		architecturalStyle: 'norse',
		culturalTraits: ['martial', 'seafaring', 'oral_tradition'],
		festivals: ['Jul (Yule)', 'blót', 'fête de moissons', 'Althing'],
		artForms: [
			'woodcarving',
			'shipbuilding',
			'skaldic_poetry',
			'rune_inscription',
		],
		cuisineStaples: ['poisson séché', 'orge', 'mouton', 'baies', 'gibier'],
		clothing: ['tunique en laine', 'manteau en fourrure', 'capuchon'],
		socialCustoms: ['thing', 'sagas', 'raids', 'funérailles par barque'],
		culturalPrestige: 4,
	},
	{
		nationId: 'nat_sweden',
		architecturalStyle: 'norse',
		culturalTraits: ['martial', 'oral_tradition', 'mercantile'],
		festivals: ['Jul (Yule)', "blót au temple d'Uppsala", 'fête de moissons'],
		artForms: [
			'woodcarving',
			'rune_inscription',
			'metalwork',
			'skaldic_poetry',
		],
		cuisineStaples: ['poisson', 'orge', 'gibier', 'baies', 'bière'],
		clothing: ['tunique en laine', 'fourrures', 'broches'],
		socialCustoms: ['blót (sacrifice)', 'thing', 'sagas', 'commerce varangien'],
		culturalPrestige: 3,
	},

	// ========================================================================
	// EUROPE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_poland',
		architecturalStyle: 'romanesque',
		culturalTraits: ['martial', 'pious', 'feudal'],
		festivals: ['Noël', 'Pâques', 'Dożynki (moissons)', 'foires'],
		artForms: ['stone_carving', 'metalwork', 'manuscript_illumination'],
		cuisineStaples: ['seigle', 'orge', 'porc', 'chou', 'bière', 'miel'],
		clothing: ['tunique en laine', 'manteau en fourrure', 'bottes'],
		socialCustoms: ['wiec (assemblée)', 'mariage chrétien', 'hospitalité'],
		culturalPrestige: 4,
	},
	{
		nationId: 'nat_hungary',
		architecturalStyle: 'romanesque',
		culturalTraits: ['martial', 'equestrian', 'pastoral'],
		festivals: ['Noël', 'Pâques', 'fête de saint Étienne', 'foires de chevaux'],
		artForms: [
			'metalwork',
			'leather_working',
			'embroidery',
			'equestrian_culture',
		],
		cuisineStaples: ['blé', 'boeuf', 'porc', 'vin', 'fromage'],
		clothing: ['tunique descendante', 'dolman', 'bottes de cavalier'],
		socialCustoms: [
			'diète royale',
			'élevage de chevaux',
			'hospitalité',
			'mariage chrétien',
		],
		culturalPrestige: 4,
	},
	{
		nationId: 'nat_kievan_rus',
		architecturalStyle: 'byzantine',
		culturalTraits: ['martial', 'mercantile', 'oral_tradition', 'pious'],
		festivals: ['Noël ortodoxe', 'Pâques', 'Maslenitsa', 'Kupala'],
		artForms: ['icon_painting', 'woodcarving', 'metalwork', 'bylina_poetry'],
		cuisineStaples: ['seigle', 'sarrasin', 'poisson', 'miel', 'kvass', 'chou'],
		clothing: [
			'rubakha (chemise longue)',
			'caftan',
			'chapka en fourrure',
			'lapti (chaussures)',
		],
		socialCustoms: [
			'veche (assemblée)',
			'mariage orthodoxe',
			'hospitalité slave',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_volga_bulgaria',
		architecturalStyle: 'islamic',
		culturalTraits: ['mercantile', 'pastoral', 'pious'],
		festivals: ['Aïd al-Fitr', 'Aïd al-Adha', 'Sabantuy (fête du labour)'],
		artForms: ['leather_working', 'metalwork', 'calligraphy'],
		cuisineStaples: ['blé', 'mouton', 'miel', 'lait fermenté', 'poisson'],
		clothing: ['caftan', 'bonnet en fourrure', 'bottes'],
		socialCustoms: ['commerce fluvial', 'assemblées tribales', 'hospitalité'],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_croatia',
		architecturalStyle: 'romanesque',
		culturalTraits: ['martial', 'pious', 'seafaring'],
		festivals: ['Noël', 'Pâques', 'fête de saint Domnius'],
		artForms: ['stone_carving', 'metalwork', 'manuscript_illumination'],
		cuisineStaples: ['blé', 'poisson', "huile d'olive", 'vin', 'mouton'],
		clothing: ['tunique dalmate', 'manteau', 'sandales'],
		socialCustoms: ['sabor (assemblée)', 'mariage chrétien', 'pêche'],
		culturalPrestige: 3,
	},

	// ========================================================================
	// BYZANCE
	// ========================================================================
	{
		nationId: 'nat_byzantine',
		architecturalStyle: 'byzantine',
		culturalTraits: [
			'literary',
			'bureaucratic',
			'artistic',
			'cosmopolitan',
			'pious',
		],
		festivals: [
			'Noël',
			'Pâques orthodoxes',
			'courses de chars',
			'célébration des saints',
		],
		artForms: [
			'mosaic',
			'icon_painting',
			'fresco',
			'silk_weaving',
			'enamel_work',
		],
		cuisineStaples: [
			'blé',
			"huile d'olive",
			'poisson',
			'vin',
			'fruits',
			'épices',
		],
		clothing: ['dalmatique', 'soie impériale', 'diadème', 'chlamyde'],
		socialCustoms: [
			'cérémonie de cour',
			'diplomatie élaborée',
			'messe orthodoxe',
			'hippodrome',
		],
		culturalPrestige: 9,
	},

	// ========================================================================
	// MONDE ISLAMIQUE
	// ========================================================================
	{
		nationId: 'nat_fatimid',
		architecturalStyle: 'islamic',
		culturalTraits: ['scholarly', 'mercantile', 'cosmopolitan', 'artistic'],
		festivals: [
			'Aïd al-Fitr',
			'Aïd al-Adha',
			'Mawlid',
			"inauguration d'al-Azhar",
		],
		artForms: [
			'calligraphy',
			'geometric_mosaic',
			'woodcarving',
			'textile_art',
			'glass_art',
		],
		cuisineStaples: [
			'blé',
			'riz',
			'agneau',
			'poisson',
			'dattes',
			'épices',
			'miel',
		],
		clothing: ['djellaba', 'turban', 'soie brodée', 'qamis'],
		socialCustoms: [
			'prière 5 fois/jour',
			'hammam',
			'souk',
			'hospitalité',
			'zakat',
		],
		culturalPrestige: 9,
	},
	{
		nationId: 'nat_buyid',
		architecturalStyle: 'islamic',
		culturalTraits: ['scholarly', 'literary', 'cosmopolitan'],
		festivals: ['Aïd al-Fitr', 'Nowruz (Nouvel An persan)', 'Achoura'],
		artForms: ['calligraphy', 'miniature_painting', 'poetry', 'metalwork'],
		cuisineStaples: [
			'riz',
			'agneau',
			'pain plat',
			'fruits',
			'épices',
			'yogourt',
		],
		clothing: ['qamis', 'turban', 'bottes persanes', 'robe brodée'],
		socialCustoms: [
			'hospitalité persane',
			'bazar',
			'hammam',
			'récitation poétique',
		],
		culturalPrestige: 8,
	},
	{
		nationId: 'nat_ghaznavid',
		architecturalStyle: 'islamic',
		culturalTraits: ['martial', 'scholarly', 'pious'],
		festivals: ['Aïd al-Fitr', 'Aïd al-Adha', 'Nowruz', 'victoires militaires'],
		artForms: ['calligraphy', 'architecture', 'poetry', 'metalwork'],
		cuisineStaples: ['pain plat', 'agneau', 'riz', 'fruits secs', 'yogourt'],
		clothing: [
			'caftan militaire',
			'turban',
			'bottes de cavalier',
			'armure décorée',
		],
		socialCustoms: ['ghazwa (raid sacré)', 'mécénat poétique', 'darbar (cour)'],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_karakhanid',
		architecturalStyle: 'islamic',
		culturalTraits: ['pastoral', 'martial', 'mercantile'],
		festivals: ['Aïd al-Fitr', 'Nowruz', 'fêtes nomades'],
		artForms: ['calligraphy', 'leather_working', 'felt_making', 'metalwork'],
		cuisineStaples: ['mouton', 'lait de jument', 'pain plat', 'fruits secs'],
		clothing: ['caftan', 'bonnet en fourrure', 'bottes de steppe'],
		socialCustoms: [
			'kurultaï (assemblée)',
			'hospitalité nomade',
			'jeux équestres',
		],
		culturalPrestige: 4,
	},

	// ========================================================================
	// ASIE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_song',
		architecturalStyle: 'chinese_imperial',
		culturalTraits: [
			'literary',
			'scholarly',
			'mercantile',
			'artistic',
			'bureaucratic',
		],
		festivals: [
			'Nouvel An chinois',
			'fête des Lanternes',
			'fête de la Lune',
			'Qingming',
		],
		artForms: [
			'calligraphy',
			'landscape_painting',
			'porcelain',
			'silk_weaving',
			'poetry',
			'opera',
		],
		cuisineStaples: ['riz', 'blé', 'porc', 'poisson', 'thé', 'soja', 'légumes'],
		clothing: [
			'hanfu',
			'robe de soie',
			'chapeau de lettré',
			'chaussures brodées',
		],
		socialCustoms: [
			'examens impériaux',
			'cérémonie du thé',
			'respect filial',
			'funérailles confucéennes',
		],
		culturalPrestige: 10,
	},
	{
		nationId: 'nat_liao',
		architecturalStyle: 'chinese_imperial',
		culturalTraits: ['martial', 'equestrian', 'dual_culture'],
		festivals: ['Nouvel An', 'fête de chasse', 'sacrifices au ciel'],
		artForms: ['porcelain', 'metalwork', 'leather_working', 'tomb_painting'],
		cuisineStaples: ['mouton', 'lait de jument', 'riz', 'millet', 'gibier'],
		clothing: ['robe khitan', 'caftan', 'fourrures', 'bottes de cavalier'],
		socialCustoms: [
			'chasse impériale',
			'double administration (khitan/chinois)',
			'jeux équestres',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_goryeo',
		architecturalStyle: 'chinese_imperial',
		culturalTraits: ['literary', 'pious', 'artistic', 'bureaucratic'],
		festivals: ['Seollal (Nouvel An)', 'Chuseok (moissons)', 'fête de Bouddha'],
		artForms: [
			'celadon_pottery',
			'calligraphy',
			'painting',
			'metalwork',
			'block_printing',
		],
		cuisineStaples: ['riz', 'orge', 'poisson', 'kimchi', 'soja', 'thé'],
		clothing: ['hanbok', 'gat (chapeau)', 'chaussures en tissu'],
		socialCustoms: [
			'examens de fonctionnaires',
			'rites confucéens',
			'rites bouddhistes',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_japan',
		architecturalStyle: 'chinese_imperial',
		culturalTraits: ['literary', 'artistic', 'courtly', 'warrior'],
		festivals: ['Nouvel An', 'Obon', 'Tanabata', 'Setsubun', 'hanami'],
		artForms: [
			'calligraphy',
			'painting',
			'poetry',
			'lacquerware',
			'sword_making',
			'garden_design',
		],
		cuisineStaples: ['riz', 'poisson', 'soja', 'algues', 'sake', 'légumes'],
		clothing: ['kimono', 'hakama', 'jūnihitoe (cour)', 'geta'],
		socialCustoms: [
			'cour de Heian',
			'waka (poésie)',
			'mono no aware',
			'rituel shinto',
		],
		culturalPrestige: 7,
	},

	// ========================================================================
	// ASIE DU SUD-EST
	// ========================================================================
	{
		nationId: 'nat_dai_viet',
		architecturalStyle: 'southeast_asian',
		culturalTraits: ['literary', 'martial', 'agricultural'],
		festivals: ['Tết (Nouvel An)', 'fête des eaux', 'fête de la Lune'],
		artForms: ['lacquerware', 'ceramics', 'wood_sculpture', 'water_puppetry'],
		cuisineStaples: [
			'riz',
			'poisson',
			'nuoc mam',
			'légumes',
			'fruits tropicaux',
		],
		clothing: ['áo dài (proto-forme)', 'turban', 'sandales'],
		socialCustoms: [
			'culte des ancêtres',
			'examen mandarinal',
			'respect des anciens',
		],
		culturalPrestige: 4,
	},
	{
		nationId: 'nat_khmer',
		architecturalStyle: 'southeast_asian',
		culturalTraits: ['artistic', 'pious', 'monumental', 'hydraulic'],
		festivals: ['Bon Om Touk (eau)', 'Nouvel An khmer', 'Pchum Ben (ancêtres)'],
		artForms: ['stone_carving', 'bas_relief', 'bronze_casting', 'dance_drama'],
		cuisineStaples: ['riz', 'poisson', 'prahok', 'fruits tropicaux', 'épices'],
		clothing: ['sampot', 'écharpe krama', 'bijoux en or'],
		socialCustoms: [
			'construction de temples',
			"système d'irrigation",
			'danse apsara',
		],
		culturalPrestige: 8,
	},
	{
		nationId: 'nat_srivijaya',
		architecturalStyle: 'southeast_asian',
		culturalTraits: ['mercantile', 'seafaring', 'cosmopolitan', 'pious'],
		festivals: ['Vesak', 'fêtes maritimes', 'fêtes de moissons'],
		artForms: [
			'bronze_casting',
			'wood_sculpture',
			'textile_art',
			'shipbuilding',
		],
		cuisineStaples: [
			'riz',
			'poisson',
			'noix de coco',
			'épices',
			'fruits tropicaux',
		],
		clothing: ['sarong', 'kain songket', 'bijoux en or et pierres'],
		socialCustoms: [
			'commerce maritime',
			'bouddhisme monastique',
			'initiation royale',
		],
		culturalPrestige: 6,
	},

	// ========================================================================
	// ASIE DU SUD
	// ========================================================================
	{
		nationId: 'nat_chola',
		architecturalStyle: 'indian',
		culturalTraits: ['artistic', 'seafaring', 'mercantile', 'pious', 'martial'],
		festivals: ['Pongal', 'Diwali', 'Navaratri', 'festivals de temple'],
		artForms: [
			'bronze_casting',
			'temple_sculpture',
			'bharatanatyam',
			'poetry',
			'music',
		],
		cuisineStaples: [
			'riz',
			'curry',
			'noix de coco',
			'épices',
			'poisson',
			'fruits',
		],
		clothing: ['dhoti', 'sari', 'bijoux en or', 'fleurs dans les cheveux'],
		socialCustoms: [
			'système des castes',
			'rites de temple',
			"mariage selon l'astrologie",
			'danse sacrée',
		],
		culturalPrestige: 8,
	},
	{
		nationId: 'nat_chalukya',
		architecturalStyle: 'indian',
		culturalTraits: ['artistic', 'pious', 'martial'],
		festivals: ['Diwali', 'Ugadi', 'Navaratri', 'festivals de temple'],
		artForms: ['temple_sculpture', 'stone_carving', 'painting', 'music'],
		cuisineStaples: ['riz', 'millet', 'curry', 'épices', 'lentilles'],
		clothing: ['dhoti', 'sari', 'bijoux', 'sandales'],
		socialCustoms: ['système des castes', 'mécénat de temples', 'rites jains'],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_pala',
		architecturalStyle: 'indian',
		culturalTraits: ['scholarly', 'pious', 'artistic'],
		festivals: ['fête de Bouddha', 'Diwali', 'Makar Sankranti'],
		artForms: [
			'bronze_casting',
			'palm_leaf_manuscript',
			'sculpture',
			'painting',
		],
		cuisineStaples: ['riz', 'poisson', 'lentilles', 'moutarde', 'fruits'],
		clothing: ['dhoti', 'sari', 'shawl en mousseline'],
		socialCustoms: [
			'université de Nalanda/Vikramashila',
			'mécénat bouddhiste',
			'rites védiques',
		],
		culturalPrestige: 7,
	},

	// ========================================================================
	// AFRIQUE
	// ========================================================================
	{
		nationId: 'nat_ghana',
		architecturalStyle: 'african_vernacular',
		culturalTraits: ['mercantile', 'oral_tradition', 'martial'],
		festivals: ['fête des moissons', 'cérémonie du sel', 'cérémonies royales'],
		artForms: [
			'goldsmithing',
			'woodcarving',
			'oral_epic',
			'drumming',
			'weaving',
		],
		cuisineStaples: [
			'millet',
			'sorgho',
			'arachide',
			'poisson',
			'viande séchée',
		],
		clothing: ['boubou', 'tunique en coton', 'sandales', 'bijoux en or'],
		socialCustoms: [
			'griot (tradition orale)',
			'cour royale',
			'commerce caravanier',
			'initiation',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_kanem',
		architecturalStyle: 'african_vernacular',
		culturalTraits: ['pastoral', 'martial', 'oral_tradition'],
		festivals: ['Aïd al-Fitr', 'récoltes', 'cérémonies royales'],
		artForms: ['leather_working', 'metalwork', 'oral_poetry', 'drumming'],
		cuisineStaples: ['millet', 'sorgho', 'lait', 'poisson', 'viande séchée'],
		clothing: ['tunique en coton', 'turban', 'sandales'],
		socialCustoms: [
			'cour royale',
			'initiation guerrière',
			'commerce transsaharien',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_ethiopia',
		architecturalStyle: 'african_vernacular',
		culturalTraits: ['pious', 'literary', 'martial', 'mountainous'],
		festivals: [
			'Timkat (Épiphanie)',
			'Meskel (Croix)',
			'Noël éthiopien',
			'Pâques',
		],
		artForms: [
			'manuscript_illumination',
			'icon_painting',
			'rock_hewn_architecture',
			'liturgical_music',
		],
		cuisineStaples: [
			'teff (injera)',
			'wot (ragoût)',
			'berbéré (épice)',
			'miel',
			'café',
		],
		clothing: ['shamma (coton blanc)', 'netela', 'sandales', 'croix pectorale'],
		socialCustoms: [
			"liturgie ge'ez",
			'jeûne orthodoxe',
			'cérémonie du café',
			'tribunal royal',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_swahili_cities',
		architecturalStyle: 'islamic',
		culturalTraits: ['mercantile', 'seafaring', 'cosmopolitan'],
		festivals: ['Aïd al-Fitr', 'Mawlid', 'festivals maritimes'],
		artForms: [
			'woodcarving',
			'textile_art',
			'pottery',
			'shipbuilding',
			'coral_architecture',
		],
		cuisineStaples: [
			'riz',
			'poisson',
			'noix de coco',
			'épices',
			'fruits tropicaux',
		],
		clothing: ['kanzu', 'kanga', 'bijoux en or et cuivre'],
		socialCustoms: [
			'commerce océanique',
			'mariage islamique',
			'hospitalité swahili',
		],
		culturalPrestige: 5,
	},

	// ========================================================================
	// AMÉRIQUES
	// ========================================================================
	{
		nationId: 'nat_toltec',
		architecturalStyle: 'mesoamerican',
		culturalTraits: ['martial', 'pious', 'monumental', 'artistic'],
		festivals: [
			'fête de Quetzalcoatl',
			'jeu de balle',
			'nouvel an solaire',
			'sacrifices saisonniers',
		],
		artForms: [
			'stone_carving',
			'featherwork',
			'pottery',
			'mural_painting',
			'goldsmithing',
		],
		cuisineStaples: ['maïs', 'haricots', 'courge', 'cacao', 'chili', 'dinde'],
		clothing: ['tilmatli (manteau)', 'maxtlatl (pagne)', 'sandales', 'plumes'],
		socialCustoms: [
			'sacrifice humain',
			'jeu de balle',
			'marché tianguis',
			'calmecac (école)',
		],
		culturalPrestige: 7,
	},
	{
		nationId: 'nat_maya_states',
		architecturalStyle: 'mesoamerican',
		culturalTraits: ['scholarly', 'artistic', 'pious', 'astronomical'],
		festivals: [
			'fête de Chaac (pluie)',
			'jeu de balle',
			'cycles calendaires',
			'sacrifices',
		],
		artForms: [
			'stone_carving',
			'mural_painting',
			'pottery',
			'jade_working',
			'hieroglyphic_writing',
		],
		cuisineStaples: ['maïs', 'haricots', 'courge', 'cacao', 'miel', 'gibier'],
		clothing: ['huipil', 'ex (pagne)', 'sandales', 'jade et plumes'],
		socialCustoms: [
			'sacrifice humain/de sang',
			'jeu de balle',
			'observation astronomique',
			'écriture hiéroglyphique',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_mississippian',
		architecturalStyle: 'mesoamerican',
		culturalTraits: ['oral_tradition', 'agricultural', 'ceremonial'],
		festivals: [
			'Green Corn Ceremony',
			'danses saisonnières',
			'cérémonies funéraires',
		],
		artForms: ['pottery', 'shell_carving', 'mound_building', 'body_painting'],
		cuisineStaples: ['maïs', 'courge', 'haricots', 'poisson', 'gibier', 'noix'],
		clothing: ['peaux de cerf', 'jupes en fibres', 'parures de coquillages'],
		socialCustoms: [
			'construction de tumuli',
			'chefferie',
			'commerce fluvial',
			'danse rituelle',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_wari',
		architecturalStyle: 'andean',
		culturalTraits: ['martial', 'artistic', 'monumental', 'hydraulic'],
		festivals: ['solstices', 'fête des moissons', "cérémonies d'irrigation"],
		artForms: ['textile_art', 'pottery', 'stone_carving', 'metallurgy'],
		cuisineStaples: [
			'maïs',
			'pomme de terre',
			'quinoa',
			'lama séché',
			'haricots',
		],
		clothing: ['tunique en laine de lama', 'bonnet en laine', 'sandales'],
		socialCustoms: [
			"mit'a (travail collectif)",
			'culte des ancêtres',
			'quipu (comptabilité)',
		],
		culturalPrestige: 5,
	},

	// ========================================================================
	// ASIE CENTRALE
	// ========================================================================
	{
		nationId: 'nat_tibet',
		architecturalStyle: 'southeast_asian',
		culturalTraits: ['pious', 'scholarly', 'pastoral', 'mountainous'],
		festivals: ['Losar (Nouvel An)', 'Saga Dawa', 'Shoton (yaourt)'],
		artForms: [
			'thangka_painting',
			'sand_mandala',
			'metalwork',
			'chant_monastique',
		],
		cuisineStaples: [
			'tsampa (orge grillée)',
			'thé au beurre',
			'viande de yak',
			'fromage',
		],
		clothing: [
			'chuba (robe longue)',
			'bottes en feutre',
			'chapeau en fourrure',
		],
		socialCustoms: [
			'pèlerinage',
			'moulin à prières',
			'polyandrie (certaines régions)',
			'funérailles célestes',
		],
		culturalPrestige: 5,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================
	{
		nationId: 'nat_puebloans',
		architecturalStyle: 'other',
		culturalTraits: ['pious', 'communal', 'agricultural', 'astronomical'],
		festivals: ['Cérémonie du solstice', 'Danse du maïs', 'Fête des kachinas'],
		artForms: ['pottery', 'petroglyph', 'weaving', 'turquoise_inlay'],
		cuisineStaples: ['maïs', 'courge', 'haricots', 'gibier'],
		clothing: ['tunique en coton', 'sandales en yucca', 'couverture tissée'],
		socialCustoms: [
			'société clanique matrilinéaire',
			'cérémonies kiva',
			'travail collectif',
			'tradition orale',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_haida',
		architecturalStyle: 'other',
		culturalTraits: ['maritime', 'artisan', 'hierarchical'],
		festivals: ['Potlatch', 'Cérémonie du saumon', 'Danse du masque'],
		artForms: ['totem_carving', 'canoe_craft', 'weaving', 'mask_making'],
		cuisineStaples: [
			'saumon',
			'flétan',
			'baies',
			'eulachân (huile de poisson)',
		],
		clothing: [
			'cape en écorce de cèdre',
			'tunique en peau',
			'chapeau tressé conique',
		],
		socialCustoms: [
			'potlatch (redistribution)',
			'système clanique (Aigle/Corbeau)',
			'esclavage de guerre',
			'tradition orale',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_thule',
		architecturalStyle: 'other',
		culturalTraits: ['survivalist', 'maritime', 'nomadic'],
		festivals: ['Fête du soleil de minuit', 'Cérémonie de la baleine'],
		artForms: ['bone_carving', 'ivory_sculpture', 'drum_music'],
		cuisineStaples: ['phoque', 'baleine', 'caribou', 'baies arctiques'],
		clothing: [
			'parka en peau de caribou',
			'bottes en peau de phoque (kamik)',
			'moufles en fourrure',
		],
		socialCustoms: [
			'chasse communautaire à la baleine',
			'partage obligatoire du gibier',
			'chants de gorge',
			'tradition orale',
		],
		culturalPrestige: 2,
	},
	{
		nationId: 'nat_tui_tonga',
		architecturalStyle: 'other',
		culturalTraits: ['maritime', 'hierarchical', 'pious'],
		festivals: ['Inasi (offrande des prémices)', 'Cérémonie du kava'],
		artForms: ['tapa_cloth', 'canoe_building', 'tattooing', 'dance'],
		cuisineStaples: ['taro', 'igname', 'noix de coco', 'poisson', 'porc'],
		clothing: [
			'tapa (tissu d’écorce)',
			'natte tressée',
			'ornements de coquillage',
		],
		socialCustoms: [
			'tu’i tonga sacré (roi divin)',
			'cérémonie du kava',
			'navigation céleste',
			'tabou (tapu)',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_aboriginal',
		architecturalStyle: 'other',
		culturalTraits: ['nomadic', 'spiritual', 'ecological'],
		festivals: ['Corroborée (danse cérémonielle)', 'Temps du Rêve (Dreamtime)'],
		artForms: ['rock_art', 'body_painting', 'didgeridoo_music', 'storytelling'],
		cuisineStaples: [
			'kangourou',
			'witchetty grubs',
			'igname sauvage',
			'poisson',
		],
		clothing: [
			'peintures corporelles',
			'pagne en écorce',
			'pas de vêtement fixe',
		],
		socialCustoms: [
			'Temps du Rêve (lois ancestrales)',
			'brûlage contrôlé (firestick farming)',
			'songlines (pistes chantées)',
			'initiations cérémonielles',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_sami',
		architecturalStyle: 'other',
		culturalTraits: ['pastoral', 'nomadic', 'spiritual'],
		festivals: ['Fête du solstice d’été', 'Cérémonie du tambour'],
		artForms: ['drum_decoration', 'duodji_crafts', 'joik_singing'],
		cuisineStaples: ['viande de renne', 'poisson séché', 'baies', 'pain plat'],
		clothing: [
			'gákti (costume traditionnel)',
			'bottes en peau de renne',
			'ceinture tissée',
		],
		socialCustoms: [
			'siida (campement communautaire)',
			'élevage transhumant de rennes',
			'joik (chant traditionnel)',
			'noaidi (chamane)',
		],
		culturalPrestige: 2,
	},
	{
		nationId: 'nat_mapuche',
		architecturalStyle: 'other',
		culturalTraits: ['warrior', 'independent', 'agricultural'],
		festivals: ['Ngillatun (prière collective)', 'We Tripantu (Nouvel An)'],
		artForms: ['silverwork', 'weaving', 'pottery', 'woodcarving'],
		cuisineStaples: ['pomme de terre', 'maïs', 'quinoa', 'poisson', 'merquén'],
		clothing: [
			'poncho en laine (makuñ)',
			'bijoux en argent (trarüwe)',
			'sandales',
		],
		socialCustoms: [
			'machi (chamane guérisseuse)',
			'rewe (lieu cérémoniel)',
			'ad mapu (loi coutumière)',
			'palin (jeu de balle)',
		],
		culturalPrestige: 4,
	},
	{
		nationId: 'nat_malagasy',
		architecturalStyle: 'southeast_asian',
		culturalTraits: ['maritime', 'ancestral', 'trader'],
		festivals: [
			'Famadihana (retournement des morts)',
			'Alahamady Be (Nouvel An)',
		],
		artForms: ['weaving', 'woodcarving', 'music_valiha', 'oral_poetry'],
		cuisineStaples: ['riz', 'zébu', 'poisson', 'fruits tropicaux', 'manioc'],
		clothing: ['lamba (grand tissu drapé)', 'chapeau en raphia'],
		socialCustoms: [
			'razana (culte des ancêtres)',
			'fady (tabous)',
			'famadihana (retournement des morts)',
			'tradition orale (hainteny)',
		],
		culturalPrestige: 4,
	},
	{
		nationId: 'nat_yoruba',
		architecturalStyle: 'west_african',
		culturalTraits: ['urban', 'artistic', 'pious', 'hierarchical'],
		festivals: [
			"Fête d'Ogun",
			'Festival Olójó (Àré crown)',
			'Egungun (mascarades)',
		],
		artForms: ['bronze_casting', 'terracotta_sculpture', 'weaving', 'beadwork'],
		cuisineStaples: ['igname', 'mil', 'huile de palme', 'poisson', 'haricots'],
		clothing: [
			'agbada (grand boubou)',
			'gele (coiffe)',
			'aso oke (tissu royal)',
		],
		socialCustoms: [
			'ifá (divination)',
			'société Ogboni',
			'Ooni sacré (roi-prêtre)',
			'artisanat du bronze sacré',
		],
		culturalPrestige: 8,
	},
	{
		nationId: 'nat_zimbabwe',
		architecturalStyle: 'other',
		culturalTraits: ['builder', 'trader', 'pastoral'],
		festivals: ['Cérémonie du Mwari', 'Fête de la récolte', 'Danse Mbira'],
		artForms: ['stone_architecture', 'pottery', 'ironwork', 'mbira_music'],
		cuisineStaples: ['sorgho', 'mil', 'viande de zébu', 'épinards sauvages'],
		clothing: ['pagne tissé', 'peaux tannées', 'ornements en or et cuivre'],
		socialCustoms: [
			'culte du Mwari (dieu suprême)',
			'construction en pierre sèche',
			'commerce aurifère à longue distance',
			'tradition orale',
		],
		culturalPrestige: 5,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 2
	// ========================================================================
	{
		nationId: 'nat_chimu',
		architecturalStyle: 'other',
		culturalTraits: ['urban', 'artistic', 'maritime', 'hierarchical'],
		festivals: ['Fête de la Lune', 'Cérémonies au Huaca', 'Fête du poisson'],
		artForms: ['goldsmithing', 'pottery', 'textile_art', 'adobe_architecture'],
		cuisineStaples: ['poisson', 'maïs', 'haricots', 'courge', 'chicha'],
		clothing: ['tunique en coton', 'ornements en or', 'coiffe cérémonielle'],
		socialCustoms: [
			'sacrifice au dieu Lune (Si)',
			'réseau routier côtier',
			'cidadelles en adobe (ciudadelas)',
			'pêche au totora',
		],
		culturalPrestige: 7,
	},
	{
		nationId: 'nat_muisca',
		architecturalStyle: 'other',
		culturalTraits: ['pious', 'mercantile', 'artistic'],
		festivals: [
			'Cérémonie El Dorado (lac Guatavita)',
			'Fête du soleil (Sué)',
			'Fête de la lune (Chía)',
		],
		artForms: ['goldsmithing', 'tunjo_figurines', 'pottery', 'weaving'],
		cuisineStaples: ['maïs', 'pomme de terre', 'quinoa', 'haricots', 'chicha'],
		clothing: ['mante en coton', 'ornements en or', 'plumes'],
		socialCustoms: [
			"offrande d'or au lac sacré",
			'commerce du sel et des émeraudes',
			'système de caciques (Zipa et Zaque)',
			'tradition orale et astronomie',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_guarani',
		architecturalStyle: 'other',
		culturalTraits: ['spiritual', 'nomadic', 'warrior', 'communal'],
		festivals: [
			"Rituel de l'Avati (maïs)",
			'Danse cérémonielle',
			'Fête de la chasse',
		],
		artForms: ['featherwork', 'pottery', 'body_painting', 'music'],
		cuisineStaples: ['manioc', 'maïs', 'patate douce', 'gibier', 'yerba maté'],
		clothing: ['pagne en coton', 'peinture corporelle', 'plumes'],
		socialCustoms: [
			'quête de la Terre sans Mal (Yvy Maraey)',
			'organisation en tekoha (village)',
			'anthropophagie rituelle',
			'tradition orale',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_hawaii',
		architecturalStyle: 'other',
		culturalTraits: ['maritime', 'hierarchical', 'warrior', 'spiritual'],
		festivals: ['Makahiki (fête de Lono)', 'Cérémonie au heiau', 'Hula sacré'],
		artForms: ['hula_dance', 'tapa_cloth', 'featherwork', 'canoe_building'],
		cuisineStaples: ['taro', 'poi', 'poisson', 'noix de coco', 'patate douce'],
		clothing: ['malo (pagne en tapa)', 'cape en plumes', 'lei de fleurs'],
		socialCustoms: [
			'kapu (tabou sacré)',
			"système ali'i (noblesse)",
			'ohana (famille étendue)',
			'navigation hauturière',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_ainu',
		architecturalStyle: 'other',
		culturalTraits: ['spiritual', 'hunter', 'communal'],
		festivals: [
			"Iyomante (cérémonie de l'ours)",
			'Fête du saumon',
			'Asiri Cep Nomi',
		],
		artForms: [
			'wood_carving',
			'textile_embroidery',
			'ritual_dance',
			'oral_poetry',
		],
		cuisineStaples: ['saumon', 'cerf', 'ours', 'racines sauvages', 'millet'],
		clothing: [
			'attus (robe en écorce)',
			'kaparimip (ornements)',
			'bandeau brodé',
		],
		socialCustoms: [
			'kamuy (esprits dans la nature)',
			"iyomante (renvoi de l'esprit de l'ours)",
			'tatouage labial féminin',
			'tradition orale (yukar)',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_makuria',
		architecturalStyle: 'byzantine_nubian',
		culturalTraits: ['pious', 'artistic', 'literate'],
		festivals: ['Noël copte', 'Pâques', 'Fête de la Croix'],
		artForms: [
			'fresco_painting',
			'pottery',
			'manuscript_illumination',
			'architecture',
		],
		cuisineStaples: ['mil', 'dattes', 'poisson du Nil', 'lentilles', 'bière'],
		clothing: ['tunique copte', 'turban', 'croix pectorale'],
		socialCustoms: [
			'liturgie copte nubienne',
			'murs peints dans les cathédrales',
			'commerce nilotique',
			'tradition monastique',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_tuareg',
		architecturalStyle: 'other',
		culturalTraits: ['nomadic', 'mercantile', 'warrior', 'poetic'],
		festivals: [
			'Fête du chameau',
			'Amagar (assemblée)',
			'Aïd (fêtes islamiques)',
		],
		artForms: [
			'silversmithing',
			'leather_work',
			'poetry',
			'tifinagh_calligraphy',
		],
		cuisineStaples: [
			'lait de chamelle',
			'dattes',
			'mil',
			'viande séchée',
			'thé',
		],
		clothing: ['tagelmust (voile indigo)', 'gandoura', 'bijoux en argent'],
		socialCustoms: [
			'tagelmust (voile des hommes)',
			'caravane transsaharienne',
			'société matrilinéaire',
			'poésie et musique imzad',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_georgia',
		architecturalStyle: 'byzantine',
		culturalTraits: ['pious', 'martial', 'hospitable', 'literary'],
		festivals: ['Noël orthodoxe', 'Pâques', 'Rtveli (vendanges)'],
		artForms: [
			'fresco_painting',
			'metalwork',
			'manuscript_illumination',
			'polyphonic_singing',
		],
		cuisineStaples: ['pain', 'vin', 'fromage', 'viande grillée', 'herbes'],
		clothing: ['chokha (tunique)', 'papakha (chapeau)', 'ceinture ornée'],
		socialCustoms: [
			'tamada (maître de cérémonie du banquet)',
			'vin en kvevri (jarre souterraine)',
			'hospitalité sacrée',
			'chevalerie caucasienne',
		],
		culturalPrestige: 6,
	},
	{
		nationId: 'nat_armenia',
		architecturalStyle: 'byzantine',
		culturalTraits: ['pious', 'literate', 'mercantile', 'artistic'],
		festivals: ['Noël arménien', 'Pâques', "Vardavar (fête de l'eau)"],
		artForms: [
			'stone_carving',
			'khachkar_cross_stones',
			'manuscript_illumination',
			'architecture',
		],
		cuisineStaples: ['pain lavash', 'agneau', 'grenade', 'herbes', 'vin'],
		clothing: [
			'taraz (costume traditionnel)',
			'ceinture ornée',
			'coiffe brodée',
		],
		socialCustoms: [
			'khachkar (croix de pierre sculptée)',
			'alphabet arménien sacré (Mesrop Mashtots)',
			'diaspora marchande',
			'Ani = cité cosmopolite',
		],
		culturalPrestige: 8,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 3
	// ========================================================================
	{
		nationId: 'nat_hohokam',
		architecturalStyle: 'other',
		culturalTraits: ['agricultural', 'communal', 'ritual'],
		festivals: ['Cérémonie du canal', 'Jeu de balle', 'Fête de la récolte'],
		artForms: ['pottery', 'shell_etching', 'canal_engineering'],
		cuisineStaples: ['maïs', 'haricots', 'courge', 'cactus', 'gibier'],
		clothing: ['pagne en coton', 'sandales', 'ornements en coquillage'],
		socialCustoms: [
			'jeu de balle rituel',
			"canaux d'irrigation collectifs",
			'crémation des morts',
			'commerce de coquillages',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_dorset',
		architecturalStyle: 'other',
		culturalTraits: ['hunter', 'artistic', 'spiritual'],
		festivals: ['Cérémonie du phoque', "Solstice d'hiver"],
		artForms: ['ivory_carving', 'bone_tools', 'miniature_masks'],
		cuisineStaples: ['phoque', 'morse', 'poisson', 'oiseau marin'],
		clothing: ['peaux de phoque', "fourrure d'ours polaire", "aiguilles d'os"],
		socialCustoms: [
			'art miniature sur ivoire',
			'chasse au phoque sur glace',
			'absence de chien de traîneau',
			'tradition orale',
		],
		culturalPrestige: 2,
	},
	{
		nationId: 'nat_beothuk',
		architecturalStyle: 'other',
		culturalTraits: ['hunter', 'reclusive', 'maritime'],
		festivals: ["Cérémonie de l'ocre rouge", 'Fête de la chasse au caribou'],
		artForms: ['bone_pendants', 'birch_bark_craft', 'ochre_painting'],
		cuisineStaples: ['caribou', 'saumon', 'phoque', 'oiseaux marins', 'baies'],
		clothing: [
			"peaux de caribou teintes à l'ocre rouge",
			'mocassins',
			'cape de fourrure',
		],
		socialCustoms: [
			'ocre rouge sur le corps et les objets',
			'mamateek (habitation conique)',
			'évitement des étrangers',
			'tradition orale',
		],
		culturalPrestige: 1,
	},
	{
		nationId: 'nat_dene',
		architecturalStyle: 'other',
		culturalTraits: ['hunter', 'nomadic', 'spiritual'],
		festivals: [
			'Danse du tambour',
			'Cérémonie de la chasse',
			'Potlatch (certains groupes)',
		],
		artForms: ['beadwork', 'birch_bark_craft', 'drum_making', 'quillwork'],
		cuisineStaples: ['caribou', 'poisson', 'orignal', 'baies', 'racines'],
		clothing: ['tunique en peau de caribou', 'mocassins', 'raquettes à neige'],
		socialCustoms: [
			'bande de chasse familiale',
			'traîneau à chien',
			'tradition orale et prophétie',
			'respect du caribou',
		],
		culturalPrestige: 2,
	},
	{
		nationId: 'nat_mikmaq',
		architecturalStyle: 'other',
		culturalTraits: ['maritime', 'diplomatic', 'spiritual'],
		festivals: [
			'Pow-wow',
			'Cérémonie du saumon',
			'Fête de la Lune des fraises',
		],
		artForms: ['quillwork', 'birch_bark_craft', 'beadwork', 'storytelling'],
		cuisineStaples: ['saumon', 'homard', 'orignal', 'maïs', 'baies'],
		clothing: [
			"tunique en peau d'orignal",
			'mocassins brodés',
			'cape de fourrure',
		],
		socialCustoms: [
			'wigwam (habitation)',
			'confédération Wabanaki',
			'commerce maritime côtier',
			'tradition orale et wampum',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_papuan',
		architecturalStyle: 'other',
		culturalTraits: ['agricultural', 'ritual', 'warrior'],
		festivals: [
			'Sing-sing',
			"Cérémonie d'initiation",
			'Fête de la patate douce',
		],
		artForms: ['body_painting', 'mask_carving', 'featherwork', 'bilum_weaving'],
		cuisineStaples: ['patate douce', 'taro', 'sagou', 'porc', 'banane'],
		clothing: [
			'koteka (étui pénien)',
			"plumes d'oiseau de paradis",
			'peinture corporelle',
		],
		socialCustoms: [
			'système du Big Man',
			'maison des hommes (haus tambaran)',
			'échange de cochons',
			'guerres rituelles',
		],
		culturalPrestige: 2,
	},
	{
		nationId: 'nat_fiji',
		architecturalStyle: 'other',
		culturalTraits: ['warrior', 'maritime', 'hierarchical'],
		festivals: ['Cérémonie du kava', 'Fête de la première récolte'],
		artForms: ['pottery', 'tapa_cloth', 'canoe_building', 'masi_printing'],
		cuisineStaples: ['taro', 'igname', 'noix de coco', 'poisson', 'porc'],
		clothing: ['masi (tapa)', 'sulu (pagne)', 'ornements en os et dents'],
		socialCustoms: [
			'cérémonie du yaqona (kava)',
			'chefs héréditaires (Ratu)',
			'cannibalisme rituel',
			'construction de drua (grands canoës)',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_chamorro',
		architecturalStyle: 'other',
		culturalTraits: ['maritime', 'builder', 'hierarchical'],
		festivals: ['Cérémonie du latte', 'Fête de la pêche'],
		artForms: [
			'latte_stone_pillars',
			'weaving',
			'shell_jewelry',
			'canoe_building',
		],
		cuisineStaples: [
			'riz sauvage',
			'poisson',
			'noix de coco',
			'taro',
			'fruit à pain',
		],
		clothing: ['pagne en tapa', 'ornements en coquillage', 'tatouages'],
		socialCustoms: [
			'maisons sur piliers de latte (latte stones)',
			'société matrilinéaire',
			'navigation en proa (sakman)',
			'tradition orale',
		],
		culturalPrestige: 3,
	},
	{
		nationId: 'nat_guanche',
		architecturalStyle: 'other',
		culturalTraits: ['pastoral', 'isolationist', 'spiritual'],
		festivals: ['Fête de Beñesmen (récolte)', 'Cérémonie à Achamán'],
		artForms: ['pottery', 'stone_tools', 'mummification', 'cave_painting'],
		cuisineStaples: [
			'gofio (farine grillée)',
			'lait de chèvre',
			'poisson',
			'baies',
		],
		clothing: ['peaux de chèvre', 'tamarco (cape)', 'sandales en cuir'],
		socialCustoms: [
			'momification des nobles',
			'pyramides à degrés (Güímar)',
			'assemblée du tagoror (conseil)',
			'culture pastorale caprine',
		],
		culturalPrestige: 2,
	},
	{
		nationId: 'nat_san',
		architecturalStyle: 'other',
		culturalTraits: ['egalitarian', 'spiritual', 'nomadic'],
		festivals: ['Danse de guérison (trance dance)', 'Cérémonie de la pluie'],
		artForms: ['rock_art', 'storytelling', 'music_bow', 'dance'],
		cuisineStaples: [
			'gibier',
			'racines',
			'tubercules',
			'baies',
			'melon tsamma',
		],
		clothing: [
			'peau de springbok',
			'sandales en cuir',
			"ornements en coquille d'autruche",
		],
		socialCustoms: [
			'société égalitaire sans chef',
			'partage obligatoire du gibier',
			'peintures rupestres',
			'pharmacopée du bush',
		],
		culturalPrestige: 2,
	},
	{
		nationId: 'nat_mbuti',
		architecturalStyle: 'other',
		culturalTraits: ['egalitarian', 'forest_people', 'musical'],
		festivals: ['Molimo (cérémonie de la forêt)', 'Elima (initiation)'],
		artForms: ['polyphonic_singing', 'body_painting', 'net_weaving'],
		cuisineStaples: [
			'gibier',
			'miel',
			'champignons',
			'igname sauvage',
			'chenilles',
		],
		clothing: ["pagne d'écorce battue", 'feuilles', 'ornements légers'],
		socialCustoms: [
			'molimo (chant pour réveiller la forêt)',
			'chasse au filet collective',
			'échange avec les villageois bantous',
			'société sans hiérarchie fixe',
		],
		culturalPrestige: 1,
	},
	{
		nationId: 'nat_igbo',
		architecturalStyle: 'west_african',
		culturalTraits: ['mercantile', 'egalitarian', 'pious', 'artistic'],
		festivals: ['Fête du Nouvel Igname', 'Mascarade Mmanwu', 'Cérémonie Nri'],
		artForms: ['bronze_casting', 'pottery', 'mask_carving', 'weaving'],
		cuisineStaples: [
			'igname',
			'huile de palme',
			'manioc',
			'poisson',
			'vin de palme',
		],
		clothing: [
			'isiagu (tunique)',
			'pagne tissé',
			'ornements en ivoire et bronze',
		],
		socialCustoms: [
			'Eze Nri (roi-prêtre pacifique)',
			'système Ozo (titres de mérite)',
			'commerce et marchés',
			'Odinani (cosmologie Igbo)',
		],
		culturalPrestige: 5,
	},
	{
		nationId: 'nat_chukchi',
		architecturalStyle: 'other',
		culturalTraits: ['nomadic', 'warrior', 'resilient'],
		festivals: ['Fête de la baleine', 'Cérémonie du renne', 'Solstice'],
		artForms: ['ivory_carving', 'drum_making', 'hide_painting', 'storytelling'],
		cuisineStaples: [
			'viande de renne',
			'viande de morse',
			'graisse de phoque',
			'racines',
			'baies',
		],
		clothing: [
			'kuhlianka (combinaison en peau de renne)',
			'bottes en phoque',
			'gants en fourrure',
		],
		socialCustoms: [
			'yaranga (tente nomade)',
			'élevage de rennes',
			'chasse au morse et à la baleine',
			'chamanisme du tambour',
		],
		culturalPrestige: 2,
	},
]
