import type { Nation, GeoPolygon } from '../../../shared/src/types/world'

// ============================================================================
// Nations du monde — An 1000
// ============================================================================
// territory : polygone simplifié (4-8 points), sera affiné avec des données SIG
// tileIds : vide pour l'instant, sera peuplé par le générateur de tuiles
// color : couleur hex pour la carte
// ============================================================================

/** Raccourci pour créer un polygone simplifié à partir de coins [lat, lng][] */
const poly = (points: [number, number][]): GeoPolygon =>
	points.map(([lat, lng]) => ({ lat, lng }))

export const nations: Nation[] = [
	// ========================================================================
	// EUROPE OCCIDENTALE
	// ========================================================================
	{
		id: 'nat_hre',
		name: 'Saint-Empire romain germanique',
		dempinym: 'Germanique',
		governance: 'feudal_monarchy',
		capital: 'set_aachen',
		territory: poly([
			[54.5, 5.5],
			[54.5, 16],
			[46, 16],
			[45.5, 12],
			[47.5, 5.5],
		]),
		tileIds: [],
		ruler: {
			name: 'Otton III',
			dynastyName: 'Ottoniens',
			birthYear: 980,
			age: 20,
			traits: ['ambitious', 'pious', 'visionary'],
		},
		diplomacy: [
			{ targetNationId: 'nat_papal', type: 'alliance', strength: 7 },
			{ targetNationId: 'nat_poland', type: 'rivalry', strength: 4 },
			{ targetNationId: 'nat_byzantine', type: 'rivalry', strength: 3 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 8,
		color: '#C4A000',
	},
	{
		id: 'nat_france',
		name: 'Royaume de France',
		dempinym: 'Français',
		governance: 'feudal_monarchy',
		capital: 'set_paris',
		territory: poly([
			[51, -1.5],
			[51, 5],
			[48, 7.5],
			[43, 7],
			[42.5, 3],
			[43, -1.5],
		]),
		tileIds: [],
		ruler: {
			name: 'Robert II le Pieux',
			dynastyName: 'Capétiens',
			birthYear: 972,
			age: 28,
			traits: ['pious', 'scholarly', 'weak'],
		},
		diplomacy: [
			{ targetNationId: 'nat_hre', type: 'neutral', strength: 4 },
			{ targetNationId: 'nat_england', type: 'rivalry', strength: 5 },
		],
		vassalOf: null,
		stability: 4, // pouvoir royal faible, féodaux puissants
		prestige: 6,
		color: '#3465A4',
	},
	{
		id: 'nat_england',
		name: "Royaume d'Angleterre",
		dempinym: 'Anglais',
		governance: 'feudal_monarchy',
		capital: 'set_london',
		territory: poly([
			[55.8, -5.5],
			[55.8, 1.5],
			[50.7, 1.5],
			[50.7, -5.5],
		]),
		tileIds: [],
		ruler: {
			name: 'Æthelred le Malavisé',
			dynastyName: 'Wessex',
			birthYear: 968,
			age: 32,
			traits: ['indecisive', 'suspicious', 'generous'],
		},
		diplomacy: [
			{ targetNationId: 'nat_denmark', type: 'war', strength: 9 },
			{ targetNationId: 'nat_france', type: 'neutral', strength: 3 },
		],
		vassalOf: null,
		stability: 3, // raids vikings incessants
		prestige: 5,
		color: '#CC0000',
	},
	{
		id: 'nat_scotland',
		name: "Royaume d'Écosse",
		dempinym: 'Écossais',
		governance: 'feudal_monarchy',
		capital: 'set_scone',
		territory: poly([
			[58.5, -7.5],
			[58.5, -1],
			[55.8, -1],
			[55.8, -5.5],
			[56, -7.5],
		]),
		tileIds: [],
		ruler: {
			name: 'Kenneth III',
			dynastyName: 'Alpin',
			birthYear: 966,
			age: 34,
			traits: ['warrior', 'ambitious'],
		},
		diplomacy: [
			{ targetNationId: 'nat_england', type: 'rivalry', strength: 4 },
		],
		vassalOf: null,
		stability: 5,
		prestige: 3,
		color: '#204A87',
	},
	{
		id: 'nat_papal',
		name: 'États pontificaux',
		dempinym: 'Pontifical',
		governance: 'theocracy',
		capital: 'set_rome',
		territory: poly([
			[43.5, 11],
			[43.5, 14],
			[41, 14.5],
			[41, 12],
			[42, 11],
		]),
		tileIds: [],
		ruler: {
			name: 'Sylvestre II',
			dynastyName: 'Papauté',
			birthYear: 946,
			age: 54,
			traits: ['scholarly', 'wise', 'diplomatic'],
		},
		diplomacy: [
			{ targetNationId: 'nat_hre', type: 'alliance', strength: 7 },
			{ targetNationId: 'nat_byzantine', type: 'rivalry', strength: 5 },
		],
		vassalOf: null,
		stability: 5,
		prestige: 9, // autorité spirituelle sur toute la chrétienté latine
		color: '#EEEECC',
	},
	{
		id: 'nat_venice',
		name: 'République de Venise',
		dempinym: 'Vénitien',
		governance: 'republic',
		capital: 'set_venice',
		territory: poly([
			[45.8, 11.5],
			[45.8, 13],
			[45, 13],
			[45, 11.5],
		]),
		tileIds: [],
		ruler: {
			name: 'Pietro II Orseolo',
			dynastyName: 'Orseolo',
			birthYear: 961,
			age: 39,
			traits: ['diplomatic', 'merchant', 'ambitious'],
		},
		diplomacy: [
			{ targetNationId: 'nat_byzantine', type: 'trade_agreement', strength: 8 },
			{ targetNationId: 'nat_fatimid', type: 'trade_agreement', strength: 5 },
		],
		vassalOf: null,
		stability: 8,
		prestige: 7,
		color: '#8F5902',
	},

	// ========================================================================
	// PÉNINSULE IBÉRIQUE
	// ========================================================================
	{
		id: 'nat_leon',
		name: 'Royaume de León',
		dempinym: 'Léonais',
		governance: 'feudal_monarchy',
		capital: 'set_leon',
		territory: poly([
			[43.5, -9],
			[43.5, -3],
			[40, -3],
			[39, -7],
			[41, -9],
		]),
		tileIds: [],
		ruler: {
			name: 'Alphonse V',
			dynastyName: 'Jimena',
			birthYear: 994,
			age: 6,
			traits: ['young', 'pious'],
		},
		diplomacy: [
			{ targetNationId: 'nat_cordoba', type: 'war', strength: 7 },
			{ targetNationId: 'nat_navarre', type: 'alliance', strength: 5 },
		],
		vassalOf: null,
		stability: 4,
		prestige: 5,
		color: '#5C3566',
	},
	{
		id: 'nat_navarre',
		name: 'Royaume de Navarre',
		dempinym: 'Navarrais',
		governance: 'feudal_monarchy',
		capital: 'set_pamplona',
		territory: poly([
			[43.5, -3],
			[43.5, -0.5],
			[42, -0.5],
			[42, -3],
		]),
		tileIds: [],
		ruler: {
			name: 'Sanche III le Grand',
			dynastyName: 'Jimena',
			birthYear: 992,
			age: 8,
			traits: ['ambitious', 'strategic'],
		},
		diplomacy: [
			{ targetNationId: 'nat_leon', type: 'alliance', strength: 5 },
			{ targetNationId: 'nat_cordoba', type: 'rivalry', strength: 6 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 4,
		color: '#A40000',
	},
	{
		id: 'nat_cordoba',
		name: 'Califat de Cordoue',
		dempinym: 'Omeyyade',
		governance: 'theocracy',
		capital: 'set_cordoba',
		territory: poly([
			[40, -7],
			[40, -0.5],
			[36.5, -1],
			[36, -6],
			[38, -9],
		]),
		tileIds: [],
		ruler: {
			name: 'Hicham II',
			dynastyName: 'Omeyyades',
			birthYear: 966,
			age: 34,
			traits: ['weak', 'puppet'], // sous domination d'Al-Mansur
		},
		diplomacy: [
			{ targetNationId: 'nat_leon', type: 'war', strength: 7 },
			{ targetNationId: 'nat_fatimid', type: 'rivalry', strength: 5 },
		],
		vassalOf: null,
		stability: 4, // fitna imminente (1009)
		prestige: 8,
		color: '#4E9A06',
	},

	// ========================================================================
	// SCANDINAVIE & EUROPE DU NORD
	// ========================================================================
	{
		id: 'nat_denmark',
		name: 'Royaume du Danemark',
		dempinym: 'Danois',
		governance: 'feudal_monarchy',
		capital: 'set_roskilde',
		territory: poly([
			[57.8, 8],
			[57.8, 13],
			[54.5, 13],
			[54.5, 8],
		]),
		tileIds: [],
		ruler: {
			name: 'Sven à la Barbe Fourchue',
			dynastyName: 'Jelling',
			birthYear: 960,
			age: 40,
			traits: ['warrior', 'ambitious', 'cunning'],
		},
		diplomacy: [
			{ targetNationId: 'nat_england', type: 'war', strength: 9 },
			{ targetNationId: 'nat_norway', type: 'vassalage', strength: 7 },
			{ targetNationId: 'nat_sweden', type: 'rivalry', strength: 4 },
		],
		vassalOf: null,
		stability: 7,
		prestige: 7,
		color: '#EF2929',
	},
	{
		id: 'nat_norway',
		name: 'Royaume de Norvège',
		dempinym: 'Norvégien',
		governance: 'feudal_monarchy',
		capital: 'set_nidaros',
		territory: poly([
			[71, 5],
			[71, 16],
			[63, 16],
			[58, 8],
			[58, 5],
		]),
		tileIds: [],
		ruler: {
			name: 'Olaf Tryggvason',
			dynastyName: 'Yngling',
			birthYear: 968,
			age: 32,
			traits: ['warrior', 'pious', 'charismatic'],
		},
		diplomacy: [
			{ targetNationId: 'nat_denmark', type: 'rivalry', strength: 6 },
		],
		vassalOf: null,
		stability: 5,
		prestige: 5,
		color: '#729FCF',
	},
	{
		id: 'nat_sweden',
		name: 'Royaume de Suède',
		dempinym: 'Suédois',
		governance: 'feudal_monarchy',
		capital: 'set_sigtuna',
		territory: poly([
			[69, 16],
			[69, 24],
			[55.5, 19],
			[55.5, 13],
			[63, 13],
		]),
		tileIds: [],
		ruler: {
			name: 'Olof Skötkonung',
			dynastyName: 'Munsö',
			birthYear: 980,
			age: 20,
			traits: ['pious', 'cautious'],
		},
		diplomacy: [
			{ targetNationId: 'nat_denmark', type: 'alliance', strength: 5 },
			{
				targetNationId: 'nat_kievan_rus',
				type: 'trade_agreement',
				strength: 4,
			},
		],
		vassalOf: null,
		stability: 5,
		prestige: 4,
		color: '#FCE94F',
	},

	// ========================================================================
	// EUROPE ORIENTALE
	// ========================================================================
	{
		id: 'nat_poland',
		name: 'Royaume de Pologne',
		dempinym: 'Polonais',
		governance: 'feudal_monarchy',
		capital: 'set_gniezno',
		territory: poly([
			[54.5, 16],
			[54.5, 24],
			[50, 24],
			[49.5, 16],
		]),
		tileIds: [],
		ruler: {
			name: 'Boleslas Ier le Vaillant',
			dynastyName: 'Piast',
			birthYear: 967,
			age: 33,
			traits: ['ambitious', 'warrior', 'diplomatic'],
		},
		diplomacy: [
			{ targetNationId: 'nat_hre', type: 'rivalry', strength: 5 },
			{ targetNationId: 'nat_kievan_rus', type: 'rivalry', strength: 4 },
			{ targetNationId: 'nat_hungary', type: 'alliance', strength: 5 },
		],
		vassalOf: null,
		stability: 7,
		prestige: 6,
		color: '#AD7FA8',
	},
	{
		id: 'nat_hungary',
		name: 'Royaume de Hongrie',
		dempinym: 'Hongrois',
		governance: 'feudal_monarchy',
		capital: 'set_esztergom',
		territory: poly([
			[49, 16],
			[49, 23],
			[45.5, 22],
			[44.5, 16],
		]),
		tileIds: [],
		ruler: {
			name: 'Étienne Ier',
			dynastyName: 'Árpád',
			birthYear: 975,
			age: 25,
			traits: ['pious', 'wise', 'reformer'],
		},
		diplomacy: [
			{ targetNationId: 'nat_poland', type: 'alliance', strength: 5 },
			{ targetNationId: 'nat_hre', type: 'neutral', strength: 5 },
			{ targetNationId: 'nat_byzantine', type: 'neutral', strength: 4 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 5,
		color: '#73D216',
	},
	{
		id: 'nat_kievan_rus',
		name: "Rus' de Kiev",
		dempinym: 'Ruthène',
		governance: 'feudal_monarchy',
		capital: 'set_kiev',
		territory: poly([
			[59, 28],
			[59, 42],
			[48, 42],
			[46, 34],
			[48, 24],
			[54.5, 24],
		]),
		tileIds: [],
		ruler: {
			name: 'Vladimir Ier le Grand',
			dynastyName: 'Riourikides',
			birthYear: 958,
			age: 42,
			traits: ['warrior', 'pious', 'reformer', 'ambitious'],
		},
		diplomacy: [
			{ targetNationId: 'nat_byzantine', type: 'alliance', strength: 7 },
			{ targetNationId: 'nat_poland', type: 'rivalry', strength: 4 },
			{ targetNationId: 'nat_volga_bulgaria', type: 'rivalry', strength: 5 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 7,
		color: '#CE5C00',
	},
	{
		id: 'nat_volga_bulgaria',
		name: 'Bulgarie de la Volga',
		dempinym: 'Bulgare (Volga)',
		governance: 'tribal_confederation',
		capital: 'set_bulgar',
		territory: poly([
			[57, 42],
			[57, 53],
			[52, 53],
			[52, 42],
		]),
		tileIds: [],
		ruler: {
			name: 'Émir inconnu',
			dynastyName: 'Dynastie bulgare',
			birthYear: 950,
			age: 50,
			traits: ['merchant', 'diplomatic'],
		},
		diplomacy: [
			{ targetNationId: 'nat_kievan_rus', type: 'rivalry', strength: 5 },
			{
				targetNationId: 'nat_karakhanid',
				type: 'trade_agreement',
				strength: 4,
			},
		],
		vassalOf: null,
		stability: 6,
		prestige: 4,
		color: '#8AE234',
	},
	{
		id: 'nat_croatia',
		name: 'Royaume de Croatie',
		dempinym: 'Croate',
		governance: 'feudal_monarchy',
		capital: 'set_biograd',
		territory: poly([
			[46, 13],
			[46, 17],
			[43, 17.5],
			[42.5, 16],
			[44.5, 13],
		]),
		tileIds: [],
		ruler: {
			name: 'Svetislav Suronja',
			dynastyName: 'Trpimirović',
			birthYear: 960,
			age: 40,
			traits: ['cautious', 'pious'],
		},
		diplomacy: [
			{ targetNationId: 'nat_byzantine', type: 'rivalry', strength: 4 },
			{ targetNationId: 'nat_hungary', type: 'neutral', strength: 4 },
			{ targetNationId: 'nat_venice', type: 'rivalry', strength: 5 },
		],
		vassalOf: null,
		stability: 4,
		prestige: 4,
		color: '#E9B96E',
	},

	// ========================================================================
	// EMPIRE BYZANTIN
	// ========================================================================
	{
		id: 'nat_byzantine',
		name: 'Empire byzantin',
		dempinym: 'Byzantin',
		governance: 'empire',
		capital: 'set_constantinople',
		territory: poly([
			[43, 22],
			[43, 37],
			[35, 37],
			[35, 24],
			[38, 22],
		]),
		tileIds: [],
		ruler: {
			name: 'Basile II le Bulgaroctone',
			dynastyName: 'Macédoniens',
			birthYear: 958,
			age: 42,
			traits: ['warrior', 'ruthless', 'strategic', 'ascetic'],
		},
		diplomacy: [
			{ targetNationId: 'nat_kievan_rus', type: 'alliance', strength: 7 },
			{ targetNationId: 'nat_fatimid', type: 'rivalry', strength: 6 },
			{ targetNationId: 'nat_hre', type: 'rivalry', strength: 3 },
			{ targetNationId: 'nat_papal', type: 'rivalry', strength: 5 },
		],
		vassalOf: null,
		stability: 8, // apogée sous Basile II
		prestige: 9,
		color: '#75507B',
	},

	// ========================================================================
	// MONDE ISLAMIQUE
	// ========================================================================
	{
		id: 'nat_fatimid',
		name: 'Califat fatimide',
		dempinym: 'Fatimide',
		governance: 'theocracy',
		capital: 'set_cairo',
		territory: poly([
			[35, 24],
			[35, 37],
			[22, 40],
			[22, 10],
			[32, 10],
		]),
		tileIds: [],
		ruler: {
			name: 'Al-Hakim bi-Amr Allah',
			dynastyName: 'Fatimides',
			birthYear: 985,
			age: 15,
			traits: ['unpredictable', 'pious', 'cruel', 'eccentric'],
		},
		diplomacy: [
			{ targetNationId: 'nat_byzantine', type: 'rivalry', strength: 6 },
			{ targetNationId: 'nat_cordoba', type: 'rivalry', strength: 5 },
			{ targetNationId: 'nat_buyid', type: 'rivalry', strength: 7 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 8,
		color: '#4E9A06',
	},
	{
		id: 'nat_buyid',
		name: 'Émirat bouyide',
		dempinym: 'Bouyide',
		governance: 'feudal_monarchy',
		capital: 'set_shiraz',
		territory: poly([
			[37, 44],
			[37, 55],
			[28, 55],
			[25, 48],
			[32, 44],
		]),
		tileIds: [],
		ruler: {
			name: 'Baha al-Dawla',
			dynastyName: 'Bouyides',
			birthYear: 970,
			age: 30,
			traits: ['cultured', 'weak', 'indecisive'],
		},
		diplomacy: [
			{ targetNationId: 'nat_fatimid', type: 'rivalry', strength: 7 },
			{ targetNationId: 'nat_ghaznavid', type: 'rivalry', strength: 6 },
		],
		vassalOf: null,
		stability: 3, // en déclin
		prestige: 5,
		color: '#D3D7CF',
	},
	{
		id: 'nat_ghaznavid',
		name: 'Empire ghaznavide',
		dempinym: 'Ghaznavide',
		governance: 'empire',
		capital: 'set_ghazni',
		territory: poly([
			[37, 55],
			[37, 72],
			[28, 72],
			[25, 62],
			[28, 55],
		]),
		tileIds: [],
		ruler: {
			name: 'Mahmoud de Ghazni',
			dynastyName: 'Ghaznavides',
			birthYear: 971,
			age: 29,
			traits: ['warrior', 'ambitious', 'pious', 'ruthless'],
		},
		diplomacy: [
			{ targetNationId: 'nat_buyid', type: 'rivalry', strength: 6 },
			{ targetNationId: 'nat_karakhanid', type: 'alliance', strength: 4 },
		],
		vassalOf: null,
		stability: 7,
		prestige: 8,
		color: '#888A85',
	},
	{
		id: 'nat_karakhanid',
		name: 'Khanat karakhanide',
		dempinym: 'Karakhanide',
		governance: 'tribal_confederation',
		capital: 'set_samarkand',
		territory: poly([
			[45, 60],
			[45, 80],
			[37, 80],
			[37, 60],
		]),
		tileIds: [],
		ruler: {
			name: 'Nasr ibn Ali',
			dynastyName: 'Karakhanides',
			birthYear: 960,
			age: 40,
			traits: ['warrior', 'merchant', 'pious'],
		},
		diplomacy: [
			{ targetNationId: 'nat_ghaznavid', type: 'alliance', strength: 4 },
			{ targetNationId: 'nat_song', type: 'trade_agreement', strength: 3 },
		],
		vassalOf: null,
		stability: 5,
		prestige: 5,
		color: '#BABDB6',
	},

	// ========================================================================
	// ASIE DE L'EST
	// ========================================================================
	{
		id: 'nat_song',
		name: 'Dynastie Song',
		dempinym: 'Song',
		governance: 'empire',
		capital: 'set_kaifeng',
		territory: poly([
			[40, 104],
			[40, 122],
			[22, 122],
			[22, 100],
			[28, 97],
		]),
		tileIds: [],
		ruler: {
			name: 'Zhenzong',
			dynastyName: 'Song',
			birthYear: 968,
			age: 32,
			traits: ['scholarly', 'cautious', 'pious', 'diplomatic'],
		},
		diplomacy: [
			{ targetNationId: 'nat_liao', type: 'rivalry', strength: 8 },
			{ targetNationId: 'nat_goryeo', type: 'trade_agreement', strength: 5 },
			{ targetNationId: 'nat_dai_viet', type: 'tributary', strength: 4 },
		],
		vassalOf: null,
		stability: 7,
		prestige: 10, // civilisation la plus avancée du monde
		color: '#EDD400',
	},
	{
		id: 'nat_liao',
		name: 'Dynastie Liao (Khitans)',
		dempinym: 'Khitan',
		governance: 'empire',
		capital: 'set_shangjing',
		territory: poly([
			[50, 104],
			[50, 128],
			[40, 128],
			[40, 104],
		]),
		tileIds: [],
		ruler: {
			name: 'Shengzong',
			dynastyName: 'Yelü (Liao)',
			birthYear: 971,
			age: 29,
			traits: ['warrior', 'diplomatic', 'cultured'],
		},
		diplomacy: [
			{ targetNationId: 'nat_song', type: 'rivalry', strength: 8 },
			{ targetNationId: 'nat_goryeo', type: 'war', strength: 7 },
		],
		vassalOf: null,
		stability: 7,
		prestige: 7,
		color: '#F57900',
	},
	{
		id: 'nat_goryeo',
		name: 'Goryeo (Corée)',
		dempinym: 'Coréen',
		governance: 'feudal_monarchy',
		capital: 'set_kaesong',
		territory: poly([
			[42, 124],
			[42, 130],
			[34, 130],
			[34, 126],
			[38, 124],
		]),
		tileIds: [],
		ruler: {
			name: 'Mokjong',
			dynastyName: 'Wang',
			birthYear: 980,
			age: 20,
			traits: ['scholarly', 'weak'],
		},
		diplomacy: [
			{ targetNationId: 'nat_song', type: 'trade_agreement', strength: 5 },
			{ targetNationId: 'nat_liao', type: 'war', strength: 7 },
		],
		vassalOf: null,
		stability: 5,
		prestige: 5,
		color: '#2E3436',
	},
	{
		id: 'nat_japan',
		name: 'Japon (Heian)',
		dempinym: 'Japonais',
		governance: 'feudal_monarchy', // Cour impériale dominée par les Fujiwara
		capital: 'set_kyoto',
		territory: poly([
			[45, 130],
			[45, 146],
			[31, 146],
			[31, 130],
		]),
		tileIds: [],
		ruler: {
			name: 'Empereur Ichijō',
			dynastyName: 'Yamato (régence Fujiwara)',
			birthYear: 980,
			age: 20,
			traits: ['cultured', 'scholarly', 'passive'],
		},
		diplomacy: [
			{ targetNationId: 'nat_song', type: 'trade_agreement', strength: 3 },
		],
		vassalOf: null,
		stability: 7, // stabilité Fujiwara
		prestige: 6,
		color: '#FCAF3E',
	},
	{
		id: 'nat_dai_viet',
		name: 'Đại Cồ Việt',
		dempinym: 'Vietnamien',
		governance: 'feudal_monarchy',
		capital: 'set_hoa_lu',
		territory: poly([
			[23, 104],
			[23, 108],
			[16, 108.5],
			[16, 104.5],
		]),
		tileIds: [],
		ruler: {
			name: 'Lê Hoàn',
			dynastyName: 'Lê antérieurs',
			birthYear: 941,
			age: 59,
			traits: ['warrior', 'cunning', 'ambitious'],
		},
		diplomacy: [
			{ targetNationId: 'nat_song', type: 'tributary', strength: 4 },
			{ targetNationId: 'nat_khmer', type: 'rivalry', strength: 4 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 4,
		color: '#C17D11',
	},

	// ========================================================================
	// ASIE DU SUD-EST
	// ========================================================================
	{
		id: 'nat_khmer',
		name: 'Empire khmer (Angkor)',
		dempinym: 'Khmer',
		governance: 'empire',
		capital: 'set_angkor',
		territory: poly([
			[16, 100],
			[16, 108],
			[10, 108],
			[10, 100],
		]),
		tileIds: [],
		ruler: {
			name: 'Jayavarman V',
			dynastyName: 'Angkor',
			birthYear: 955,
			age: 45,
			traits: ['pious', 'builder', 'cultured'],
		},
		diplomacy: [
			{ targetNationId: 'nat_dai_viet', type: 'rivalry', strength: 4 },
			{ targetNationId: 'nat_srivijaya', type: 'trade_agreement', strength: 3 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 7,
		color: '#4E9A06',
	},
	{
		id: 'nat_srivijaya',
		name: 'Empire de Srivijaya',
		dempinym: 'Srivijayan',
		governance: 'empire',
		capital: 'set_palembang',
		territory: poly([
			[4, 97],
			[4, 110],
			[-8, 115],
			[-8, 100],
		]),
		tileIds: [],
		ruler: {
			name: 'Maharaja de Srivijaya',
			dynastyName: 'Sailendra',
			birthYear: 955,
			age: 45,
			traits: ['merchant', 'diplomatic', 'naval'],
		},
		diplomacy: [
			{ targetNationId: 'nat_song', type: 'trade_agreement', strength: 6 },
			{ targetNationId: 'nat_chola', type: 'rivalry', strength: 5 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 7,
		color: '#06989A',
	},

	// ========================================================================
	// ASIE DU SUD (INDE)
	// ========================================================================
	{
		id: 'nat_chola',
		name: 'Dynastie Chola',
		dempinym: 'Chola',
		governance: 'empire',
		capital: 'set_thanjavur',
		territory: poly([
			[16, 76],
			[16, 82],
			[8, 80],
			[8, 76],
		]),
		tileIds: [],
		ruler: {
			name: 'Rajaraja Ier le Grand',
			dynastyName: 'Chola',
			birthYear: 947,
			age: 53,
			traits: ['warrior', 'ambitious', 'naval', 'builder'],
		},
		diplomacy: [
			{ targetNationId: 'nat_srivijaya', type: 'rivalry', strength: 5 },
			{ targetNationId: 'nat_chalukya', type: 'war', strength: 7 },
			{ targetNationId: 'nat_song', type: 'trade_agreement', strength: 4 },
		],
		vassalOf: null,
		stability: 8,
		prestige: 8,
		color: '#CC0000',
	},
	{
		id: 'nat_chalukya',
		name: 'Chalukyas occidentaux',
		dempinym: 'Chalukya',
		governance: 'feudal_monarchy',
		capital: 'set_manyakheta',
		territory: poly([
			[20, 73],
			[20, 78],
			[14, 78],
			[14, 73],
		]),
		tileIds: [],
		ruler: {
			name: 'Satyashraya',
			dynastyName: 'Chalukya',
			birthYear: 955,
			age: 45,
			traits: ['warrior', 'pious'],
		},
		diplomacy: [{ targetNationId: 'nat_chola', type: 'war', strength: 7 }],
		vassalOf: null,
		stability: 5,
		prestige: 5,
		color: '#D3D7CF',
	},
	{
		id: 'nat_pala',
		name: 'Empire Pâla (Bengale)',
		dempinym: 'Pâla',
		governance: 'feudal_monarchy',
		capital: 'set_vikramapura',
		territory: poly([
			[27, 83],
			[27, 92],
			[21, 92],
			[21, 83],
		]),
		tileIds: [],
		ruler: {
			name: 'Mahipala Ier',
			dynastyName: 'Pâla',
			birthYear: 978,
			age: 22,
			traits: ['pious', 'scholarly'],
		},
		diplomacy: [{ targetNationId: 'nat_chola', type: 'neutral', strength: 3 }],
		vassalOf: null,
		stability: 4, // en déclin
		prestige: 5,
		color: '#E9B96E',
	},

	// ========================================================================
	// AFRIQUE
	// ========================================================================
	{
		id: 'nat_ghana',
		name: 'Empire du Ghana',
		dempinym: 'Ghanéen',
		governance: 'empire',
		capital: 'set_koumbi_saleh',
		territory: poly([
			[18, -12],
			[18, -2],
			[12, -2],
			[12, -12],
		]),
		tileIds: [],
		ruler: {
			name: 'Ghana (titre royal)',
			dynastyName: 'Cissé',
			birthYear: 950,
			age: 50,
			traits: ['merchant', 'warrior', 'wealthy'],
		},
		diplomacy: [
			{ targetNationId: 'nat_fatimid', type: 'trade_agreement', strength: 5 },
		],
		vassalOf: null,
		stability: 7,
		prestige: 7,
		color: '#EDD400',
	},
	{
		id: 'nat_kanem',
		name: 'Empire du Kanem',
		dempinym: 'Kanembu',
		governance: 'empire',
		capital: 'set_njimi',
		territory: poly([
			[17, 10],
			[17, 20],
			[10, 20],
			[10, 10],
		]),
		tileIds: [],
		ruler: {
			name: 'Hummay',
			dynastyName: 'Sefuwa',
			birthYear: 960,
			age: 40,
			traits: ['pious', 'warrior'],
		},
		diplomacy: [
			{ targetNationId: 'nat_fatimid', type: 'trade_agreement', strength: 3 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 5,
		color: '#8F5902',
	},
	{
		id: 'nat_ethiopia',
		name: "Royaume d'Éthiopie (Zagwé)",
		dempinym: 'Éthiopien',
		governance: 'feudal_monarchy',
		capital: 'set_lalibela',
		territory: poly([
			[15, 36],
			[15, 43],
			[6, 43],
			[6, 36],
		]),
		tileIds: [],
		ruler: {
			name: 'Roi Zagwé',
			dynastyName: 'Zagwé',
			birthYear: 960,
			age: 40,
			traits: ['pious', 'builder'],
		},
		diplomacy: [
			{ targetNationId: 'nat_fatimid', type: 'rivalry', strength: 4 },
		],
		vassalOf: null,
		stability: 6,
		prestige: 5,
		color: '#4E9A06',
	},
	{
		id: 'nat_swahili_cities',
		name: 'Cités-États swahilies',
		dempinym: 'Swahili',
		governance: 'city_state',
		capital: 'set_kilwa',
		territory: poly([
			[-2, 38],
			[-2, 42],
			[-12, 42],
			[-12, 38],
		]),
		tileIds: [],
		ruler: {
			name: 'Sultan de Kilwa',
			dynastyName: 'Shirazi',
			birthYear: 965,
			age: 35,
			traits: ['merchant', 'diplomatic'],
		},
		diplomacy: [
			{ targetNationId: 'nat_fatimid', type: 'trade_agreement', strength: 5 },
		],
		vassalOf: null,
		stability: 7,
		prestige: 5,
		color: '#06989A',
	},

	// ========================================================================
	// AMÉRIQUES
	// ========================================================================
	{
		id: 'nat_toltec',
		name: 'Empire toltèque',
		dempinym: 'Toltèque',
		governance: 'empire',
		capital: 'set_tula',
		territory: poly([
			[22, -104],
			[22, -96],
			[17, -96],
			[17, -104],
		]),
		tileIds: [],
		ruler: {
			name: 'Ce Acatl Topiltzin',
			dynastyName: 'Toltèque',
			birthYear: 950,
			age: 50,
			traits: ['warrior', 'builder', 'pious'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 5, // tensions internes
		prestige: 8,
		color: '#A40000',
	},
	{
		id: 'nat_maya_states',
		name: 'Cités-États mayas (post-classique)',
		dempinym: 'Maya',
		governance: 'city_state',
		capital: 'set_chichen_itza',
		territory: poly([
			[22, -92],
			[22, -87],
			[15, -87],
			[15, -92],
		]),
		tileIds: [],
		ruler: {
			name: 'Halach Uinic de Chichén Itzá',
			dynastyName: 'Itza',
			birthYear: 955,
			age: 45,
			traits: ['pious', 'scholarly', 'warrior'],
		},
		diplomacy: [
			{ targetNationId: 'nat_toltec', type: 'vassalage', strength: 5 },
		],
		vassalOf: null,
		stability: 4,
		prestige: 6,
		color: '#73D216',
	},
	{
		id: 'nat_mississippian',
		name: 'Culture mississippienne (Cahokia)',
		dempinym: 'Mississippien',
		governance: 'chiefdom',
		capital: 'set_cahokia',
		territory: poly([
			[42, -92],
			[42, -86],
			[35, -86],
			[35, -92],
		]),
		tileIds: [],
		ruler: {
			name: 'Grand Chef de Cahokia',
			dynastyName: 'Cahokia',
			birthYear: 960,
			age: 40,
			traits: ['builder', 'pious'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 5,
		color: '#C17D11',
	},
	{
		id: 'nat_wari',
		name: 'Successeurs Wari / Pré-Inca',
		dempinym: 'Andin',
		governance: 'tribal_confederation',
		capital: 'set_huari',
		territory: poly([
			[-8, -78],
			[-8, -70],
			[-17, -67],
			[-17, -76],
		]),
		tileIds: [],
		ruler: {
			name: 'Seigneur régional',
			dynastyName: 'Andes',
			birthYear: 960,
			age: 40,
			traits: ['builder', 'warrior'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 4, // période d'états régionaux fragmentés
		prestige: 4,
		color: '#F57900',
	},

	// ========================================================================
	// ASIE CENTRALE (nomades et Tibet)
	// ========================================================================
	{
		id: 'nat_tibet',
		name: 'Tibet (période de fragmentation)',
		dempinym: 'Tibétain',
		governance: 'tribal_confederation',
		capital: 'set_lhasa',
		territory: poly([
			[37, 78],
			[37, 100],
			[28, 100],
			[28, 78],
		]),
		tileIds: [],
		ruler: {
			name: 'Seigneurs locaux',
			dynastyName: 'Divers',
			birthYear: 955,
			age: 45,
			traits: ['pious', 'independent'],
		},
		diplomacy: [{ targetNationId: 'nat_song', type: 'neutral', strength: 3 }],
		vassalOf: null,
		stability: 3, // fragmentation post-empire
		prestige: 4,
		color: '#AD7FA8',
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================

	// --- Amérique du Nord ---
	{
		id: 'nat_puebloans',
		name: 'Puebloans ancestraux (Chaco)',
		dempinym: 'Puebloan',
		governance: 'tribal_confederation',
		capital: 'set_chaco_canyon',
		territory: poly([
			[38, -112],
			[38, -106],
			[34, -106],
			[34, -112],
		]),
		tileIds: [],
		ruler: {
			name: 'Conseil cérémoniel',
			dynastyName: 'Chaco',
			birthYear: 950,
			age: 50,
			traits: ['builder', 'pious'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7, // apogée de Chaco Canyon vers l'an 1000
		prestige: 5,
		color: '#D2691E',
	},
	{
		id: 'nat_haida',
		name: 'Confédération Haida-Tlingit',
		dempinym: 'Haida',
		governance: 'tribal_confederation',
		capital: 'set_haida_gwaii',
		territory: poly([
			[60, -140],
			[60, -130],
			[52, -130],
			[52, -140],
		]),
		tileIds: [],
		ruler: {
			name: 'Chef de clan',
			dynastyName: 'Aigle-Corbeau',
			birthYear: 955,
			age: 45,
			traits: ['navigator', 'artisan'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 5,
		color: '#1B5E20',
	},
	{
		id: 'nat_thule',
		name: 'Thulé (proto-Inuit)',
		dempinym: 'Thuléen',
		governance: 'tribal_confederation',
		capital: 'set_thule_camp',
		territory: poly([
			[76, -100],
			[76, -60],
			[65, -60],
			[65, -100],
		]),
		tileIds: [],
		ruler: {
			name: 'Chef de camp',
			dynastyName: 'Thulé',
			birthYear: 960,
			age: 40,
			traits: ['navigator', 'survivalist'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 6,
		prestige: 3,
		color: '#81D4FA',
	},

	// --- Pacifique ---
	{
		id: 'nat_tui_tonga',
		name: "Tu'i Tonga (Empire tongien)",
		dempinym: 'Tongien',
		governance: 'theocratic_monarchy',
		capital: 'set_tongatapu',
		territory: poly([
			[-13, -178],
			[-13, -170],
			[-23, -170],
			[-23, -178],
		]),
		tileIds: [],
		ruler: {
			name: "Tu'i Tonga",
			dynastyName: "Tu'i Tonga",
			birthYear: 955,
			age: 45,
			traits: ['navigator', 'charismatic'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 8, // empire maritime à son apogée
		prestige: 7,
		color: '#FF6F00',
	},
	{
		id: 'nat_aboriginal',
		name: 'Nations aborigènes australiennes',
		dempinym: 'Aborigène',
		governance: 'tribal_confederation',
		capital: 'set_uluru',
		territory: poly([
			[-10, 115],
			[-10, 153],
			[-39, 153],
			[-39, 115],
		]),
		tileIds: [],
		ruler: {
			name: 'Conseil des Anciens',
			dynastyName: 'Terres du Rêve',
			birthYear: 940,
			age: 60,
			traits: ['wise', 'pious'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 8, // société stable depuis des millénaires
		prestige: 3,
		color: '#BF360C',
	},

	// --- Europe du Nord ---
	{
		id: 'nat_sami',
		name: 'Sami (Laponie)',
		dempinym: 'Sami',
		governance: 'tribal_confederation',
		capital: 'set_sapmi',
		territory: poly([
			[70, 15],
			[70, 30],
			[65, 30],
			[65, 15],
		]),
		tileIds: [],
		ruler: {
			name: 'Noaidi (chamane)',
			dynastyName: 'Siida',
			birthYear: 958,
			age: 42,
			traits: ['pious', 'survivalist'],
		},
		diplomacy: [{ targetNationId: 'nat_norway', type: 'neutral', strength: 3 }],
		vassalOf: null,
		stability: 6,
		prestige: 2,
		color: '#1A237E',
	},

	// --- Amérique du Sud ---
	{
		id: 'nat_mapuche',
		name: 'Mapuche (Reche)',
		dempinym: 'Mapuche',
		governance: 'tribal_confederation',
		capital: 'set_mapuche_rewe',
		territory: poly([
			[-33, -73],
			[-33, -69],
			[-43, -69],
			[-43, -73],
		]),
		tileIds: [],
		ruler: {
			name: 'Toki (chef de guerre)',
			dynastyName: 'Reche',
			birthYear: 960,
			age: 40,
			traits: ['warrior', 'independent'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 4,
		color: '#4A148C',
	},

	// --- Madagascar ---
	{
		id: 'nat_malagasy',
		name: 'Royaumes malgaches proto-historiques',
		dempinym: 'Malgache',
		governance: 'tribal_confederation',
		capital: 'set_mahilaka',
		territory: poly([
			[-12, 43],
			[-12, 51],
			[-26, 51],
			[-26, 43],
		]),
		tileIds: [],
		ruler: {
			name: 'Mpanjaka (roi local)',
			dynastyName: 'Vazimba',
			birthYear: 955,
			age: 45,
			traits: ['trader', 'navigator'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 5, // période de migrations et regroupements
		prestige: 4,
		color: '#00695C',
	},

	// --- Afrique de l'Ouest et du Sud ---
	{
		id: 'nat_yoruba',
		name: 'Ifè (Yoruba)',
		dempinym: 'Yoruba',
		governance: 'city_state',
		capital: 'set_ife',
		territory: poly([
			[10, 2],
			[10, 6],
			[6, 6],
			[6, 2],
		]),
		tileIds: [],
		ruler: {
			name: 'Ooni',
			dynastyName: 'Oduduwa',
			birthYear: 950,
			age: 50,
			traits: ['pious', 'artisan'],
		},
		diplomacy: [{ targetNationId: 'nat_ghana', type: 'trade', strength: 4 }],
		vassalOf: null,
		stability: 7,
		prestige: 7, // Ifè est un centre religieux et artistique majeur
		color: '#FDD835',
	},
	{
		id: 'nat_zimbabwe',
		name: 'Grand Zimbabwe (proto-Shona)',
		dempinym: 'Zimbabwéen',
		governance: 'kingdom',
		capital: 'set_great_zimbabwe',
		territory: poly([
			[-15, 25],
			[-15, 33],
			[-23, 33],
			[-23, 25],
		]),
		tileIds: [],
		ruler: {
			name: 'Mambo (roi)',
			dynastyName: 'Shona',
			birthYear: 958,
			age: 42,
			traits: ['builder', 'trader'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 6, // début de la période de construction
		prestige: 5,
		color: '#795548',
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 2
	// ========================================================================

	// --- Amérique du Sud ---
	{
		id: 'nat_chimu',
		name: 'Royaume Chimú (Chan Chan)',
		dempinym: 'Chimú',
		governance: 'kingdom',
		capital: 'set_chan_chan',
		territory: poly([
			[-5, -81],
			[-5, -77],
			[-10, -77],
			[-10, -81],
		]),
		tileIds: [],
		ruler: {
			name: 'Tacaynamo',
			dynastyName: 'Chimú',
			birthYear: 955,
			age: 45,
			traits: ['builder', 'administrator'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 7, // grande cité d'adobe
		color: '#D4A017',
	},
	{
		id: 'nat_muisca',
		name: 'Confédération Muisca',
		dempinym: 'Muisca',
		governance: 'tribal_confederation',
		capital: 'set_bacata',
		territory: poly([
			[8, -75],
			[8, -72],
			[4, -72],
			[4, -75],
		]),
		tileIds: [],
		ruler: {
			name: 'Zipa',
			dynastyName: 'Muisca',
			birthYear: 960,
			age: 40,
			traits: ['pious', 'wealthy'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 6, // orfèvrerie et cérémonie El Dorado
		color: '#FFD700',
	},
	{
		id: 'nat_guarani',
		name: 'Guaraní',
		dempinym: 'Guaraní',
		governance: 'tribal_confederation',
		capital: 'set_guarani_tekoha',
		territory: poly([
			[-18, -60],
			[-18, -48],
			[-28, -48],
			[-28, -60],
		]),
		tileIds: [],
		ruler: {
			name: 'Tuvicha (chef)',
			dynastyName: 'Guaraní',
			birthYear: 955,
			age: 45,
			traits: ['warrior', 'spiritual'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 6,
		prestige: 3,
		color: '#2E7D32',
	},

	// --- Océanie ---
	{
		id: 'nat_hawaii',
		name: "Ali'i d'Hawaï",
		dempinym: 'Hawaïen',
		governance: 'chiefdom',
		capital: 'set_waipio',
		territory: poly([
			[22, -161],
			[22, -154],
			[18, -154],
			[18, -161],
		]),
		tileIds: [],
		ruler: {
			name: "Ali'i Nui",
			dynastyName: 'Pili',
			birthYear: 960,
			age: 40,
			traits: ['navigator', 'warrior'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 5,
		color: '#E65100',
	},

	// --- Asie ---
	{
		id: 'nat_ainu',
		name: 'Aïnous (Hokkaido)',
		dempinym: 'Aïnou',
		governance: 'tribal_confederation',
		capital: 'set_ainu_kotan',
		territory: poly([
			[46, 140],
			[46, 146],
			[41, 146],
			[41, 140],
		]),
		tileIds: [],
		ruler: {
			name: 'Kotan-kor-kur (chef de village)',
			dynastyName: 'Aïnou',
			birthYear: 955,
			age: 45,
			traits: ['hunter', 'spiritual'],
		},
		diplomacy: [{ targetNationId: 'nat_japan', type: 'rivalry', strength: 5 }],
		vassalOf: null,
		stability: 7,
		prestige: 3,
		color: '#5D4037',
	},

	// --- Afrique ---
	{
		id: 'nat_makuria',
		name: 'Royaume de Makuria',
		dempinym: 'Nubien',
		governance: 'kingdom',
		capital: 'set_old_dongola',
		territory: poly([
			[22, 28],
			[22, 36],
			[16, 36],
			[16, 28],
		]),
		tileIds: [],
		ruler: {
			name: 'Georgios III',
			dynastyName: 'Makuria',
			birthYear: 945,
			age: 55,
			traits: ['pious', 'diplomat'],
		},
		diplomacy: [
			{ targetNationId: 'nat_fatimid', type: 'rivalry', strength: 6 },
		],
		vassalOf: null,
		stability: 7,
		prestige: 7, // apogée du royaume chrétien nubien
		color: '#6A1B9A',
	},
	{
		id: 'nat_tuareg',
		name: 'Confédération touarègue (Sanhadja)',
		dempinym: 'Touareg',
		governance: 'tribal_confederation',
		capital: 'set_tadmekka',
		territory: poly([
			[25, -5],
			[25, 12],
			[15, 12],
			[15, -5],
		]),
		tileIds: [],
		ruler: {
			name: 'Amenokal',
			dynastyName: 'Sanhadja',
			birthYear: 950,
			age: 50,
			traits: ['nomadic', 'trader', 'warrior'],
		},
		diplomacy: [{ targetNationId: 'nat_ghana', type: 'rivalry', strength: 7 }],
		vassalOf: null,
		stability: 6,
		prestige: 6, // maîtres des routes transsahariennes
		color: '#1565C0',
	},

	// --- Caucase ---
	{
		id: 'nat_georgia',
		name: 'Royaume de Géorgie',
		dempinym: 'Géorgien',
		governance: 'kingdom',
		capital: 'set_kutaisi',
		territory: poly([
			[43.5, 40],
			[43.5, 46],
			[41, 46],
			[41, 40],
		]),
		tileIds: [],
		ruler: {
			name: 'Bagrat III',
			dynastyName: 'Bagrationi',
			birthYear: 960,
			age: 40,
			traits: ['unifier', 'pious', 'diplomat'],
		},
		diplomacy: [
			{ targetNationId: 'nat_byzantine', type: 'alliance', strength: 6 },
			{ targetNationId: 'nat_armenia', type: 'alliance', strength: 7 },
		],
		vassalOf: null,
		stability: 7, // unification en cours
		prestige: 7,
		color: '#C62828',
	},
	{
		id: 'nat_armenia',
		name: "Royaume d'Arménie (Bagratides)",
		dempinym: 'Arménien',
		governance: 'kingdom',
		capital: 'set_ani',
		territory: poly([
			[41.5, 42],
			[41.5, 46],
			[39, 46],
			[39, 42],
		]),
		tileIds: [],
		ruler: {
			name: 'Gagik Ier',
			dynastyName: 'Bagratuni',
			birthYear: 950,
			age: 50,
			traits: ['builder', 'pious', 'diplomat'],
		},
		diplomacy: [
			{ targetNationId: 'nat_byzantine', type: 'neutral', strength: 5 },
			{ targetNationId: 'nat_georgia', type: 'alliance', strength: 7 },
		],
		vassalOf: null,
		stability: 6, // menace byzantine et seldjoukide imminente
		prestige: 8, // Ani = « ville aux mille et une églises »
		color: '#E91E63',
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 3
	// ========================================================================

	// --- Amérique du Nord ---
	{
		id: 'nat_hohokam',
		name: 'Hohokam',
		dempinym: 'Hohokam',
		governance: 'tribal_confederation',
		capital: 'set_snaketown',
		territory: poly([
			[34, -113],
			[34, -109],
			[31, -109],
			[31, -113],
		]),
		tileIds: [],
		ruler: {
			name: 'Conseil des anciens',
			dynastyName: 'Hohokam',
			birthYear: 950,
			age: 50,
			traits: ['builder', 'irrigator'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 4, // grands canaux d'irrigation
		color: '#BF360C',
	},
	{
		id: 'nat_dorset',
		name: 'Culture de Dorset (Tuniit)',
		dempinym: 'Dorset',
		governance: 'tribal',
		capital: 'set_dorset_camp',
		territory: poly([
			[72, -80],
			[72, -55],
			[60, -55],
			[60, -80],
		]),
		tileIds: [],
		ruler: {
			name: 'Ancien chasseur',
			dynastyName: 'Tuniit',
			birthYear: 945,
			age: 55,
			traits: ['hunter', 'ice_carver'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 5, // en déclin face aux Thulé
		prestige: 2,
		color: '#78909C',
	},
	{
		id: 'nat_beothuk',
		name: 'Béothuks (Terre-Neuve)',
		dempinym: 'Béothuk',
		governance: 'tribal',
		capital: 'set_beothuk_village',
		territory: poly([
			[51, -59],
			[51, -52],
			[46, -52],
			[46, -59],
		]),
		tileIds: [],
		ruler: {
			name: 'Chef de bande',
			dynastyName: 'Béothuk',
			birthYear: 960,
			age: 40,
			traits: ['hunter', 'independent'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 6,
		prestige: 2,
		color: '#FF0000', // « Red Indians » — ocre rouge
	},
	{
		id: 'nat_dene',
		name: 'Nations dénées (Athapascanes)',
		dempinym: 'Déné',
		governance: 'tribal_confederation',
		capital: 'set_dene_camp',
		territory: poly([
			[65, -140],
			[65, -110],
			[55, -110],
			[55, -140],
		]),
		tileIds: [],
		ruler: {
			name: 'Ancien',
			dynastyName: 'Déné',
			birthYear: 950,
			age: 50,
			traits: ['hunter', 'wise'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 2,
		color: '#004D40',
	},
	{
		id: 'nat_mikmaq',
		name: "Mi'kmaq",
		dempinym: "Mi'kmaq",
		governance: 'tribal_confederation',
		capital: 'set_mikmaq_village',
		territory: poly([
			[49, -67],
			[49, -59],
			[43, -59],
			[43, -67],
		]),
		tileIds: [],
		ruler: {
			name: 'Kji-saqmaw (grand chef)',
			dynastyName: "Mi'kmaq",
			birthYear: 955,
			age: 45,
			traits: ['diplomat', 'fisher'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 3,
		color: '#1B5E20',
	},

	// --- Océanie ---
	{
		id: 'nat_papuan',
		name: 'Peuples papous (hautes terres)',
		dempinym: 'Papou',
		governance: 'tribal',
		capital: 'set_papuan_highlands',
		territory: poly([
			[-2, 135],
			[-2, 155],
			[-10, 155],
			[-10, 135],
		]),
		tileIds: [],
		ruler: {
			name: 'Big Man',
			dynastyName: 'Papou',
			birthYear: 955,
			age: 45,
			traits: ['orator', 'generous'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 6,
		prestige: 2,
		color: '#33691E',
	},
	{
		id: 'nat_fiji',
		name: 'Chefferies fidjiennes',
		dempinym: 'Fidjien',
		governance: 'chiefdom',
		capital: 'set_fiji_village',
		territory: poly([
			[-16, 176],
			[-16, -179],
			[-21, -179],
			[-21, 176],
		]),
		tileIds: [],
		ruler: {
			name: 'Ratu (chef)',
			dynastyName: 'Fidjien',
			birthYear: 960,
			age: 40,
			traits: ['warrior', 'navigator'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 5, // rivalités inter-chefferies
		prestige: 3,
		color: '#00838F',
	},
	{
		id: 'nat_chamorro',
		name: 'Chamorros (îles Mariannes)',
		dempinym: 'Chamorro',
		governance: 'chiefdom',
		capital: 'set_hagatna',
		territory: poly([
			[15, 144],
			[15, 146],
			[13, 146],
			[13, 144],
		]),
		tileIds: [],
		ruler: {
			name: "Maga'låhi (chef)",
			dynastyName: 'Chamorro',
			birthYear: 958,
			age: 42,
			traits: ['navigator', 'builder'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 3, // latte stones
		color: '#0097A7',
	},

	// --- Atlantique ---
	{
		id: 'nat_guanche',
		name: 'Guanches (îles Canaries)',
		dempinym: 'Guanche',
		governance: 'chiefdom',
		capital: 'set_guimar',
		territory: poly([
			[29, -19],
			[29, -13],
			[27, -13],
			[27, -19],
		]),
		tileIds: [],
		ruler: {
			name: 'Mencey',
			dynastyName: 'Guanche',
			birthYear: 955,
			age: 45,
			traits: ['herder', 'isolationist'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 2,
		color: '#F9A825',
	},

	// --- Afrique ---
	{
		id: 'nat_san',
		name: 'San (Bushmen du Kalahari)',
		dempinym: 'San',
		governance: 'tribal',
		capital: 'set_tsodilo',
		territory: poly([
			[-18, 18],
			[-18, 28],
			[-26, 28],
			[-26, 18],
		]),
		tileIds: [],
		ruler: {
			name: 'Conseil des anciens',
			dynastyName: 'San',
			birthYear: 945,
			age: 55,
			traits: ['wise', 'tracker'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 2,
		color: '#A1887F',
	},
	{
		id: 'nat_mbuti',
		name: 'Mbuti (Pygmées de la forêt Ituri)',
		dempinym: 'Mbuti',
		governance: 'tribal',
		capital: 'set_ituri',
		territory: poly([
			[3, 26],
			[3, 30],
			[-1, 30],
			[-1, 26],
		]),
		tileIds: [],
		ruler: {
			name: 'Ancien du campement',
			dynastyName: 'Mbuti',
			birthYear: 950,
			age: 50,
			traits: ['hunter', 'forest_master'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 1,
		color: '#4E342E',
	},
	{
		id: 'nat_igbo',
		name: 'Royaume de Nri (Igbo)',
		dempinym: 'Igbo',
		governance: 'theocracy',
		capital: 'set_nri',
		territory: poly([
			[8, 5],
			[8, 8],
			[5, 8],
			[5, 5],
		]),
		tileIds: [],
		ruler: {
			name: 'Eze Nri',
			dynastyName: 'Nri',
			birthYear: 948,
			age: 52,
			traits: ['pious', 'ritual_master'],
		},
		diplomacy: [{ targetNationId: 'nat_yoruba', type: 'trade', strength: 5 }],
		vassalOf: null,
		stability: 8, // théocratie pacifique
		prestige: 5,
		color: '#388E3C',
	},

	// --- Sibérie ---
	{
		id: 'nat_chukchi',
		name: 'Tchouktches',
		dempinym: 'Tchouktche',
		governance: 'tribal_confederation',
		capital: 'set_chukchi_camp',
		territory: poly([
			[72, 165],
			[72, -170],
			[62, -170],
			[62, 165],
		]),
		tileIds: [],
		ruler: {
			name: 'Erme-chyn (ancien)',
			dynastyName: 'Tchouktche',
			birthYear: 948,
			age: 52,
			traits: ['hunter', 'resilient'],
		},
		diplomacy: [],
		vassalOf: null,
		stability: 7,
		prestige: 2,
		color: '#546E7A',
	},
]
