import type { NationEconomy } from '../../../shared/src/types/world'

// ============================================================================
// Économies par nation — An 1000
// ============================================================================
// gdpEstimate : unité abstraite, Song China = 100 (référence mondiale max)
// currencyValue : valeur relative (1 = référence, solidus byzantin)
// mainExports/mainImports : commodity IDs
// tradeRouteAccess : trade route IDs accessibles
// marketPrices : prix locaux vs baseValue des commodités
// ============================================================================

export const nationEconomies: NationEconomy[] = [
	// ========================================================================
	// EUROPE OCCIDENTALE
	// ========================================================================
	{
		nationId: 'nat_hre',
		currency: 'Denier impérial',
		currencyValue: 0.6,
		gdpEstimate: 35,
		taxRate: 0.12,
		tradeBalance: -2,
		mainExports: [
			'com_iron_ore',
			'com_timber',
			'com_silver',
			'com_wool',
			'com_furs',
		],
		mainImports: ['com_silk', 'com_spices', 'com_gold', 'com_wine'],
		tradeRouteAccess: ['tr_north_sea_baltic', 'tr_mediterranean'],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 10 },
			{ commodityId: 'com_iron_ore', price: 15 },
			{ commodityId: 'com_silk', price: 120 },
			{ commodityId: 'com_spices', price: 150 },
		],
	},
	{
		nationId: 'nat_france',
		currency: 'Denier tournois',
		currencyValue: 0.5,
		gdpEstimate: 28,
		taxRate: 0.1,
		tradeBalance: -1,
		mainExports: ['com_wine', 'com_wheat', 'com_wool', 'com_timber'],
		mainImports: ['com_silk', 'com_spices', 'com_iron_ore'],
		tradeRouteAccess: ['tr_north_sea_baltic', 'tr_mediterranean'],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 9 },
			{ commodityId: 'com_wine', price: 20 },
			{ commodityId: 'com_silk', price: 130 },
		],
	},
	{
		nationId: 'nat_england',
		currency: 'Penny',
		currencyValue: 0.5,
		gdpEstimate: 18,
		taxRate: 0.15,
		tradeBalance: 1,
		mainExports: ['com_wool', 'com_tin', 'com_fish', 'com_leather'],
		mainImports: ['com_wine', 'com_silk', 'com_spices', 'com_iron_ore'],
		tradeRouteAccess: ['tr_north_sea_baltic'],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 11 },
			{ commodityId: 'com_wool', price: 18 },
			{ commodityId: 'com_tin', price: 30 },
		],
	},
	{
		nationId: 'nat_scotland',
		currency: 'Penny écossais',
		currencyValue: 0.3,
		gdpEstimate: 5,
		taxRate: 0.08,
		tradeBalance: -1,
		mainExports: ['com_wool', 'com_fish', 'com_furs', 'com_cattle'],
		mainImports: ['com_wine', 'com_iron_ore', 'com_textiles'],
		tradeRouteAccess: ['tr_north_sea_baltic'],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 12 },
			{ commodityId: 'com_wool', price: 15 },
		],
	},
	{
		nationId: 'nat_papal',
		currency: 'Denier papal',
		currencyValue: 0.7,
		gdpEstimate: 12,
		taxRate: 0.2,
		tradeBalance: 5,
		mainExports: ['com_wine', 'com_olive_oil', 'com_textiles', 'com_books'],
		mainImports: ['com_timber', 'com_furs', 'com_iron_ore'],
		tradeRouteAccess: ['tr_mediterranean'],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 10 },
			{ commodityId: 'com_olive_oil', price: 22 },
		],
	},
	{
		nationId: 'nat_venice',
		currency: 'Denier vénitien',
		currencyValue: 0.9,
		gdpEstimate: 22,
		taxRate: 0.1,
		tradeBalance: 15,
		mainExports: ['com_glass', 'com_textiles', 'com_salt', 'com_spices'],
		mainImports: [
			'com_silk',
			'com_spices',
			'com_timber',
			'com_iron_ore',
			'com_cotton',
		],
		tradeRouteAccess: [
			'tr_mediterranean',
			'tr_silk_road',
			'tr_north_sea_baltic',
		],
		marketPrices: [
			{ commodityId: 'com_silk', price: 90 },
			{ commodityId: 'com_spices', price: 110 },
			{ commodityId: 'com_glass', price: 45 },
			{ commodityId: 'com_salt', price: 20 },
		],
	},

	// ========================================================================
	// IBÉRIE
	// ========================================================================
	{
		nationId: 'nat_leon',
		currency: 'Dinero',
		currencyValue: 0.4,
		gdpEstimate: 10,
		taxRate: 0.1,
		tradeBalance: -2,
		mainExports: ['com_wool', 'com_cattle', 'com_iron_ore', 'com_wine'],
		mainImports: ['com_silk', 'com_spices', 'com_weapons'],
		tradeRouteAccess: [],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 9 },
			{ commodityId: 'com_wool', price: 16 },
		],
	},
	{
		nationId: 'nat_navarre',
		currency: 'Dinero',
		currencyValue: 0.4,
		gdpEstimate: 4,
		taxRate: 0.1,
		tradeBalance: 0,
		mainExports: ['com_wool', 'com_cattle', 'com_wine'],
		mainImports: ['com_iron_ore', 'com_weapons', 'com_textiles'],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_wheat', price: 10 }],
	},
	{
		nationId: 'nat_cordoba',
		currency: 'Dinar omeyyade',
		currencyValue: 1.2,
		gdpEstimate: 55,
		taxRate: 0.12,
		tradeBalance: 10,
		mainExports: [
			'com_silk',
			'com_leather',
			'com_olive_oil',
			'com_dyes',
			'com_textiles',
			'com_books',
			'com_glass',
		],
		mainImports: [
			'com_gold',
			'com_slaves',
			'com_timber',
			'com_furs',
			'com_iron_ore',
		],
		tradeRouteAccess: ['tr_mediterranean', 'tr_trans_saharan'],
		marketPrices: [
			{ commodityId: 'com_silk', price: 60 },
			{ commodityId: 'com_olive_oil', price: 15 },
			{ commodityId: 'com_leather', price: 12 },
			{ commodityId: 'com_gold', price: 180 },
		],
	},

	// ========================================================================
	// SCANDINAVIE
	// ========================================================================
	{
		nationId: 'nat_denmark',
		currency: 'Mark danois',
		currencyValue: 0.5,
		gdpEstimate: 12,
		taxRate: 0.1,
		tradeBalance: 3,
		mainExports: [
			'com_fish',
			'com_furs',
			'com_amber',
			'com_cattle',
			'com_horses',
		],
		mainImports: ['com_wine', 'com_silk', 'com_weapons', 'com_silver'],
		tradeRouteAccess: ['tr_north_sea_baltic', 'tr_varangian_route'],
		marketPrices: [
			{ commodityId: 'com_fish', price: 6 },
			{ commodityId: 'com_furs', price: 35 },
			{ commodityId: 'com_amber', price: 55 },
		],
	},
	{
		nationId: 'nat_norway',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 6,
		taxRate: 0.08,
		tradeBalance: 1,
		mainExports: ['com_fish', 'com_furs', 'com_timber', 'com_dried_fish'],
		mainImports: ['com_wheat', 'com_wine', 'com_weapons', 'com_textiles'],
		tradeRouteAccess: ['tr_north_sea_baltic'],
		marketPrices: [
			{ commodityId: 'com_fish', price: 5 },
			{ commodityId: 'com_furs', price: 30 },
		],
	},
	{
		nationId: 'nat_sweden',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 5,
		taxRate: 0.07,
		tradeBalance: 1,
		mainExports: ['com_iron_ore', 'com_furs', 'com_timber', 'com_fish'],
		mainImports: ['com_wheat', 'com_wine', 'com_silk', 'com_silver'],
		tradeRouteAccess: ['tr_north_sea_baltic', 'tr_varangian_route'],
		marketPrices: [
			{ commodityId: 'com_iron_ore', price: 12 },
			{ commodityId: 'com_furs', price: 28 },
		],
	},

	// ========================================================================
	// EUROPE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_poland',
		currency: 'Denier polonais',
		currencyValue: 0.3,
		gdpEstimate: 10,
		taxRate: 0.1,
		tradeBalance: -1,
		mainExports: [
			'com_furs',
			'com_timber',
			'com_salt',
			'com_cattle',
			'com_honey',
		],
		mainImports: ['com_silk', 'com_spices', 'com_weapons', 'com_wine'],
		tradeRouteAccess: ['tr_north_sea_baltic', 'tr_varangian_route'],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 8 },
			{ commodityId: 'com_salt', price: 22 },
		],
	},
	{
		nationId: 'nat_hungary',
		currency: 'Denier hongrois',
		currencyValue: 0.4,
		gdpEstimate: 12,
		taxRate: 0.1,
		tradeBalance: 0,
		mainExports: [
			'com_horses',
			'com_cattle',
			'com_salt',
			'com_gold',
			'com_silver',
		],
		mainImports: ['com_silk', 'com_spices', 'com_textiles', 'com_weapons'],
		tradeRouteAccess: ['tr_north_sea_baltic'],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 8 },
			{ commodityId: 'com_horses', price: 40 },
			{ commodityId: 'com_salt', price: 18 },
		],
	},
	{
		nationId: 'nat_kievan_rus',
		currency: 'Grivna',
		currencyValue: 0.5,
		gdpEstimate: 18,
		taxRate: 0.1,
		tradeBalance: 4,
		mainExports: [
			'com_furs',
			'com_honey',
			'com_timber',
			'com_fish',
			'com_amber',
		],
		mainImports: [
			'com_silk',
			'com_spices',
			'com_wine',
			'com_weapons',
			'com_glass',
		],
		tradeRouteAccess: [
			'tr_varangian_route',
			'tr_volga_route',
			'tr_north_sea_baltic',
		],
		marketPrices: [
			{ commodityId: 'com_furs', price: 25 },
			{ commodityId: 'com_honey', price: 18 },
			{ commodityId: 'com_silk', price: 110 },
		],
	},
	{
		nationId: 'nat_volga_bulgaria',
		currency: 'Dirham (argent)',
		currencyValue: 0.6,
		gdpEstimate: 8,
		taxRate: 0.1,
		tradeBalance: 3,
		mainExports: ['com_furs', 'com_leather', 'com_honey', 'com_horses'],
		mainImports: ['com_silk', 'com_spices', 'com_textiles', 'com_weapons'],
		tradeRouteAccess: ['tr_volga_route', 'tr_silk_road'],
		marketPrices: [
			{ commodityId: 'com_furs', price: 22 },
			{ commodityId: 'com_leather', price: 14 },
		],
	},
	{
		nationId: 'nat_croatia',
		currency: 'Denier croate',
		currencyValue: 0.3,
		gdpEstimate: 5,
		taxRate: 0.1,
		tradeBalance: 0,
		mainExports: ['com_timber', 'com_fish', 'com_salt', 'com_cattle'],
		mainImports: ['com_silk', 'com_spices', 'com_textiles'],
		tradeRouteAccess: ['tr_mediterranean'],
		marketPrices: [{ commodityId: 'com_wheat', price: 9 }],
	},

	// ========================================================================
	// BYZANCE
	// ========================================================================
	{
		nationId: 'nat_byzantine',
		currency: 'Solidus (nomisma)',
		currencyValue: 1.0,
		gdpEstimate: 50,
		taxRate: 0.18,
		tradeBalance: 8,
		mainExports: [
			'com_silk',
			'com_textiles',
			'com_glass',
			'com_wine',
			'com_olive_oil',
			'com_jewelry',
		],
		mainImports: [
			'com_spices',
			'com_furs',
			'com_timber',
			'com_iron_ore',
			'com_gold',
		],
		tradeRouteAccess: [
			'tr_mediterranean',
			'tr_silk_road',
			'tr_varangian_route',
			'tr_indian_ocean',
		],
		marketPrices: [
			{ commodityId: 'com_silk', price: 70 },
			{ commodityId: 'com_spices', price: 100 },
			{ commodityId: 'com_wheat', price: 10 },
			{ commodityId: 'com_olive_oil', price: 18 },
		],
	},

	// ========================================================================
	// MONDE ISLAMIQUE
	// ========================================================================
	{
		nationId: 'nat_fatimid',
		currency: 'Dinar fatimide',
		currencyValue: 1.3,
		gdpEstimate: 60,
		taxRate: 0.15,
		tradeBalance: 12,
		mainExports: [
			'com_cotton',
			'com_textiles',
			'com_paper',
			'com_glass',
			'com_spices',
			'com_gold',
		],
		mainImports: ['com_timber', 'com_iron_ore', 'com_furs', 'com_horses'],
		tradeRouteAccess: [
			'tr_mediterranean',
			'tr_indian_ocean',
			'tr_incense_route',
			'tr_trans_saharan',
		],
		marketPrices: [
			{ commodityId: 'com_wheat', price: 8 },
			{ commodityId: 'com_cotton', price: 20 },
			{ commodityId: 'com_spices', price: 80 },
			{ commodityId: 'com_gold', price: 160 },
		],
	},
	{
		nationId: 'nat_buyid',
		currency: 'Dinar buyide',
		currencyValue: 1.0,
		gdpEstimate: 40,
		taxRate: 0.15,
		tradeBalance: 5,
		mainExports: [
			'com_silk',
			'com_textiles',
			'com_spices',
			'com_paper',
			'com_books',
		],
		mainImports: ['com_gold', 'com_timber', 'com_horses', 'com_furs'],
		tradeRouteAccess: ['tr_silk_road', 'tr_indian_ocean', 'tr_incense_route'],
		marketPrices: [
			{ commodityId: 'com_silk', price: 65 },
			{ commodityId: 'com_spices', price: 75 },
			{ commodityId: 'com_wheat', price: 9 },
		],
	},
	{
		nationId: 'nat_ghaznavid',
		currency: 'Dinar ghaznavide',
		currencyValue: 0.9,
		gdpEstimate: 30,
		taxRate: 0.18,
		tradeBalance: 4,
		mainExports: [
			'com_gems',
			'com_horses',
			'com_cotton',
			'com_leather',
			'com_weapons',
		],
		mainImports: ['com_silk', 'com_spices', 'com_gold', 'com_textiles'],
		tradeRouteAccess: ['tr_silk_road', 'tr_indian_ocean'],
		marketPrices: [
			{ commodityId: 'com_gems', price: 140 },
			{ commodityId: 'com_horses', price: 50 },
			{ commodityId: 'com_wheat', price: 8 },
		],
	},
	{
		nationId: 'nat_karakhanid',
		currency: 'Dirham karakhanide',
		currencyValue: 0.6,
		gdpEstimate: 18,
		taxRate: 0.12,
		tradeBalance: 3,
		mainExports: ['com_horses', 'com_furs', 'com_leather', 'com_camels'],
		mainImports: ['com_silk', 'com_spices', 'com_textiles', 'com_weapons'],
		tradeRouteAccess: ['tr_silk_road'],
		marketPrices: [
			{ commodityId: 'com_horses', price: 35 },
			{ commodityId: 'com_furs', price: 28 },
		],
	},

	// ========================================================================
	// ASIE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_song',
		currency: 'Jiaozi (papier-monnaie) / Cash en cuivre',
		currencyValue: 1.5,
		gdpEstimate: 100,
		taxRate: 0.15,
		tradeBalance: 20,
		mainExports: [
			'com_silk',
			'com_porcelain',
			'com_tea',
			'com_paper',
			'com_textiles',
			'com_iron_ore',
		],
		mainImports: [
			'com_horses',
			'com_incense',
			'com_gems',
			'com_ivory',
			'com_spices',
		],
		tradeRouteAccess: [
			'tr_silk_road',
			'tr_maritime_silk_road',
			'tr_grand_canal_china',
		],
		marketPrices: [
			{ commodityId: 'com_rice', price: 6 },
			{ commodityId: 'com_silk', price: 40 },
			{ commodityId: 'com_porcelain', price: 35 },
			{ commodityId: 'com_tea', price: 15 },
			{ commodityId: 'com_horses', price: 80 },
		],
	},
	{
		nationId: 'nat_liao',
		currency: 'Cash en cuivre (Song)',
		currencyValue: 0.7,
		gdpEstimate: 25,
		taxRate: 0.12,
		tradeBalance: -3,
		mainExports: ['com_horses', 'com_furs', 'com_leather', 'com_cattle'],
		mainImports: [
			'com_silk',
			'com_tea',
			'com_porcelain',
			'com_rice',
			'com_iron_ore',
		],
		tradeRouteAccess: ['tr_silk_road'],
		marketPrices: [
			{ commodityId: 'com_horses', price: 30 },
			{ commodityId: 'com_furs', price: 20 },
			{ commodityId: 'com_silk', price: 55 },
		],
	},
	{
		nationId: 'nat_goryeo',
		currency: 'Mun (cash en cuivre)',
		currencyValue: 0.5,
		gdpEstimate: 15,
		taxRate: 0.12,
		tradeBalance: 0,
		mainExports: ['com_porcelain', 'com_silk', 'com_paper', 'com_fish'],
		mainImports: ['com_spices', 'com_books', 'com_tea', 'com_incense'],
		tradeRouteAccess: ['tr_maritime_silk_road'],
		marketPrices: [
			{ commodityId: 'com_rice', price: 7 },
			{ commodityId: 'com_porcelain', price: 38 },
		],
	},
	{
		nationId: 'nat_japan',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 18,
		taxRate: 0.15,
		tradeBalance: -1,
		mainExports: [
			'com_gold',
			'com_silver',
			'com_timber',
			'com_fish',
			'com_pearls',
		],
		mainImports: [
			'com_silk',
			'com_porcelain',
			'com_books',
			'com_tea',
			'com_incense',
		],
		tradeRouteAccess: ['tr_maritime_silk_road'],
		marketPrices: [
			{ commodityId: 'com_rice', price: 8 },
			{ commodityId: 'com_gold', price: 170 },
			{ commodityId: 'com_silk', price: 65 },
		],
	},

	// ========================================================================
	// ASIE DU SUD-EST
	// ========================================================================
	{
		nationId: 'nat_dai_viet',
		currency: 'Dong (cash en cuivre)',
		currencyValue: 0.4,
		gdpEstimate: 10,
		taxRate: 0.12,
		tradeBalance: 1,
		mainExports: ['com_rice', 'com_timber', 'com_fish', 'com_cotton'],
		mainImports: ['com_silk', 'com_porcelain', 'com_weapons', 'com_iron_ore'],
		tradeRouteAccess: ['tr_maritime_silk_road'],
		marketPrices: [{ commodityId: 'com_rice', price: 5 }],
	},
	{
		nationId: 'nat_khmer',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 22,
		taxRate: 0.15,
		tradeBalance: 2,
		mainExports: [
			'com_rice',
			'com_spices',
			'com_timber',
			'com_gems',
			'com_ivory',
		],
		mainImports: ['com_silk', 'com_porcelain', 'com_iron_ore', 'com_textiles'],
		tradeRouteAccess: ['tr_maritime_silk_road'],
		marketPrices: [
			{ commodityId: 'com_rice', price: 4 },
			{ commodityId: 'com_gems', price: 120 },
		],
	},
	{
		nationId: 'nat_srivijaya',
		currency: 'Piloncitos (or)',
		currencyValue: 0.8,
		gdpEstimate: 25,
		taxRate: 0.1,
		tradeBalance: 10,
		mainExports: [
			'com_spices',
			'com_timber',
			'com_incense',
			'com_ivory',
			'com_pearls',
		],
		mainImports: [
			'com_silk',
			'com_porcelain',
			'com_iron_ore',
			'com_textiles',
			'com_rice',
		],
		tradeRouteAccess: ['tr_maritime_silk_road', 'tr_indian_ocean'],
		marketPrices: [
			{ commodityId: 'com_spices', price: 50 },
			{ commodityId: 'com_incense', price: 65 },
		],
	},

	// ========================================================================
	// ASIE DU SUD
	// ========================================================================
	{
		nationId: 'nat_chola',
		currency: 'Kahapana (or)',
		currencyValue: 1.1,
		gdpEstimate: 45,
		taxRate: 0.15,
		tradeBalance: 8,
		mainExports: [
			'com_spices',
			'com_cotton',
			'com_gems',
			'com_textiles',
			'com_rice',
			'com_ivory',
		],
		mainImports: ['com_silk', 'com_horses', 'com_gold', 'com_porcelain'],
		tradeRouteAccess: ['tr_indian_ocean', 'tr_maritime_silk_road'],
		marketPrices: [
			{ commodityId: 'com_rice', price: 5 },
			{ commodityId: 'com_spices', price: 40 },
			{ commodityId: 'com_gems', price: 100 },
			{ commodityId: 'com_cotton', price: 15 },
		],
	},
	{
		nationId: 'nat_chalukya',
		currency: 'Gadyanaka (or)',
		currencyValue: 0.8,
		gdpEstimate: 28,
		taxRate: 0.12,
		tradeBalance: 2,
		mainExports: ['com_cotton', 'com_spices', 'com_iron_ore', 'com_gems'],
		mainImports: ['com_silk', 'com_horses', 'com_gold'],
		tradeRouteAccess: ['tr_indian_ocean'],
		marketPrices: [
			{ commodityId: 'com_rice', price: 5 },
			{ commodityId: 'com_cotton', price: 14 },
		],
	},
	{
		nationId: 'nat_pala',
		currency: 'Pana (argent)',
		currencyValue: 0.6,
		gdpEstimate: 22,
		taxRate: 0.12,
		tradeBalance: 1,
		mainExports: ['com_rice', 'com_cotton', 'com_textiles', 'com_ivory'],
		mainImports: ['com_silk', 'com_horses', 'com_gold', 'com_spices'],
		tradeRouteAccess: ['tr_indian_ocean'],
		marketPrices: [
			{ commodityId: 'com_rice', price: 4 },
			{ commodityId: 'com_cotton', price: 13 },
		],
	},

	// ========================================================================
	// AFRIQUE
	// ========================================================================
	{
		nationId: 'nat_ghana',
		currency: "Poudre d'or / Sel-barre",
		currencyValue: 1.0,
		gdpEstimate: 30,
		taxRate: 0.2,
		tradeBalance: 8,
		mainExports: ['com_gold', 'com_salt', 'com_ivory', 'com_leather'],
		mainImports: [
			'com_textiles',
			'com_horses',
			'com_weapons',
			'com_books',
			'com_dates',
		],
		tradeRouteAccess: ['tr_trans_saharan'],
		marketPrices: [
			{ commodityId: 'com_gold', price: 120 },
			{ commodityId: 'com_salt', price: 35 },
			{ commodityId: 'com_ivory', price: 70 },
		],
	},
	{
		nationId: 'nat_kanem',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 10,
		taxRate: 0.12,
		tradeBalance: 1,
		mainExports: ['com_salt', 'com_leather', 'com_cattle', 'com_horses'],
		mainImports: ['com_textiles', 'com_weapons', 'com_books', 'com_dates'],
		tradeRouteAccess: ['tr_trans_saharan'],
		marketPrices: [
			{ commodityId: 'com_salt', price: 30 },
			{ commodityId: 'com_cattle', price: 25 },
		],
	},
	{
		nationId: 'nat_ethiopia',
		currency: 'Amolé (barre de sel)',
		currencyValue: 0.4,
		gdpEstimate: 12,
		taxRate: 0.12,
		tradeBalance: 1,
		mainExports: ['com_gold', 'com_ivory', 'com_incense', 'com_coffee'],
		mainImports: ['com_textiles', 'com_weapons', 'com_salt', 'com_horses'],
		tradeRouteAccess: ['tr_east_african_coast', 'tr_incense_route'],
		marketPrices: [
			{ commodityId: 'com_gold', price: 140 },
			{ commodityId: 'com_incense', price: 55 },
		],
	},
	{
		nationId: 'nat_swahili_cities',
		currency: 'Dinar (importé)',
		currencyValue: 0.7,
		gdpEstimate: 15,
		taxRate: 0.1,
		tradeBalance: 5,
		mainExports: ['com_gold', 'com_ivory', 'com_iron_ore', 'com_timber'],
		mainImports: [
			'com_silk',
			'com_porcelain',
			'com_textiles',
			'com_spices',
			'com_glass',
		],
		tradeRouteAccess: ['tr_east_african_coast', 'tr_indian_ocean'],
		marketPrices: [
			{ commodityId: 'com_gold', price: 130 },
			{ commodityId: 'com_ivory', price: 65 },
		],
	},

	// ========================================================================
	// AMÉRIQUES
	// ========================================================================
	{
		nationId: 'nat_toltec',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 12,
		taxRate: 0.15,
		tradeBalance: 2,
		mainExports: ['com_cotton', 'com_dyes', 'com_pottery_goods', 'com_gems'],
		mainImports: ['com_gold', 'com_gems', 'com_furs'],
		tradeRouteAccess: [],
		marketPrices: [
			{ commodityId: 'com_maize', price: 5 },
			{ commodityId: 'com_cotton', price: 12 },
		],
	},
	{
		nationId: 'nat_maya_states',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 10,
		taxRate: 0.12,
		tradeBalance: 0,
		mainExports: ['com_cotton', 'com_dyes', 'com_honey', 'com_salt'],
		mainImports: ['com_gold', 'com_gems', 'com_obsidian'],
		tradeRouteAccess: [],
		marketPrices: [
			{ commodityId: 'com_maize', price: 5 },
			{ commodityId: 'com_honey', price: 15 },
		],
	},
	{
		nationId: 'nat_mississippian',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 5,
		taxRate: 0.05,
		tradeBalance: 0,
		mainExports: ['com_copper_ore', 'com_furs', 'com_pottery_goods'],
		mainImports: ['com_salt', 'com_gems'],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_maize', price: 4 }],
	},
	{
		nationId: 'nat_wari',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 10,
		taxRate: 0.15,
		tradeBalance: 1,
		mainExports: ['com_cotton', 'com_pottery_goods', 'com_gold', 'com_silver'],
		mainImports: ['com_timber', 'com_fish'],
		tradeRouteAccess: [],
		marketPrices: [
			{ commodityId: 'com_maize', price: 5 },
			{ commodityId: 'com_gold', price: 150 },
		],
	},

	// ========================================================================
	// ASIE CENTRALE
	// ========================================================================
	{
		nationId: 'nat_tibet',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 8,
		taxRate: 0.1,
		tradeBalance: -1,
		mainExports: ['com_salt', 'com_horses', 'com_wool', 'com_furs'],
		mainImports: ['com_tea', 'com_silk', 'com_rice', 'com_textiles'],
		tradeRouteAccess: ['tr_silk_road'],
		marketPrices: [
			{ commodityId: 'com_salt', price: 20 },
			{ commodityId: 'com_horses', price: 45 },
			{ commodityId: 'com_tea', price: 30 },
		],
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================
	{
		nationId: 'nat_puebloans',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 3,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_pottery_goods', 'com_cotton', 'com_maize'],
		mainImports: ['com_copper_ore', 'com_furs'],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_maize', price: 3 }],
	},
	{
		nationId: 'nat_haida',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 3,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_fish', 'com_timber'],
		mainImports: ['com_copper_ore', 'com_obsidian'],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_furs', price: 15 }],
	},
	{
		nationId: 'nat_thule',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 1,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_fish'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_furs', price: 20 }],
	},
	{
		nationId: 'nat_tui_tonga',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 4,
		taxRate: 0.1,
		tradeBalance: 1,
		mainExports: ['com_fish', 'com_spices', 'com_cotton'],
		mainImports: ['com_copper_ore', 'com_pottery_goods'],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_fish', price: 5 }],
	},
	{
		nationId: 'nat_aboriginal',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 1,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: [],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_sami',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 2,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_fish'],
		mainImports: ['com_iron_goods', 'com_salt'],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_furs', price: 18 }],
	},
	{
		nationId: 'nat_mapuche',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 3,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_fish', 'com_wool'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_wool', price: 8 }],
	},
	{
		nationId: 'nat_malagasy',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 4,
		taxRate: 0.05,
		tradeBalance: 1,
		mainExports: ['com_spices', 'com_rice', 'com_iron_goods'],
		mainImports: ['com_textiles', 'com_pottery_goods'],
		tradeRouteAccess: ['tr_indian_ocean'],
		marketPrices: [{ commodityId: 'com_spices', price: 25 }],
	},
	{
		nationId: 'nat_yoruba',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 8,
		taxRate: 0.1,
		tradeBalance: 1,
		mainExports: ['com_iron_goods', 'com_pottery_goods', 'com_cotton'],
		mainImports: ['com_salt', 'com_copper_ore', 'com_horses'],
		tradeRouteAccess: ['tr_trans_saharan'],
		marketPrices: [
			{ commodityId: 'com_iron_goods', price: 20 },
			{ commodityId: 'com_salt', price: 25 },
		],
	},
	{
		nationId: 'nat_zimbabwe',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 6,
		taxRate: 0.08,
		tradeBalance: 1,
		mainExports: ['com_gold', 'com_iron_goods', 'com_copper_ore'],
		mainImports: ['com_textiles', 'com_pottery_goods', 'com_glass'],
		tradeRouteAccess: ['tr_indian_ocean'],
		marketPrices: [
			{ commodityId: 'com_gold', price: 140 },
			{ commodityId: 'com_iron_goods', price: 18 },
		],
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 2
	// ========================================================================
	{
		nationId: 'nat_chimu',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 8,
		taxRate: 0.12,
		tradeBalance: 1,
		mainExports: ['com_gold', 'com_copper_ore', 'com_textiles', 'com_fish'],
		mainImports: ['com_tropical_wood'],
		tradeRouteAccess: [],
		marketPrices: [
			{ commodityId: 'com_gold', price: 130 },
			{ commodityId: 'com_fish', price: 5 },
		],
	},
	{
		nationId: 'nat_muisca',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 6,
		taxRate: 0.08,
		tradeBalance: 1,
		mainExports: ['com_gold', 'com_emeralds', 'com_salt'],
		mainImports: ['com_cotton', 'com_tropical_wood'],
		tradeRouteAccess: [],
		marketPrices: [
			{ commodityId: 'com_gold', price: 145 },
			{ commodityId: 'com_salt', price: 20 },
		],
	},
	{
		nationId: 'nat_guarani',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 3,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_tropical_wood', 'com_cotton'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_hawaii',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 4,
		taxRate: 0.1,
		tradeBalance: 0,
		mainExports: ['com_fish', 'com_tropical_wood'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [{ commodityId: 'com_fish', price: 4 }],
	},
	{
		nationId: 'nat_ainu',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 3,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_fish', 'com_dried_salmon'],
		mainImports: ['com_iron_goods', 'com_rice'],
		tradeRouteAccess: [],
		marketPrices: [
			{ commodityId: 'com_furs', price: 30 },
			{ commodityId: 'com_fish', price: 4 },
		],
	},
	{
		nationId: 'nat_makuria',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 6,
		taxRate: 0.1,
		tradeBalance: 0,
		mainExports: ['com_gold', 'com_ivory', 'com_slaves'],
		mainImports: ['com_textiles', 'com_pottery_goods', 'com_wine'],
		tradeRouteAccess: ['tr_nile'],
		marketPrices: [
			{ commodityId: 'com_gold', price: 135 },
			{ commodityId: 'com_ivory', price: 60 },
		],
	},
	{
		nationId: 'nat_tuareg',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 5,
		taxRate: 0.05,
		tradeBalance: 2,
		mainExports: ['com_salt', 'com_gold'],
		mainImports: ['com_textiles', 'com_grain'],
		tradeRouteAccess: ['tr_trans_saharan'],
		marketPrices: [
			{ commodityId: 'com_salt', price: 35 },
			{ commodityId: 'com_gold', price: 140 },
		],
	},
	{
		nationId: 'nat_georgia',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 6,
		taxRate: 0.1,
		tradeBalance: 1,
		mainExports: ['com_wine', 'com_iron_goods', 'com_textiles'],
		mainImports: ['com_spices', 'com_silk'],
		tradeRouteAccess: ['tr_silk_road'],
		marketPrices: [
			{ commodityId: 'com_wine', price: 15 },
			{ commodityId: 'com_iron_goods', price: 20 },
		],
	},
	{
		nationId: 'nat_armenia',
		currency: 'dram',
		currencyValue: 4,
		gdpEstimate: 8,
		taxRate: 0.12,
		tradeBalance: 2,
		mainExports: ['com_textiles', 'com_wine', 'com_iron_goods', 'com_dyes'],
		mainImports: ['com_spices', 'com_silk', 'com_horses'],
		tradeRouteAccess: ['tr_silk_road'],
		marketPrices: [
			{ commodityId: 'com_textiles', price: 22 },
			{ commodityId: 'com_wine', price: 14 },
		],
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 3
	// ========================================================================
	{
		nationId: 'nat_hohokam',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 3,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_cotton', 'com_pottery_goods'],
		mainImports: ['com_turquoise', 'com_shells'],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_dorset',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 1,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_ivory', 'com_furs'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_beothuk',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 1,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_fish'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_dene',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 2,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_copper_ore'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_mikmaq',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 2,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_fish'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_papuan',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 2,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_tropical_wood'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_fiji',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 2,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_tropical_wood', 'com_fish'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_chamorro',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 2,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_fish', 'com_shells'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_guanche',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 2,
		taxRate: 0.05,
		tradeBalance: 0,
		mainExports: ['com_grain', 'com_livestock'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_san',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 1,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: [],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_mbuti',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 1,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_ivory', 'com_honey'],
		mainImports: ['com_iron_goods'],
		tradeRouteAccess: [],
		marketPrices: [],
	},
	{
		nationId: 'nat_igbo',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 5,
		taxRate: 0.05,
		tradeBalance: 1,
		mainExports: ['com_iron_goods', 'com_pottery_goods', 'com_palm_oil'],
		mainImports: ['com_salt', 'com_copper_ore'],
		tradeRouteAccess: [],
		marketPrices: [
			{ commodityId: 'com_iron_goods', price: 18 },
			{ commodityId: 'com_palm_oil', price: 10 },
		],
	},
	{
		nationId: 'nat_chukchi',
		currency: null,
		currencyValue: 0,
		gdpEstimate: 1,
		taxRate: 0.0,
		tradeBalance: 0,
		mainExports: ['com_furs', 'com_ivory'],
		mainImports: [],
		tradeRouteAccess: [],
		marketPrices: [],
	},
]
