import type { NationLaw } from '../../../shared/src/types/world'

// ============================================================================
// Systèmes juridiques par nation — An 1000
// ============================================================================

export const nationLawsData: NationLaw[] = [
	// ========================================================================
	// EUROPE OCCIDENTALE
	// ========================================================================
	{
		nationId: 'nat_hre',
		legalSystem: 'feudal_law',
		propertyRights: 5,
		personalFreedom: 3,
		genderEquality: 2,
		slaveryStatus: 'restricted',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['banditry', 'theft', 'heresy', 'feudal_violence'],
		punishments: ['fine', 'mutilation', 'execution', 'exile', 'ordeal'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_france',
		legalSystem: 'feudal_law',
		propertyRights: 4,
		personalFreedom: 3,
		genderEquality: 2,
		slaveryStatus: 'restricted',
		judicialIndependence: 2,
		crimeRate: 5,
		commonCrimes: ['banditry', 'theft', 'feudal_violence', 'poaching'],
		punishments: ['fine', 'mutilation', 'execution', 'imprisonment'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_england',
		legalSystem: 'customary',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 2,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['theft', 'banditry', 'arson', 'cattle_raiding'],
		punishments: ['fine', 'outlawry', 'execution', 'mutilation', 'ordeal'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_scotland',
		legalSystem: 'customary',
		propertyRights: 3,
		personalFreedom: 4,
		genderEquality: 2,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 6,
		commonCrimes: ['cattle_raiding', 'blood_feud', 'banditry', 'theft'],
		punishments: ['fine', 'exile', 'execution', 'blood_price'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_papal',
		legalSystem: 'religious_canon',
		propertyRights: 6,
		personalFreedom: 4,
		genderEquality: 2,
		slaveryStatus: 'restricted',
		judicialIndependence: 4,
		crimeRate: 4,
		commonCrimes: ['heresy', 'theft', 'simony', 'assault'],
		punishments: [
			'excommunication',
			'fine',
			'imprisonment',
			'exile',
			'penance',
		],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_venice',
		legalSystem: 'imperial_code',
		propertyRights: 7,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 6,
		crimeRate: 3,
		commonCrimes: ['smuggling', 'fraud', 'piracy', 'theft'],
		punishments: [
			'fine',
			'imprisonment',
			'exile',
			'execution',
			'galley_service',
		],
		lawEnforcement: 7,
	},

	// ========================================================================
	// IBÉRIE
	// ========================================================================
	{
		nationId: 'nat_leon',
		legalSystem: 'feudal_law',
		propertyRights: 4,
		personalFreedom: 4,
		genderEquality: 2,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['banditry', 'cattle_raiding', 'border_raids', 'theft'],
		punishments: ['fine', 'exile', 'execution', 'imprisonment'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_navarre',
		legalSystem: 'customary',
		propertyRights: 4,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'restricted',
		judicialIndependence: 4,
		crimeRate: 4,
		commonCrimes: ['banditry', 'smuggling', 'theft'],
		punishments: ['fine', 'exile', 'imprisonment'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_cordoba',
		legalSystem: 'religious_sharia',
		propertyRights: 7,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 6,
		crimeRate: 3,
		commonCrimes: ['theft', 'smuggling', 'apostasy', 'fraud'],
		punishments: ['fine', 'flogging', 'imprisonment', 'execution', 'exile'],
		lawEnforcement: 7,
	},

	// ========================================================================
	// SCANDINAVIE
	// ========================================================================
	{
		nationId: 'nat_denmark',
		legalSystem: 'customary',
		propertyRights: 4,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 5,
		commonCrimes: ['blood_feud', 'theft', 'raiding', 'assault'],
		punishments: ['fine', 'outlawry', 'blood_price', 'execution'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_norway',
		legalSystem: 'customary',
		propertyRights: 4,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 5,
		commonCrimes: ['blood_feud', 'theft', 'piracy', 'raiding'],
		punishments: ['fine', 'outlawry', 'blood_price', 'execution'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_sweden',
		legalSystem: 'customary',
		propertyRights: 4,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['blood_feud', 'theft', 'raiding', 'cattle_raiding'],
		punishments: ['fine', 'outlawry', 'blood_price', 'execution'],
		lawEnforcement: 3,
	},

	// ========================================================================
	// EUROPE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_poland',
		legalSystem: 'customary',
		propertyRights: 4,
		personalFreedom: 4,
		genderEquality: 2,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['banditry', 'theft', 'cattle_raiding', 'arson'],
		punishments: ['fine', 'mutilation', 'execution', 'exile'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_hungary',
		legalSystem: 'mixed',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 2,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['banditry', 'theft', 'blood_feud', 'horse_theft'],
		punishments: ['fine', 'mutilation', 'execution', 'imprisonment'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_kievan_rus',
		legalSystem: 'customary',
		propertyRights: 4,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['banditry', 'theft', 'blood_feud', 'arson'],
		punishments: ['fine', 'blood_price', 'exile', 'execution'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_volga_bulgaria',
		legalSystem: 'religious_sharia',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 4,
		commonCrimes: ['theft', 'smuggling', 'banditry'],
		punishments: ['fine', 'flogging', 'imprisonment', 'execution'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_croatia',
		legalSystem: 'mixed',
		propertyRights: 4,
		personalFreedom: 4,
		genderEquality: 2,
		slaveryStatus: 'restricted',
		judicialIndependence: 3,
		crimeRate: 4,
		commonCrimes: ['piracy', 'banditry', 'theft', 'smuggling'],
		punishments: ['fine', 'imprisonment', 'exile', 'execution'],
		lawEnforcement: 4,
	},

	// ========================================================================
	// BYZANCE
	// ========================================================================
	{
		nationId: 'nat_byzantine',
		legalSystem: 'imperial_code',
		propertyRights: 7,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 5,
		crimeRate: 4,
		commonCrimes: ['theft', 'fraud', 'treason', 'smuggling', 'heresy'],
		punishments: [
			'fine',
			'mutilation',
			'blinding',
			'exile',
			'execution',
			'imprisonment',
		],
		lawEnforcement: 7,
	},

	// ========================================================================
	// MONDE ISLAMIQUE
	// ========================================================================
	{
		nationId: 'nat_fatimid',
		legalSystem: 'religious_sharia',
		propertyRights: 7,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 5,
		crimeRate: 3,
		commonCrimes: ['theft', 'fraud', 'smuggling', 'banditry'],
		punishments: [
			'fine',
			'flogging',
			'imprisonment',
			'execution',
			'amputation',
		],
		lawEnforcement: 7,
	},
	{
		nationId: 'nat_buyid',
		legalSystem: 'religious_sharia',
		propertyRights: 6,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 4,
		commonCrimes: ['banditry', 'theft', 'sectarian_violence', 'smuggling'],
		punishments: ['fine', 'flogging', 'imprisonment', 'execution'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_ghaznavid',
		legalSystem: 'religious_sharia',
		propertyRights: 5,
		personalFreedom: 3,
		genderEquality: 2,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['banditry', 'theft', 'smuggling', 'tribal_raiding'],
		punishments: [
			'flogging',
			'execution',
			'imprisonment',
			'fine',
			'enslavement',
		],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_karakhanid',
		legalSystem: 'mixed',
		propertyRights: 4,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['raiding', 'horse_theft', 'banditry', 'smuggling'],
		punishments: ['fine', 'flogging', 'execution', 'exile'],
		lawEnforcement: 4,
	},

	// ========================================================================
	// ASIE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_song',
		legalSystem: 'imperial_code',
		propertyRights: 7,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'restricted',
		judicialIndependence: 5,
		crimeRate: 3,
		commonCrimes: ['theft', 'fraud', 'smuggling', 'counterfeiting'],
		punishments: ['fine', 'flogging', 'exile', 'execution', 'forced_labor'],
		lawEnforcement: 7,
	},
	{
		nationId: 'nat_liao',
		legalSystem: 'mixed',
		propertyRights: 4,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['horse_theft', 'raiding', 'banditry', 'smuggling'],
		punishments: ['fine', 'flogging', 'execution', 'forced_labor'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_goryeo',
		legalSystem: 'imperial_code',
		propertyRights: 6,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 3,
		commonCrimes: ['theft', 'fraud', 'smuggling', 'banditry'],
		punishments: ['fine', 'flogging', 'exile', 'execution', 'forced_labor'],
		lawEnforcement: 6,
	},
	{
		nationId: 'nat_japan',
		legalSystem: 'imperial_code',
		propertyRights: 5,
		personalFreedom: 3,
		genderEquality: 4,
		slaveryStatus: 'restricted',
		judicialIndependence: 3,
		crimeRate: 3,
		commonCrimes: ['theft', 'arson', 'banditry', 'smuggling'],
		punishments: ['exile', 'flogging', 'execution', 'forced_labor', 'fine'],
		lawEnforcement: 5,
	},

	// ========================================================================
	// ASIE DU SUD-EST
	// ========================================================================
	{
		nationId: 'nat_dai_viet',
		legalSystem: 'imperial_code',
		propertyRights: 5,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 4,
		commonCrimes: ['theft', 'banditry', 'piracy', 'smuggling'],
		punishments: ['fine', 'flogging', 'exile', 'execution', 'forced_labor'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_khmer',
		legalSystem: 'religious_dharma',
		propertyRights: 5,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 3,
		commonCrimes: ['theft', 'banditry', 'smuggling'],
		punishments: ['fine', 'flogging', 'imprisonment', 'execution', 'ordeal'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_srivijaya',
		legalSystem: 'mixed',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 4,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 4,
		commonCrimes: ['piracy', 'smuggling', 'theft', 'mutiny'],
		punishments: ['fine', 'exile', 'execution', 'enslavement'],
		lawEnforcement: 4,
	},

	// ========================================================================
	// ASIE DU SUD
	// ========================================================================
	{
		nationId: 'nat_chola',
		legalSystem: 'religious_dharma',
		propertyRights: 6,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 5,
		crimeRate: 3,
		commonCrimes: ['theft', 'piracy', 'banditry', 'fraud'],
		punishments: ['fine', 'imprisonment', 'exile', 'execution', 'mutilation'],
		lawEnforcement: 6,
	},
	{
		nationId: 'nat_chalukya',
		legalSystem: 'religious_dharma',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 4,
		commonCrimes: ['banditry', 'theft', 'cattle_raiding', 'smuggling'],
		punishments: ['fine', 'imprisonment', 'exile', 'execution'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_pala',
		legalSystem: 'religious_dharma',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 4,
		commonCrimes: ['banditry', 'theft', 'river_piracy', 'smuggling'],
		punishments: ['fine', 'imprisonment', 'exile', 'execution'],
		lawEnforcement: 4,
	},

	// ========================================================================
	// AFRIQUE
	// ========================================================================
	{
		nationId: 'nat_ghana',
		legalSystem: 'customary',
		propertyRights: 4,
		personalFreedom: 4,
		genderEquality: 4,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 4,
		commonCrimes: ['theft', 'banditry', 'smuggling', 'cattle_raiding'],
		punishments: ['fine', 'enslavement', 'exile', 'execution'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_kanem',
		legalSystem: 'mixed',
		propertyRights: 3,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 5,
		commonCrimes: ['raiding', 'cattle_raiding', 'theft', 'banditry'],
		punishments: ['fine', 'enslavement', 'execution', 'exile'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_ethiopia',
		legalSystem: 'religious_canon',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 2,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 4,
		commonCrimes: ['banditry', 'theft', 'cattle_raiding', 'heresy'],
		punishments: ['fine', 'imprisonment', 'exile', 'execution', 'penance'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_swahili_cities',
		legalSystem: 'mixed',
		propertyRights: 6,
		personalFreedom: 5,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 5,
		crimeRate: 3,
		commonCrimes: ['piracy', 'smuggling', 'theft', 'fraud'],
		punishments: ['fine', 'imprisonment', 'exile', 'execution'],
		lawEnforcement: 5,
	},

	// ========================================================================
	// AMÉRIQUES
	// ========================================================================
	{
		nationId: 'nat_toltec',
		legalSystem: 'customary',
		propertyRights: 4,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 2,
		crimeRate: 4,
		commonCrimes: ['theft', 'drunkenness', 'desertion', 'sacrilege'],
		punishments: ['execution', 'enslavement', 'fine', 'exile'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_maya_states',
		legalSystem: 'customary',
		propertyRights: 5,
		personalFreedom: 3,
		genderEquality: 2,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 4,
		commonCrimes: ['theft', 'adultery', 'sacrilege', 'murder'],
		punishments: ['enslavement', 'execution', 'fine', 'exile'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_mississippian',
		legalSystem: 'tribal_law',
		propertyRights: 3,
		personalFreedom: 4,
		genderEquality: 4,
		slaveryStatus: 'restricted',
		judicialIndependence: 3,
		crimeRate: 4,
		commonCrimes: ['theft', 'witchcraft', 'taboo_violation'],
		punishments: ['exile', 'execution', 'ritual_punishment'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_wari',
		legalSystem: 'imperial_code',
		propertyRights: 4,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 2,
		crimeRate: 3,
		commonCrimes: ['theft', 'desertion', 'sacrilege', 'rebellion'],
		punishments: ['execution', 'forced_labor', 'exile'],
		lawEnforcement: 6,
	},

	// ========================================================================
	// ASIE CENTRALE
	// ========================================================================
	{
		nationId: 'nat_tibet',
		legalSystem: 'religious_dharma',
		propertyRights: 4,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 3,
		commonCrimes: ['banditry', 'theft', 'cattle_raiding'],
		punishments: ['fine', 'flogging', 'exile', 'mutilation'],
		lawEnforcement: 3,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================
	{
		nationId: 'nat_puebloans',
		legalSystem: 'customary_law',
		propertyRights: 5,
		personalFreedom: 7,
		genderEquality: 6, // société matrilinéaire
		slaveryStatus: 'none',
		judicialIndependence: 4,
		crimeRate: 2,
		commonCrimes: ['theft', 'taboo_violation'],
		punishments: ['exile', 'shaming', 'restitution'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_haida',
		legalSystem: 'customary_law',
		propertyRights: 5,
		personalFreedom: 5,
		genderEquality: 5,
		slaveryStatus: 'legal', // esclavage de guerre
		judicialIndependence: 3,
		crimeRate: 3,
		commonCrimes: ['theft', 'insult_to_chief', 'taboo_violation'],
		punishments: ['restitution', 'shaming', 'exile', 'execution'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_thule',
		legalSystem: 'customary_law',
		propertyRights: 3,
		personalFreedom: 8,
		genderEquality: 5,
		slaveryStatus: 'none',
		judicialIndependence: 2,
		crimeRate: 2,
		commonCrimes: ['theft', 'murder'],
		punishments: ['exile', 'blood_feud', 'restitution'],
		lawEnforcement: 1,
	},
	{
		nationId: 'nat_tui_tonga',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 4,
		genderEquality: 4,
		slaveryStatus: 'restricted',
		judicialIndependence: 2,
		crimeRate: 2,
		commonCrimes: ['theft', 'taboo_violation', 'disrespect_to_chief'],
		punishments: ['exile', 'execution', 'ritual_punishment'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_aboriginal',
		legalSystem: 'customary_law',
		propertyRights: 2, // pas de propriété particulière, territoire clanique
		personalFreedom: 7,
		genderEquality: 4,
		slaveryStatus: 'none',
		judicialIndependence: 3,
		crimeRate: 2,
		commonCrimes: ['taboo_violation', 'sorcery', 'theft'],
		punishments: ['spearing', 'exile', 'ritual_punishment'],
		lawEnforcement: 2,
	},
	{
		nationId: 'nat_sami',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 7,
		genderEquality: 5,
		slaveryStatus: 'none',
		judicialIndependence: 3,
		crimeRate: 2,
		commonCrimes: ['theft', 'reindeer_rustling'],
		punishments: ['fine', 'restitution', 'exile'],
		lawEnforcement: 2,
	},
	{
		nationId: 'nat_mapuche',
		legalSystem: 'customary_law',
		propertyRights: 5,
		personalFreedom: 7,
		genderEquality: 5,
		slaveryStatus: 'none',
		judicialIndependence: 3,
		crimeRate: 3,
		commonCrimes: ['theft', 'cattle_raiding', 'witchcraft'],
		punishments: ['restitution', 'exile', 'execution'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_malagasy',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 5,
		genderEquality: 4,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 3,
		commonCrimes: ['theft', 'taboo_violation', 'cattle_raiding'],
		punishments: ['fine', 'exile', 'ordeal_trial'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_yoruba',
		legalSystem: 'customary_law',
		propertyRights: 5,
		personalFreedom: 5,
		genderEquality: 4,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 3,
		commonCrimes: ['theft', 'sacrilege', 'murder'],
		punishments: ['fine', 'exile', 'execution', 'ordeal_trial'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_zimbabwe',
		legalSystem: 'customary_law',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 3,
		crimeRate: 3,
		commonCrimes: ['theft', 'cattle_raiding', 'witchcraft'],
		punishments: ['fine', 'exile', 'execution', 'forced_labor'],
		lawEnforcement: 4,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 2
	// ========================================================================
	{
		nationId: 'nat_chimu',
		legalSystem: 'royal_decree',
		propertyRights: 4,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 2,
		crimeRate: 3,
		commonCrimes: ['theft', 'disobedience', 'sacrilege'],
		punishments: ['execution', 'forced_labor', 'exile'],
		lawEnforcement: 6,
	},
	{
		nationId: 'nat_muisca',
		legalSystem: 'customary_law',
		propertyRights: 5,
		personalFreedom: 5,
		genderEquality: 4,
		slaveryStatus: 'limited',
		judicialIndependence: 3,
		crimeRate: 2,
		commonCrimes: ['theft', 'sacrilege', 'adultery'],
		punishments: ['fine', 'public_humiliation', 'exile'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_guarani',
		legalSystem: 'customary_law',
		propertyRights: 3,
		personalFreedom: 7,
		genderEquality: 5,
		slaveryStatus: 'limited',
		judicialIndependence: 3,
		crimeRate: 3,
		commonCrimes: ['theft', 'cowardice', 'witchcraft'],
		punishments: ['exile', 'restitution', 'physical_punishment'],
		lawEnforcement: 2,
	},
	{
		nationId: 'nat_hawaii',
		legalSystem: 'royal_decree',
		propertyRights: 3,
		personalFreedom: 3,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 2,
		crimeRate: 2,
		commonCrimes: ['kapu_violation', 'theft', 'disrespect'],
		punishments: ['execution', 'exile', 'sacrifice'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_ainu',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 7,
		genderEquality: 5,
		slaveryStatus: 'none',
		judicialIndependence: 4,
		crimeRate: 2,
		commonCrimes: ['theft', 'taboo_violation'],
		punishments: ['restitution', 'exile', 'social_ostracism'],
		lawEnforcement: 2,
	},
	{
		nationId: 'nat_makuria',
		legalSystem: 'canon_law',
		propertyRights: 5,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 3,
		commonCrimes: ['theft', 'heresy', 'murder'],
		punishments: ['fine', 'imprisonment', 'exile', 'execution'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_tuareg',
		legalSystem: 'customary_law',
		propertyRights: 5,
		personalFreedom: 5,
		genderEquality: 6,
		slaveryStatus: 'legal',
		judicialIndependence: 4,
		crimeRate: 3,
		commonCrimes: ['theft', 'caravan_raiding', 'blood_feud'],
		punishments: ['fine', 'blood_price', 'exile'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_georgia',
		legalSystem: 'royal_decree',
		propertyRights: 6,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'serfdom',
		judicialIndependence: 4,
		crimeRate: 3,
		commonCrimes: ['theft', 'treason', 'murder'],
		punishments: ['fine', 'imprisonment', 'execution', 'exile'],
		lawEnforcement: 5,
	},
	{
		nationId: 'nat_armenia',
		legalSystem: 'royal_decree',
		propertyRights: 6,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'serfdom',
		judicialIndependence: 5,
		crimeRate: 2,
		commonCrimes: ['theft', 'treason', 'heresy'],
		punishments: ['fine', 'imprisonment', 'execution', 'exile'],
		lawEnforcement: 6,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 3
	// ========================================================================
	{
		nationId: 'nat_hohokam',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 6,
		genderEquality: 5,
		slaveryStatus: 'none',
		judicialIndependence: 3,
		crimeRate: 2,
		commonCrimes: ['theft', 'water_disputes'],
		punishments: ['restitution', 'exile', 'social_ostracism'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_dorset',
		legalSystem: 'customary_law',
		propertyRights: 3,
		personalFreedom: 8,
		genderEquality: 6,
		slaveryStatus: 'none',
		judicialIndependence: 3,
		crimeRate: 1,
		commonCrimes: ['theft', 'taboo_violation'],
		punishments: ['exile', 'social_ostracism'],
		lawEnforcement: 1,
	},
	{
		nationId: 'nat_beothuk',
		legalSystem: 'customary_law',
		propertyRights: 3,
		personalFreedom: 8,
		genderEquality: 6,
		slaveryStatus: 'none',
		judicialIndependence: 3,
		crimeRate: 1,
		commonCrimes: ['theft'],
		punishments: ['exile', 'social_ostracism'],
		lawEnforcement: 1,
	},
	{
		nationId: 'nat_dene',
		legalSystem: 'customary_law',
		propertyRights: 3,
		personalFreedom: 8,
		genderEquality: 5,
		slaveryStatus: 'none',
		judicialIndependence: 3,
		crimeRate: 2,
		commonCrimes: ['theft', 'witchcraft'],
		punishments: ['exile', 'restitution', 'social_ostracism'],
		lawEnforcement: 1,
	},
	{
		nationId: 'nat_mikmaq',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 7,
		genderEquality: 5,
		slaveryStatus: 'limited',
		judicialIndependence: 4,
		crimeRate: 2,
		commonCrimes: ['theft', 'blood_feud'],
		punishments: ['restitution', 'exile', 'social_ostracism'],
		lawEnforcement: 2,
	},
	{
		nationId: 'nat_papuan',
		legalSystem: 'customary_law',
		propertyRights: 3,
		personalFreedom: 6,
		genderEquality: 2,
		slaveryStatus: 'none',
		judicialIndependence: 2,
		crimeRate: 4,
		commonCrimes: ['theft', 'sorcery', 'pig_theft', 'murder'],
		punishments: ['blood_price', 'warfare', 'exile'],
		lawEnforcement: 2,
	},
	{
		nationId: 'nat_fiji',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 4,
		genderEquality: 3,
		slaveryStatus: 'legal',
		judicialIndependence: 2,
		crimeRate: 3,
		commonCrimes: ['theft', 'disrespect_to_chief', 'taboo_violation'],
		punishments: ['execution', 'exile', 'cannibalism_ritual'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_chamorro',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 5,
		genderEquality: 6,
		slaveryStatus: 'limited',
		judicialIndependence: 3,
		crimeRate: 2,
		commonCrimes: ['theft', 'disrespect'],
		punishments: ['restitution', 'exile', 'social_ostracism'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_guanche',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 5,
		genderEquality: 4,
		slaveryStatus: 'limited',
		judicialIndependence: 3,
		crimeRate: 2,
		commonCrimes: ['theft', 'cattle_raiding'],
		punishments: ['fine', 'exile', 'social_ostracism'],
		lawEnforcement: 3,
	},
	{
		nationId: 'nat_san',
		legalSystem: 'customary_law',
		propertyRights: 2,
		personalFreedom: 9,
		genderEquality: 7,
		slaveryStatus: 'none',
		judicialIndependence: 5,
		crimeRate: 1,
		commonCrimes: ['hoarding', 'laziness'],
		punishments: ['social_ostracism', 'ridicule'],
		lawEnforcement: 1,
	},
	{
		nationId: 'nat_mbuti',
		legalSystem: 'customary_law',
		propertyRights: 2,
		personalFreedom: 9,
		genderEquality: 7,
		slaveryStatus: 'none',
		judicialIndependence: 5,
		crimeRate: 1,
		commonCrimes: ['hoarding', 'noise_during_hunt'],
		punishments: ['social_ostracism', 'ridicule', 'exile'],
		lawEnforcement: 1,
	},
	{
		nationId: 'nat_igbo',
		legalSystem: 'customary_law',
		propertyRights: 5,
		personalFreedom: 6,
		genderEquality: 4,
		slaveryStatus: 'legal',
		judicialIndependence: 5,
		crimeRate: 2,
		commonCrimes: ['theft', 'sacrilege', 'murder'],
		punishments: ['fine', 'exile', 'ordeal_trial', 'execution'],
		lawEnforcement: 4,
	},
	{
		nationId: 'nat_chukchi',
		legalSystem: 'customary_law',
		propertyRights: 4,
		personalFreedom: 7,
		genderEquality: 4,
		slaveryStatus: 'limited',
		judicialIndependence: 3,
		crimeRate: 2,
		commonCrimes: ['theft', 'reindeer_theft', 'blood_feud'],
		punishments: ['blood_price', 'exile', 'physical_punishment'],
		lawEnforcement: 2,
	},
]
