import type { NationTechnology } from '../../../shared/src/types/world'

// ============================================================================
// Technologies par nation — An 1000
// ============================================================================
// Chaque nation possède un sous-ensemble du DAG technologique.
// Les techs listées respectent les prérequis (un nation ne peut avoir
// une tech sans ses prerequisites).
// innovationCapacity reflète la capacité de R&D en l'an 1000.
// ============================================================================

// --- Bases communes à toute civilisation sédentaire ---
const BASE_SEDENTARY = [
	'tech_basic_agriculture',
	'tech_animal_husbandry',
	'tech_basic_construction',
	'tech_basic_weapons',
	'tech_pottery',
	'tech_weaving',
	'tech_leather_working',
	'tech_tribal_governance',
	'tech_basic_trade',
	'tech_herbal_medicine',
	'tech_basic_philosophy',
]

// --- Bases communes aux civilisations avec écriture ---
const BASE_LITERATE = [
	...BASE_SEDENTARY,
	'tech_basic_writing',
	'tech_basic_astronomy',
	'tech_basic_mathematics',
	'tech_calendar',
	'tech_coinage',
	'tech_codified_law',
]

// --- Métallurgie classique (Ancien Monde) ---
const METALLURGY_OLD_WORLD = [
	'tech_copper_working',
	'tech_bronze_working',
	'tech_iron_working',
	'tech_gold_silver_working',
	'tech_metal_weapons',
]

// --- Socle militaire méditerranéen/européen ---
const MILITARY_CLASSICAL = [
	...METALLURGY_OLD_WORLD,
	'tech_armor',
	'tech_chainmail',
	'tech_cavalry',
	'tech_siege_warfare',
]

// --- Construction avancée ---
const CONSTRUCTION_ADVANCED = [
	'tech_stone_masonry',
	'tech_arch_vault',
	'tech_fortification',
	'tech_road_building',
	'tech_bridge_building',
]

// --- Navigation basique ---
const SAILING_BASIC = ['tech_basic_sailing']

export const nationTechnologies: NationTechnology[] = [
	// ========================================================================
	// EUROPE OCCIDENTALE
	// ========================================================================
	{
		nationId: 'nat_hre',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_heavy_plow',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_aqueduct',
			'tech_feudalism',
			'tech_guilds',
			'tech_ink_production',
			'tech_surgery_basic',
			'tech_stirrup',
			'tech_crossbow',
			'tech_glass_making',
			'tech_horse_collar',
		],
		researchProgress: [{ techId: 'tech_paper_making', progress: 0.1 }],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_france',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_heavy_plow',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_feudalism',
			'tech_guilds',
			'tech_ink_production',
			'tech_surgery_basic',
			'tech_stirrup',
			'tech_crossbow',
			'tech_glass_making',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_england',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_heavy_plow',
			'tech_water_mill',
			'tech_feudalism',
			'tech_ink_production',
			'tech_surgery_basic',
			'tech_stirrup',
			'tech_longship', // influence viking
			'tech_horse_collar',
		],
		researchProgress: [{ techId: 'tech_crop_rotation', progress: 0.3 }],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_scotland',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_heavy_plow',
			'tech_feudalism',
			'tech_ink_production',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_papal',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...CONSTRUCTION_ADVANCED,
			'tech_irrigation',
			'tech_aqueduct',
			'tech_feudalism',
			'tech_ink_production',
			'tech_surgery_basic',
			'tech_glass_making',
			'tech_bureaucracy',
			'tech_armor',
			'tech_cavalry',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_venice',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_aqueduct',
			'tech_glass_making',
			'tech_guilds',
			'tech_banking_basic',
			'tech_ink_production',
			'tech_armor',
			'tech_chainmail',
			'tech_lateen_sail',
			'tech_celestial_navigation',
			'tech_bureaucracy',
		],
		researchProgress: [],
		innovationCapacity: 7,
	},

	// ========================================================================
	// IBÉRIE
	// ========================================================================
	{
		nationId: 'nat_leon',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_heavy_plow',
			'tech_feudalism',
			'tech_stirrup',
			'tech_ink_production',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_navarre',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			...CONSTRUCTION_ADVANCED,
			'tech_irrigation',
			'tech_feudalism',
			'tech_stirrup',
			'tech_ink_production',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_cordoba',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_aqueduct',
			'tech_feudalism',
			'tech_bureaucracy',
			'tech_ink_production',
			'tech_paper_making',
			'tech_algebra',
			'tech_advanced_astronomy',
			'tech_astrolabe',
			'tech_islamic_medicine',
			'tech_surgery_basic',
			'tech_lateen_sail',
			'tech_celestial_navigation',
			'tech_glass_making',
			'tech_silk_production',
			'tech_stirrup',
			'tech_composite_bow',
			'tech_caravanserai',
			'tech_zero_decimal',
			'tech_basic_alchemy',
			'tech_natural_philosophy',
		],
		researchProgress: [],
		innovationCapacity: 9,
	},

	// ========================================================================
	// SCANDINAVIE
	// ========================================================================
	{
		nationId: 'nat_denmark',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_road_building',
			...SAILING_BASIC,
			'tech_longship',
			'tech_celestial_navigation',
			'tech_heavy_plow',
			'tech_stirrup',
			'tech_ink_production',
		],
		researchProgress: [{ techId: 'tech_feudalism', progress: 0.4 }],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_norway',
		unlockedTechs: [
			...BASE_SEDENTARY,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_basic_writing',
			'tech_basic_astronomy',
			'tech_calendar',
			...SAILING_BASIC,
			'tech_longship',
			'tech_celestial_navigation',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_stirrup',
		],
		researchProgress: [{ techId: 'tech_basic_mathematics', progress: 0.5 }],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_sweden',
		unlockedTechs: [
			...BASE_SEDENTARY,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_basic_writing',
			'tech_basic_astronomy',
			'tech_calendar',
			...SAILING_BASIC,
			'tech_longship',
			'tech_celestial_navigation',
			'tech_stone_masonry',
			'tech_stirrup',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},

	// ========================================================================
	// EUROPE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_poland',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_road_building',
			'tech_irrigation',
			'tech_heavy_plow',
			'tech_feudalism',
			'tech_stirrup',
			'tech_ink_production',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_hungary',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_road_building',
			'tech_irrigation',
			'tech_heavy_plow',
			'tech_feudalism',
			'tech_stirrup',
			'tech_composite_bow',
			'tech_ink_production',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_kievan_rus',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_road_building',
			...SAILING_BASIC,
			'tech_longship',
			'tech_irrigation',
			'tech_heavy_plow',
			'tech_feudalism',
			'tech_stirrup',
			'tech_ink_production',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_volga_bulgaria',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_stirrup',
			'tech_composite_bow',
			'tech_caravanserai',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_croatia',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_road_building',
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_feudalism',
			'tech_stirrup',
			'tech_ink_production',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},

	// ========================================================================
	// BYZANCE
	// ========================================================================
	{
		nationId: 'nat_byzantine',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_aqueduct',
			'tech_bureaucracy',
			'tech_census',
			'tech_ink_production',
			'tech_paper_making',
			'tech_surgery_basic',
			'tech_advanced_astronomy',
			'tech_algebra',
			'tech_glass_making',
			'tech_silk_production',
			'tech_lateen_sail',
			'tech_celestial_navigation',
			'tech_stirrup',
			'tech_crossbow',
			'tech_greek_fire',
			'tech_trebuchet',
			'tech_basic_alchemy',
			'tech_natural_philosophy',
			'tech_quarantine',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 7,
	},

	// ========================================================================
	// MONDE ISLAMIQUE
	// ========================================================================
	{
		nationId: 'nat_fatimid',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_aqueduct',
			'tech_bureaucracy',
			'tech_census',
			'tech_ink_production',
			'tech_paper_making',
			'tech_algebra',
			'tech_zero_decimal',
			'tech_advanced_astronomy',
			'tech_astrolabe',
			'tech_islamic_medicine',
			'tech_surgery_basic',
			'tech_quarantine',
			'tech_glass_making',
			'tech_silk_production',
			'tech_lateen_sail',
			'tech_celestial_navigation',
			'tech_stirrup',
			'tech_composite_bow',
			'tech_caravanserai',
			'tech_banking_basic',
			'tech_basic_alchemy',
			'tech_natural_philosophy',
		],
		researchProgress: [],
		innovationCapacity: 8,
	},
	{
		nationId: 'nat_buyid',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_aqueduct',
			'tech_bureaucracy',
			'tech_ink_production',
			'tech_paper_making',
			'tech_algebra',
			'tech_zero_decimal',
			'tech_advanced_astronomy',
			'tech_astrolabe',
			'tech_islamic_medicine',
			'tech_surgery_basic',
			'tech_glass_making',
			'tech_silk_production',
			'tech_lateen_sail',
			'tech_stirrup',
			'tech_composite_bow',
			'tech_caravanserai',
			'tech_basic_alchemy',
			'tech_natural_philosophy',
		],
		researchProgress: [],
		innovationCapacity: 7,
	},
	{
		nationId: 'nat_ghaznavid',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_bureaucracy',
			'tech_ink_production',
			'tech_paper_making',
			'tech_algebra',
			'tech_zero_decimal',
			'tech_islamic_medicine',
			'tech_surgery_basic',
			'tech_stirrup',
			'tech_composite_bow',
			'tech_caravanserai',
			'tech_steel_making',
			'tech_damascus_steel',
		],
		researchProgress: [],
		innovationCapacity: 6,
	},
	{
		nationId: 'nat_karakhanid',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_ink_production',
			'tech_paper_making',
			'tech_stirrup',
			'tech_composite_bow',
			'tech_caravanserai',
			'tech_islamic_medicine',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},

	// ========================================================================
	// ASIE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_song',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_selective_breeding',
			'tech_terracing',
			'tech_water_mill',
			'tech_aqueduct',
			'tech_bureaucracy',
			'tech_census',
			'tech_civil_examination',
			'tech_ink_production',
			'tech_paper_making',
			'tech_block_printing',
			'tech_algebra',
			'tech_zero_decimal',
			'tech_advanced_astronomy',
			'tech_chinese_medicine',
			'tech_surgery_basic',
			'tech_silk_production',
			'tech_porcelain',
			'tech_glass_making',
			'tech_chinese_junk',
			'tech_celestial_navigation',
			'tech_lateen_sail',
			'tech_stirrup',
			'tech_crossbow',
			'tech_trebuchet',
			'tech_gunpowder',
			'tech_steel_making',
			'tech_banking_basic',
			'tech_guilds',
			'tech_basic_alchemy',
			'tech_natural_philosophy',
			'tech_horse_collar',
			'tech_compass',
			'tech_blast_furnace',
		],
		researchProgress: [],
		innovationCapacity: 10,
	},
	{
		nationId: 'nat_liao',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_irrigation',
			'tech_ink_production',
			'tech_paper_making',
			'tech_stirrup',
			'tech_composite_bow',
			'tech_chinese_medicine',
			'tech_porcelain',
			'tech_block_printing',
			'tech_horse_collar',
		],
		researchProgress: [{ techId: 'tech_gunpowder', progress: 0.2 }],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_goryeo',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_road_building',
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_terracing',
			'tech_bureaucracy',
			'tech_civil_examination',
			'tech_ink_production',
			'tech_paper_making',
			'tech_block_printing',
			'tech_chinese_medicine',
			'tech_porcelain',
			'tech_silk_production',
			'tech_stirrup',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 6,
	},
	{
		nationId: 'nat_japan',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_chainmail',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_terracing',
			'tech_bureaucracy',
			'tech_ink_production',
			'tech_paper_making',
			'tech_block_printing',
			'tech_chinese_medicine',
			'tech_silk_production',
			'tech_porcelain',
			'tech_steel_making',
			'tech_stirrup',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 6,
	},

	// ========================================================================
	// ASIE DU SUD-EST
	// ========================================================================
	{
		nationId: 'nat_dai_viet',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_terracing',
			'tech_crop_rotation',
			'tech_bureaucracy',
			'tech_ink_production',
			'tech_paper_making',
			'tech_chinese_medicine',
			'tech_crossbow',
			'tech_stirrup',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_khmer',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_arch_vault',
			'tech_fortification',
			'tech_road_building',
			'tech_bridge_building',
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_aqueduct',
			'tech_terracing',
			'tech_bureaucracy',
			'tech_census',
			'tech_ink_production',
			'tech_chinese_medicine',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 6,
	},
	{
		nationId: 'nat_srivijaya',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_stone_masonry',
			...SAILING_BASIC,
			'tech_lateen_sail',
			'tech_celestial_navigation',
			'tech_irrigation',
			'tech_bureaucracy',
			'tech_ink_production',
			'tech_caravanserai',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},

	// ========================================================================
	// ASIE DU SUD
	// ========================================================================
	{
		nationId: 'nat_chola',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			...SAILING_BASIC,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_aqueduct',
			'tech_bureaucracy',
			'tech_census',
			'tech_ink_production',
			'tech_paper_making',
			'tech_algebra',
			'tech_zero_decimal',
			'tech_advanced_astronomy',
			'tech_chinese_medicine',
			'tech_surgery_basic',
			'tech_silk_production',
			'tech_lateen_sail',
			'tech_celestial_navigation',
			'tech_steel_making',
			'tech_damascus_steel',
			'tech_stirrup',
			'tech_horse_collar',
		],
		researchProgress: [],
		innovationCapacity: 7,
	},
	{
		nationId: 'nat_chalukya',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_bureaucracy',
			'tech_ink_production',
			'tech_algebra',
			'tech_zero_decimal',
			'tech_surgery_basic',
			'tech_steel_making',
			'tech_stirrup',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_pala',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			'tech_irrigation',
			'tech_crop_rotation',
			'tech_water_mill',
			'tech_bureaucracy',
			'tech_ink_production',
			'tech_paper_making',
			'tech_algebra',
			'tech_zero_decimal',
			'tech_advanced_astronomy',
			'tech_surgery_basic',
			'tech_steel_making',
			'tech_stirrup',
		],
		researchProgress: [],
		innovationCapacity: 6,
	},

	// ========================================================================
	// AFRIQUE
	// ========================================================================
	{
		nationId: 'nat_ghana',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_copper_working',
			'tech_bronze_working',
			'tech_iron_working',
			'tech_gold_silver_working',
			'tech_metal_weapons',
			'tech_armor',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_irrigation',
			'tech_caravanserai',
			'tech_basic_writing',
			'tech_calendar',
			'tech_stirrup',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_kanem',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_copper_working',
			'tech_bronze_working',
			'tech_iron_working',
			'tech_gold_silver_working',
			'tech_metal_weapons',
			'tech_armor',
			'tech_cavalry',
			'tech_irrigation',
			'tech_caravanserai',
			'tech_basic_writing',
			'tech_calendar',
			'tech_stirrup',
			'tech_composite_bow',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_ethiopia',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_arch_vault',
			'tech_fortification',
			'tech_road_building',
			'tech_irrigation',
			'tech_terracing',
			'tech_ink_production',
			'tech_stirrup',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_swahili_cities',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_stone_masonry',
			...SAILING_BASIC,
			'tech_lateen_sail',
			'tech_celestial_navigation',
			'tech_irrigation',
			'tech_caravanserai',
			'tech_ink_production',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},

	// ========================================================================
	// AMÉRIQUES
	// ========================================================================
	{
		nationId: 'nat_toltec',
		unlockedTechs: [
			'tech_basic_agriculture',
			'tech_irrigation',
			'tech_terracing',
			'tech_animal_husbandry',
			'tech_basic_construction',
			'tech_stone_masonry',
			'tech_arch_vault',
			'tech_road_building',
			'tech_basic_weapons',
			'tech_pottery',
			'tech_weaving',
			'tech_leather_working',
			'tech_tribal_governance',
			'tech_basic_trade',
			'tech_herbal_medicine',
			'tech_basic_philosophy',
			'tech_basic_writing',
			'tech_basic_astronomy',
			'tech_calendar',
			'tech_basic_mathematics',
			'tech_copper_working',
			'tech_gold_silver_working',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_maya_states',
		unlockedTechs: [
			'tech_basic_agriculture',
			'tech_irrigation',
			'tech_terracing',
			'tech_animal_husbandry',
			'tech_basic_construction',
			'tech_stone_masonry',
			'tech_arch_vault',
			'tech_road_building',
			'tech_basic_weapons',
			'tech_pottery',
			'tech_weaving',
			'tech_leather_working',
			'tech_tribal_governance',
			'tech_basic_trade',
			'tech_herbal_medicine',
			'tech_basic_philosophy',
			'tech_basic_writing',
			'tech_basic_astronomy',
			'tech_advanced_astronomy',
			'tech_calendar',
			'tech_basic_mathematics',
			'tech_zero_decimal',
			'tech_copper_working',
			'tech_gold_silver_working',
		],
		researchProgress: [],
		innovationCapacity: 6,
	},
	{
		nationId: 'nat_mississippian',
		unlockedTechs: [
			'tech_basic_agriculture',
			'tech_irrigation',
			'tech_animal_husbandry',
			'tech_basic_construction',
			'tech_stone_masonry',
			'tech_basic_weapons',
			'tech_pottery',
			'tech_weaving',
			'tech_leather_working',
			'tech_tribal_governance',
			'tech_basic_trade',
			'tech_herbal_medicine',
			'tech_basic_philosophy',
			'tech_basic_astronomy',
			'tech_calendar',
			'tech_copper_working',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_wari',
		unlockedTechs: [
			'tech_basic_agriculture',
			'tech_irrigation',
			'tech_terracing',
			'tech_animal_husbandry',
			'tech_selective_breeding',
			'tech_basic_construction',
			'tech_stone_masonry',
			'tech_arch_vault',
			'tech_road_building',
			'tech_bridge_building',
			'tech_aqueduct',
			'tech_basic_weapons',
			'tech_pottery',
			'tech_weaving',
			'tech_leather_working',
			'tech_tribal_governance',
			'tech_basic_trade',
			'tech_herbal_medicine',
			'tech_basic_philosophy',
			'tech_basic_astronomy',
			'tech_calendar',
			'tech_copper_working',
			'tech_bronze_working',
			'tech_gold_silver_working',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},

	// ========================================================================
	// ASIE CENTRALE
	// ========================================================================
	{
		nationId: 'nat_tibet',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_irrigation',
			'tech_terracing',
			'tech_ink_production',
			'tech_paper_making',
			'tech_block_printing',
			'tech_chinese_medicine',
			'tech_stirrup',
			'tech_composite_bow',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================
	{
		nationId: 'nat_puebloans',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_basic_astronomy',
			'tech_calendar',
			'tech_stone_masonry',
			'tech_irrigation',
			'tech_road_building',
			'tech_basic_mathematics',
			'tech_copper_working',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_haida',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_basic_sailing',
			'tech_copper_working',
			'tech_gold_silver_working',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_thule',
		unlockedTechs: [
			'tech_basic_weapons',
			'tech_leather_working',
			'tech_basic_trade',
			'tech_herbal_medicine',
			'tech_basic_philosophy',
			'tech_basic_sailing',
			'tech_animal_husbandry',
			'tech_pottery',
			'tech_weaving',
			'tech_basic_astronomy',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_tui_tonga',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_basic_sailing',
			'tech_basic_astronomy',
			'tech_calendar',
			'tech_stone_masonry',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_aboriginal',
		unlockedTechs: [
			'tech_basic_weapons',
			'tech_leather_working',
			'tech_basic_trade',
			'tech_herbal_medicine',
			'tech_basic_philosophy',
			'tech_basic_astronomy',
			'tech_basic_agriculture', // firestick farming
		],
		researchProgress: [],
		innovationCapacity: 2,
	},
	{
		nationId: 'nat_sami',
		unlockedTechs: [
			'tech_animal_husbandry',
			'tech_basic_weapons',
			'tech_leather_working',
			'tech_basic_trade',
			'tech_herbal_medicine',
			'tech_basic_philosophy',
			'tech_basic_sailing',
			'tech_weaving',
			'tech_pottery',
			'tech_tribal_governance',
			'tech_iron_working', // influence scandinave
			'tech_copper_working',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_mapuche',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_basic_astronomy',
			'tech_irrigation',
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_malagasy',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_basic_sailing',
			'tech_basic_astronomy',
			'tech_iron_working',
			'tech_copper_working',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_yoruba',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_iron_working',
			'tech_copper_working',
			'tech_bronze_working',
			'tech_gold_silver_working',
			'tech_stone_masonry',
			'tech_basic_astronomy',
			'tech_calendar',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_zimbabwe',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_iron_working',
			'tech_copper_working',
			'tech_gold_silver_working',
			'tech_stone_masonry',
			'tech_road_building',
			'tech_basic_trade',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 2
	// ========================================================================
	{
		nationId: 'nat_chimu',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_copper_working',
			'tech_bronze_working',
			'tech_gold_silver_working',
			'tech_irrigation',
			'tech_road_building',
			'tech_stone_masonry',
			'tech_basic_astronomy',
			'tech_calendar',
			'tech_basic_sailing',
		],
		researchProgress: [],
		innovationCapacity: 6, // métallurgie avancée, canaux
	},
	{
		nationId: 'nat_muisca',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_gold_silver_working',
			'tech_copper_working',
			'tech_irrigation',
			'tech_basic_astronomy',
			'tech_calendar',
			'tech_basic_trade',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_guarani',
		unlockedTechs: [...BASE_SEDENTARY, 'tech_basic_sailing'],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_hawaii',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_basic_sailing',
			'tech_basic_astronomy',
			'tech_irrigation',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_ainu',
		unlockedTechs: [...BASE_SEDENTARY, 'tech_basic_sailing'],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_makuria',
		unlockedTechs: [
			...BASE_LITERATE,
			...METALLURGY_OLD_WORLD,
			'tech_armor',
			'tech_cavalry',
			'tech_stone_masonry',
			'tech_fortification',
			'tech_irrigation',
			'tech_arch_vault',
			'tech_basic_sailing',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_tuareg',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_iron_working',
			'tech_copper_working',
			'tech_cavalry',
			'tech_basic_astronomy',
			'tech_basic_trade',
		],
		researchProgress: [],
		innovationCapacity: 4,
	},
	{
		nationId: 'nat_georgia',
		unlockedTechs: [
			...BASE_LITERATE,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			'tech_irrigation',
			'tech_basic_sailing',
			'tech_ink_production',
		],
		researchProgress: [],
		innovationCapacity: 6,
	},
	{
		nationId: 'nat_armenia',
		unlockedTechs: [
			...BASE_LITERATE,
			...MILITARY_CLASSICAL,
			...CONSTRUCTION_ADVANCED,
			'tech_irrigation',
			'tech_ink_production',
			'tech_paper_making',
		],
		researchProgress: [],
		innovationCapacity: 7, // tradition littéraire et architecturale ancienne
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 3
	// ========================================================================
	{
		nationId: 'nat_hohokam',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_irrigation',
			'tech_basic_astronomy',
		],
		researchProgress: [],
		innovationCapacity: 4, // ingénieurs hydrauliques
	},
	{
		nationId: 'nat_dorset',
		unlockedTechs: [
			'tech_basic_weapons',
			'tech_leather_working',
			'tech_herbal_medicine',
			'tech_basic_construction',
		],
		researchProgress: [],
		innovationCapacity: 2,
	},
	{
		nationId: 'nat_beothuk',
		unlockedTechs: [
			'tech_basic_weapons',
			'tech_leather_working',
			'tech_herbal_medicine',
			'tech_basic_construction',
			'tech_basic_sailing',
		],
		researchProgress: [],
		innovationCapacity: 2,
	},
	{
		nationId: 'nat_dene',
		unlockedTechs: [
			'tech_basic_weapons',
			'tech_leather_working',
			'tech_herbal_medicine',
			'tech_basic_construction',
			'tech_basic_trade',
		],
		researchProgress: [],
		innovationCapacity: 2,
	},
	{
		nationId: 'nat_mikmaq',
		unlockedTechs: [...BASE_SEDENTARY, 'tech_basic_sailing'],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_papuan',
		unlockedTechs: [...BASE_SEDENTARY, 'tech_irrigation'],
		researchProgress: [],
		innovationCapacity: 3, // agriculture ancienne (10 000 ans)
	},
	{
		nationId: 'nat_fiji',
		unlockedTechs: [...BASE_SEDENTARY, 'tech_basic_sailing'],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_chamorro',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_basic_sailing',
			'tech_stone_masonry', // latte stones
		],
		researchProgress: [],
		innovationCapacity: 3,
	},
	{
		nationId: 'nat_guanche',
		unlockedTechs: [...BASE_SEDENTARY],
		researchProgress: [],
		innovationCapacity: 2, // isolement insulaire
	},
	{
		nationId: 'nat_san',
		unlockedTechs: [
			'tech_basic_weapons',
			'tech_herbal_medicine',
			'tech_basic_philosophy',
		],
		researchProgress: [],
		innovationCapacity: 2,
	},
	{
		nationId: 'nat_mbuti',
		unlockedTechs: [
			'tech_basic_weapons',
			'tech_herbal_medicine',
			'tech_basic_construction',
			'tech_basic_trade',
		],
		researchProgress: [],
		innovationCapacity: 2,
	},
	{
		nationId: 'nat_igbo',
		unlockedTechs: [
			...BASE_SEDENTARY,
			'tech_iron_working',
			'tech_copper_working',
			'tech_bronze_working',
			'tech_basic_trade',
		],
		researchProgress: [],
		innovationCapacity: 5,
	},
	{
		nationId: 'nat_chukchi',
		unlockedTechs: [
			'tech_basic_weapons',
			'tech_leather_working',
			'tech_herbal_medicine',
			'tech_basic_construction',
			'tech_basic_sailing',
		],
		researchProgress: [],
		innovationCapacity: 2,
	},
]
