import type { NationMilitary } from '../../../shared/src/types/world'

// ============================================================================
// Forces militaires par nation — An 1000
// ============================================================================

export const nationMilitaryData: NationMilitary[] = [
	// ========================================================================
	// EUROPE OCCIDENTALE
	// ========================================================================
	{
		nationId: 'nat_hre',
		armySize: 30000,
		availableUnits: [
			'heavy_cavalry',
			'infantry',
			'archers',
			'militia',
			'siege_engineers',
		],
		militaryStrength: 7,
		navalStrength: 2,
		fortificationCount: 200,
		warExperience: 7,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_france',
		armySize: 15000,
		availableUnits: ['heavy_cavalry', 'infantry', 'archers', 'militia'],
		militaryStrength: 5,
		navalStrength: 2,
		fortificationCount: 100,
		warExperience: 5,
		morale: 5,
		professionalArmy: false,
	},
	{
		nationId: 'nat_england',
		armySize: 12000,
		availableUnits: [
			'infantry',
			'heavy_infantry',
			'archers',
			'militia',
			'navy',
		],
		militaryStrength: 5,
		navalStrength: 4,
		fortificationCount: 80,
		warExperience: 6,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_scotland',
		armySize: 5000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 3,
		navalStrength: 1,
		fortificationCount: 20,
		warExperience: 5,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_papal',
		armySize: 3000,
		availableUnits: ['infantry', 'militia', 'mercenaries'],
		militaryStrength: 2,
		navalStrength: 1,
		fortificationCount: 30,
		warExperience: 3,
		morale: 5,
		professionalArmy: false,
	},
	{
		nationId: 'nat_venice',
		armySize: 8000,
		availableUnits: ['infantry', 'crossbowmen', 'navy', 'mercenaries'],
		militaryStrength: 5,
		navalStrength: 8,
		fortificationCount: 25,
		warExperience: 6,
		morale: 7,
		professionalArmy: true,
	},

	// ========================================================================
	// IBÉRIE
	// ========================================================================
	{
		nationId: 'nat_leon',
		armySize: 8000,
		availableUnits: ['heavy_cavalry', 'infantry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 1,
		fortificationCount: 60,
		warExperience: 7,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_navarre',
		armySize: 3000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 3,
		navalStrength: 0,
		fortificationCount: 20,
		warExperience: 5,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_cordoba',
		armySize: 40000,
		availableUnits: [
			'heavy_cavalry',
			'infantry',
			'archers',
			'crossbowmen',
			'siege_engineers',
			'navy',
			'mercenaries',
		],
		militaryStrength: 7,
		navalStrength: 6,
		fortificationCount: 150,
		warExperience: 8,
		morale: 5,
		professionalArmy: true,
	},

	// ========================================================================
	// SCANDINAVIE
	// ========================================================================
	{
		nationId: 'nat_denmark',
		armySize: 10000,
		availableUnits: [
			'infantry',
			'heavy_infantry',
			'archers',
			'navy',
			'militia',
		],
		militaryStrength: 5,
		navalStrength: 7,
		fortificationCount: 15,
		warExperience: 8,
		morale: 8,
		professionalArmy: false,
	},
	{
		nationId: 'nat_norway',
		armySize: 6000,
		availableUnits: ['infantry', 'archers', 'navy', 'militia'],
		militaryStrength: 4,
		navalStrength: 7,
		fortificationCount: 5,
		warExperience: 8,
		morale: 8,
		professionalArmy: false,
	},
	{
		nationId: 'nat_sweden',
		armySize: 5000,
		availableUnits: ['infantry', 'archers', 'navy', 'militia'],
		militaryStrength: 3,
		navalStrength: 4,
		fortificationCount: 5,
		warExperience: 6,
		morale: 7,
		professionalArmy: false,
	},

	// ========================================================================
	// EUROPE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_poland',
		armySize: 8000,
		availableUnits: ['heavy_cavalry', 'infantry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 0,
		fortificationCount: 30,
		warExperience: 5,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_hungary',
		armySize: 12000,
		availableUnits: [
			'heavy_cavalry',
			'cavalry',
			'archers',
			'infantry',
			'militia',
		],
		militaryStrength: 5,
		navalStrength: 1,
		fortificationCount: 40,
		warExperience: 6,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_kievan_rus',
		armySize: 20000,
		availableUnits: [
			'cavalry',
			'infantry',
			'archers',
			'navy',
			'militia',
			'mercenaries',
		],
		militaryStrength: 6,
		navalStrength: 3,
		fortificationCount: 50,
		warExperience: 7,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_volga_bulgaria',
		armySize: 8000,
		availableUnits: ['cavalry', 'infantry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 2,
		fortificationCount: 15,
		warExperience: 5,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_croatia',
		armySize: 5000,
		availableUnits: ['infantry', 'cavalry', 'archers', 'navy', 'militia'],
		militaryStrength: 3,
		navalStrength: 3,
		fortificationCount: 20,
		warExperience: 5,
		morale: 6,
		professionalArmy: false,
	},

	// ========================================================================
	// BYZANCE
	// ========================================================================
	{
		nationId: 'nat_byzantine',
		armySize: 50000,
		availableUnits: [
			'heavy_cavalry',
			'heavy_infantry',
			'infantry',
			'archers',
			'crossbowmen',
			'siege_engineers',
			'navy',
			'mercenaries',
		],
		militaryStrength: 8,
		navalStrength: 8,
		fortificationCount: 300,
		warExperience: 9,
		morale: 7,
		professionalArmy: true,
	},

	// ========================================================================
	// MONDE ISLAMIQUE
	// ========================================================================
	{
		nationId: 'nat_fatimid',
		armySize: 50000,
		availableUnits: [
			'heavy_cavalry',
			'cavalry',
			'infantry',
			'archers',
			'siege_engineers',
			'navy',
			'mercenaries',
		],
		militaryStrength: 7,
		navalStrength: 7,
		fortificationCount: 150,
		warExperience: 7,
		morale: 6,
		professionalArmy: true,
	},
	{
		nationId: 'nat_buyid',
		armySize: 30000,
		availableUnits: [
			'heavy_cavalry',
			'cavalry',
			'infantry',
			'archers',
			'siege_engineers',
			'mercenaries',
		],
		militaryStrength: 6,
		navalStrength: 3,
		fortificationCount: 80,
		warExperience: 7,
		morale: 5,
		professionalArmy: true,
	},
	{
		nationId: 'nat_ghaznavid',
		armySize: 60000,
		availableUnits: [
			'heavy_cavalry',
			'cavalry',
			'infantry',
			'archers',
			'war_elephants',
			'siege_engineers',
			'mercenaries',
		],
		militaryStrength: 8,
		navalStrength: 1,
		fortificationCount: 60,
		warExperience: 9,
		morale: 7,
		professionalArmy: true,
	},
	{
		nationId: 'nat_karakhanid',
		armySize: 25000,
		availableUnits: ['cavalry', 'heavy_cavalry', 'archers', 'infantry'],
		militaryStrength: 6,
		navalStrength: 0,
		fortificationCount: 30,
		warExperience: 7,
		morale: 7,
		professionalArmy: false,
	},

	// ========================================================================
	// ASIE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_song',
		armySize: 900000,
		availableUnits: [
			'infantry',
			'heavy_infantry',
			'archers',
			'crossbowmen',
			'cavalry',
			'siege_engineers',
			'navy',
		],
		militaryStrength: 7,
		navalStrength: 8,
		fortificationCount: 1000,
		warExperience: 6,
		morale: 5,
		professionalArmy: true,
	},
	{
		nationId: 'nat_liao',
		armySize: 150000,
		availableUnits: ['cavalry', 'heavy_cavalry', 'archers', 'infantry'],
		militaryStrength: 7,
		navalStrength: 1,
		fortificationCount: 50,
		warExperience: 8,
		morale: 8,
		professionalArmy: false,
	},
	{
		nationId: 'nat_goryeo',
		armySize: 40000,
		availableUnits: ['infantry', 'archers', 'cavalry', 'navy', 'militia'],
		militaryStrength: 5,
		navalStrength: 5,
		fortificationCount: 80,
		warExperience: 5,
		morale: 6,
		professionalArmy: true,
	},
	{
		nationId: 'nat_japan',
		armySize: 20000,
		availableUnits: [
			'infantry',
			'heavy_infantry',
			'cavalry',
			'archers',
			'navy',
		],
		militaryStrength: 5,
		navalStrength: 4,
		fortificationCount: 50,
		warExperience: 4,
		morale: 8,
		professionalArmy: true,
	},

	// ========================================================================
	// ASIE DU SUD-EST
	// ========================================================================
	{
		nationId: 'nat_dai_viet',
		armySize: 30000,
		availableUnits: [
			'infantry',
			'archers',
			'cavalry',
			'navy',
			'war_elephants',
			'militia',
		],
		militaryStrength: 5,
		navalStrength: 4,
		fortificationCount: 30,
		warExperience: 7,
		morale: 8,
		professionalArmy: true,
	},
	{
		nationId: 'nat_khmer',
		armySize: 50000,
		availableUnits: ['infantry', 'war_elephants', 'cavalry', 'archers', 'navy'],
		militaryStrength: 7,
		navalStrength: 4,
		fortificationCount: 40,
		warExperience: 7,
		morale: 7,
		professionalArmy: true,
	},
	{
		nationId: 'nat_srivijaya',
		armySize: 15000,
		availableUnits: ['infantry', 'navy', 'archers', 'mercenaries'],
		militaryStrength: 4,
		navalStrength: 7,
		fortificationCount: 15,
		warExperience: 5,
		morale: 5,
		professionalArmy: false,
	},

	// ========================================================================
	// ASIE DU SUD
	// ========================================================================
	{
		nationId: 'nat_chola',
		armySize: 60000,
		availableUnits: [
			'infantry',
			'heavy_infantry',
			'cavalry',
			'war_elephants',
			'archers',
			'navy',
			'siege_engineers',
		],
		militaryStrength: 8,
		navalStrength: 9,
		fortificationCount: 100,
		warExperience: 9,
		morale: 8,
		professionalArmy: true,
	},
	{
		nationId: 'nat_chalukya',
		armySize: 40000,
		availableUnits: [
			'infantry',
			'cavalry',
			'war_elephants',
			'archers',
			'siege_engineers',
		],
		militaryStrength: 6,
		navalStrength: 3,
		fortificationCount: 70,
		warExperience: 7,
		morale: 6,
		professionalArmy: true,
	},
	{
		nationId: 'nat_pala',
		armySize: 30000,
		availableUnits: ['infantry', 'war_elephants', 'cavalry', 'archers', 'navy'],
		militaryStrength: 5,
		navalStrength: 3,
		fortificationCount: 40,
		warExperience: 5,
		morale: 5,
		professionalArmy: true,
	},

	// ========================================================================
	// AFRIQUE
	// ========================================================================
	{
		nationId: 'nat_ghana',
		armySize: 40000,
		availableUnits: ['infantry', 'cavalry', 'archers'],
		militaryStrength: 6,
		navalStrength: 0,
		fortificationCount: 10,
		warExperience: 6,
		morale: 7,
		professionalArmy: true,
	},
	{
		nationId: 'nat_kanem',
		armySize: 15000,
		availableUnits: ['cavalry', 'infantry', 'archers'],
		militaryStrength: 4,
		navalStrength: 0,
		fortificationCount: 5,
		warExperience: 5,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_ethiopia',
		armySize: 15000,
		availableUnits: ['infantry', 'cavalry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 1,
		fortificationCount: 25,
		warExperience: 5,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_swahili_cities',
		armySize: 5000,
		availableUnits: ['infantry', 'navy', 'archers', 'mercenaries'],
		militaryStrength: 3,
		navalStrength: 5,
		fortificationCount: 10,
		warExperience: 3,
		morale: 5,
		professionalArmy: false,
	},

	// ========================================================================
	// AMÉRIQUES
	// ========================================================================
	{
		nationId: 'nat_toltec',
		armySize: 20000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 5,
		navalStrength: 0,
		fortificationCount: 10,
		warExperience: 7,
		morale: 8,
		professionalArmy: true,
	},
	{
		nationId: 'nat_maya_states',
		armySize: 15000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 1,
		fortificationCount: 15,
		warExperience: 7,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_mississippian',
		armySize: 5000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 3,
		navalStrength: 1,
		fortificationCount: 5,
		warExperience: 4,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_wari',
		armySize: 20000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 5,
		navalStrength: 1,
		fortificationCount: 15,
		warExperience: 6,
		morale: 7,
		professionalArmy: true,
	},

	// ========================================================================
	// ASIE CENTRALE
	// ========================================================================
	{
		nationId: 'nat_tibet',
		armySize: 15000,
		availableUnits: ['cavalry', 'infantry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 0,
		fortificationCount: 20,
		warExperience: 5,
		morale: 7,
		professionalArmy: false,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================
	{
		nationId: 'nat_puebloans',
		armySize: 3000,
		availableUnits: ['militia', 'archers'],
		militaryStrength: 2,
		navalStrength: 0,
		fortificationCount: 5,
		warExperience: 3,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_haida',
		armySize: 2000,
		availableUnits: ['militia', 'archers', 'war_canoe'],
		militaryStrength: 3,
		navalStrength: 4, // excellents guerriers maritimes
		fortificationCount: 2,
		warExperience: 5,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_thule',
		armySize: 500,
		availableUnits: ['militia'],
		militaryStrength: 1,
		navalStrength: 2, // kayaks et umiaks
		fortificationCount: 0,
		warExperience: 2,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_tui_tonga',
		armySize: 5000,
		availableUnits: ['infantry', 'militia', 'war_canoe'],
		militaryStrength: 4,
		navalStrength: 7, // empire maritime
		fortificationCount: 3,
		warExperience: 5,
		morale: 8,
		professionalArmy: false,
	},
	{
		nationId: 'nat_aboriginal',
		armySize: 0, // pas d’armée organisée
		availableUnits: ['militia'],
		militaryStrength: 1,
		navalStrength: 0,
		fortificationCount: 0,
		warExperience: 2,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_sami',
		armySize: 1000,
		availableUnits: ['militia', 'archers'],
		militaryStrength: 2,
		navalStrength: 1,
		fortificationCount: 0,
		warExperience: 3,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_mapuche',
		armySize: 10000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 5, // réputés pour leur résistance
		navalStrength: 1,
		fortificationCount: 5,
		warExperience: 6,
		morale: 9,
		professionalArmy: false,
	},
	{
		nationId: 'nat_malagasy',
		armySize: 3000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 3,
		navalStrength: 3, // héritage austronésien
		fortificationCount: 2,
		warExperience: 3,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_yoruba',
		armySize: 15000,
		availableUnits: ['infantry', 'archers', 'cavalry', 'militia'],
		militaryStrength: 5,
		navalStrength: 1,
		fortificationCount: 10,
		warExperience: 5,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_zimbabwe',
		armySize: 8000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 0,
		fortificationCount: 8, // enceintes de pierre sèche
		warExperience: 4,
		morale: 7,
		professionalArmy: false,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 2
	// ========================================================================
	{
		nationId: 'nat_chimu',
		armySize: 25000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 5,
		navalStrength: 2,
		fortificationCount: 15,
		warExperience: 5,
		morale: 6,
		professionalArmy: true,
	},
	{
		nationId: 'nat_muisca',
		armySize: 12000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 4,
		navalStrength: 0,
		fortificationCount: 5,
		warExperience: 4,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_guarani',
		armySize: 8000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 1,
		fortificationCount: 2,
		warExperience: 5,
		morale: 8,
		professionalArmy: false,
	},
	{
		nationId: 'nat_hawaii',
		armySize: 5000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 4,
		navalStrength: 4,
		fortificationCount: 3,
		warExperience: 5,
		morale: 8,
		professionalArmy: false,
	},
	{
		nationId: 'nat_ainu',
		armySize: 3000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 3,
		navalStrength: 1,
		fortificationCount: 2,
		warExperience: 4,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_makuria',
		armySize: 15000,
		availableUnits: ['infantry', 'archers', 'cavalry', 'militia'],
		militaryStrength: 6,
		navalStrength: 1,
		fortificationCount: 12,
		warExperience: 7,
		morale: 8,
		professionalArmy: true,
	},
	{
		nationId: 'nat_tuareg',
		armySize: 8000,
		availableUnits: ['cavalry', 'camel_cavalry', 'infantry', 'militia'],
		militaryStrength: 5,
		navalStrength: 0,
		fortificationCount: 3,
		warExperience: 6,
		morale: 9,
		professionalArmy: false,
	},
	{
		nationId: 'nat_georgia',
		armySize: 30000,
		availableUnits: [
			'infantry',
			'archers',
			'cavalry',
			'heavy_cavalry',
			'militia',
		],
		militaryStrength: 7,
		navalStrength: 2,
		fortificationCount: 25,
		warExperience: 8,
		morale: 8,
		professionalArmy: true,
	},
	{
		nationId: 'nat_armenia',
		armySize: 40000,
		availableUnits: [
			'infantry',
			'archers',
			'cavalry',
			'heavy_cavalry',
			'militia',
		],
		militaryStrength: 7,
		navalStrength: 1,
		fortificationCount: 30,
		warExperience: 8,
		morale: 9,
		professionalArmy: true,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 3
	// ========================================================================
	{
		nationId: 'nat_hohokam',
		armySize: 2000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 2,
		navalStrength: 0,
		fortificationCount: 2,
		warExperience: 2,
		morale: 5,
		professionalArmy: false,
	},
	{
		nationId: 'nat_dorset',
		armySize: 500,
		availableUnits: ['militia'],
		militaryStrength: 1,
		navalStrength: 1,
		fortificationCount: 0,
		warExperience: 1,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_beothuk',
		armySize: 400,
		availableUnits: ['militia'],
		militaryStrength: 1,
		navalStrength: 1,
		fortificationCount: 0,
		warExperience: 2,
		morale: 6,
		professionalArmy: false,
	},
	{
		nationId: 'nat_dene',
		armySize: 2000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 2,
		navalStrength: 0,
		fortificationCount: 0,
		warExperience: 3,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_mikmaq',
		armySize: 3000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 3,
		navalStrength: 2,
		fortificationCount: 2,
		warExperience: 4,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_papuan',
		armySize: 3000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 3,
		navalStrength: 0,
		fortificationCount: 1,
		warExperience: 5,
		morale: 8,
		professionalArmy: false,
	},
	{
		nationId: 'nat_fiji',
		armySize: 3000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 3,
		navalStrength: 3,
		fortificationCount: 3,
		warExperience: 5,
		morale: 8,
		professionalArmy: false,
	},
	{
		nationId: 'nat_chamorro',
		armySize: 2000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 3,
		navalStrength: 3,
		fortificationCount: 2,
		warExperience: 3,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_guanche',
		armySize: 3000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 3,
		navalStrength: 0,
		fortificationCount: 3,
		warExperience: 3,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_san',
		armySize: 500,
		availableUnits: ['militia'],
		militaryStrength: 2,
		navalStrength: 0,
		fortificationCount: 0,
		warExperience: 3,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_mbuti',
		armySize: 300,
		availableUnits: ['militia'],
		militaryStrength: 1,
		navalStrength: 0,
		fortificationCount: 0,
		warExperience: 1,
		morale: 5,
		professionalArmy: false,
	},
	{
		nationId: 'nat_igbo',
		armySize: 10000,
		availableUnits: ['infantry', 'archers', 'militia'],
		militaryStrength: 4,
		navalStrength: 1,
		fortificationCount: 5,
		warExperience: 4,
		morale: 7,
		professionalArmy: false,
	},
	{
		nationId: 'nat_chukchi',
		armySize: 2000,
		availableUnits: ['infantry', 'militia'],
		militaryStrength: 3,
		navalStrength: 2,
		fortificationCount: 0,
		warExperience: 5,
		morale: 9,
		professionalArmy: false,
	},
]
