import type { Population } from '../../../shared/src/types/world'

// ============================================================================
// Population & Démographie par nation — An 1000
// Estimations basées sur les données historiques disponibles
// ============================================================================

export const populationsData: Population[] = [
	// ========================================================================
	// EUROPE OCCIDENTALE
	// ========================================================================
	{
		nationId: 'nat_hre',
		total: 7_000_000,
		urbanRatio: 0.08,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.03, influence: 7, wealth: 7 },
			{ class: 'merchants', percentage: 0.03, influence: 3, wealth: 6 },
			{ class: 'artisans', percentage: 0.05, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.4, influence: 1, wealth: 2 },
			{ class: 'serfs', percentage: 0.45, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.019, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.3,
		birthRate: 0.04,
		deathRate: 0.035,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_france',
		total: 6_000_000,
		urbanRatio: 0.06,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 8, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 9, wealth: 9 },
			{ class: 'clergy', percentage: 0.03, influence: 7, wealth: 7 },
			{ class: 'merchants', percentage: 0.02, influence: 2, wealth: 5 },
			{ class: 'artisans', percentage: 0.04, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.35, influence: 1, wealth: 2 },
			{ class: 'serfs', percentage: 0.52, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.009, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.32,
		birthRate: 0.042,
		deathRate: 0.037,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_england',
		total: 2_000_000,
		urbanRatio: 0.07,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.03, influence: 6, wealth: 7 },
			{ class: 'merchants', percentage: 0.03, influence: 3, wealth: 6 },
			{ class: 'artisans', percentage: 0.04, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.45, influence: 2, wealth: 3 },
			{ class: 'serfs', percentage: 0.4, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.019, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.04,
		deathRate: 0.035,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_scotland',
		total: 500_000,
		urbanRatio: 0.03,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 7, wealth: 9 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.02, influence: 5, wealth: 6 },
			{ class: 'warriors', percentage: 0.05, influence: 6, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.6, influence: 2, wealth: 2 },
			{ class: 'serfs', percentage: 0.2, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.038, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 29,
		infantMortality: 0.35,
		birthRate: 0.042,
		deathRate: 0.039,
		growthRate: 0.003,
	},
	{
		nationId: 'nat_papal',
		total: 1_500_000,
		urbanRatio: 0.15,
		socialGroups: [
			{ class: 'clergy', percentage: 0.08, influence: 10, wealth: 9 },
			{ class: 'nobility', percentage: 0.03, influence: 6, wealth: 8 },
			{ class: 'merchants', percentage: 0.05, influence: 4, wealth: 6 },
			{ class: 'artisans', percentage: 0.07, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.5, influence: 1, wealth: 2 },
			{ class: 'serfs', percentage: 0.27, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.038,
		deathRate: 0.033,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_venice',
		total: 200_000,
		urbanRatio: 0.6,
		socialGroups: [
			{ class: 'nobility', percentage: 0.04, influence: 10, wealth: 10 },
			{ class: 'clergy', percentage: 0.03, influence: 4, wealth: 6 },
			{ class: 'merchants', percentage: 0.15, influence: 8, wealth: 9 },
			{ class: 'artisans', percentage: 0.2, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.35, influence: 1, wealth: 3 },
			{ class: 'serfs', percentage: 0.15, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.08, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.25,
		birthRate: 0.035,
		deathRate: 0.03,
		growthRate: 0.005,
	},

	// ========================================================================
	// IBÉRIE
	// ========================================================================
	{
		nationId: 'nat_leon',
		total: 1_500_000,
		urbanRatio: 0.06,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.03, influence: 7, wealth: 7 },
			{ class: 'warriors', percentage: 0.04, influence: 6, wealth: 5 },
			{ class: 'merchants', percentage: 0.02, influence: 2, wealth: 5 },
			{ class: 'artisans', percentage: 0.04, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.55, influence: 2, wealth: 2 },
			{ class: 'serfs', percentage: 0.28, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_navarre',
		total: 300_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'royalty', percentage: 0.003, influence: 9, wealth: 9 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 7 },
			{ class: 'clergy', percentage: 0.02, influence: 5, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.65, influence: 3, wealth: 3 },
			{ class: 'serfs', percentage: 0.25, influence: 0, wealth: 1 },
			{ class: 'artisans', percentage: 0.047, influence: 2, wealth: 4 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.04,
		deathRate: 0.036,
		growthRate: 0.004,
	},
	{
		nationId: 'nat_cordoba',
		total: 5_000_000,
		urbanRatio: 0.2,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 7, wealth: 9 },
			{ class: 'clergy', percentage: 0.03, influence: 6, wealth: 7 },
			{ class: 'merchants', percentage: 0.08, influence: 5, wealth: 8 },
			{ class: 'artisans', percentage: 0.1, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.45, influence: 1, wealth: 3 },
			{ class: 'slaves', percentage: 0.15, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.159, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 36,
		infantMortality: 0.25,
		birthRate: 0.038,
		deathRate: 0.03,
		growthRate: 0.008,
	},

	// ========================================================================
	// SCANDINAVIE
	// ========================================================================
	{
		nationId: 'nat_denmark',
		total: 800_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 8 },
			{ class: 'warriors', percentage: 0.06, influence: 6, wealth: 6 },
			{ class: 'merchants', percentage: 0.03, influence: 4, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.6, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'artisans', percentage: 0.078, influence: 2, wealth: 4 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.33,
		birthRate: 0.042,
		deathRate: 0.038,
		growthRate: 0.004,
	},
	{
		nationId: 'nat_norway',
		total: 400_000,
		urbanRatio: 0.04,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 8, wealth: 9 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 8 },
			{ class: 'warriors', percentage: 0.08, influence: 7, wealth: 6 },
			{ class: 'merchants', percentage: 0.02, influence: 4, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.55, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.12, influence: 0, wealth: 0 },
			{ class: 'artisans', percentage: 0.198, influence: 2, wealth: 4 },
		],
		lifeExpectancy: 29,
		infantMortality: 0.35,
		birthRate: 0.043,
		deathRate: 0.04,
		growthRate: 0.003,
	},
	{
		nationId: 'nat_sweden',
		total: 400_000,
		urbanRatio: 0.03,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 7, wealth: 9 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 7 },
			{ class: 'warriors', percentage: 0.06, influence: 6, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.6, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'artisans', percentage: 0.198, influence: 2, wealth: 4 },
		],
		lifeExpectancy: 29,
		infantMortality: 0.35,
		birthRate: 0.042,
		deathRate: 0.039,
		growthRate: 0.003,
	},

	// ========================================================================
	// EUROPE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_poland',
		total: 1_500_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.02, influence: 5, wealth: 6 },
			{ class: 'warriors', percentage: 0.04, influence: 6, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.55, influence: 2, wealth: 2 },
			{ class: 'serfs', percentage: 0.3, influence: 0, wealth: 1 },
			{ class: 'artisans', percentage: 0.059, influence: 2, wealth: 4 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.32,
		birthRate: 0.042,
		deathRate: 0.037,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_hungary',
		total: 2_000_000,
		urbanRatio: 0.06,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.02, influence: 5, wealth: 6 },
			{ class: 'warriors', percentage: 0.05, influence: 7, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.55, influence: 2, wealth: 2 },
			{ class: 'serfs', percentage: 0.3, influence: 0, wealth: 1 },
			{ class: 'artisans', percentage: 0.049, influence: 2, wealth: 4 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.32,
		birthRate: 0.042,
		deathRate: 0.036,
		growthRate: 0.006,
	},
	{
		nationId: 'nat_kievan_rus',
		total: 5_000_000,
		urbanRatio: 0.07,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.02, influence: 5, wealth: 6 },
			{ class: 'warriors', percentage: 0.05, influence: 7, wealth: 6 },
			{ class: 'merchants', percentage: 0.03, influence: 4, wealth: 7 },
			{ class: 'artisans', percentage: 0.05, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.5, influence: 1, wealth: 2 },
			{ class: 'serfs', percentage: 0.25, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.059, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.33,
		birthRate: 0.043,
		deathRate: 0.037,
		growthRate: 0.006,
	},
	{
		nationId: 'nat_volga_bulgaria',
		total: 500_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 8 },
			{ class: 'clergy', percentage: 0.02, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.06, influence: 5, wealth: 7 },
			{ class: 'artisans', percentage: 0.06, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.55, influence: 2, wealth: 2 },
			{ class: 'slaves', percentage: 0.078, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.041,
		deathRate: 0.036,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_croatia',
		total: 500_000,
		urbanRatio: 0.08,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 8, wealth: 9 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 7 },
			{ class: 'clergy', percentage: 0.02, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.03, influence: 3, wealth: 6 },
			{ class: 'artisans', percentage: 0.05, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.55, influence: 2, wealth: 2 },
			{ class: 'serfs', percentage: 0.3, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.008, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.04,
		deathRate: 0.036,
		growthRate: 0.004,
	},

	// ========================================================================
	// BYZANCE
	// ========================================================================
	{
		nationId: 'nat_byzantine',
		total: 12_000_000,
		urbanRatio: 0.15,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.04, influence: 7, wealth: 8 },
			{ class: 'merchants', percentage: 0.06, influence: 5, wealth: 7 },
			{ class: 'artisans', percentage: 0.08, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.45, influence: 2, wealth: 3 },
			{ class: 'serfs', percentage: 0.25, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.089, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.28,
		birthRate: 0.038,
		deathRate: 0.032,
		growthRate: 0.006,
	},

	// ========================================================================
	// MONDE ISLAMIQUE
	// ========================================================================
	{
		nationId: 'nat_fatimid',
		total: 12_000_000,
		urbanRatio: 0.18,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 7, wealth: 9 },
			{ class: 'clergy', percentage: 0.03, influence: 8, wealth: 8 },
			{ class: 'merchants', percentage: 0.07, influence: 5, wealth: 8 },
			{ class: 'artisans', percentage: 0.1, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.5, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'warriors', percentage: 0.079, influence: 6, wealth: 6 },
		],
		lifeExpectancy: 36,
		infantMortality: 0.26,
		birthRate: 0.04,
		deathRate: 0.032,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_buyid',
		total: 8_000_000,
		urbanRatio: 0.15,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 7, wealth: 9 },
			{ class: 'clergy', percentage: 0.03, influence: 8, wealth: 7 },
			{ class: 'warriors', percentage: 0.05, influence: 7, wealth: 7 },
			{ class: 'merchants', percentage: 0.06, influence: 5, wealth: 8 },
			{ class: 'artisans', percentage: 0.08, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.45, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.009, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.28,
		birthRate: 0.04,
		deathRate: 0.034,
		growthRate: 0.006,
	},
	{
		nationId: 'nat_ghaznavid',
		total: 10_000_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 7, wealth: 9 },
			{ class: 'warriors', percentage: 0.06, influence: 8, wealth: 7 },
			{ class: 'clergy', percentage: 0.03, influence: 6, wealth: 6 },
			{ class: 'merchants', percentage: 0.04, influence: 3, wealth: 6 },
			{ class: 'artisans', percentage: 0.06, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.5, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.12, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.059, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_karakhanid',
		total: 3_000_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 8 },
			{ class: 'warriors', percentage: 0.06, influence: 7, wealth: 6 },
			{ class: 'clergy', percentage: 0.02, influence: 5, wealth: 5 },
			{ class: 'merchants', percentage: 0.05, influence: 4, wealth: 7 },
			{ class: 'nomads', percentage: 0.4, influence: 3, wealth: 3 },
			{ class: 'free_peasants', percentage: 0.3, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.138, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.32,
		birthRate: 0.043,
		deathRate: 0.038,
		growthRate: 0.005,
	},

	// ========================================================================
	// ASIE ORIENTALE
	// ========================================================================
	{
		nationId: 'nat_song',
		total: 100_000_000,
		urbanRatio: 0.12,
		socialGroups: [
			{ class: 'royalty', percentage: 0.0001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.01, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.02, influence: 4, wealth: 5 },
			{ class: 'merchants', percentage: 0.05, influence: 5, wealth: 8 },
			{ class: 'artisans', percentage: 0.08, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.7, influence: 1, wealth: 2 },
			{ class: 'serfs', percentage: 0.1, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.0399, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.25,
		birthRate: 0.038,
		deathRate: 0.03,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_liao',
		total: 4_000_000,
		urbanRatio: 0.06,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 9 },
			{ class: 'warriors', percentage: 0.08, influence: 8, wealth: 7 },
			{ class: 'nomads', percentage: 0.4, influence: 4, wealth: 3 },
			{ class: 'free_peasants', percentage: 0.35, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.08, influence: 0, wealth: 0 },
			{ class: 'artisans', percentage: 0.058, influence: 2, wealth: 4 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.33,
		birthRate: 0.043,
		deathRate: 0.038,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_goryeo',
		total: 3_000_000,
		urbanRatio: 0.08,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 9, wealth: 9 },
			{ class: 'clergy', percentage: 0.03, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.04, influence: 3, wealth: 6 },
			{ class: 'artisans', percentage: 0.06, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.5, influence: 1, wealth: 2 },
			{ class: 'serfs', percentage: 0.25, influence: 0, wealth: 1 },
			{ class: 'slaves', percentage: 0.079, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.04,
		deathRate: 0.034,
		growthRate: 0.006,
	},
	{
		nationId: 'nat_japan',
		total: 7_000_000,
		urbanRatio: 0.08,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 6, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 10, wealth: 9 },
			{ class: 'clergy', percentage: 0.03, influence: 5, wealth: 6 },
			{ class: 'warriors', percentage: 0.04, influence: 7, wealth: 7 },
			{ class: 'merchants', percentage: 0.03, influence: 2, wealth: 5 },
			{ class: 'artisans', percentage: 0.05, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.6, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.05, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.109, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.038,
		deathRate: 0.032,
		growthRate: 0.006,
	},

	// ========================================================================
	// ASIE DU SUD-EST
	// ========================================================================
	{
		nationId: 'nat_dai_viet',
		total: 3_000_000,
		urbanRatio: 0.08,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.02, influence: 4, wealth: 5 },
			{ class: 'warriors', percentage: 0.04, influence: 6, wealth: 6 },
			{ class: 'merchants', percentage: 0.03, influence: 3, wealth: 6 },
			{ class: 'artisans', percentage: 0.05, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.7, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.029, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_khmer',
		total: 2_000_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.04, influence: 7, wealth: 7 },
			{ class: 'warriors', percentage: 0.04, influence: 6, wealth: 6 },
			{ class: 'merchants', percentage: 0.03, influence: 3, wealth: 6 },
			{ class: 'artisans', percentage: 0.06, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.6, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.099, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.034,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_srivijaya',
		total: 2_000_000,
		urbanRatio: 0.12,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 7, wealth: 8 },
			{ class: 'clergy', percentage: 0.03, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.08, influence: 6, wealth: 8 },
			{ class: 'artisans', percentage: 0.06, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.5, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'warriors', percentage: 0.208, influence: 5, wealth: 5 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.036,
		growthRate: 0.006,
	},

	// ========================================================================
	// ASIE DU SUD
	// ========================================================================
	{
		nationId: 'nat_chola',
		total: 15_000_000,
		urbanRatio: 0.12,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.04, influence: 7, wealth: 7 },
			{ class: 'merchants', percentage: 0.06, influence: 5, wealth: 8 },
			{ class: 'artisans', percentage: 0.08, influence: 3, wealth: 5 },
			{ class: 'warriors', percentage: 0.03, influence: 6, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.6, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.05, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.109, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.04,
		deathRate: 0.033,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_chalukya',
		total: 10_000_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.04, influence: 6, wealth: 7 },
			{ class: 'warriors', percentage: 0.04, influence: 7, wealth: 6 },
			{ class: 'merchants', percentage: 0.04, influence: 4, wealth: 7 },
			{ class: 'artisans', percentage: 0.06, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.6, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.05, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.139, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_pala',
		total: 12_000_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.02, influence: 7, wealth: 8 },
			{ class: 'clergy', percentage: 0.04, influence: 7, wealth: 7 },
			{ class: 'merchants', percentage: 0.04, influence: 4, wealth: 7 },
			{ class: 'artisans', percentage: 0.06, influence: 2, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.55, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.05, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.23, influence: 0, wealth: 1 },
			{ class: 'warriors', percentage: 0.009, influence: 5, wealth: 5 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.036,
		growthRate: 0.006,
	},

	// ========================================================================
	// AFRIQUE
	// ========================================================================
	{
		nationId: 'nat_ghana',
		total: 3_000_000,
		urbanRatio: 0.08,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 9 },
			{ class: 'warriors', percentage: 0.06, influence: 7, wealth: 6 },
			{ class: 'merchants', percentage: 0.05, influence: 5, wealth: 8 },
			{ class: 'artisans', percentage: 0.04, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.5, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.2, influence: 0, wealth: 0 },
			{ class: 'clergy', percentage: 0.019, influence: 3, wealth: 4 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.33,
		birthRate: 0.045,
		deathRate: 0.038,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_kanem',
		total: 1_500_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 8 },
			{ class: 'warriors', percentage: 0.06, influence: 7, wealth: 5 },
			{ class: 'clergy', percentage: 0.02, influence: 4, wealth: 5 },
			{ class: 'nomads', percentage: 0.3, influence: 3, wealth: 3 },
			{ class: 'free_peasants', percentage: 0.35, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.2, influence: 0, wealth: 0 },
			{ class: 'merchants', percentage: 0.038, influence: 3, wealth: 6 },
		],
		lifeExpectancy: 28,
		infantMortality: 0.35,
		birthRate: 0.047,
		deathRate: 0.042,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_ethiopia',
		total: 3_000_000,
		urbanRatio: 0.06,
		socialGroups: [
			{ class: 'royalty', percentage: 0.001, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.05, influence: 8, wealth: 7 },
			{ class: 'warriors', percentage: 0.04, influence: 6, wealth: 5 },
			{ class: 'merchants', percentage: 0.03, influence: 3, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.6, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'artisans', percentage: 0.049, influence: 2, wealth: 4 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.33,
		birthRate: 0.045,
		deathRate: 0.039,
		growthRate: 0.006,
	},
	{
		nationId: 'nat_swahili_cities',
		total: 500_000,
		urbanRatio: 0.3,
		socialGroups: [
			{ class: 'royalty', percentage: 0.003, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 8 },
			{ class: 'clergy', percentage: 0.03, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.12, influence: 8, wealth: 9 },
			{ class: 'artisans', percentage: 0.08, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.4, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.15, influence: 0, wealth: 0 },
			{ class: 'warriors', percentage: 0.187, influence: 5, wealth: 4 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.043,
		deathRate: 0.037,
		growthRate: 0.006,
	},

	// ========================================================================
	// AMÉRIQUES
	// ========================================================================
	{
		nationId: 'nat_toltec',
		total: 2_000_000,
		urbanRatio: 0.15,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.04, influence: 8, wealth: 7 },
			{ class: 'warriors', percentage: 0.08, influence: 7, wealth: 6 },
			{ class: 'merchants', percentage: 0.04, influence: 4, wealth: 6 },
			{ class: 'artisans', percentage: 0.06, influence: 3, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.55, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.098, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.3,
		birthRate: 0.043,
		deathRate: 0.036,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_maya_states',
		total: 2_000_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.05, influence: 8, wealth: 7 },
			{ class: 'warriors', percentage: 0.06, influence: 6, wealth: 5 },
			{ class: 'merchants', percentage: 0.04, influence: 4, wealth: 6 },
			{ class: 'artisans', percentage: 0.06, influence: 3, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.55, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.108, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_mississippian',
		total: 200_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.005, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 7 },
			{ class: 'clergy', percentage: 0.04, influence: 7, wealth: 6 },
			{ class: 'warriors', percentage: 0.06, influence: 6, wealth: 5 },
			{ class: 'artisans', percentage: 0.05, influence: 3, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.7, influence: 2, wealth: 2 },
			{ class: 'slaves', percentage: 0.115, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.044,
		deathRate: 0.036,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_wari',
		total: 1_500_000,
		urbanRatio: 0.12,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.03, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.04, influence: 7, wealth: 7 },
			{ class: 'warriors', percentage: 0.06, influence: 7, wealth: 6 },
			{ class: 'artisans', percentage: 0.06, influence: 3, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.55, influence: 1, wealth: 2 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'serfs', percentage: 0.158, influence: 0, wealth: 1 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.042,
		deathRate: 0.034,
		growthRate: 0.008,
	},

	// ========================================================================
	// ASIE CENTRALE
	// ========================================================================
	{
		nationId: 'nat_tibet',
		total: 2_000_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 7, wealth: 9 },
			{ class: 'nobility', percentage: 0.03, influence: 7, wealth: 8 },
			{ class: 'clergy', percentage: 0.1, influence: 10, wealth: 8 },
			{ class: 'warriors', percentage: 0.05, influence: 5, wealth: 5 },
			{ class: 'nomads', percentage: 0.35, influence: 3, wealth: 3 },
			{ class: 'free_peasants', percentage: 0.35, influence: 1, wealth: 2 },
			{ class: 'serfs', percentage: 0.1, influence: 0, wealth: 1 },
			{ class: 'merchants', percentage: 0.018, influence: 2, wealth: 5 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.33,
		birthRate: 0.04,
		deathRate: 0.037,
		growthRate: 0.003,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================
	{
		nationId: 'nat_puebloans',
		total: 30_000,
		urbanRatio: 0.3, // Chaco Canyon = proto-urbain
		socialGroups: [
			{ class: 'clergy', percentage: 0.05, influence: 9, wealth: 6 },
			{ class: 'artisans', percentage: 0.1, influence: 4, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.8, influence: 2, wealth: 3 },
			{ class: 'merchants', percentage: 0.05, influence: 3, wealth: 5 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.28,
		birthRate: 0.04,
		deathRate: 0.035,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_haida',
		total: 15_000,
		urbanRatio: 0.2,
		socialGroups: [
			{ class: 'nobility', percentage: 0.05, influence: 9, wealth: 8 },
			{ class: 'free_peasants', percentage: 0.6, influence: 3, wealth: 4 },
			{ class: 'slaves', percentage: 0.15, influence: 0, wealth: 0 },
			{ class: 'artisans', percentage: 0.15, influence: 5, wealth: 5 },
			{ class: 'merchants', percentage: 0.05, influence: 4, wealth: 6 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.25,
		birthRate: 0.038,
		deathRate: 0.032,
		growthRate: 0.006,
	},
	{
		nationId: 'nat_thule',
		total: 5_000,
		urbanRatio: 0.0,
		socialGroups: [
			{ class: 'free_peasants', percentage: 0.9, influence: 3, wealth: 2 },
			{ class: 'clergy', percentage: 0.05, influence: 7, wealth: 3 },
			{ class: 'warriors', percentage: 0.05, influence: 5, wealth: 3 },
		],
		lifeExpectancy: 28,
		infantMortality: 0.35,
		birthRate: 0.04,
		deathRate: 0.038,
		growthRate: 0.002,
	},
	{
		nationId: 'nat_tui_tonga',
		total: 40_000,
		urbanRatio: 0.15,
		socialGroups: [
			{ class: 'royalty', percentage: 0.005, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.05, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.05, influence: 7, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.75, influence: 2, wealth: 3 },
			{ class: 'artisans', percentage: 0.1, influence: 3, wealth: 4 },
			{ class: 'slaves', percentage: 0.045, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.25,
		birthRate: 0.04,
		deathRate: 0.03,
		growthRate: 0.01,
	},
	{
		nationId: 'nat_aboriginal',
		total: 300_000,
		urbanRatio: 0.0,
		socialGroups: [
			{ class: 'free_peasants', percentage: 0.85, influence: 3, wealth: 2 },
			{ class: 'clergy', percentage: 0.1, influence: 8, wealth: 3 },
			{ class: 'warriors', percentage: 0.05, influence: 5, wealth: 2 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.25,
		birthRate: 0.035,
		deathRate: 0.032,
		growthRate: 0.003,
	},
	{
		nationId: 'nat_sami',
		total: 20_000,
		urbanRatio: 0.0,
		socialGroups: [
			{ class: 'nomads', percentage: 0.7, influence: 3, wealth: 3 },
			{ class: 'clergy', percentage: 0.05, influence: 7, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.15, influence: 2, wealth: 2 },
			{ class: 'merchants', percentage: 0.1, influence: 4, wealth: 5 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.3,
		birthRate: 0.04,
		deathRate: 0.036,
		growthRate: 0.004,
	},
	{
		nationId: 'nat_mapuche',
		total: 500_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'warriors', percentage: 0.15, influence: 7, wealth: 5 },
			{ class: 'clergy', percentage: 0.05, influence: 6, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.7, influence: 3, wealth: 3 },
			{ class: 'artisans', percentage: 0.05, influence: 3, wealth: 4 },
			{ class: 'merchants', percentage: 0.05, influence: 3, wealth: 4 },
		],
		lifeExpectancy: 34,
		infantMortality: 0.27,
		birthRate: 0.04,
		deathRate: 0.033,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_malagasy',
		total: 200_000,
		urbanRatio: 0.08,
		socialGroups: [
			{ class: 'royalty', percentage: 0.003, influence: 8, wealth: 8 },
			{ class: 'nobility', percentage: 0.04, influence: 7, wealth: 7 },
			{ class: 'free_peasants', percentage: 0.7, influence: 2, wealth: 3 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'merchants', percentage: 0.07, influence: 4, wealth: 6 },
			{ class: 'artisans', percentage: 0.087, influence: 3, wealth: 4 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_yoruba',
		total: 500_000,
		urbanRatio: 0.25, // Ifè est une grande cité
		socialGroups: [
			{ class: 'royalty', percentage: 0.003, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.04, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.06, influence: 9, wealth: 7 },
			{ class: 'artisans', percentage: 0.12, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.08, influence: 5, wealth: 7 },
			{ class: 'free_peasants', percentage: 0.55, influence: 2, wealth: 3 },
			{ class: 'slaves', percentage: 0.1, influence: 0, wealth: 0 },
			{ class: 'warriors', percentage: 0.047, influence: 6, wealth: 5 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.043,
		deathRate: 0.035,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_zimbabwe',
		total: 200_000,
		urbanRatio: 0.12,
		socialGroups: [
			{ class: 'royalty', percentage: 0.003, influence: 9, wealth: 10 },
			{ class: 'nobility', percentage: 0.04, influence: 7, wealth: 8 },
			{ class: 'clergy', percentage: 0.04, influence: 6, wealth: 5 },
			{ class: 'warriors', percentage: 0.08, influence: 6, wealth: 5 },
			{ class: 'artisans', percentage: 0.1, influence: 4, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.6, influence: 2, wealth: 3 },
			{ class: 'merchants', percentage: 0.08, influence: 5, wealth: 7 },
			{ class: 'slaves', percentage: 0.057, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.29,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 2
	// ========================================================================
	{
		nationId: 'nat_chimu',
		total: 500_000,
		urbanRatio: 0.35,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.05, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.05, influence: 7, wealth: 6 },
			{ class: 'artisans', percentage: 0.15, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.05, influence: 4, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.55, influence: 2, wealth: 3 },
			{ class: 'slaves', percentage: 0.098, influence: 0, wealth: 0 },
			{ class: 'warriors', percentage: 0.05, influence: 6, wealth: 5 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.25,
		birthRate: 0.04,
		deathRate: 0.032,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_muisca',
		total: 300_000,
		urbanRatio: 0.15,
		socialGroups: [
			{ class: 'royalty', percentage: 0.003, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.04, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.06, influence: 8, wealth: 6 },
			{ class: 'artisans', percentage: 0.1, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.08, influence: 5, wealth: 7 },
			{ class: 'free_peasants', percentage: 0.65, influence: 2, wealth: 3 },
			{ class: 'slaves', percentage: 0.007, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 34,
		infantMortality: 0.26,
		birthRate: 0.042,
		deathRate: 0.034,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_guarani',
		total: 400_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'warriors', percentage: 0.15, influence: 7, wealth: 4 },
			{ class: 'clergy', percentage: 0.05, influence: 8, wealth: 3 },
			{ class: 'free_peasants', percentage: 0.78, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.02, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.28,
		birthRate: 0.044,
		deathRate: 0.036,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_hawaii',
		total: 100_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.005, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.08, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.06, influence: 9, wealth: 6 },
			{ class: 'free_peasants', percentage: 0.75, influence: 2, wealth: 3 },
			{ class: 'slaves', percentage: 0.105, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.24,
		birthRate: 0.04,
		deathRate: 0.032,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_ainu',
		total: 50_000,
		urbanRatio: 0.02,
		socialGroups: [
			{ class: 'nobility', percentage: 0.05, influence: 7, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.93, influence: 4, wealth: 3 },
			{ class: 'slaves', percentage: 0.02, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.27,
		birthRate: 0.04,
		deathRate: 0.035,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_makuria',
		total: 300_000,
		urbanRatio: 0.15,
		socialGroups: [
			{ class: 'royalty', percentage: 0.003, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.05, influence: 8, wealth: 8 },
			{ class: 'clergy', percentage: 0.08, influence: 9, wealth: 7 },
			{ class: 'warriors', percentage: 0.06, influence: 7, wealth: 5 },
			{ class: 'artisans', percentage: 0.08, influence: 4, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.6, influence: 2, wealth: 3 },
			{ class: 'merchants', percentage: 0.04, influence: 5, wealth: 6 },
			{ class: 'slaves', percentage: 0.087, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.27,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_tuareg',
		total: 200_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'nobility', percentage: 0.1, influence: 9, wealth: 8 },
			{ class: 'warriors', percentage: 0.15, influence: 7, wealth: 6 },
			{ class: 'clergy', percentage: 0.05, influence: 6, wealth: 4 },
			{ class: 'artisans', percentage: 0.1, influence: 3, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.35, influence: 2, wealth: 2 },
			{ class: 'slaves', percentage: 0.25, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.037,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_georgia',
		total: 1_000_000,
		urbanRatio: 0.15,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.06, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.07, influence: 8, wealth: 7 },
			{ class: 'warriors', percentage: 0.06, influence: 7, wealth: 6 },
			{ class: 'artisans', percentage: 0.08, influence: 4, wealth: 5 },
			{ class: 'merchants', percentage: 0.05, influence: 5, wealth: 7 },
			{ class: 'free_peasants', percentage: 0.55, influence: 2, wealth: 3 },
			{ class: 'serfs', percentage: 0.128, influence: 1, wealth: 1 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.25,
		birthRate: 0.04,
		deathRate: 0.033,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_armenia',
		total: 1_200_000,
		urbanRatio: 0.2,
		socialGroups: [
			{ class: 'royalty', percentage: 0.002, influence: 10, wealth: 10 },
			{ class: 'nobility', percentage: 0.06, influence: 8, wealth: 9 },
			{ class: 'clergy', percentage: 0.08, influence: 9, wealth: 8 },
			{ class: 'warriors', percentage: 0.06, influence: 7, wealth: 6 },
			{ class: 'artisans', percentage: 0.1, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.08, influence: 6, wealth: 8 },
			{ class: 'free_peasants', percentage: 0.5, influence: 2, wealth: 3 },
			{ class: 'serfs', percentage: 0.118, influence: 1, wealth: 1 },
		],
		lifeExpectancy: 36,
		infantMortality: 0.24,
		birthRate: 0.039,
		deathRate: 0.032,
		growthRate: 0.007,
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 3
	// ========================================================================
	{
		nationId: 'nat_hohokam',
		total: 40_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'nobility', percentage: 0.05, influence: 7, wealth: 5 },
			{ class: 'clergy', percentage: 0.05, influence: 6, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.88, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.02, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.28,
		birthRate: 0.042,
		deathRate: 0.036,
		growthRate: 0.006,
	},
	{
		nationId: 'nat_dorset',
		total: 5_000,
		urbanRatio: 0,
		socialGroups: [
			{ class: 'free_peasants', percentage: 0.95, influence: 5, wealth: 2 },
			{ class: 'clergy', percentage: 0.05, influence: 6, wealth: 2 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.32,
		birthRate: 0.04,
		deathRate: 0.038,
		growthRate: 0.002,
	},
	{
		nationId: 'nat_beothuk',
		total: 5_000,
		urbanRatio: 0,
		socialGroups: [
			{ class: 'free_peasants', percentage: 0.95, influence: 5, wealth: 2 },
			{ class: 'clergy', percentage: 0.05, influence: 5, wealth: 2 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.31,
		birthRate: 0.04,
		deathRate: 0.037,
		growthRate: 0.003,
	},
	{
		nationId: 'nat_dene',
		total: 50_000,
		urbanRatio: 0,
		socialGroups: [
			{ class: 'nobility', percentage: 0.03, influence: 6, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.95, influence: 4, wealth: 2 },
			{ class: 'slaves', percentage: 0.02, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 31,
		infantMortality: 0.3,
		birthRate: 0.042,
		deathRate: 0.037,
		growthRate: 0.005,
	},
	{
		nationId: 'nat_mikmaq',
		total: 30_000,
		urbanRatio: 0.02,
		socialGroups: [
			{ class: 'nobility', percentage: 0.05, influence: 7, wealth: 5 },
			{ class: 'warriors', percentage: 0.1, influence: 6, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.84, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.01, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.28,
		birthRate: 0.042,
		deathRate: 0.035,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_papuan',
		total: 500_000,
		urbanRatio: 0,
		socialGroups: [
			{ class: 'warriors', percentage: 0.2, influence: 7, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.77, influence: 3, wealth: 3 },
			{ class: 'clergy', percentage: 0.03, influence: 6, wealth: 3 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.32,
		birthRate: 0.045,
		deathRate: 0.038,
		growthRate: 0.007,
	},
	{
		nationId: 'nat_fiji',
		total: 50_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'royalty', percentage: 0.005, influence: 10, wealth: 8 },
			{ class: 'nobility', percentage: 0.05, influence: 7, wealth: 6 },
			{ class: 'warriors', percentage: 0.15, influence: 6, wealth: 5 },
			{ class: 'free_peasants', percentage: 0.75, influence: 2, wealth: 3 },
			{ class: 'slaves', percentage: 0.045, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 32,
		infantMortality: 0.28,
		birthRate: 0.043,
		deathRate: 0.035,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_chamorro',
		total: 40_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'nobility', percentage: 0.1, influence: 9, wealth: 7 },
			{ class: 'free_peasants', percentage: 0.7, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.2, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.26,
		birthRate: 0.042,
		deathRate: 0.034,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_guanche',
		total: 80_000,
		urbanRatio: 0.05,
		socialGroups: [
			{ class: 'royalty', percentage: 0.005, influence: 9, wealth: 7 },
			{ class: 'nobility', percentage: 0.06, influence: 7, wealth: 6 },
			{ class: 'clergy', percentage: 0.04, influence: 6, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.85, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.045, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.27,
		birthRate: 0.041,
		deathRate: 0.035,
		growthRate: 0.006,
	},
	{
		nationId: 'nat_san',
		total: 50_000,
		urbanRatio: 0,
		socialGroups: [
			{ class: 'free_peasants', percentage: 1.0, influence: 5, wealth: 2 },
		],
		lifeExpectancy: 35,
		infantMortality: 0.25,
		birthRate: 0.035,
		deathRate: 0.032,
		growthRate: 0.003,
	},
	{
		nationId: 'nat_mbuti',
		total: 40_000,
		urbanRatio: 0,
		socialGroups: [
			{ class: 'free_peasants', percentage: 1.0, influence: 5, wealth: 2 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.28,
		birthRate: 0.038,
		deathRate: 0.035,
		growthRate: 0.003,
	},
	{
		nationId: 'nat_igbo',
		total: 300_000,
		urbanRatio: 0.1,
		socialGroups: [
			{ class: 'royalty', percentage: 0.003, influence: 8, wealth: 9 },
			{ class: 'nobility', percentage: 0.05, influence: 7, wealth: 7 },
			{ class: 'clergy', percentage: 0.06, influence: 8, wealth: 6 },
			{ class: 'artisans', percentage: 0.12, influence: 5, wealth: 6 },
			{ class: 'merchants', percentage: 0.08, influence: 5, wealth: 7 },
			{ class: 'free_peasants', percentage: 0.55, influence: 3, wealth: 3 },
			{ class: 'slaves', percentage: 0.137, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 33,
		infantMortality: 0.27,
		birthRate: 0.043,
		deathRate: 0.035,
		growthRate: 0.008,
	},
	{
		nationId: 'nat_chukchi',
		total: 15_000,
		urbanRatio: 0,
		socialGroups: [
			{ class: 'nobility', percentage: 0.05, influence: 6, wealth: 5 },
			{ class: 'warriors', percentage: 0.15, influence: 6, wealth: 4 },
			{ class: 'free_peasants', percentage: 0.78, influence: 4, wealth: 3 },
			{ class: 'slaves', percentage: 0.02, influence: 0, wealth: 0 },
		],
		lifeExpectancy: 30,
		infantMortality: 0.32,
		birthRate: 0.042,
		deathRate: 0.039,
		growthRate: 0.003,
	},
]
