import type { Religion } from '../../../shared/src/types/world'

// ============================================================================
// Religions du monde — An 1000
// ============================================================================

export const religions: Religion[] = [
	// --- Christianisme ---
	{
		id: 'rel_catholic',
		name: 'Catholicisme romain',
		family: 'christianity',
		holyCity: 'set_rome',
		organizationLevel: 9,
		proselytism: 7,
		politicalInfluence: 9,
		practices: [
			'pilgrimage',
			'monasticism',
			'sacraments',
			'papacy',
			'tithe',
			'holy_war',
		],
	},
	{
		id: 'rel_orthodox',
		name: 'Christianisme orthodoxe',
		family: 'christianity',
		holyCity: 'set_constantinople',
		organizationLevel: 8,
		proselytism: 5,
		politicalInfluence: 8,
		practices: [
			'monasticism',
			'icon_veneration',
			'liturgy',
			'patriarchate',
			'sacraments',
		],
	},
	{
		id: 'rel_coptic',
		name: 'Christianisme copte',
		family: 'christianity',
		holyCity: 'set_alexandria',
		organizationLevel: 6,
		proselytism: 3,
		politicalInfluence: 4,
		practices: ['monasticism', 'fasting', 'sacraments', 'pilgrimage'],
	},
	{
		id: 'rel_ethiopian_christian',
		name: 'Christianisme éthiopien',
		family: 'christianity',
		holyCity: 'set_axum',
		organizationLevel: 6,
		proselytism: 2,
		politicalInfluence: 7,
		practices: [
			'monasticism',
			'fasting',
			'ark_veneration',
			'pilgrimage',
			'sacraments',
		],
	},
	{
		id: 'rel_nestorian',
		name: 'Christianisme nestorien',
		family: 'christianity',
		holyCity: null,
		organizationLevel: 5,
		proselytism: 4,
		politicalInfluence: 3,
		practices: ['monasticism', 'missionary_work', 'sacraments'],
	},

	// --- Islam ---
	{
		id: 'rel_sunni',
		name: 'Islam sunnite',
		family: 'islam',
		holyCity: 'set_mecca',
		organizationLevel: 7,
		proselytism: 8,
		politicalInfluence: 9,
		practices: [
			'five_pillars',
			'pilgrimage',
			'sharia',
			'jihad',
			'mosque_building',
			'zakat',
		],
	},
	{
		id: 'rel_shia',
		name: 'Islam chiite',
		family: 'islam',
		holyCity: 'set_karbala',
		organizationLevel: 7,
		proselytism: 5,
		politicalInfluence: 8,
		practices: [
			'five_pillars',
			'imam_veneration',
			'pilgrimage',
			'ashura',
			'sharia',
		],
	},
	{
		id: 'rel_ismaili',
		name: 'Islam ismaélien',
		family: 'islam',
		holyCity: 'set_cairo',
		organizationLevel: 8,
		proselytism: 6,
		politicalInfluence: 8,
		practices: [
			'imamate',
			'esoteric_knowledge',
			'missionary_work',
			'five_pillars',
		],
	},
	{
		id: 'rel_ibadi',
		name: 'Islam ibadite',
		family: 'islam',
		holyCity: null,
		organizationLevel: 5,
		proselytism: 2,
		politicalInfluence: 4,
		practices: ['five_pillars', 'shura', 'austere_living'],
	},

	// --- Bouddhisme ---
	{
		id: 'rel_theravada',
		name: 'Bouddhisme Theravada',
		family: 'buddhism',
		holyCity: null,
		organizationLevel: 6,
		proselytism: 3,
		politicalInfluence: 7,
		practices: [
			'monasticism',
			'meditation',
			'alms_giving',
			'temple_building',
			'scripture_study',
		],
	},
	{
		id: 'rel_mahayana',
		name: 'Bouddhisme Mahayana',
		family: 'buddhism',
		holyCity: null,
		organizationLevel: 5,
		proselytism: 4,
		politicalInfluence: 6,
		practices: [
			'monasticism',
			'meditation',
			'bodhisattva_veneration',
			'temple_building',
			'scripture_study',
		],
	},
	{
		id: 'rel_vajrayana',
		name: 'Bouddhisme Vajrayana (tibétain)',
		family: 'buddhism',
		holyCity: 'set_lhasa',
		organizationLevel: 7,
		proselytism: 2,
		politicalInfluence: 8,
		practices: [
			'monasticism',
			'tantra',
			'meditation',
			'mandala',
			'reincarnation_lineage',
		],
	},

	// --- Hindouisme ---
	{
		id: 'rel_hinduism_shaivism',
		name: 'Hindouisme Shaivite',
		family: 'hinduism',
		holyCity: 'set_varanasi',
		organizationLevel: 4,
		proselytism: 2,
		politicalInfluence: 7,
		practices: [
			'temple_worship',
			'pilgrimage',
			'caste_system',
			'festivals',
			'yoga',
			'fire_ritual',
		],
	},
	{
		id: 'rel_hinduism_vaishnavism',
		name: 'Hindouisme Vishnouiste',
		family: 'hinduism',
		holyCity: 'set_varanasi',
		organizationLevel: 4,
		proselytism: 2,
		politicalInfluence: 7,
		practices: [
			'temple_worship',
			'pilgrimage',
			'bhakti',
			'caste_system',
			'festivals',
			'vegetarianism',
		],
	},

	// --- Autres religions organisées ---
	{
		id: 'rel_judaism',
		name: 'Judaïsme',
		family: 'judaism',
		holyCity: 'set_jerusalem',
		organizationLevel: 6,
		proselytism: 1,
		politicalInfluence: 3,
		practices: [
			'sabbath',
			'synagogue_worship',
			'dietary_laws',
			'scripture_study',
			'circumcision',
		],
	},
	{
		id: 'rel_zoroastrianism',
		name: 'Zoroastrisme',
		family: 'zoroastrianism',
		holyCity: null,
		organizationLevel: 5,
		proselytism: 1,
		politicalInfluence: 2,
		practices: ['fire_veneration', 'purity_rituals', 'sky_burial', 'festivals'],
	},
	{
		id: 'rel_taoism',
		name: 'Taoïsme',
		family: 'taoism',
		holyCity: null,
		organizationLevel: 4,
		proselytism: 1,
		politicalInfluence: 5,
		practices: [
			'meditation',
			'alchemy',
			'divination',
			'temple_worship',
			'festivals',
		],
	},
	{
		id: 'rel_confucianism',
		name: 'Confucianisme',
		family: 'confucianism',
		holyCity: 'set_qufu',
		organizationLevel: 6,
		proselytism: 2,
		politicalInfluence: 9,
		practices: [
			'ancestor_veneration',
			'civil_examination',
			'filial_piety',
			'ritual_propriety',
			'scholarship',
		],
	},
	{
		id: 'rel_shinto',
		name: 'Shintō',
		family: 'shintoism',
		holyCity: 'set_ise',
		organizationLevel: 4,
		proselytism: 1,
		politicalInfluence: 6,
		practices: [
			'kami_veneration',
			'shrine_worship',
			'purification',
			'festivals',
			'nature_reverence',
		],
	},
	{
		id: 'rel_jainism',
		name: 'Jaïnisme',
		family: 'other',
		holyCity: null,
		organizationLevel: 4,
		proselytism: 1,
		politicalInfluence: 3,
		practices: [
			'non_violence',
			'asceticism',
			'vegetarianism',
			'meditation',
			'temple_worship',
		],
	},

	// --- Religions traditionnelles / animistes ---
	{
		id: 'rel_tengriism',
		name: 'Tengrisme',
		family: 'tengriism',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 6,
		practices: [
			'sky_worship',
			'shamanism',
			'ancestor_veneration',
			'horse_sacrifice',
			'nature_reverence',
		],
	},
	{
		id: 'rel_norse_paganism',
		name: 'Paganisme nordique',
		family: 'norse_paganism',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 5,
		practices: [
			'blot_sacrifice',
			'rune_divination',
			'ancestor_veneration',
			'feast_rituals',
			'nature_reverence',
		],
	},
	{
		id: 'rel_slavic_paganism',
		name: 'Paganisme slave',
		family: 'slavic_paganism',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 4,
		practices: [
			'nature_worship',
			'ancestor_veneration',
			'seasonal_festivals',
			'divination',
			'sacrifice',
		],
	},
	{
		id: 'rel_west_african_traditional',
		name: 'Religions traditionnelles ouest-africaines',
		family: 'traditional_african',
		holyCity: null,
		organizationLevel: 3,
		proselytism: 1,
		politicalInfluence: 6,
		practices: [
			'ancestor_veneration',
			'spirit_worship',
			'divination',
			'oral_tradition',
			'masquerade',
			'sacrifice',
		],
	},
	{
		id: 'rel_east_african_traditional',
		name: 'Religions traditionnelles est-africaines',
		family: 'traditional_african',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 5,
		practices: [
			'ancestor_veneration',
			'rain_making',
			'divination',
			'spirit_mediums',
		],
	},
	{
		id: 'rel_mesoamerican',
		name: 'Religion mésoaméricaine',
		family: 'mesoamerican',
		holyCity: null,
		organizationLevel: 7,
		proselytism: 3,
		politicalInfluence: 9,
		practices: [
			'human_sacrifice',
			'blood_offering',
			'calendar_rituals',
			'temple_pyramid_building',
			'astronomy',
			'ball_game',
		],
	},
	{
		id: 'rel_andean_traditional',
		name: 'Religion andine traditionnelle',
		family: 'other',
		holyCity: null,
		organizationLevel: 5,
		proselytism: 2,
		politicalInfluence: 7,
		practices: [
			'sun_worship',
			'ancestor_veneration',
			'mountain_worship',
			'sacrifice',
			'divination',
		],
	},
	{
		id: 'rel_polynesian',
		name: 'Religion polynésienne',
		family: 'polynesian',
		holyCity: null,
		organizationLevel: 4,
		proselytism: 1,
		politicalInfluence: 7,
		practices: [
			'mana_belief',
			'tapu_system',
			'ancestor_veneration',
			'navigation_rituals',
			'oral_tradition',
		],
	},
	{
		id: 'rel_australian_aboriginal',
		name: 'Spiritualité aborigène (Temps du Rêve)',
		family: 'other',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 8,
		practices: [
			'dreamtime',
			'songlines',
			'land_connection',
			'initiation_rites',
			'oral_tradition',
			'rock_art',
		],
	},
	{
		id: 'rel_north_american_traditional',
		name: 'Religions traditionnelles nord-américaines',
		family: 'other',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 6,
		practices: [
			'vision_quest',
			'sweat_lodge',
			'sun_dance',
			'ancestor_spirits',
			'nature_reverence',
			'oral_tradition',
		],
	},
	{
		id: 'rel_sami_shamanism',
		name: 'Chamanisme sami (noaidi)',
		family: 'other',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 7,
		practices: [
			'drum_divination',
			'spirit_journey',
			'animal_totems',
			'nature_worship',
			'ancestor_veneration',
			'sacred_landscapes',
			'oral_tradition',
		],
	},
	{
		id: 'rel_mapuche_traditional',
		name: 'Religion mapuche (Ngenechen)',
		family: 'other',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 8,
		practices: [
			'machitun_healing',
			'ngillatun_ceremony',
			'ancestor_spirits',
			'pillan_volcano_worship',
			'machi_shamanism',
			'oral_tradition',
		],
	},
	{
		id: 'rel_malagasy_traditional',
		name: 'Religion malgache (Razana)',
		family: 'other',
		holyCity: null,
		organizationLevel: 3,
		proselytism: 1,
		politicalInfluence: 8,
		practices: [
			'ancestor_worship',
			'famadihana_reburial',
			'fady_taboo',
			'divination',
			'sacred_forests',
			'oral_tradition',
		],
	},

	// --- Peuples Tier 2 & 3 (ajouts) ---
	{
		id: 'rel_ainu_kamuy',
		name: 'Spiritualité aïnoue (Kamuy)',
		family: 'other',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 7,
		practices: [
			'kamuy_worship',
			'bear_ceremony',
			'nature_reverence',
			'ancestor_veneration',
			'oral_tradition',
			'fire_goddess_worship',
		],
	},
	{
		id: 'rel_armenian_apostolic',
		name: 'Église apostolique arménienne',
		family: 'christianity',
		holyCity: 'set_ani',
		organizationLevel: 7,
		proselytism: 2,
		politicalInfluence: 9,
		practices: [
			'monasticism',
			'liturgy',
			'sacraments',
			'pilgrimage',
			'fasting',
			'khachkar_cross_stones',
		],
	},
	{
		id: 'rel_muisca_traditional',
		name: 'Religion muisca (Sué et Chía)',
		family: 'other',
		holyCity: null,
		organizationLevel: 4,
		proselytism: 1,
		politicalInfluence: 8,
		practices: [
			'sun_moon_worship',
			'gold_offerings',
			'lake_rituals',
			'pilgrimage',
			'sacrifice',
			'oral_tradition',
		],
	},
	{
		id: 'rel_guarani_traditional',
		name: 'Spiritualité guaraní (Terre sans Mal)',
		family: 'other',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 6,
		practices: [
			'shamanism',
			'land_without_evil_quest',
			'nature_spirits',
			'ancestor_veneration',
			'oral_tradition',
			'ritual_dance',
		],
	},
	{
		id: 'rel_papuan_traditional',
		name: 'Religions papoues traditionnelles',
		family: 'other',
		holyCity: null,
		organizationLevel: 1,
		proselytism: 1,
		politicalInfluence: 7,
		practices: [
			'ancestor_spirits',
			'spirit_houses',
			'initiation_rites',
			'divination',
			'nature_reverence',
			'oral_tradition',
		],
	},
	{
		id: 'rel_guanche_traditional',
		name: 'Religion guanche (Achamán)',
		family: 'other',
		holyCity: null,
		organizationLevel: 3,
		proselytism: 1,
		politicalInfluence: 7,
		practices: [
			'sun_worship',
			'mountain_worship',
			'ancestor_veneration',
			'mummification',
			'oracle_consultation',
			'oral_tradition',
		],
	},
	{
		id: 'rel_san_traditional',
		name: 'Spiritualité San (trance healing)',
		family: 'other',
		holyCity: null,
		organizationLevel: 1,
		proselytism: 1,
		politicalInfluence: 8,
		practices: [
			'trance_dance',
			'rock_art',
			'rain_making',
			'spirit_world',
			'healing_rituals',
			'oral_tradition',
		],
	},
	{
		id: 'rel_central_african_traditional',
		name: 'Religions traditionnelles de la forêt équatoriale',
		family: 'traditional_african',
		holyCity: null,
		organizationLevel: 1,
		proselytism: 1,
		politicalInfluence: 6,
		practices: [
			'forest_spirit_worship',
			'ancestor_veneration',
			'hunting_rituals',
			'music_ceremony',
			'oral_tradition',
			'nature_reverence',
		],
	},
	{
		id: 'rel_siberian_shamanism',
		name: 'Chamanisme sibérien',
		family: 'other',
		holyCity: null,
		organizationLevel: 2,
		proselytism: 1,
		politicalInfluence: 7,
		practices: [
			'shamanic_journey',
			'drum_divination',
			'animal_spirits',
			'ancestor_veneration',
			'nature_worship',
			'oral_tradition',
		],
	},
]
