import type { Settlement } from '../../../shared/src/types/world'

// ============================================================================
// Établissements (villes majeures) — An 1000
// ============================================================================
// population : estimation approximative
// defenseLevel / wealthLevel : 0-10
// ============================================================================

export const settlements: Settlement[] = [
	// --- Europe occidentale ---
	{
		id: 'set_aachen',
		name: 'Aix-la-Chapelle',
		type: 'capital',
		coord: { lat: 50.78, lng: 6.08 },
		tileId: '',
		nationId: 'nat_hre',
		population: 10_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['religious_center', 'administrative'],
	},
	{
		id: 'set_paris',
		name: 'Paris',
		type: 'capital',
		coord: { lat: 48.86, lng: 2.35 },
		tileId: '',
		nationId: 'nat_france',
		population: 20_000,
		defenseLevel: 6,
		wealthLevel: 6,
		specializations: ['trade', 'religious_center'],
	},
	{
		id: 'set_london',
		name: 'Londres',
		type: 'capital',
		coord: { lat: 51.51, lng: -0.13 },
		tileId: '',
		nationId: 'nat_england',
		population: 15_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['trade', 'port'],
	},
	{
		id: 'set_rome',
		name: 'Rome',
		type: 'capital',
		coord: { lat: 41.9, lng: 12.5 },
		tileId: '',
		nationId: 'nat_papal',
		population: 35_000,
		defenseLevel: 5,
		wealthLevel: 8,
		specializations: ['religious_center', 'academic'],
	},
	{
		id: 'set_venice',
		name: 'Venise',
		type: 'capital',
		coord: { lat: 45.44, lng: 12.34 },
		tileId: '',
		nationId: 'nat_venice',
		population: 50_000,
		defenseLevel: 7,
		wealthLevel: 9,
		specializations: ['trade', 'port', 'naval'],
	},
	{
		id: 'set_scone',
		name: 'Scone',
		type: 'capital',
		coord: { lat: 56.42, lng: -3.43 },
		tileId: '',
		nationId: 'nat_scotland',
		population: 3_000,
		defenseLevel: 4,
		wealthLevel: 3,
		specializations: ['religious_center'],
	},

	// --- Péninsule ibérique ---
	{
		id: 'set_leon',
		name: 'León',
		type: 'capital',
		coord: { lat: 42.6, lng: -5.57 },
		tileId: '',
		nationId: 'nat_leon',
		population: 8_000,
		defenseLevel: 6,
		wealthLevel: 5,
		specializations: ['military', 'religious_center'],
	},
	{
		id: 'set_pamplona',
		name: 'Pampelune',
		type: 'capital',
		coord: { lat: 42.81, lng: -1.65 },
		tileId: '',
		nationId: 'nat_navarre',
		population: 5_000,
		defenseLevel: 6,
		wealthLevel: 4,
		specializations: ['military'],
	},
	{
		id: 'set_cordoba',
		name: 'Cordoue',
		type: 'capital',
		coord: { lat: 37.88, lng: -4.78 },
		tileId: '',
		nationId: 'nat_cordoba',
		population: 400_000, // plus grande ville d'Europe occidentale
		defenseLevel: 8,
		wealthLevel: 10,
		specializations: ['trade', 'academic', 'religious_center', 'manufacturing'],
	},

	// --- Scandinavie ---
	{
		id: 'set_roskilde',
		name: 'Roskilde',
		type: 'capital',
		coord: { lat: 55.64, lng: 12.08 },
		tileId: '',
		nationId: 'nat_denmark',
		population: 5_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['trade', 'port'],
	},
	{
		id: 'set_nidaros',
		name: 'Nidaros (Trondheim)',
		type: 'capital',
		coord: { lat: 63.43, lng: 10.39 },
		tileId: '',
		nationId: 'nat_norway',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['port', 'religious_center'],
	},
	{
		id: 'set_sigtuna',
		name: 'Sigtuna',
		type: 'capital',
		coord: { lat: 59.62, lng: 17.72 },
		tileId: '',
		nationId: 'nat_sweden',
		population: 4_000,
		defenseLevel: 3,
		wealthLevel: 4,
		specializations: ['trade', 'religious_center'],
	},

	// --- Europe orientale ---
	{
		id: 'set_gniezno',
		name: 'Gniezno',
		type: 'capital',
		coord: { lat: 52.53, lng: 17.6 },
		tileId: '',
		nationId: 'nat_poland',
		population: 5_000,
		defenseLevel: 5,
		wealthLevel: 4,
		specializations: ['religious_center'],
	},
	{
		id: 'set_esztergom',
		name: 'Esztergom',
		type: 'capital',
		coord: { lat: 47.79, lng: 18.74 },
		tileId: '',
		nationId: 'nat_hungary',
		population: 8_000,
		defenseLevel: 6,
		wealthLevel: 5,
		specializations: ['religious_center', 'administrative'],
	},
	{
		id: 'set_kiev',
		name: 'Kiev',
		type: 'capital',
		coord: { lat: 50.45, lng: 30.52 },
		tileId: '',
		nationId: 'nat_kievan_rus',
		population: 50_000,
		defenseLevel: 7,
		wealthLevel: 7,
		specializations: ['trade', 'religious_center', 'academic'],
	},
	{
		id: 'set_bulgar',
		name: 'Bulgar',
		type: 'capital',
		coord: { lat: 54.95, lng: 49.05 },
		tileId: '',
		nationId: 'nat_volga_bulgaria',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['trade'],
	},
	{
		id: 'set_biograd',
		name: 'Biograd na Moru',
		type: 'capital',
		coord: { lat: 43.94, lng: 15.44 },
		tileId: '',
		nationId: 'nat_croatia',
		population: 4_000,
		defenseLevel: 5,
		wealthLevel: 4,
		specializations: ['port'],
	},

	// --- Empire byzantin ---
	{
		id: 'set_constantinople',
		name: 'Constantinople',
		type: 'capital',
		coord: { lat: 41.01, lng: 28.98 },
		tileId: '',
		nationId: 'nat_byzantine',
		population: 500_000, // plus grande ville du monde chrétien
		defenseLevel: 10,
		wealthLevel: 10,
		specializations: [
			'trade',
			'academic',
			'religious_center',
			'military',
			'manufacturing',
			'port',
		],
	},

	// --- Monde islamique ---
	{
		id: 'set_cairo',
		name: 'Le Caire',
		type: 'capital',
		coord: { lat: 30.04, lng: 31.24 },
		tileId: '',
		nationId: 'nat_fatimid',
		population: 250_000,
		defenseLevel: 8,
		wealthLevel: 9,
		specializations: ['trade', 'academic', 'religious_center', 'manufacturing'],
	},
	{
		id: 'set_shiraz',
		name: 'Chiraz',
		type: 'capital',
		coord: { lat: 29.59, lng: 52.58 },
		tileId: '',
		nationId: 'nat_buyid',
		population: 80_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['academic', 'trade'],
	},
	{
		id: 'set_ghazni',
		name: 'Ghazni',
		type: 'capital',
		coord: { lat: 33.55, lng: 68.42 },
		tileId: '',
		nationId: 'nat_ghaznavid',
		population: 60_000,
		defenseLevel: 7,
		wealthLevel: 8,
		specializations: ['military', 'trade', 'academic'],
	},
	{
		id: 'set_samarkand',
		name: 'Samarcande',
		type: 'capital',
		coord: { lat: 39.65, lng: 66.96 },
		tileId: '',
		nationId: 'nat_karakhanid',
		population: 100_000,
		defenseLevel: 7,
		wealthLevel: 8,
		specializations: ['trade', 'academic', 'manufacturing'],
	},

	// --- Asie de l'Est ---
	{
		id: 'set_kaifeng',
		name: 'Kaifeng',
		type: 'capital',
		coord: { lat: 34.8, lng: 114.31 },
		tileId: '',
		nationId: 'nat_song',
		population: 1_000_000, // plus grande ville du monde
		defenseLevel: 7,
		wealthLevel: 10,
		specializations: ['trade', 'academic', 'manufacturing', 'administrative'],
	},
	{
		id: 'set_hangzhou',
		name: 'Hangzhou',
		type: 'major_city',
		coord: { lat: 30.27, lng: 120.15 },
		tileId: '',
		nationId: 'nat_song',
		population: 500_000,
		defenseLevel: 5,
		wealthLevel: 9,
		specializations: ['trade', 'manufacturing', 'port'],
	},
	{
		id: 'set_shangjing',
		name: 'Shangjing (Capitale suprême)',
		type: 'capital',
		coord: { lat: 43.97, lng: 118.97 },
		tileId: '',
		nationId: 'nat_liao',
		population: 60_000,
		defenseLevel: 7,
		wealthLevel: 6,
		specializations: ['military', 'administrative'],
	},
	{
		id: 'set_kaesong',
		name: 'Kaesŏng',
		type: 'capital',
		coord: { lat: 37.97, lng: 126.56 },
		tileId: '',
		nationId: 'nat_goryeo',
		population: 100_000,
		defenseLevel: 7,
		wealthLevel: 7,
		specializations: ['trade', 'academic', 'religious_center'],
	},
	{
		id: 'set_kyoto',
		name: 'Heian-kyō (Kyoto)',
		type: 'capital',
		coord: { lat: 35.01, lng: 135.77 },
		tileId: '',
		nationId: 'nat_japan',
		population: 175_000,
		defenseLevel: 4,
		wealthLevel: 8,
		specializations: ['academic', 'religious_center', 'administrative'],
	},
	{
		id: 'set_hoa_lu',
		name: 'Hoa Lư',
		type: 'capital',
		coord: { lat: 20.28, lng: 105.94 },
		tileId: '',
		nationId: 'nat_dai_viet',
		population: 30_000,
		defenseLevel: 8,
		wealthLevel: 5,
		specializations: ['military', 'administrative'],
	},

	// --- Asie du Sud-Est ---
	{
		id: 'set_angkor',
		name: 'Angkor',
		type: 'capital',
		coord: { lat: 13.41, lng: 103.87 },
		tileId: '',
		nationId: 'nat_khmer',
		population: 200_000, // une des plus grandes villes du monde
		defenseLevel: 7,
		wealthLevel: 8,
		specializations: ['religious_center', 'administrative', 'trade'],
	},
	{
		id: 'set_palembang',
		name: 'Palembang',
		type: 'capital',
		coord: { lat: -2.99, lng: 104.76 },
		tileId: '',
		nationId: 'nat_srivijaya',
		population: 80_000,
		defenseLevel: 5,
		wealthLevel: 8,
		specializations: ['trade', 'port', 'religious_center'],
	},

	// --- Asie du Sud ---
	{
		id: 'set_thanjavur',
		name: 'Thanjavur (Tanjore)',
		type: 'capital',
		coord: { lat: 10.79, lng: 79.14 },
		tileId: '',
		nationId: 'nat_chola',
		population: 100_000,
		defenseLevel: 7,
		wealthLevel: 9,
		specializations: ['religious_center', 'trade', 'academic'],
	},
	{
		id: 'set_manyakheta',
		name: 'Manyakheta',
		type: 'capital',
		coord: { lat: 17.19, lng: 76.52 },
		tileId: '',
		nationId: 'nat_chalukya',
		population: 50_000,
		defenseLevel: 6,
		wealthLevel: 6,
		specializations: ['military', 'religious_center'],
	},
	{
		id: 'set_vikramapura',
		name: 'Vikramapura',
		type: 'capital',
		coord: { lat: 23.63, lng: 90.35 },
		tileId: '',
		nationId: 'nat_pala',
		population: 40_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['academic', 'religious_center'],
	},

	// --- Afrique ---
	{
		id: 'set_koumbi_saleh',
		name: 'Koumbi Saleh',
		type: 'capital',
		coord: { lat: 15.77, lng: -7.97 },
		tileId: '',
		nationId: 'nat_ghana',
		population: 30_000,
		defenseLevel: 5,
		wealthLevel: 8,
		specializations: ['trade'],
	},
	{
		id: 'set_njimi',
		name: 'Njimi',
		type: 'capital',
		coord: { lat: 13.5, lng: 14.8 },
		tileId: '',
		nationId: 'nat_kanem',
		population: 15_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['trade', 'military'],
	},
	{
		id: 'set_lalibela',
		name: 'Roha (future Lalibela)',
		type: 'capital',
		coord: { lat: 12.03, lng: 39.04 },
		tileId: '',
		nationId: 'nat_ethiopia',
		population: 10_000,
		defenseLevel: 6,
		wealthLevel: 5,
		specializations: ['religious_center'],
	},
	{
		id: 'set_kilwa',
		name: 'Kilwa Kisiwani',
		type: 'capital',
		coord: { lat: -8.96, lng: 39.52 },
		tileId: '',
		nationId: 'nat_swahili_cities',
		population: 12_000,
		defenseLevel: 4,
		wealthLevel: 7,
		specializations: ['trade', 'port'],
	},

	// --- Amériques ---
	{
		id: 'set_tula',
		name: 'Tula',
		type: 'capital',
		coord: { lat: 20.06, lng: -99.34 },
		tileId: '',
		nationId: 'nat_toltec',
		population: 40_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['military', 'religious_center', 'trade'],
	},
	{
		id: 'set_chichen_itza',
		name: 'Chichén Itzá',
		type: 'capital',
		coord: { lat: 20.68, lng: -88.57 },
		tileId: '',
		nationId: 'nat_maya_states',
		population: 35_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['religious_center', 'academic', 'trade'],
	},
	{
		id: 'set_cahokia',
		name: 'Cahokia',
		type: 'capital',
		coord: { lat: 38.66, lng: -90.06 },
		tileId: '',
		nationId: 'nat_mississippian',
		population: 15_000, // en croissance, pic vers 1100
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['religious_center', 'trade'],
	},
	{
		id: 'set_huari',
		name: 'Huari',
		type: 'capital',
		coord: { lat: -13.18, lng: -74.22 },
		tileId: '',
		nationId: 'nat_wari',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 4,
		specializations: ['military'],
	},

	// --- Tibet ---
	{
		id: 'set_lhasa',
		name: 'Lhassa',
		type: 'capital',
		coord: { lat: 29.65, lng: 91.13 },
		tileId: '',
		nationId: 'nat_tibet',
		population: 15_000,
		defenseLevel: 6,
		wealthLevel: 5,
		specializations: ['religious_center'],
	},

	// --- Villes majeures supplémentaires (non-capitales) ---
	{
		id: 'set_alexandria',
		name: 'Alexandrie',
		type: 'major_city',
		coord: { lat: 31.2, lng: 29.92 },
		tileId: '',
		nationId: 'nat_fatimid',
		population: 100_000,
		defenseLevel: 6,
		wealthLevel: 8,
		specializations: ['trade', 'port', 'academic'],
	},
	{
		id: 'set_baghdad',
		name: 'Bagdad',
		type: 'major_city',
		coord: { lat: 33.31, lng: 44.37 },
		tileId: '',
		nationId: 'nat_buyid',
		population: 300_000, // encore très peuplée malgré le déclin abbasside
		defenseLevel: 7,
		wealthLevel: 8,
		specializations: ['trade', 'academic', 'religious_center', 'manufacturing'],
	},
	{
		id: 'set_novgorod',
		name: 'Novgorod',
		type: 'major_city',
		coord: { lat: 58.52, lng: 31.27 },
		tileId: '',
		nationId: 'nat_kievan_rus',
		population: 20_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['trade', 'port'],
	},
	{
		id: 'set_guangzhou',
		name: 'Canton (Guangzhou)',
		type: 'major_city',
		coord: { lat: 23.13, lng: 113.26 },
		tileId: '',
		nationId: 'nat_song',
		population: 200_000,
		defenseLevel: 5,
		wealthLevel: 9,
		specializations: ['trade', 'port', 'manufacturing'],
	},
	{
		id: 'set_timbuktu',
		name: 'Tombouctou',
		type: 'trading_post',
		coord: { lat: 16.77, lng: -3.01 },
		tileId: '',
		nationId: 'nat_ghana',
		population: 10_000,
		defenseLevel: 3,
		wealthLevel: 7,
		specializations: ['trade', 'academic'],
	},

	// --- Villes saintes (non-capitales) ---
	{
		id: 'set_jerusalem',
		name: 'Jérusalem',
		type: 'major_city',
		coord: { lat: 31.77, lng: 35.23 },
		tileId: '',
		nationId: 'nat_fatimid', // sous contrôle fatimide en l'an 1000
		population: 20_000,
		defenseLevel: 7,
		wealthLevel: 6,
		specializations: ['religious_center'],
	},
	{
		id: 'set_mecca',
		name: 'La Mecque',
		type: 'major_city',
		coord: { lat: 21.43, lng: 39.83 },
		tileId: '',
		nationId: 'nat_fatimid', // Hejaz sous suzeraineté fatimide
		population: 30_000,
		defenseLevel: 5,
		wealthLevel: 7,
		specializations: ['religious_center', 'trade'],
	},
	{
		id: 'set_karbala',
		name: 'Karbala',
		type: 'major_city',
		coord: { lat: 32.62, lng: 44.02 },
		tileId: '',
		nationId: 'nat_buyid',
		population: 15_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['religious_center'],
	},
	{
		id: 'set_axum',
		name: 'Axoum',
		type: 'major_city',
		coord: { lat: 14.13, lng: 38.72 },
		tileId: '',
		nationId: 'nat_ethiopia',
		population: 8_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['religious_center'],
	},
	{
		id: 'set_varanasi',
		name: 'Vârânasî (Bénarès)',
		type: 'major_city',
		coord: { lat: 25.32, lng: 83.01 },
		tileId: '',
		nationId: 'nat_pala', // nord de l'Inde, proche sphère Pala
		population: 50_000,
		defenseLevel: 4,
		wealthLevel: 6,
		specializations: ['religious_center', 'academic'],
	},
	{
		id: 'set_qufu',
		name: 'Qufu',
		type: 'major_city',
		coord: { lat: 35.6, lng: 116.99 },
		tileId: '',
		nationId: 'nat_song',
		population: 20_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['religious_center', 'academic'],
	},
	{
		id: 'set_ise',
		name: 'Ise',
		type: 'major_city',
		coord: { lat: 34.49, lng: 136.73 },
		tileId: '',
		nationId: 'nat_japan',
		population: 8_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['religious_center'],
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 1
	// ========================================================================
	{
		id: 'set_chaco_canyon',
		name: 'Chaco Canyon (Pueblo Bonito)',
		type: 'major_city',
		coord: { lat: 36.06, lng: -107.96 },
		tileId: '',
		nationId: 'nat_puebloans',
		population: 5_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['religious', 'academic'],
	},
	{
		id: 'set_haida_gwaii',
		name: 'Haida Gwaii (village principal)',
		type: 'town',
		coord: { lat: 53.25, lng: -132.07 },
		tileId: '',
		nationId: 'nat_haida',
		population: 3_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['port', 'manufacturing'],
	},
	{
		id: 'set_thule_camp',
		name: 'Camp principal thuléen (Arctique)',
		type: 'town',
		coord: { lat: 72.78, lng: -86.22 },
		tileId: '',
		nationId: 'nat_thule',
		population: 500,
		defenseLevel: 3,
		wealthLevel: 2,
		specializations: ['port'],
	},
	{
		id: 'set_tongatapu',
		name: 'Tongatapu (Lapaha)',
		type: 'major_city',
		coord: { lat: -21.21, lng: -175.15 },
		tileId: '',
		nationId: 'nat_tui_tonga',
		population: 10_000,
		defenseLevel: 4,
		wealthLevel: 6,
		specializations: ['religious', 'port'],
	},
	{
		id: 'set_uluru',
		name: 'Uluru (site cérémoniel central)',
		type: 'town',
		coord: { lat: -25.34, lng: 131.04 },
		tileId: '',
		nationId: 'nat_aboriginal',
		population: 1_000,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['religious'],
	},
	{
		id: 'set_sapmi',
		name: 'Sápmi (camp central de Laponie)',
		type: 'town',
		coord: { lat: 68.35, lng: 22.34 },
		tileId: '',
		nationId: 'nat_sami',
		population: 1_500,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['trade'],
	},
	{
		id: 'set_mapuche_rewe',
		name: 'Rewe mapuche (Araucanie)',
		type: 'town',
		coord: { lat: -38.74, lng: -72.6 },
		tileId: '',
		nationId: 'nat_mapuche',
		population: 5_000,
		defenseLevel: 6,
		wealthLevel: 4,
		specializations: ['military'],
	},
	{
		id: 'set_mahilaka',
		name: 'Mahilaka (port malgache)',
		type: 'town',
		coord: { lat: -15.18, lng: 46.31 },
		tileId: '',
		nationId: 'nat_malagasy',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['trade', 'port'],
	},
	{
		id: 'set_ife',
		name: 'Ifè',
		type: 'major_city',
		coord: { lat: 7.47, lng: 4.56 },
		tileId: '',
		nationId: 'nat_yoruba',
		population: 20_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['religious', 'manufacturing'],
	},
	{
		id: 'set_great_zimbabwe',
		name: 'Grand Zimbabwe',
		type: 'major_city',
		coord: { lat: -20.27, lng: 30.93 },
		tileId: '',
		nationId: 'nat_zimbabwe',
		population: 10_000,
		defenseLevel: 7,
		wealthLevel: 6,
		specializations: ['trade', 'religious'],
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 2
	// ========================================================================
	{
		id: 'set_chan_chan',
		name: 'Chan Chan',
		type: 'capital',
		coord: { lat: -8.1, lng: -79.07 },
		tileId: '',
		nationId: 'nat_chimu',
		population: 30_000,
		defenseLevel: 7,
		wealthLevel: 8,
		specializations: ['manufacturing', 'trade', 'religious'],
	},
	{
		id: 'set_bacata',
		name: 'Bacatá (Bogotá)',
		type: 'capital',
		coord: { lat: 4.6, lng: -74.08 },
		tileId: '',
		nationId: 'nat_muisca',
		population: 15_000,
		defenseLevel: 5,
		wealthLevel: 7,
		specializations: ['trade', 'religious'],
	},
	{
		id: 'set_guarani_tekoha',
		name: 'Tekoha guaraní principal',
		type: 'town',
		coord: { lat: -23.5, lng: -54.5 },
		tileId: '',
		nationId: 'nat_guarani',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['agriculture'],
	},
	{
		id: 'set_waipio',
		name: "Waipi'o (vallée sacrée)",
		type: 'capital',
		coord: { lat: 20.1, lng: -155.6 },
		tileId: '',
		nationId: 'nat_hawaii',
		population: 5_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['religious', 'agriculture'],
	},
	{
		id: 'set_ainu_kotan',
		name: 'Kotan aïnou (Hokkaido)',
		type: 'town',
		coord: { lat: 43.06, lng: 141.35 },
		tileId: '',
		nationId: 'nat_ainu',
		population: 2_000,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['trade'],
	},
	{
		id: 'set_old_dongola',
		name: 'Vieille Dongola',
		type: 'capital',
		coord: { lat: 18.22, lng: 30.74 },
		tileId: '',
		nationId: 'nat_makuria',
		population: 20_000,
		defenseLevel: 7,
		wealthLevel: 6,
		specializations: ['religious', 'trade'],
	},
	{
		id: 'set_tadmekka',
		name: 'Tadmekka (Essouk)',
		type: 'capital',
		coord: { lat: 19.8, lng: 1.4 },
		tileId: '',
		nationId: 'nat_tuareg',
		population: 8_000,
		defenseLevel: 5,
		wealthLevel: 7,
		specializations: ['trade'],
	},
	{
		id: 'set_kutaisi',
		name: 'Koutaïssi',
		type: 'capital',
		coord: { lat: 42.27, lng: 42.69 },
		tileId: '',
		nationId: 'nat_georgia',
		population: 25_000,
		defenseLevel: 8,
		wealthLevel: 7,
		specializations: ['religious', 'trade'],
	},
	{
		id: 'set_ani',
		name: 'Ani (ville aux mille et une églises)',
		type: 'capital',
		coord: { lat: 40.51, lng: 43.57 },
		tileId: '',
		nationId: 'nat_armenia',
		population: 100_000,
		defenseLevel: 9,
		wealthLevel: 9,
		specializations: ['trade', 'religious', 'manufacturing'],
	},

	// ========================================================================
	// PEUPLES AUTOCHTONES ET MARGINALISÉS — TIER 3
	// ========================================================================
	{
		id: 'set_snaketown',
		name: 'Snaketown (Skoaquik)',
		type: 'town',
		coord: { lat: 33.19, lng: -111.87 },
		tileId: '',
		nationId: 'nat_hohokam',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 4,
		specializations: ['agriculture'],
	},
	{
		id: 'set_dorset_camp',
		name: 'Campement Dorset (Terre de Baffin)',
		type: 'town',
		coord: { lat: 66.0, lng: -66.0 },
		tileId: '',
		nationId: 'nat_dorset',
		population: 500,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['hunting'],
	},
	{
		id: 'set_beothuk_village',
		name: 'Village béothuk (rivière des Exploits)',
		type: 'town',
		coord: { lat: 49.0, lng: -55.7 },
		tileId: '',
		nationId: 'nat_beothuk',
		population: 500,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['hunting'],
	},
	{
		id: 'set_dene_camp',
		name: 'Camp déné (Grand lac des Esclaves)',
		type: 'town',
		coord: { lat: 62.5, lng: -114.4 },
		tileId: '',
		nationId: 'nat_dene',
		population: 1_000,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['hunting'],
	},
	{
		id: 'set_mikmaq_village',
		name: "Village mi'kmaq (Nouvelle-Écosse)",
		type: 'town',
		coord: { lat: 44.65, lng: -63.57 },
		tileId: '',
		nationId: 'nat_mikmaq',
		population: 2_000,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['hunting', 'port'],
	},
	{
		id: 'set_papuan_highlands',
		name: 'Hautes terres papoues',
		type: 'town',
		coord: { lat: -6.0, lng: 145.0 },
		tileId: '',
		nationId: 'nat_papuan',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['agriculture'],
	},
	{
		id: 'set_fiji_village',
		name: 'Village fortifié fidjien (Viti Levu)',
		type: 'town',
		coord: { lat: -17.8, lng: 178.0 },
		tileId: '',
		nationId: 'nat_fiji',
		population: 2_000,
		defenseLevel: 4,
		wealthLevel: 3,
		specializations: ['military'],
	},
	{
		id: 'set_hagatna',
		name: 'Hagåtña (Guam)',
		type: 'town',
		coord: { lat: 13.48, lng: 144.75 },
		tileId: '',
		nationId: 'nat_chamorro',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 4,
		specializations: ['port'],
	},
	{
		id: 'set_guimar',
		name: 'Güímar (Tenerife)',
		type: 'town',
		coord: { lat: 28.31, lng: -16.38 },
		tileId: '',
		nationId: 'nat_guanche',
		population: 4_000,
		defenseLevel: 4,
		wealthLevel: 3,
		specializations: ['agriculture'],
	},
	{
		id: 'set_tsodilo',
		name: 'Tsodilo (collines sacrées)',
		type: 'town',
		coord: { lat: -18.75, lng: 21.73 },
		tileId: '',
		nationId: 'nat_san',
		population: 500,
		defenseLevel: 1,
		wealthLevel: 1,
		specializations: ['religious'],
	},
	{
		id: 'set_ituri',
		name: 'Campement Ituri',
		type: 'town',
		coord: { lat: 1.5, lng: 28.5 },
		tileId: '',
		nationId: 'nat_mbuti',
		population: 300,
		defenseLevel: 1,
		wealthLevel: 1,
		specializations: ['hunting'],
	},
	{
		id: 'set_nri',
		name: 'Nri (cité sacrée)',
		type: 'major_city',
		coord: { lat: 6.1, lng: 7.0 },
		tileId: '',
		nationId: 'nat_igbo',
		population: 10_000,
		defenseLevel: 4,
		wealthLevel: 6,
		specializations: ['religious', 'trade'],
	},
	{
		id: 'set_chukchi_camp',
		name: 'Campement tchouktche (détroit de Béring)',
		type: 'town',
		coord: { lat: 66.0, lng: -170.0 },
		tileId: '',
		nationId: 'nat_chukchi',
		population: 1_000,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['hunting'],
	},

	// ========================================================================
	// Villes futures (référencées par les événements historiques post-1000)
	// ========================================================================
	{
		id: 'set_nanjing',
		name: 'Nankin (Jinling)',
		type: 'major_city',
		coord: { lat: 32.06, lng: 118.8 },
		tileId: '',
		nationId: 'nat_song',
		population: 500_000,
		defenseLevel: 7,
		wealthLevel: 7,
		specializations: ['trade', 'administration'],
	},
	{
		id: 'set_delhi',
		name: 'Delhi',
		type: 'town',
		coord: { lat: 28.61, lng: 77.21 },
		tileId: '',
		nationId: 'nat_ghaznavid',
		population: 50_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['military', 'trade'],
	},
	{
		id: 'set_tabriz',
		name: 'Tabriz',
		type: 'city',
		coord: { lat: 38.08, lng: 46.29 },
		tileId: '',
		nationId: 'nat_buyid',
		population: 100_000,
		defenseLevel: 6,
		wealthLevel: 6,
		specializations: ['trade', 'craftsmanship'],
	},
	{
		id: 'set_moscow',
		name: 'Moscou (Moskva)',
		type: 'town',
		coord: { lat: 55.75, lng: 37.62 },
		tileId: '',
		nationId: 'nat_kievan_rus',
		population: 5_000,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['trade'],
	},
	{
		id: 'set_berlin',
		name: 'Berlin',
		type: 'village',
		coord: { lat: 52.52, lng: 13.41 },
		tileId: '',
		nationId: 'nat_hre',
		population: 1_000,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: [],
	},
	{
		id: 'set_turin',
		name: 'Turin (Torino)',
		type: 'town',
		coord: { lat: 45.07, lng: 7.69 },
		tileId: '',
		nationId: 'nat_hre',
		population: 10_000,
		defenseLevel: 4,
		wealthLevel: 4,
		specializations: ['trade'],
	},
	{
		id: 'set_tokyo',
		name: 'Edo (futur Tokyo)',
		type: 'village',
		coord: { lat: 35.68, lng: 139.69 },
		tileId: '',
		nationId: 'nat_japan',
		population: 500,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['fishing'],
	},
	{
		id: 'set_saint_petersburg',
		name: 'Site de Saint-Pétersbourg',
		type: 'village',
		coord: { lat: 59.93, lng: 30.32 },
		tileId: '',
		nationId: 'nat_kievan_rus',
		population: 200,
		defenseLevel: 1,
		wealthLevel: 1,
		specializations: [],
	},
	{
		id: 'set_beijing',
		name: 'Yanjing (futur Pékin)',
		type: 'city',
		coord: { lat: 39.9, lng: 116.4 },
		tileId: '',
		nationId: 'nat_liao',
		population: 200_000,
		defenseLevel: 7,
		wealthLevel: 6,
		specializations: ['administration', 'military'],
	},
	{
		id: 'set_ankara',
		name: 'Ancyre (futur Ankara)',
		type: 'town',
		coord: { lat: 39.93, lng: 32.86 },
		tileId: '',
		nationId: 'nat_byzantine',
		population: 10_000,
		defenseLevel: 4,
		wealthLevel: 3,
		specializations: [],
	},

	// ========================================================================
	// Enrichissement — Établissements additionnels (~120 entrées)
	// ========================================================================

	// --- Europe occidentale (ajouts) ---
	{
		id: 'set_cologne',
		name: 'Cologne',
		type: 'major_city',
		coord: { lat: 50.94, lng: 6.96 },
		tileId: '',
		nationId: 'nat_hre',
		population: 20_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['trade', 'religious_center'],
	},
	{
		id: 'set_regensburg',
		name: 'Ratisbonne',
		type: 'city',
		coord: { lat: 49.02, lng: 12.1 },
		tileId: '',
		nationId: 'nat_hre',
		population: 12_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['trade', 'administration'],
	},
	{
		id: 'set_hamburg',
		name: 'Hambourg',
		type: 'port',
		coord: { lat: 53.55, lng: 10.0 },
		tileId: '',
		nationId: 'nat_hre',
		population: 5_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['trade', 'port'],
	},
	{
		id: 'set_lyon',
		name: 'Lyon',
		type: 'city',
		coord: { lat: 45.76, lng: 4.83 },
		tileId: '',
		nationId: 'nat_france',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['trade', 'religious_center'],
	},
	{
		id: 'set_rouen',
		name: 'Rouen',
		type: 'city',
		coord: { lat: 49.44, lng: 1.1 },
		tileId: '',
		nationId: 'nat_france',
		population: 8_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_orleans',
		name: 'Orléans',
		type: 'city',
		coord: { lat: 47.9, lng: 1.9 },
		tileId: '',
		nationId: 'nat_france',
		population: 7_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['religious_center', 'trade'],
	},
	{
		id: 'set_york',
		name: 'York',
		type: 'major_city',
		coord: { lat: 53.96, lng: -1.08 },
		tileId: '',
		nationId: 'nat_england',
		population: 10_000,
		defenseLevel: 6,
		wealthLevel: 6,
		specializations: ['trade', 'religious_center'],
	},
	{
		id: 'set_winchester',
		name: 'Winchester',
		type: 'city',
		coord: { lat: 51.06, lng: -1.31 },
		tileId: '',
		nationId: 'nat_england',
		population: 8_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['administration', 'religious_center'],
	},
	{
		id: 'set_bristol',
		name: 'Bristol',
		type: 'port',
		coord: { lat: 51.45, lng: -2.59 },
		tileId: '',
		nationId: 'nat_england',
		population: 5_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_dunfermline',
		name: 'Dunfermline',
		type: 'town',
		coord: { lat: 56.07, lng: -3.46 },
		tileId: '',
		nationId: 'nat_scotland',
		population: 3_000,
		defenseLevel: 4,
		wealthLevel: 4,
		specializations: ['religious_center', 'administration'],
	},
	{
		id: 'set_murano',
		name: 'Murano',
		type: 'town',
		coord: { lat: 45.46, lng: 12.35 },
		tileId: '',
		nationId: 'nat_venice',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 7,
		specializations: ['artisan'],
	},
	{
		id: 'set_ravenna',
		name: 'Ravenne',
		type: 'city',
		coord: { lat: 44.42, lng: 12.2 },
		tileId: '',
		nationId: 'nat_papal',
		population: 8_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['religious_center'],
	},
	{
		id: 'set_monte_cassino',
		name: 'Mont-Cassin',
		type: 'monastery',
		coord: { lat: 41.49, lng: 13.81 },
		tileId: '',
		nationId: 'nat_papal',
		population: 500,
		defenseLevel: 3,
		wealthLevel: 4,
		specializations: ['religious_center', 'scholarship'],
	},

	// --- Ibérie ---
	{
		id: 'set_burgos',
		name: 'Burgos',
		type: 'city',
		coord: { lat: 42.34, lng: -3.7 },
		tileId: '',
		nationId: 'nat_leon',
		population: 5_000,
		defenseLevel: 6,
		wealthLevel: 4,
		specializations: ['military', 'religious_center'],
	},
	{
		id: 'set_santiago',
		name: 'Saint-Jacques-de-Compostelle',
		type: 'city',
		coord: { lat: 42.88, lng: -8.54 },
		tileId: '',
		nationId: 'nat_leon',
		population: 4_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['religious_center'],
	},
	{
		id: 'set_toledo',
		name: 'Tolède',
		type: 'major_city',
		coord: { lat: 39.86, lng: -4.03 },
		tileId: '',
		nationId: 'nat_cordoba',
		population: 35_000,
		defenseLevel: 7,
		wealthLevel: 7,
		specializations: ['trade', 'scholarship', 'artisan'],
	},
	{
		id: 'set_sevilla',
		name: 'Séville',
		type: 'major_city',
		coord: { lat: 37.39, lng: -5.98 },
		tileId: '',
		nationId: 'nat_cordoba',
		population: 30_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['trade', 'port', 'artisan'],
	},
	{
		id: 'set_granada',
		name: 'Grenade',
		type: 'city',
		coord: { lat: 37.18, lng: -3.6 },
		tileId: '',
		nationId: 'nat_cordoba',
		population: 15_000,
		defenseLevel: 7,
		wealthLevel: 6,
		specializations: ['artisan', 'agriculture'],
	},
	{
		id: 'set_tudela',
		name: 'Tudela',
		type: 'town',
		coord: { lat: 42.06, lng: -1.61 },
		tileId: '',
		nationId: 'nat_navarre',
		population: 3_000,
		defenseLevel: 4,
		wealthLevel: 4,
		specializations: ['agriculture', 'trade'],
	},

	{
		id: 'set_trondheim',
		name: 'Nidaros (Trondheim)',
		type: 'city',
		coord: { lat: 63.43, lng: 10.4 },
		tileId: '',
		nationId: 'nat_norway',
		population: 3_000,
		defenseLevel: 4,
		wealthLevel: 4,
		specializations: ['religious_center', 'port'],
	},
	{
		id: 'set_bergen',
		name: 'Bergen',
		type: 'port',
		coord: { lat: 60.39, lng: 5.32 },
		tileId: '',
		nationId: 'nat_norway',
		population: 2_000,
		defenseLevel: 3,
		wealthLevel: 4,
		specializations: ['port', 'trade'],
	},

	{
		id: 'set_wroclaw',
		name: 'Wrocław',
		type: 'city',
		coord: { lat: 51.11, lng: 17.04 },
		tileId: '',
		nationId: 'nat_poland',
		population: 4_000,
		defenseLevel: 4,
		wealthLevel: 4,
		specializations: ['trade'],
	},
	{
		id: 'set_pecs',
		name: 'Pécs',
		type: 'city',
		coord: { lat: 46.07, lng: 18.23 },
		tileId: '',
		nationId: 'nat_hungary',
		population: 4_000,
		defenseLevel: 4,
		wealthLevel: 4,
		specializations: ['religious_center', 'scholarship'],
	},
	{
		id: 'set_split',
		name: 'Split',
		type: 'port',
		coord: { lat: 43.51, lng: 16.44 },
		tileId: '',
		nationId: 'nat_croatia',
		population: 5_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_smolensk',
		name: 'Smolensk',
		type: 'city',
		coord: { lat: 54.78, lng: 32.05 },
		tileId: '',
		nationId: 'nat_kievan_rus',
		population: 6_000,
		defenseLevel: 5,
		wealthLevel: 4,
		specializations: ['trade', 'military'],
	},

	{
		id: 'set_dvin',
		name: 'Dvin',
		type: 'city',
		coord: { lat: 40.01, lng: 44.58 },
		tileId: '',
		nationId: 'nat_armenia',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['trade', 'artisan'],
	},

	// --- Empire byzantin (ajouts) ---
	{
		id: 'set_thessalonica',
		name: 'Thessalonique',
		type: 'major_city',
		coord: { lat: 40.63, lng: 22.94 },
		tileId: '',
		nationId: 'nat_byzantine',
		population: 40_000,
		defenseLevel: 7,
		wealthLevel: 7,
		specializations: ['trade', 'port', 'religious_center'],
	},
	{
		id: 'set_trebizond',
		name: 'Trébizonde',
		type: 'port',
		coord: { lat: 41.0, lng: 39.72 },
		tileId: '',
		nationId: 'nat_byzantine',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['port', 'trade'],
	},

	{
		id: 'set_damascus',
		name: 'Damas',
		type: 'major_city',
		coord: { lat: 33.51, lng: 36.29 },
		tileId: '',
		nationId: 'nat_fatimid',
		population: 40_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['trade', 'artisan', 'religious_center'],
	},
	{
		id: 'set_isfahan',
		name: 'Ispahan',
		type: 'major_city',
		coord: { lat: 32.65, lng: 51.68 },
		tileId: '',
		nationId: 'nat_buyid',
		population: 50_000,
		defenseLevel: 6,
		wealthLevel: 8,
		specializations: ['trade', 'artisan', 'scholarship'],
	},
	{
		id: 'set_basra',
		name: 'Bassora',
		type: 'port',
		coord: { lat: 30.51, lng: 47.81 },
		tileId: '',
		nationId: 'nat_buyid',
		population: 30_000,
		defenseLevel: 5,
		wealthLevel: 7,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_lahore',
		name: 'Lahore',
		type: 'major_city',
		coord: { lat: 31.55, lng: 74.35 },
		tileId: '',
		nationId: 'nat_ghaznavid',
		population: 25_000,
		defenseLevel: 6,
		wealthLevel: 6,
		specializations: ['trade', 'military'],
	},
	{
		id: 'set_bukhara',
		name: 'Boukhara',
		type: 'major_city',
		coord: { lat: 39.77, lng: 64.42 },
		tileId: '',
		nationId: 'nat_karakhanid',
		population: 40_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['trade', 'scholarship', 'religious_center'],
	},
	{
		id: 'set_fergana',
		name: 'Fergana',
		type: 'city',
		coord: { lat: 40.38, lng: 71.79 },
		tileId: '',
		nationId: 'nat_karakhanid',
		population: 10_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['agriculture', 'trade'],
	},
	{
		id: 'set_dongola',
		name: 'Dongola',
		type: 'city',
		coord: { lat: 19.17, lng: 30.47 },
		tileId: '',
		nationId: 'nat_makuria',
		population: 8_000,
		defenseLevel: 5,
		wealthLevel: 4,
		specializations: ['religious_center', 'trade'],
	},
	{
		id: 'set_gao',
		name: 'Gao',
		type: 'city',
		coord: { lat: 16.27, lng: -0.04 },
		tileId: '',
		nationId: 'nat_tuareg',
		population: 5_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['trade', 'caravan_hub'],
	},

	// --- Asie de l'Est (ajouts) ---
	{
		id: 'set_quanzhou',
		name: 'Quanzhou',
		type: 'port',
		coord: { lat: 24.91, lng: 118.59 },
		tileId: '',
		nationId: 'nat_song',
		population: 80_000,
		defenseLevel: 5,
		wealthLevel: 9,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_chengdu',
		name: 'Chengdu',
		type: 'major_city',
		coord: { lat: 30.57, lng: 104.07 },
		tileId: '',
		nationId: 'nat_song',
		population: 100_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['trade', 'agriculture', 'artisan'],
	},
	{
		id: 'set_liaoyang',
		name: 'Liaoyang',
		type: 'city',
		coord: { lat: 41.27, lng: 123.17 },
		tileId: '',
		nationId: 'nat_liao',
		population: 20_000,
		defenseLevel: 6,
		wealthLevel: 5,
		specializations: ['military', 'administration'],
	},
	{
		id: 'set_gyeongju',
		name: 'Gyeongju',
		type: 'city',
		coord: { lat: 35.86, lng: 129.22 },
		tileId: '',
		nationId: 'nat_goryeo',
		population: 20_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['religious_center', 'artisan'],
	},
	{
		id: 'set_pyongyang',
		name: 'Pyongyang',
		type: 'city',
		coord: { lat: 39.02, lng: 125.75 },
		tileId: '',
		nationId: 'nat_goryeo',
		population: 15_000,
		defenseLevel: 6,
		wealthLevel: 5,
		specializations: ['military', 'trade'],
	},
	{
		id: 'set_nara',
		name: 'Nara',
		type: 'city',
		coord: { lat: 34.68, lng: 135.8 },
		tileId: '',
		nationId: 'nat_japan',
		population: 20_000,
		defenseLevel: 4,
		wealthLevel: 6,
		specializations: ['religious_center', 'scholarship'],
	},
	{
		id: 'set_dazaifu',
		name: 'Dazaifu',
		type: 'city',
		coord: { lat: 33.52, lng: 130.52 },
		tileId: '',
		nationId: 'nat_japan',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['military', 'trade'],
	},

	{
		id: 'set_yasodharapura',
		name: 'Yasodharapura (Angkor)',
		type: 'city',
		coord: { lat: 13.44, lng: 103.84 },
		tileId: '',
		nationId: 'nat_khmer',
		population: 25_000,
		defenseLevel: 6,
		wealthLevel: 7,
		specializations: ['religious_center', 'agriculture'],
	},
	{
		id: 'set_kedah',
		name: 'Kedah',
		type: 'port',
		coord: { lat: 6.12, lng: 100.37 },
		tileId: '',
		nationId: 'nat_srivijaya',
		population: 8_000,
		defenseLevel: 3,
		wealthLevel: 6,
		specializations: ['port', 'trade'],
	},

	// --- Inde ---
	{
		id: 'set_nagapattinam',
		name: 'Nagapattinam',
		type: 'port',
		coord: { lat: 10.76, lng: 79.84 },
		tileId: '',
		nationId: 'nat_chola',
		population: 15_000,
		defenseLevel: 5,
		wealthLevel: 7,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_madurai',
		name: 'Madurai',
		type: 'city',
		coord: { lat: 9.93, lng: 78.12 },
		tileId: '',
		nationId: 'nat_chola',
		population: 20_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['religious_center', 'artisan'],
	},
	{
		id: 'set_badami',
		name: 'Bâdâmi',
		type: 'city',
		coord: { lat: 15.92, lng: 75.68 },
		tileId: '',
		nationId: 'nat_chalukya',
		population: 12_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['religious_center', 'artisan'],
	},
	{
		id: 'set_goa_ancient',
		name: 'Goa (Chandrapur)',
		type: 'port',
		coord: { lat: 15.5, lng: 73.83 },
		tileId: '',
		nationId: 'nat_chalukya',
		population: 8_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_nalanda',
		name: 'Nalanda',
		type: 'monastery',
		coord: { lat: 25.14, lng: 85.44 },
		tileId: '',
		nationId: 'nat_pala',
		population: 3_000,
		defenseLevel: 2,
		wealthLevel: 5,
		specializations: ['scholarship', 'religious_center'],
	},

	// --- Tibet ---
	{
		id: 'set_shigatse',
		name: 'Shigatsé',
		type: 'monastery',
		coord: { lat: 29.27, lng: 88.88 },
		tileId: '',
		nationId: 'nat_tibet',
		population: 2_000,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['religious_center'],
	},

	{
		id: 'set_awdaghust',
		name: 'Aoudaghost',
		type: 'trading_post',
		coord: { lat: 17.82, lng: -10.06 },
		tileId: '',
		nationId: 'nat_ghana',
		population: 3_000,
		defenseLevel: 2,
		wealthLevel: 5,
		specializations: ['trade', 'caravan_hub'],
	},
	{
		id: 'set_adulis',
		name: 'Adulis',
		type: 'port',
		coord: { lat: 15.4, lng: 39.66 },
		tileId: '',
		nationId: 'nat_ethiopia',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_mogadishu',
		name: 'Mogadiscio',
		type: 'port',
		coord: { lat: 2.05, lng: 45.32 },
		tileId: '',
		nationId: 'nat_swahili_cities',
		population: 10_000,
		defenseLevel: 4,
		wealthLevel: 6,
		specializations: ['port', 'trade'],
	},
	{
		id: 'set_mombasa',
		name: 'Mombasa',
		type: 'port',
		coord: { lat: -4.05, lng: 39.67 },
		tileId: '',
		nationId: 'nat_swahili_cities',
		population: 8_000,
		defenseLevel: 4,
		wealthLevel: 6,
		specializations: ['port', 'trade'],
	},

	// --- Amériques ---
	{
		id: 'set_cholula',
		name: 'Cholula',
		type: 'city',
		coord: { lat: 19.06, lng: -98.31 },
		tileId: '',
		nationId: 'nat_toltec',
		population: 20_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['religious_center', 'trade'],
	},
	{
		id: 'set_uxmal',
		name: 'Uxmal',
		type: 'city',
		coord: { lat: 20.36, lng: -89.77 },
		tileId: '',
		nationId: 'nat_maya_states',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['religious_center', 'artisan'],
	},
	{
		id: 'set_east_st_louis',
		name: 'East St. Louis (Mississippien)',
		type: 'town',
		coord: { lat: 38.62, lng: -90.15 },
		tileId: '',
		nationId: 'nat_mississippian',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['agriculture'],
	},
	{
		id: 'set_tiwanaku',
		name: 'Tiwanaku',
		type: 'city',
		coord: { lat: -16.55, lng: -68.67 },
		tileId: '',
		nationId: 'nat_wari',
		population: 8_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['religious_center', 'artisan'],
	},
	{
		id: 'set_sogamoso',
		name: 'Sogamoso',
		type: 'town',
		coord: { lat: 5.71, lng: -72.93 },
		tileId: '',
		nationId: 'nat_muisca',
		population: 5_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['religious_center', 'trade'],
	},
	{
		id: 'set_pueblo_bonito',
		name: 'Pueblo Bonito',
		type: 'town',
		coord: { lat: 36.06, lng: -107.96 },
		tileId: '',
		nationId: 'nat_puebloans',
		population: 1_500,
		defenseLevel: 4,
		wealthLevel: 3,
		specializations: ['agriculture', 'artisan'],
	},

	{
		id: 'set_bau',
		name: 'Bau',
		type: 'village',
		coord: { lat: -17.99, lng: 178.37 },
		tileId: '',
		nationId: 'nat_fiji',
		population: 1_500,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['military'],
	},
	{
		id: 'set_waimea',
		name: 'Waimea',
		type: 'village',
		coord: { lat: 21.96, lng: -159.67 },
		tileId: '',
		nationId: 'nat_hawaii',
		population: 1_000,
		defenseLevel: 2,
		wealthLevel: 3,
		specializations: ['agriculture'],
	},

	// --- Arctique / Sub-arctique ---
	{
		id: 'set_thule_site',
		name: 'Ruin Island',
		type: 'nomadic_camp',
		coord: { lat: 77.47, lng: -68.77 },
		tileId: '',
		nationId: 'nat_thule',
		population: 200,
		defenseLevel: 1,
		wealthLevel: 2,
		specializations: [],
	},
	{
		id: 'set_sami_camp',
		name: 'Staloluokta',
		type: 'nomadic_camp',
		coord: { lat: 67.2, lng: 16.5 },
		tileId: '',
		nationId: 'nat_sami',
		population: 300,
		defenseLevel: 1,
		wealthLevel: 2,
		specializations: [],
	},

	// --- Peuples arctiques et nord-américains ---
	{
		id: 'set_haida_village',
		name: 'SGang Gwaay (Ninstints)',
		type: 'village',
		coord: { lat: 52.1, lng: -131.22 },
		tileId: '',
		nationId: 'nat_haida',
		population: 500,
		defenseLevel: 2,
		wealthLevel: 3,
		specializations: ['artisan'],
	},
	{
		id: 'set_beothuk_camp',
		name: "Boyd's Cove",
		type: 'village',
		coord: { lat: 49.34, lng: -55.35 },
		tileId: '',
		nationId: 'nat_beothuk',
		population: 300,
		defenseLevel: 1,
		wealthLevel: 2,
		specializations: [],
	},

	// --- Amérique du Sud ---
	{
		id: 'set_mapuche_ruka',
		name: 'Temuco (Rewe)',
		type: 'village',
		coord: { lat: -38.74, lng: -72.6 },
		tileId: '',
		nationId: 'nat_mapuche',
		population: 500,
		defenseLevel: 3,
		wealthLevel: 2,
		specializations: ['military'],
	},
	{
		id: 'set_guarani_village',
		name: 'Tekoha (Paraná)',
		type: 'village',
		coord: { lat: -25.29, lng: -57.58 },
		tileId: '',
		nationId: 'nat_guarani',
		population: 400,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['agriculture'],
	},

	// --- Îles / Peuples isolés ---
	{
		id: 'set_aboriginal_camp',
		name: 'Uluru (campement)',
		type: 'nomadic_camp',
		coord: { lat: -25.34, lng: 131.04 },
		tileId: '',
		nationId: 'nat_aboriginal',
		population: 200,
		defenseLevel: 1,
		wealthLevel: 1,
		specializations: [],
	},
	{
		id: 'set_papuan_village',
		name: 'Village des Hautes Terres (Baliem)',
		type: 'village',
		coord: { lat: -4.0, lng: 138.93 },
		tileId: '',
		nationId: 'nat_papuan',
		population: 500,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['agriculture'],
	},
	{
		id: 'set_chamorro_village',
		name: 'Hagåtña',
		type: 'village',
		coord: { lat: 13.48, lng: 144.75 },
		tileId: '',
		nationId: 'nat_chamorro',
		population: 500,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: [],
	},
	{
		id: 'set_guanche_village',
		name: 'Gáldar',
		type: 'village',
		coord: { lat: 28.15, lng: -15.65 },
		tileId: '',
		nationId: 'nat_guanche',
		population: 1_000,
		defenseLevel: 2,
		wealthLevel: 2,
		specializations: ['agriculture'],
	},
	{
		id: 'set_san_camp',
		name: 'Tsodilo Hills',
		type: 'nomadic_camp',
		coord: { lat: -18.77, lng: 21.73 },
		tileId: '',
		nationId: 'nat_san',
		population: 150,
		defenseLevel: 1,
		wealthLevel: 1,
		specializations: [],
	},
	{
		id: 'set_mbuti_camp',
		name: 'Ituri (campement)',
		type: 'nomadic_camp',
		coord: { lat: 1.5, lng: 28.5 },
		tileId: '',
		nationId: 'nat_mbuti',
		population: 100,
		defenseLevel: 1,
		wealthLevel: 1,
		specializations: [],
	},
	{
		id: 'set_volga_bulgar',
		name: 'Bolgar',
		type: 'city',
		coord: { lat: 54.97, lng: 49.05 },
		tileId: '',
		nationId: 'nat_volga_bulgaria',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 6,
		specializations: ['trade', 'artisan'],
	},

	// --- Settlements supplémentaires (nations à 1 seul settlement) ---

	// nat_denmark — 2e settlement
	{
		id: 'set_hedeby',
		name: 'Hedeby',
		type: 'port',
		coord: { lat: 54.49, lng: 9.57 },
		tileId: '',
		nationId: 'nat_denmark',
		population: 5_000,
		defenseLevel: 5,
		wealthLevel: 7,
		specializations: ['trade', 'port', 'artisan'],
	},

	// nat_sweden — 2e settlement
	{
		id: 'set_birka',
		name: 'Birka',
		type: 'port',
		coord: { lat: 59.33, lng: 17.55 },
		tileId: '',
		nationId: 'nat_sweden',
		population: 3_000,
		defenseLevel: 4,
		wealthLevel: 7,
		specializations: ['trade', 'port', 'artisan'],
	},

	// nat_dai_viet — 2e settlement
	{
		id: 'set_dai_la',
		name: 'Đại La (futur Thăng Long)',
		type: 'city',
		coord: { lat: 21.03, lng: 105.85 },
		tileId: '',
		nationId: 'nat_dai_viet',
		population: 15_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['trade', 'administrative'],
	},

	// nat_kanem — 2e settlement
	{
		id: 'set_bilma',
		name: 'Bilma',
		type: 'trading_post',
		coord: { lat: 18.69, lng: 12.92 },
		tileId: '',
		nationId: 'nat_kanem',
		population: 2_000,
		defenseLevel: 2,
		wealthLevel: 5,
		specializations: ['trade', 'salt_production'],
	},

	// nat_tui_tonga — 2e settlement
	{
		id: 'set_mua',
		name: "Mu'a",
		type: 'capital',
		coord: { lat: -21.17, lng: -175.15 },
		tileId: '',
		nationId: 'nat_tui_tonga',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['religious_center', 'administrative'],
	},

	// nat_malagasy — 2e settlement
	{
		id: 'set_vohimarina',
		name: 'Vohémar',
		type: 'port',
		coord: { lat: -13.35, lng: 50.0 },
		tileId: '',
		nationId: 'nat_malagasy',
		population: 2_000,
		defenseLevel: 2,
		wealthLevel: 4,
		specializations: ['trade', 'port'],
	},

	// nat_yoruba — 2e settlement
	{
		id: 'set_oyo',
		name: 'Oyo',
		type: 'city',
		coord: { lat: 7.85, lng: 3.93 },
		tileId: '',
		nationId: 'nat_yoruba',
		population: 10_000,
		defenseLevel: 5,
		wealthLevel: 5,
		specializations: ['trade', 'military'],
	},

	// nat_zimbabwe — 2e settlement
	{
		id: 'set_mapungubwe',
		name: 'Mapungubwe',
		type: 'city',
		coord: { lat: -22.19, lng: 29.27 },
		tileId: '',
		nationId: 'nat_zimbabwe',
		population: 5_000,
		defenseLevel: 4,
		wealthLevel: 6,
		specializations: ['trade', 'gold_production'],
	},

	// nat_chimu — 2e settlement
	{
		id: 'set_tucume',
		name: 'Túcume',
		type: 'city',
		coord: { lat: -6.51, lng: -79.85 },
		tileId: '',
		nationId: 'nat_chimu',
		population: 8_000,
		defenseLevel: 4,
		wealthLevel: 5,
		specializations: ['religious_center', 'artisan'],
	},

	// nat_ainu — 2e settlement
	{
		id: 'set_ainu_chasi',
		name: 'Chasi aïnou (Hokkaido méridional)',
		type: 'village',
		coord: { lat: 42.32, lng: 141.0 },
		tileId: '',
		nationId: 'nat_ainu',
		population: 500,
		defenseLevel: 3,
		wealthLevel: 3,
		specializations: ['trade', 'fishing'],
	},

	// nat_georgia — 2e settlement
	{
		id: 'set_tbilisi',
		name: 'Tbilissi',
		type: 'major_city',
		coord: { lat: 41.72, lng: 44.79 },
		tileId: '',
		nationId: 'nat_georgia',
		population: 20_000,
		defenseLevel: 6,
		wealthLevel: 6,
		specializations: ['trade', 'artisan', 'fortress'],
	},

	// nat_hohokam — 2e settlement
	{
		id: 'set_pueblo_grande',
		name: 'Pueblo Grande',
		type: 'town',
		coord: { lat: 33.45, lng: -111.97 },
		tileId: '',
		nationId: 'nat_hohokam',
		population: 2_000,
		defenseLevel: 2,
		wealthLevel: 4,
		specializations: ['irrigation', 'artisan'],
	},

	// nat_dorset — 2e settlement
	{
		id: 'set_dorset_ilulik',
		name: 'Camp Dorset (Igloolik)',
		type: 'village',
		coord: { lat: 69.38, lng: -81.8 },
		tileId: '',
		nationId: 'nat_dorset',
		population: 200,
		defenseLevel: 1,
		wealthLevel: 2,
		specializations: ['hunting', 'ivory_carving'],
	},

	// nat_dene — 2e settlement
	{
		id: 'set_dene_liard',
		name: 'Camp déné (rivière Liard)',
		type: 'village',
		coord: { lat: 60.05, lng: -123.77 },
		tileId: '',
		nationId: 'nat_dene',
		population: 200,
		defenseLevel: 1,
		wealthLevel: 2,
		specializations: ['hunting', 'trapping'],
	},

	// nat_mikmaq — 2e settlement
	{
		id: 'set_mikmaq_gaspe',
		name: "Village mi'kmaq (Gaspésie)",
		type: 'village',
		coord: { lat: 48.83, lng: -64.49 },
		tileId: '',
		nationId: 'nat_mikmaq',
		population: 300,
		defenseLevel: 1,
		wealthLevel: 2,
		specializations: ['fishing', 'trade'],
	},

	// nat_igbo — 2e settlement
	{
		id: 'set_igbo_ukwu',
		name: 'Igbo-Ukwu',
		type: 'town',
		coord: { lat: 6.02, lng: 7.02 },
		tileId: '',
		nationId: 'nat_igbo',
		population: 3_000,
		defenseLevel: 3,
		wealthLevel: 5,
		specializations: ['artisan', 'bronze_casting'],
	},

	// nat_chukchi — 2e settlement
	{
		id: 'set_chukchi_whale',
		name: 'Camp tchouktche (cap Dejnev)',
		type: 'village',
		coord: { lat: 66.08, lng: -169.65 },
		tileId: '',
		nationId: 'nat_chukchi',
		population: 150,
		defenseLevel: 1,
		wealthLevel: 2,
		specializations: ['hunting', 'whaling'],
	},
]
