import type {
	SocialMobilityPath,
	SocialMobilityModifier,
} from '../../../shared/src/types/world'

// ============================================================================
// Chemins de mobilité sociale — transitions universelles
// ============================================================================
// Chaque chemin décrit UNE transition entre deux classes sociales.
// Les modificateurs nationaux (plus bas) ajustent la faisabilité par nation.
// ============================================================================

export const socialMobilityPaths: SocialMobilityPath[] = [
	// ========================================================================
	// ASCENSION — depuis serfs
	// ========================================================================
	{
		id: 'mob_serf_to_free_peasant_manumission',
		fromClass: 'serfs',
		toClass: 'free_peasants',
		direction: 'up',
		mechanism: 'manumission',
		name: 'Affranchissement par le seigneur',
		description:
			"Le seigneur libère un serf de ses obligations foncières, souvent en échange de services rendus ou d'un paiement.",
		requiredTechs: [],
		minWealth: 2,
		minReputation: 3,
		durationYears: 1,
		wealthCost: 50,
		baseSuccessRate: 0.3,
		reputationChangeOnSuccess: 1,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			"Dans l'Europe féodale, certains seigneurs affranchissent des serfs pour peupler de nouvelles terres.",
	},
	{
		id: 'mob_serf_to_free_peasant_flight',
		fromClass: 'serfs',
		toClass: 'free_peasants',
		direction: 'up',
		mechanism: 'exile',
		name: 'Fuite vers une ville libre',
		description:
			"Un serf s'enfuit vers une ville où, selon la coutume, un an et un jour de résidence lui confèrent la liberté.",
		requiredTechs: [],
		minWealth: 0,
		minReputation: 0,
		durationYears: 2,
		wealthCost: 0,
		baseSuccessRate: 0.4,
		reputationChangeOnSuccess: -1,
		reputationChangeOnFailure: -3,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			'"L\'air de la ville rend libre" — dicton médiéval allemand (Stadtluft macht frei).',
	},
	{
		id: 'mob_serf_to_free_peasant_religion',
		fromClass: 'serfs',
		toClass: 'free_peasants',
		direction: 'up',
		mechanism: 'religious_ordination',
		name: 'Entrée en religion',
		description:
			"Un serf rejoint un ordre monastique, ce qui le soustrait à l'autorité seigneuriale.",
		requiredTechs: [],
		minWealth: 0,
		minReputation: 2,
		durationYears: 1,
		wealthCost: 0,
		baseSuccessRate: 0.25,
		reputationChangeOnSuccess: 2,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			"L'Église accepte théoriquement tous les fidèles, mais les seigneurs résistent à perdre leur main-d'œuvre.",
	},

	// ========================================================================
	// ASCENSION — depuis free_peasants
	// ========================================================================
	{
		id: 'mob_peasant_to_artisan_guild',
		fromClass: 'free_peasants',
		toClass: 'artisans',
		direction: 'up',
		mechanism: 'guild_mastery',
		name: 'Apprentissage de guilde',
		description:
			'Un paysan envoie son fils en apprentissage chez un maître artisan. Après des années de formation, il obtient le statut de compagnon.',
		requiredTechs: ['tech_guilds'],
		minWealth: 3,
		minReputation: 2,
		durationYears: 7,
		wealthCost: 30,
		baseSuccessRate: 0.5,
		reputationChangeOnSuccess: 2,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			"L'apprentissage dure typiquement 5-7 ans. Le passage de compagnon à maître peut prendre une génération de plus.",
	},
	{
		id: 'mob_peasant_to_warrior_military',
		fromClass: 'free_peasants',
		toClass: 'warriors',
		direction: 'up',
		mechanism: 'military_service',
		name: 'Enrôlement militaire',
		description:
			"Un paysan libre s'engage comme homme d'armes, acquérant entraînement et statut de combattant.",
		requiredTechs: [],
		minWealth: 1,
		minReputation: 1,
		durationYears: 3,
		wealthCost: 10,
		baseSuccessRate: 0.6,
		reputationChangeOnSuccess: 2,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			"Les fyrd anglo-saxons, les almogávares ibériques — le service armé est un levier d'ascension classique.",
	},
	{
		id: 'mob_peasant_to_clergy',
		fromClass: 'free_peasants',
		toClass: 'clergy',
		direction: 'up',
		mechanism: 'religious_ordination',
		name: 'Ordination religieuse',
		description:
			'Un paysan entre dans les ordres, devenant moine, prêtre ou religieuse selon les rites de sa confession.',
		requiredTechs: [],
		minWealth: 1,
		minReputation: 3,
		durationYears: 3,
		wealthCost: 5,
		baseSuccessRate: 0.45,
		reputationChangeOnSuccess: 3,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			"L'Église reste le principal ascenseur social du Moyen Âge pour les classes basses.",
	},
	{
		id: 'mob_peasant_to_merchant_trade',
		fromClass: 'free_peasants',
		toClass: 'merchants',
		direction: 'up',
		mechanism: 'trade_wealth',
		name: 'Enrichissement par le commerce',
		description:
			'Un paysan accumule un surplus agricole, commence le négoce local, puis régional.',
		requiredTechs: ['tech_basic_trade'],
		minWealth: 4,
		minReputation: 3,
		durationYears: 10,
		wealthCost: 40,
		baseSuccessRate: 0.2,
		reputationChangeOnSuccess: 2,
		reputationChangeOnFailure: -2,
		generationsRequired: 2,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			"Transition rare et lente, nécessitant souvent deux générations d'accumulation de capital.",
	},

	// ========================================================================
	// ASCENSION — depuis artisans
	// ========================================================================
	{
		id: 'mob_artisan_to_merchant_trade',
		fromClass: 'artisans',
		toClass: 'merchants',
		direction: 'up',
		mechanism: 'trade_wealth',
		name: 'Du maître artisan au négociant',
		description:
			"Un artisan prospère diversifie ses activités vers le commerce de gros et l'export.",
		requiredTechs: ['tech_basic_trade'],
		minWealth: 5,
		minReputation: 4,
		durationYears: 8,
		wealthCost: 60,
		baseSuccessRate: 0.35,
		reputationChangeOnSuccess: 2,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			'Les drapiers flamands, les verriers vénitiens — certains artisans deviennent de riches marchands.',
	},
	{
		id: 'mob_artisan_to_clergy_education',
		fromClass: 'artisans',
		toClass: 'clergy',
		direction: 'up',
		mechanism: 'education',
		name: 'Études monastiques',
		description:
			"Un fils d'artisan lettré entre au monastère et accède au savoir ecclésiastique.",
		requiredTechs: [],
		minWealth: 3,
		minReputation: 3,
		durationYears: 5,
		wealthCost: 20,
		baseSuccessRate: 0.4,
		reputationChangeOnSuccess: 2,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			'Les monastères forment des scribes, enlumineurs et architectes issus de familles artisanes.',
	},

	// ========================================================================
	// ASCENSION — depuis merchants
	// ========================================================================
	{
		id: 'mob_merchant_to_minor_noble_land',
		fromClass: 'merchants',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'land_acquisition',
		name: 'Achat de terres et de titres',
		description:
			'Un marchand très riche acquiert des domaines fonciers et achète ou négocie un titre de noblesse.',
		requiredTechs: [],
		minWealth: 8,
		minReputation: 6,
		durationYears: 15,
		wealthCost: 200,
		baseSuccessRate: 0.2,
		reputationChangeOnSuccess: 3,
		reputationChangeOnFailure: -2,
		generationsRequired: 2,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			'Les patriciens de Venise, les marchands de Lubeck — la richesse peut ouvrir les portes de la noblesse.',
	},
	{
		id: 'mob_merchant_to_noble_marriage',
		fromClass: 'merchants',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'marriage',
		name: 'Mariage dans la noblesse',
		description:
			'Un marchand fortuné marie son enfant dans une famille noble appauvrie, échangeant richesse contre titre.',
		requiredTechs: [],
		minWealth: 7,
		minReputation: 5,
		durationYears: 5,
		wealthCost: 150,
		baseSuccessRate: 0.25,
		reputationChangeOnSuccess: 4,
		reputationChangeOnFailure: -3,
		generationsRequired: 2,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			"Alliance classique : l'argent du roturier contre le prestige du noble. Les enfants seront nobles.",
	},
	{
		id: 'mob_merchant_to_noble_royal_favour',
		fromClass: 'merchants',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'royal_favour',
		name: 'Anoblissement par le souverain',
		description:
			'Le roi anoblit un marchand en récompense de services financiers ou diplomatiques rendus à la couronne.',
		requiredTechs: [],
		minWealth: 7,
		minReputation: 7,
		durationYears: 5,
		wealthCost: 100,
		baseSuccessRate: 0.15,
		reputationChangeOnSuccess: 5,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			'Les financiers de la couronne, les banquiers des Médicis — le pouvoir économique mène au titre.',
	},

	// ========================================================================
	// ASCENSION — depuis warriors
	// ========================================================================
	{
		id: 'mob_warrior_to_noble_military',
		fromClass: 'warriors',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'military_service',
		name: "Anoblissement pour faits d'armes",
		description:
			'Un guerrier distingué au combat reçoit terres et titre de chevalier ou équivalent.',
		requiredTechs: [],
		minWealth: 3,
		minReputation: 6,
		durationYears: 10,
		wealthCost: 30,
		baseSuccessRate: 0.15,
		reputationChangeOnSuccess: 5,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			"Les mamelouks, les samourais, les chevaliers — l'épée est un chemin vers la noblesse.",
	},
	{
		id: 'mob_warrior_to_noble_conquest',
		fromClass: 'warriors',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'conquest',
		name: 'Conquête et fondation de lignée',
		description:
			'Un chef de guerre victorieux fonde sa propre seigneurie sur les terres conquises.',
		requiredTechs: [],
		minWealth: 4,
		minReputation: 7,
		durationYears: 5,
		wealthCost: 50,
		baseSuccessRate: 0.1,
		reputationChangeOnSuccess: 6,
		reputationChangeOnFailure: -5,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			'Guillaume le Conquérant, les émirs Ghaznavides — la conquête crée une nouvelle noblesse.',
	},

	// ========================================================================
	// ASCENSION — depuis clergy
	// ========================================================================
	{
		id: 'mob_clergy_to_nobility_politics',
		fromClass: 'clergy',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'royal_favour',
		name: 'Prince-évêque ou cardinal politique',
		description:
			'Un ecclésiastique accumule pouvoir temporel, devenant seigneur de facto avec terres et armées.',
		requiredTechs: [],
		minWealth: 5,
		minReputation: 7,
		durationYears: 15,
		wealthCost: 80,
		baseSuccessRate: 0.1,
		reputationChangeOnSuccess: 4,
		reputationChangeOnFailure: -3,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			'Les princes-évêques du Saint-Empire, les papes-rois — le pouvoir spirituel mène au temporel.',
	},

	// ========================================================================
	// ASCENSION — depuis nomads
	// ========================================================================
	{
		id: 'mob_nomad_to_warrior',
		fromClass: 'nomads',
		toClass: 'warriors',
		direction: 'up',
		mechanism: 'military_service',
		name: 'Intégration dans une armée',
		description:
			"Un nomade s'enrôle comme cavalier ou éclaireur dans une armée sédentaire.",
		requiredTechs: [],
		minWealth: 1,
		minReputation: 2,
		durationYears: 3,
		wealthCost: 5,
		baseSuccessRate: 0.5,
		reputationChangeOnSuccess: 2,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			'Les Turcs, Bédouins et Mongols sont recherchés comme cavaliers par les empires sédentaires.',
	},
	{
		id: 'mob_nomad_to_merchant',
		fromClass: 'nomads',
		toClass: 'merchants',
		direction: 'up',
		mechanism: 'trade_wealth',
		name: 'Caravanier devenu marchand',
		description:
			'Un nomade spécialisé dans le transport de caravanes accumule assez de capital pour devenir négociant.',
		requiredTechs: ['tech_basic_trade'],
		minWealth: 3,
		minReputation: 3,
		durationYears: 8,
		wealthCost: 30,
		baseSuccessRate: 0.3,
		reputationChangeOnSuccess: 2,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			'Les Touaregs et les Sogdiens contrôlent des routes commerciales entières.',
	},

	// ========================================================================
	// ASCENSION — depuis slaves
	// ========================================================================
	{
		id: 'mob_slave_to_free_manumission',
		fromClass: 'slaves',
		toClass: 'free_peasants',
		direction: 'up',
		mechanism: 'manumission',
		name: 'Affranchissement',
		description:
			'Un esclave est libéré par son maître, devenant un homme libre de statut modeste.',
		requiredTechs: [],
		minWealth: 0,
		minReputation: 1,
		durationYears: 1,
		wealthCost: 0,
		baseSuccessRate: 0.15,
		reputationChangeOnSuccess: 1,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			"L'affranchissement est reconnu par l'Islam, le droit romain et le droit canon.",
	},
	{
		id: 'mob_slave_to_warrior_mamluk',
		fromClass: 'slaves',
		toClass: 'warriors',
		direction: 'up',
		mechanism: 'military_service',
		name: 'Esclave-soldat (ghulam / mamelouk)',
		description:
			"Un esclave est entraîné comme soldat d'élite, acquérant statut et pouvoir par les armes.",
		requiredTechs: [],
		minWealth: 0,
		minReputation: 0,
		durationYears: 5,
		wealthCost: 0,
		baseSuccessRate: 0.3,
		reputationChangeOnSuccess: 4,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			"Les Mamelouks d'Égypte passent de l'esclavage au sultanat — un cas unique dans l'Histoire.",
	},

	// ========================================================================
	// ASCENSION — via éducation / examens
	// ========================================================================
	{
		id: 'mob_peasant_to_clergy_exam',
		fromClass: 'free_peasants',
		toClass: 'clergy',
		direction: 'up',
		mechanism: 'education',
		name: 'Réussite aux examens impériaux',
		description:
			'Un fils de paysan réussit les examens impériaux et entre dans la bureaucratie lettrée.',
		requiredTechs: ['tech_civil_examination'],
		minWealth: 2,
		minReputation: 2,
		durationYears: 10,
		wealthCost: 20,
		baseSuccessRate: 0.05,
		reputationChangeOnSuccess: 6,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			"Le système d'examens impériaux chinois (keju) est le plus grand ascenseur social méritocratique du monde médiéval.",
	},
	{
		id: 'mob_merchant_to_nobility_exam',
		fromClass: 'merchants',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'education',
		name: 'Examens impériaux vers la haute fonction',
		description:
			'Un fils de marchand lettré réussit les examens de plus haut niveau et accède à la haute administration.',
		requiredTechs: ['tech_civil_examination'],
		minWealth: 5,
		minReputation: 4,
		durationYears: 12,
		wealthCost: 40,
		baseSuccessRate: 0.08,
		reputationChangeOnSuccess: 5,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			"En Chine Song, le lettré-fonctionnaire est l'aristocrate par excellence.",
	},

	// ========================================================================
	// DÉCHÉANCE — chemins descendants
	// ========================================================================
	{
		id: 'mob_noble_to_merchant_ruin',
		fromClass: 'nobility',
		toClass: 'merchants',
		direction: 'down',
		mechanism: 'debt',
		name: 'Noblesse ruinée',
		description:
			'Un noble criblé de dettes perd ses terres et doit se reconvertir dans le commerce.',
		requiredTechs: [],
		minWealth: 0,
		minReputation: 0,
		durationYears: 3,
		wealthCost: 0,
		baseSuccessRate: 0.7,
		reputationChangeOnSuccess: -4,
		reputationChangeOnFailure: -2,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			'La noblesse espagnole méprise le commerce mais y est parfois contrainte par la ruine.',
	},
	{
		id: 'mob_noble_to_clergy_exile',
		fromClass: 'nobility',
		toClass: 'clergy',
		direction: 'down',
		mechanism: 'exile',
		name: 'Exil monastique',
		description:
			'Un noble vaincu politiquement se retire dans un monastère, volontairement ou sous contrainte.',
		requiredTechs: [],
		minWealth: 0,
		minReputation: 0,
		durationYears: 1,
		wealthCost: 0,
		baseSuccessRate: 0.8,
		reputationChangeOnSuccess: -2,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			'Les cadets de famille, les prétendants déchus — le cloître est une retraite honorable.',
	},
	{
		id: 'mob_merchant_to_artisan_ruin',
		fromClass: 'merchants',
		toClass: 'artisans',
		direction: 'down',
		mechanism: 'debt',
		name: 'Faillite commerciale',
		description:
			"Un marchand ruiné par un naufrage, une guerre ou une mauvaise créance retombe au statut d'artisan.",
		requiredTechs: [],
		minWealth: 0,
		minReputation: 0,
		durationYears: 1,
		wealthCost: 0,
		baseSuccessRate: 0.6,
		reputationChangeOnSuccess: -3,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			'Le risque commercial est élevé : pirates, naufrages, guerres interrompent le commerce.',
	},
	{
		id: 'mob_free_peasant_to_serf_debt',
		fromClass: 'free_peasants',
		toClass: 'serfs',
		direction: 'down',
		mechanism: 'debt',
		name: 'Asservissement pour dettes',
		description:
			"Un paysan libre endetté se place sous la protection d'un seigneur, perdant sa liberté en échange de la sécurité.",
		requiredTechs: [],
		minWealth: 0,
		minReputation: 0,
		durationYears: 1,
		wealthCost: 0,
		baseSuccessRate: 0.5,
		reputationChangeOnSuccess: -3,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			"En période de famine ou d'invasion, beaucoup de paysans libres se placent sous servage volontaire.",
	},
	{
		id: 'mob_any_to_slave_capture',
		fromClass: 'free_peasants',
		toClass: 'slaves',
		direction: 'down',
		mechanism: 'enslavement',
		name: 'Capture et mise en esclavage',
		description:
			"Un individu capturé lors d'un raid, d'une guerre ou d'une razzia est réduit en esclavage.",
		requiredTechs: [],
		minWealth: 0,
		minReputation: 0,
		durationYears: 0,
		wealthCost: 0,
		baseSuccessRate: 1.0,
		reputationChangeOnSuccess: -5,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			"L'esclavage par capture est courant dans toutes les civilisations en l'an 1000.",
	},
	{
		id: 'mob_warrior_to_peasant_defeat',
		fromClass: 'warriors',
		toClass: 'free_peasants',
		direction: 'down',
		mechanism: 'exile',
		name: 'Guerrier déshonoré',
		description:
			'Un guerrier vaincu ou déshonoré perd son statut et retourne à la vie civile.',
		requiredTechs: [],
		minWealth: 0,
		minReputation: 0,
		durationYears: 1,
		wealthCost: 0,
		baseSuccessRate: 0.5,
		reputationChangeOnSuccess: -3,
		reputationChangeOnFailure: -1,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			'La déchéance militaire entraîne souvent la perte de terres et de titre.',
	},

	// ========================================================================
	// ASCENSION — via héritage et adoption
	// ========================================================================
	{
		id: 'mob_artisan_to_merchant_inheritance',
		fromClass: 'artisans',
		toClass: 'merchants',
		direction: 'up',
		mechanism: 'inheritance',
		name: "Héritage d'un commerce",
		description:
			"Un artisan hérite d'un parent marchand ou d'un maître sans descendance.",
		requiredTechs: [],
		minWealth: 4,
		minReputation: 3,
		durationYears: 1,
		wealthCost: 0,
		baseSuccessRate: 0.15,
		reputationChangeOnSuccess: 1,
		reputationChangeOnFailure: 0,
		generationsRequired: 1,
		reversible: true,
		minYear: 0,
		maxYear: null,
		notes:
			'Les guildes transmettent parfois le statut de maître au sein de la famille élargie.',
	},
	{
		id: 'mob_merchant_to_noble_adoption',
		fromClass: 'merchants',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'adoption',
		name: 'Adoption par une famille noble',
		description:
			'Un enfant de marchand riche est adopté par une lignée noble sans héritier.',
		requiredTechs: [],
		minWealth: 7,
		minReputation: 5,
		durationYears: 5,
		wealthCost: 100,
		baseSuccessRate: 0.1,
		reputationChangeOnSuccess: 4,
		reputationChangeOnFailure: -2,
		generationsRequired: 2,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes: 'Pratique courante au Japon (yōshi) et dans le monde byzantin.',
	},

	// ========================================================================
	// ASCENSION — via rébellion
	// ========================================================================
	{
		id: 'mob_peasant_to_noble_rebellion',
		fromClass: 'free_peasants',
		toClass: 'nobility',
		direction: 'up',
		mechanism: 'rebellion',
		name: 'Révolte paysanne victorieuse',
		description:
			'Un leader paysan charismatique mène une révolte, renverse le seigneur local et prend le pouvoir.',
		requiredTechs: [],
		minWealth: 2,
		minReputation: 7,
		durationYears: 3,
		wealthCost: 10,
		baseSuccessRate: 0.05,
		reputationChangeOnSuccess: 7,
		reputationChangeOnFailure: -8,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			'Extrêmement rare et risqué. La plupart des révoltes médiévales sont écrasées (Jacquerie, Wat Tyler).',
	},
	{
		id: 'mob_warrior_to_royalty_coup',
		fromClass: 'warriors',
		toClass: 'royalty',
		direction: 'up',
		mechanism: 'conquest',
		name: "Coup d'État militaire",
		description:
			"Un chef militaire s'empare du trône par la force, fondant une nouvelle dynastie.",
		requiredTechs: [],
		minWealth: 5,
		minReputation: 8,
		durationYears: 2,
		wealthCost: 100,
		baseSuccessRate: 0.05,
		reputationChangeOnSuccess: 8,
		reputationChangeOnFailure: -10,
		generationsRequired: 1,
		reversible: false,
		minYear: 0,
		maxYear: null,
		notes:
			'Les Mamelouks, les Seldjoukides, Basile Ier le Macédonien — le glaive forge des dynasties.',
	},
]

// ============================================================================
// Modificateurs nationaux de mobilité sociale — An 1000
// ============================================================================
// Chaque nation module les chemins ci-dessus via son ouverture, ses blocages,
// et ses mécanismes culturels spécifiques.
// ============================================================================

export const socialMobilityModifiers: SocialMobilityModifier[] = [
	// --- Europe occidentale ---
	{
		nationId: 'nat_hre',
		upwardOpenness: 3,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: ['rebellion'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Société féodale rigide mais l'Église et l'armée offrent des voies d'ascension.",
	},
	{
		nationId: 'nat_france',
		upwardOpenness: 3,
		downwardRisk: 3,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: ['rebellion'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Féodalité capétienne stricte. Les trois ordres (bellatores, oratores, laboratores) se figent.',
	},
	{
		nationId: 'nat_england',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: [
			'military_service',
			'trade_wealth',
			'religious_ordination',
		],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"L'Angleterre anglo-saxonne est relativement flexible ; la conquête normande (1066) rigidifiera le système.",
	},
	{
		nationId: 'nat_scotland',
		upwardOpenness: 5,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'marriage'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société clanique avec mobilité par la valeur guerrière et les alliances matrimoniales.',
	},
	{
		nationId: 'nat_papal',
		upwardOpenness: 6,
		downwardRisk: 2,
		encouragedMechanisms: ['religious_ordination', 'education'],
		blockedMechanisms: ['conquest', 'rebellion'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Les États pontificaux offrent l'ascension par le mérite ecclésiastique à toutes les classes.",
	},
	{
		nationId: 'nat_venice',
		upwardOpenness: 5,
		downwardRisk: 4,
		encouragedMechanisms: ['trade_wealth', 'guild_mastery'],
		blockedMechanisms: ['rebellion', 'conquest'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"République marchande où la richesse ouvre des portes, mais le Libro d'Oro se ferme progressivement.",
	},

	// --- Péninsule ibérique ---
	{
		nationId: 'nat_leon',
		upwardOpenness: 5,
		downwardRisk: 4,
		encouragedMechanisms: [
			'military_service',
			'conquest',
			'religious_ordination',
		],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'La Reconquista crée des opportunités : repeupler les terres conquises confère terres et statut.',
	},
	{
		nationId: 'nat_navarre',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['military_service', 'marriage'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes: 'Petit royaume pyrénéen avec noblesse basque relativement ouverte.',
	},
	{
		nationId: 'nat_cordoba',
		upwardOpenness: 6,
		downwardRisk: 5,
		encouragedMechanisms: ['education', 'trade_wealth', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Al-Andalus : société multiculturelle où le savoir et le commerce permettent l'ascension, même pour les dhimmis.",
	},

	// --- Scandinavie ---
	{
		nationId: 'nat_denmark',
		upwardOpenness: 5,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'conquest', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société viking en transition : la valeur guerrière prime encore sur la naissance.',
	},
	{
		nationId: 'nat_norway',
		upwardOpenness: 6,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'conquest', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Les jarls norvégiens sont souvent d'anciens guerriers ayant gagné leurs terres par le raid.",
	},
	{
		nationId: 'nat_sweden',
		upwardOpenness: 5,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'La Suède pré-chrétienne valorise le mérite guerrier et marchand, les thralls peuvent être affranchis.',
	},

	// --- Europe de l'Est ---
	{
		nationId: 'nat_poland',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"La szlachta (noblesse) polonaise s'élargit progressivement par le service militaire.",
	},
	{
		nationId: 'nat_hungary',
		upwardOpenness: 5,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service', 'royal_favour'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"La Hongrie d'Étienne Ier intègre des guerriers de toutes origines dans la nouvelle noblesse chrétienne.",
	},
	{
		nationId: 'nat_kievan_rus',
		upwardOpenness: 5,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'trade_wealth', 'conquest'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"La Rous' kiévienne est une société marchande-guerrière où les druzhina gagnent en statut par le combat.",
	},
	{
		nationId: 'nat_volga_bulgaria',
		upwardOpenness: 5,
		downwardRisk: 4,
		encouragedMechanisms: ['trade_wealth', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Carrefour commercial entre le monde nordique et islamique. Le commerce est roi.',
	},
	{
		nationId: 'nat_croatia',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes: 'Noblesse croate entre modèle byzantin et féodal occidental.',
	},

	// --- Empire byzantin ---
	{
		nationId: 'nat_byzantine',
		upwardOpenness: 6,
		downwardRisk: 6,
		encouragedMechanisms: ['education', 'military_service', 'royal_favour'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: true,
		manumissionAllowed: true,
		notes:
			"Byzance est remarquablement méritocratique : des empereurs comme Basile Ier sont d'origine paysanne.",
	},

	// --- Monde islamique ---
	{
		nationId: 'nat_fatimid',
		upwardOpenness: 6,
		downwardRisk: 5,
		encouragedMechanisms: ['education', 'military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Le califat fatimide ismaélien encourage le savoir. Les esclaves affranchis accèdent aux plus hautes fonctions.',
	},
	{
		nationId: 'nat_buyid',
		upwardOpenness: 5,
		downwardRisk: 6,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Dynastie militaire chiite. La force armée est le principal vecteur d'ascension.",
	},
	{
		nationId: 'nat_ghaznavid',
		upwardOpenness: 5,
		downwardRisk: 6,
		encouragedMechanisms: ['military_service', 'conquest'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Mahmûd de Ghazni était fils d'un esclave-soldat turc devenu souverain. L'armée est tout.",
	},
	{
		nationId: 'nat_karakhanid',
		upwardOpenness: 5,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Khaganat turco-islamique de la Route de la Soie. Commerce et guerre ouvrent des voies.',
	},

	// --- Asie de l'Est ---
	{
		nationId: 'nat_song',
		upwardOpenness: 8,
		downwardRisk: 5,
		encouragedMechanisms: ['education', 'trade_wealth', 'guild_mastery'],
		blockedMechanisms: ['conquest', 'rebellion'],
		clergyOpenToAll: true,
		hasMeritExam: true,
		manumissionAllowed: true,
		notes:
			"La Chine Song est la société la plus méritocratique du monde en l'an 1000 grâce au système keju.",
	},
	{
		nationId: 'nat_liao',
		upwardOpenness: 4,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'conquest'],
		blockedMechanisms: ['education'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société Khitan dualiste : système tribal nomade au nord, bureaucratie chinoise au sud.',
	},
	{
		nationId: 'nat_goryeo',
		upwardOpenness: 5,
		downwardRisk: 3,
		encouragedMechanisms: ['education', 'religious_ordination'],
		blockedMechanisms: ['rebellion'],
		clergyOpenToAll: true,
		hasMeritExam: true,
		manumissionAllowed: true,
		notes:
			"Goryeo adopte le système d'examens chinois, mais la noblesse (yangban) reste dominante.",
	},
	{
		nationId: 'nat_japan',
		upwardOpenness: 2,
		downwardRisk: 3,
		encouragedMechanisms: ['military_service', 'adoption'],
		blockedMechanisms: ['rebellion', 'trade_wealth'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Le Japon Heian a une aristocratie de cour très fermée. L'adoption (yōshi) est le principal levier.",
	},

	// --- Asie du Sud-Est ---
	{
		nationId: 'nat_dai_viet',
		upwardOpenness: 6,
		downwardRisk: 4,
		encouragedMechanisms: ['education', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: true,
		manumissionAllowed: true,
		notes:
			"Le Đại Việt adopte le modèle d'examens chinois pour sélectionner ses mandarins.",
	},
	{
		nationId: 'nat_khmer',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['religious_ordination', 'royal_favour'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"L'empire khmer est une théocratie hindouiste-bouddhiste où les temples sont vecteurs d'ascension.",
	},
	{
		nationId: 'nat_srivijaya',
		upwardOpenness: 6,
		downwardRisk: 5,
		encouragedMechanisms: ['trade_wealth', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Thalassocratie marchande : la richesse commerciale prime dans cette société insulaire.',
	},

	// --- Inde ---
	{
		nationId: 'nat_chola',
		upwardOpenness: 3,
		downwardRisk: 2,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: ['marriage', 'rebellion'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: false,
		notes:
			"Système de castes (varna/jati) rigide. L'ascension se fait au sein de sa caste, rarement entre castes.",
	},
	{
		nationId: 'nat_chalukya',
		upwardOpenness: 3,
		downwardRisk: 2,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: ['marriage'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: false,
		notes:
			"La mobilité inter-castes est quasi impossible ; l'ascension se fait par le mérite militaire au sein de sa jati.",
	},
	{
		nationId: 'nat_pala',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['education', 'religious_ordination'],
		blockedMechanisms: ['marriage'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les Pala bouddhistes sont plus ouverts que les dynasties hindouistes. Nalanda accueille tous les étudiants.',
	},

	// --- Afrique ---
	{
		nationId: 'nat_ghana',
		upwardOpenness: 5,
		downwardRisk: 4,
		encouragedMechanisms: ['trade_wealth', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"L'empire du Ghana valorise le commerce de l'or et le service guerrier comme leviers d'avancement.",
	},
	{
		nationId: 'nat_kanem',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Royaume sahélien islamisé. Les marabouts et les guerriers accèdent au cercle du maï (roi).',
	},
	{
		nationId: 'nat_ethiopia',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['religious_ordination', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"L'Église éthiopienne est un puissant vecteur d'ascension. Le clergé copte accueille toutes les origines.",
	},
	{
		nationId: 'nat_swahili_cities',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['trade_wealth', 'marriage'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Cités-États marchandes cosmopolites. La richesse est le principal moteur de statut social.',
	},
	{
		nationId: 'nat_yoruba',
		upwardOpenness: 5,
		downwardRisk: 4,
		encouragedMechanisms: [
			'trade_wealth',
			'military_service',
			'religious_ordination',
		],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les cités yoruba comme Ife ont une structure sociale où le mérite et la richesse comptent.',
	},
	{
		nationId: 'nat_zimbabwe',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['trade_wealth', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Le commerce de l'or et de l'ivoire avec la côte swahili crée une élite marchande.",
	},
	{
		nationId: 'nat_makuria',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['religious_ordination', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Royaume chrétien nubien avec succession matrilinéaire, offrant des dynamiques uniques.',
	},
	{
		nationId: 'nat_tuareg',
		upwardOpenness: 3,
		downwardRisk: 3,
		encouragedMechanisms: ['trade_wealth', 'military_service'],
		blockedMechanisms: ['religious_ordination'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société très stratifiée : nobles (imajeghen), vassaux (imghad), artisans (inadan), esclaves (iklan).',
	},

	// --- Amériques ---
	{
		nationId: 'nat_toltec',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: ['trade_wealth'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: false,
		notes:
			"Société militariste mésoaméricaine. Le guerrier-prêtre est l'archétype de l'ascension.",
	},
	{
		nationId: 'nat_maya_states',
		upwardOpenness: 3,
		downwardRisk: 3,
		encouragedMechanisms: ['religious_ordination', 'military_service'],
		blockedMechanisms: ['trade_wealth'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: false,
		notes:
			'Classes sociales mayas très rigides. Les scribes et prêtres forment une caste héréditaire.',
	},
	{
		nationId: 'nat_mississippian',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les chefferies mississippiennes (Cahokia) hiérarchisent par lignage et mérite rituel.',
	},
	{
		nationId: 'nat_wari',
		upwardOpenness: 3,
		downwardRisk: 3,
		encouragedMechanisms: ['military_service', 'conquest'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: false,
		notes: 'Empire andin centralisé avec hiérarchie administrative stricte.',
	},
	{
		nationId: 'nat_chimu',
		upwardOpenness: 3,
		downwardRisk: 3,
		encouragedMechanisms: ['military_service', 'guild_mastery'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: false,
		notes:
			"Le Chimú valorise les artisans spécialisés (orfèvres) qui jouissent d'un statut élevé.",
	},
	{
		nationId: 'nat_muisca',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['trade_wealth', 'religious_ordination'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Confédération muisca avec commerce actif d'émeraudes et d'or. Les marchands ont du prestige.",
	},
	{
		nationId: 'nat_guarani',
		upwardOpenness: 6,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'marriage'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société semi-égalitaire. Le leadership se gagne par le charisme et la valeur guerrière.',
	},

	// --- Amérique du Nord ---
	{
		nationId: 'nat_puebloans',
		upwardOpenness: 5,
		downwardRisk: 4,
		encouragedMechanisms: ['religious_ordination'],
		blockedMechanisms: ['conquest'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Sociétés puebloanes relativement égalitaires, organisées autour de clans et sociétés cérémonielles.',
	},
	{
		nationId: 'nat_hohokam',
		upwardOpenness: 5,
		downwardRisk: 4,
		encouragedMechanisms: ['trade_wealth', 'religious_ordination'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Culture du désert avec réseaux d'irrigation sophistiqués. Le prestige vient du savoir hydraulique.",
	},
	{
		nationId: 'nat_haida',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['trade_wealth', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société de la côte Nord-Ouest avec potlatch : la redistribution de richesse confère le prestige.',
	},
	{
		nationId: 'nat_dorset',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société arctique de chasseurs avec hiérarchie souple basée sur les compétences de survie.',
	},
	{
		nationId: 'nat_beothuk',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Peuple de Terre-Neuve avec organisation sociale égalitaire et leadership par consensus.',
	},
	{
		nationId: 'nat_dene',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Bandes athapascanes semi-nomades avec hiérarchie souple et leadership situationnel.',
	},
	{
		nationId: 'nat_mikmaq',
		upwardOpenness: 6,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Confédération mi'kmaq avec sagamos (chefs) élus pour leurs compétences.",
	},
	{
		nationId: 'nat_thule',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société inuit proto-Thulé où le meilleur chasseur de baleine devient umialik (chef de bateau).',
	},

	// --- Asie centrale ---
	{
		nationId: 'nat_tibet',
		upwardOpenness: 4,
		downwardRisk: 3,
		encouragedMechanisms: ['religious_ordination', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Le bouddhisme tibétain offre une voie d'ascension par la vie monastique ouverte à tous.",
	},

	// --- Caucase ---
	{
		nationId: 'nat_georgia',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service', 'religious_ordination'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Royaume chrétien avec noblesse (aznauri) accessible par le service militaire au roi.',
	},
	{
		nationId: 'nat_armenia',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['trade_wealth', 'religious_ordination'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les nakharar (clans nobles) arméniens coexistent avec une diaspora marchande influente.',
	},

	// --- Pacifique & Océanie ---
	{
		nationId: 'nat_tui_tonga',
		upwardOpenness: 3,
		downwardRisk: 3,
		encouragedMechanisms: ['military_service', 'marriage'],
		blockedMechanisms: ['trade_wealth'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Empire tongien avec système de rang héréditaire strict (tu'i) basé sur la généalogie sacrée.",
	},
	{
		nationId: 'nat_hawaii',
		upwardOpenness: 3,
		downwardRisk: 3,
		encouragedMechanisms: ['military_service'],
		blockedMechanisms: ['trade_wealth'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: false,
		notes:
			"Système kapu très rigide. Les ali'i (nobles) sont séparés des maka'āinana (roturiers) par le mana sacré.",
	},
	{
		nationId: 'nat_aboriginal',
		upwardOpenness: 6,
		downwardRisk: 4,
		encouragedMechanisms: ['religious_ordination'],
		blockedMechanisms: ['trade_wealth', 'land_acquisition'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Sociétés aborigènes égalitaires avec prestige basé sur le savoir rituel (Dreamtime) et l'âge.",
	},
	{
		nationId: 'nat_fiji',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service', 'marriage'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Chefferies fidjiennes avec hiérarchie basée sur le lignage et la valeur guerrière.',
	},
	{
		nationId: 'nat_chamorro',
		upwardOpenness: 3,
		downwardRisk: 3,
		encouragedMechanisms: ['marriage'],
		blockedMechanisms: ['trade_wealth'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société matrilinéaire avec castes (chamorri / manachang) relativement rigides.',
	},
	{
		nationId: 'nat_papuan',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Sociétés mélanésiennes de "Big Men" : le prestige se gagne par la redistribution et la bravoure.',
	},
	{
		nationId: 'nat_malagasy',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['trade_wealth', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société malgache stratifiée (andriana / hova / andevo) avec mobilité limitée mais possible.',
	},

	// --- Autres ---
	{
		nationId: 'nat_sami',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Société sami semi-nomade, relativement égalitaire. Le prestige vient de la taille du troupeau de rennes.',
	},
	{
		nationId: 'nat_mapuche',
		upwardOpenness: 6,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'marriage'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les lonko (chefs) mapuche sont choisis par mérite. Société décentralisée et résistante.',
	},
	{
		nationId: 'nat_ainu',
		upwardOpenness: 6,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les ekashi (anciens) aïnous sont respectés pour leur sagesse. Commerce avec le Japon et les Toungouses.',
	},
	{
		nationId: 'nat_guanche',
		upwardOpenness: 4,
		downwardRisk: 4,
		encouragedMechanisms: ['military_service'],
		blockedMechanisms: ['trade_wealth'],
		clergyOpenToAll: false,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les Guanches des Canaries ont une société stratifiée avec noblesse héréditaire (mencey).',
	},
	{
		nationId: 'nat_san',
		upwardOpenness: 8,
		downwardRisk: 4,
		encouragedMechanisms: [],
		blockedMechanisms: ['land_acquisition', 'conquest'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les San (Bushmen) sont parmi les sociétés les plus égalitaires au monde. Pas de hiérarchie formelle.',
	},
	{
		nationId: 'nat_mbuti',
		upwardOpenness: 8,
		downwardRisk: 4,
		encouragedMechanisms: [],
		blockedMechanisms: ['land_acquisition', 'conquest'],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			"Les Mbuti (Pygmées) vivent en bandes égalitaires dans la forêt de l'Ituri.",
	},
	{
		nationId: 'nat_igbo',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['trade_wealth', 'military_service'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'"Igbo enwe eze" (les Igbo n\'ont pas de roi). Société acéphale où le mérite individuel prime.',
	},
	{
		nationId: 'nat_chukchi',
		upwardOpenness: 7,
		downwardRisk: 5,
		encouragedMechanisms: ['military_service', 'trade_wealth'],
		blockedMechanisms: [],
		clergyOpenToAll: true,
		hasMeritExam: false,
		manumissionAllowed: true,
		notes:
			'Les Tchouktches, guerriers et éleveurs de rennes, ont une société relativement égalitaire.',
	},
]
