import type { TransportVehicle } from '../../../shared/src/types/world'

export const transportVehicles: TransportVehicle[] = [
	// ========================================================================
	// NAVIRES DE HAUTE MER
	// ========================================================================
	{
		id: 'veh_drakkar',
		name: 'Drakkar (Langskip)',
		description:
			'Navire long à fond plat, propulsé par rames et voile carrée. Capable de naviguer en haute mer comme en rivière.',
		domain: 'ocean',
		roles: ['war', 'raid', 'exploration'],
		requiredTechs: ['tech_longship'],
		cargoCapacity: 20,
		passengerCapacity: 60,
		speedKmPerDay: 150,
		crewRequired: 30,
		buildCost: 200,
		maintenanceCostPerYear: 20,
		combatStrength: 7,
		seaworthiness: 7,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: true,
		culturalOrigins: ['nat_denmark', 'nat_norway', 'nat_sweden'],
		minYear: 700,
		maxYear: 1300,
		notes:
			"Le drakkar permet les raids vikings de Lindisfarne à Constantinople et la colonisation de l'Islande et du Groenland.",
	},
	{
		id: 'veh_knarr',
		name: 'Knarr',
		description:
			'Navire marchand nordique à coque large, optimisé pour le transport de cargaison en haute mer.',
		domain: 'ocean',
		roles: ['trade', 'passenger'],
		requiredTechs: ['tech_longship'],
		cargoCapacity: 80,
		passengerCapacity: 30,
		speedKmPerDay: 100,
		crewRequired: 12,
		buildCost: 150,
		maintenanceCostPerYear: 15,
		combatStrength: 2,
		seaworthiness: 8,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: false,
		culturalOrigins: ['nat_denmark', 'nat_norway', 'nat_sweden'],
		minYear: 800,
		maxYear: 1300,
		notes:
			'Le knarr transporte colons, bétail et marchandises entre Scandinavie, Islande et Groenland.',
	},
	{
		id: 'veh_chinese_junk',
		name: 'Jonque chinoise',
		description:
			"Grand navire à voiles lattées, cloisons étanches et gouvernail d'étambot. Le plus avancé du monde en l'an 1000.",
		domain: 'ocean',
		roles: ['trade', 'war', 'exploration'],
		requiredTechs: ['tech_chinese_junk'],
		cargoCapacity: 200,
		passengerCapacity: 100,
		speedKmPerDay: 120,
		crewRequired: 40,
		buildCost: 400,
		maintenanceCostPerYear: 35,
		combatStrength: 6,
		seaworthiness: 9,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: false,
		culturalOrigins: ['nat_song'],
		minYear: 200,
		maxYear: null,
		notes:
			'Cloisons étanches, gouvernail axial, boussole — la jonque Song est le navire le plus sophistiqué du monde.',
	},
	{
		id: 'veh_river_junk',
		name: 'Jonque fluviale',
		description:
			"Version à faible tirant d'eau de la jonque, adaptée à la navigation sur le Yangtsé et le Grand Canal.",
		domain: 'river',
		roles: ['trade', 'passenger'],
		requiredTechs: ['tech_basic_sailing'],
		cargoCapacity: 100,
		passengerCapacity: 40,
		speedKmPerDay: 60,
		crewRequired: 10,
		buildCost: 120,
		maintenanceCostPerYear: 12,
		combatStrength: 2,
		seaworthiness: 4,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: ['nat_song'],
		minYear: 0,
		maxYear: null,
		notes:
			'Le Grand Canal impérial est parcouru par des milliers de jonques fluviales transportant grain et soie.',
	},
	{
		id: 'veh_dromon',
		name: 'Dromon',
		description:
			'Galère de guerre byzantine à deux rangs de rames, équipée de siphons à feu grégeois.',
		domain: 'ocean',
		roles: ['war'],
		requiredTechs: ['tech_basic_sailing', 'tech_greek_fire'],
		cargoCapacity: 10,
		passengerCapacity: 200,
		speedKmPerDay: 80,
		crewRequired: 150,
		buildCost: 500,
		maintenanceCostPerYear: 50,
		combatStrength: 9,
		seaworthiness: 6,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: false,
		culturalOrigins: ['nat_byzantine'],
		minYear: 500,
		maxYear: 1300,
		notes:
			'Le dromon et son feu grégeois assurent la suprématie navale byzantine en Méditerranée orientale.',
	},
	{
		id: 'veh_galley_merchant',
		name: 'Galère marchande',
		description:
			'Galère méditerranéenne mixte rames/voiles, servant au commerce et pouvant se défendre contre les pirates.',
		domain: 'coastal',
		roles: ['trade', 'passenger'],
		requiredTechs: ['tech_basic_sailing'],
		cargoCapacity: 100,
		passengerCapacity: 30,
		speedKmPerDay: 70,
		crewRequired: 50,
		buildCost: 250,
		maintenanceCostPerYear: 25,
		combatStrength: 4,
		seaworthiness: 5,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: ['nat_venice', 'nat_byzantine', 'nat_fatimid'],
		minYear: 0,
		maxYear: null,
		notes:
			'Les galères marchandes relient Venise, Constantinople et Alexandrie le long de la Méditerranée.',
	},
	{
		id: 'veh_dhow',
		name: 'Boutre (Dhow)',
		description:
			"Voilier à voile latine, navire emblématique de l'océan Indien et du commerce arabe.",
		domain: 'ocean',
		roles: ['trade', 'fishing', 'passenger'],
		requiredTechs: ['tech_lateen_sail'],
		cargoCapacity: 60,
		passengerCapacity: 20,
		speedKmPerDay: 110,
		crewRequired: 12,
		buildCost: 120,
		maintenanceCostPerYear: 12,
		combatStrength: 2,
		seaworthiness: 7,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: false,
		culturalOrigins: ['nat_fatimid', 'nat_swahili_cities'],
		minYear: 0,
		maxYear: null,
		notes:
			"Le dhow traverse l'océan Indien avec la mousson, reliant l'Arabie à l'Inde et à l'Afrique orientale.",
	},
	{
		id: 'veh_chola_warship',
		name: 'Navire de guerre Chola',
		description:
			"Grand navire de guerre du sud de l'Inde, capable de projeter des forces à travers l'océan Indien.",
		domain: 'ocean',
		roles: ['war', 'raid'],
		requiredTechs: ['tech_basic_sailing', 'tech_iron_working'],
		cargoCapacity: 30,
		passengerCapacity: 150,
		speedKmPerDay: 90,
		crewRequired: 100,
		buildCost: 400,
		maintenanceCostPerYear: 40,
		combatStrength: 8,
		seaworthiness: 7,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: false,
		culturalOrigins: ['nat_chola'],
		minYear: 900,
		maxYear: 1200,
		notes:
			"La marine Chola de Rajendra Ier conquiert le Sri Lanka et attaque Srivijaya — la plus grande force navale d'Asie du Sud.",
	},

	// ========================================================================
	// NAVIRES CÔTIERS & FLUVIAUX
	// ========================================================================
	{
		id: 'veh_coracle',
		name: 'Coracle / Currach',
		description:
			'Petit esquif rond en osier et peau, utilisé pour la pêche en rivière et le cabotage côtier.',
		domain: 'river',
		roles: ['fishing', 'passenger'],
		requiredTechs: [],
		cargoCapacity: 3,
		passengerCapacity: 2,
		speedKmPerDay: 20,
		crewRequired: 1,
		buildCost: 5,
		maintenanceCostPerYear: 1,
		combatStrength: 0,
		seaworthiness: 2,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: ['nat_england', 'nat_scotland'],
		minYear: 0,
		maxYear: null,
		notes:
			"Les moines irlandais auraient traversé l'Atlantique Nord dans des currachs (légende de saint Brendan).",
	},
	{
		id: 'veh_dugout_canoe',
		name: 'Pirogue monoxyle',
		description:
			"Embarcation creusée dans un tronc d'arbre, universelle dans les cultures fluviales.",
		domain: 'river',
		roles: ['fishing', 'trade', 'passenger'],
		requiredTechs: [],
		cargoCapacity: 5,
		passengerCapacity: 6,
		speedKmPerDay: 30,
		crewRequired: 2,
		buildCost: 8,
		maintenanceCostPerYear: 2,
		combatStrength: 0,
		seaworthiness: 2,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			'La pirogue est le moyen de transport fluvial le plus ancien et le plus répandu au monde.',
	},
	{
		id: 'veh_outrigger_canoe',
		name: 'Pirogue à balancier',
		description:
			'Pirogue stabilisée par un ou deux flotteurs latéraux, permettant la navigation en mer ouverte.',
		domain: 'ocean',
		roles: ['fishing', 'trade', 'exploration'],
		requiredTechs: ['tech_basic_sailing'],
		cargoCapacity: 10,
		passengerCapacity: 8,
		speedKmPerDay: 80,
		crewRequired: 4,
		buildCost: 25,
		maintenanceCostPerYear: 4,
		combatStrength: 1,
		seaworthiness: 6,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: false,
		culturalOrigins: [
			'nat_srivijaya',
			'nat_tui_tonga',
			'nat_hawaii',
			'nat_fiji',
			'nat_chamorro',
			'nat_malagasy',
		],
		minYear: 0,
		maxYear: null,
		notes:
			'Les Austronésiens ont colonisé le Pacifique et Madagascar grâce à la pirogue à balancier.',
	},
	{
		id: 'veh_double_hull_canoe',
		name: 'Pirogue double coque',
		description:
			'Deux coques reliées par une plateforme, capable de transporter des dizaines de personnes en haute mer.',
		domain: 'ocean',
		roles: ['trade', 'war', 'exploration', 'passenger'],
		requiredTechs: ['tech_basic_sailing'],
		cargoCapacity: 30,
		passengerCapacity: 40,
		speedKmPerDay: 100,
		crewRequired: 10,
		buildCost: 60,
		maintenanceCostPerYear: 8,
		combatStrength: 3,
		seaworthiness: 7,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: false,
		culturalOrigins: ['nat_tui_tonga', 'nat_hawaii', 'nat_fiji'],
		minYear: 0,
		maxYear: null,
		notes:
			"Les grandes pirogues doubles polynésiennes transportent familles, bétail et provisions pour la colonisation d'îles.",
	},
	{
		id: 'veh_srivijayan_jong',
		name: 'Jong (navire malais)',
		description:
			"Grand navire marchand d'Asie du Sud-Est, à double mât et coque en bois tropical.",
		domain: 'ocean',
		roles: ['trade', 'war'],
		requiredTechs: ['tech_basic_sailing', 'tech_iron_working'],
		cargoCapacity: 120,
		passengerCapacity: 50,
		speedKmPerDay: 90,
		crewRequired: 30,
		buildCost: 300,
		maintenanceCostPerYear: 25,
		combatStrength: 5,
		seaworthiness: 7,
		allowedTerrains: [],
		oceanCapable: true,
		riverCapable: false,
		culturalOrigins: ['nat_srivijaya'],
		minYear: 500,
		maxYear: null,
		notes:
			'Les jongs de Srivijaya dominent le détroit de Malacca et le commerce des épices.',
	},
	{
		id: 'veh_reed_boat',
		name: 'Bateau de roseaux',
		description:
			"Embarcation en roseaux tressés, utilisée sur les lacs d'altitude et les fleuves tropicaux.",
		domain: 'river',
		roles: ['fishing', 'passenger', 'trade'],
		requiredTechs: [],
		cargoCapacity: 5,
		passengerCapacity: 4,
		speedKmPerDay: 15,
		crewRequired: 1,
		buildCost: 3,
		maintenanceCostPerYear: 2,
		combatStrength: 0,
		seaworthiness: 1,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: ['nat_wari', 'nat_fatimid'],
		minYear: 0,
		maxYear: null,
		notes:
			'Les totoras du lac Titicaca et les felouques du Nil sont en roseaux depuis des millénaires.',
	},
	{
		id: 'veh_felucca',
		name: 'Felouque',
		description:
			'Voilier à voile latine du Nil et de la Méditerranée, maniable et polyvalent.',
		domain: 'coastal',
		roles: ['trade', 'fishing', 'passenger'],
		requiredTechs: ['tech_lateen_sail'],
		cargoCapacity: 15,
		passengerCapacity: 10,
		speedKmPerDay: 60,
		crewRequired: 3,
		buildCost: 40,
		maintenanceCostPerYear: 5,
		combatStrength: 1,
		seaworthiness: 4,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: ['nat_fatimid'],
		minYear: 0,
		maxYear: null,
		notes:
			"La felouque navigue sur le Nil depuis l'Antiquité, profitant du vent du nord et du courant du sud.",
	},
	{
		id: 'veh_umiak',
		name: 'Umiak',
		description:
			"Grande embarcation en peau de morse sur structure de bois, transportant familles entières dans l'Arctique.",
		domain: 'coastal',
		roles: ['passenger', 'trade'],
		requiredTechs: [],
		cargoCapacity: 15,
		passengerCapacity: 15,
		speedKmPerDay: 40,
		crewRequired: 6,
		buildCost: 30,
		maintenanceCostPerYear: 5,
		combatStrength: 0,
		seaworthiness: 5,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: ['nat_thule', 'nat_dorset'],
		minYear: 0,
		maxYear: null,
		notes:
			'L\'umiak est le "bus de la mer" des Inuit, utilisé pour les migrations saisonnières le long des côtes.',
	},
	{
		id: 'veh_kayak',
		name: 'Kayak',
		description:
			'Embarcation fermée en peau de phoque, manœuvrée par un seul pagayeur. Idéale pour la chasse en mer.',
		domain: 'coastal',
		roles: ['fishing', 'courier'],
		requiredTechs: [],
		cargoCapacity: 2,
		passengerCapacity: 1,
		speedKmPerDay: 50,
		crewRequired: 1,
		buildCost: 15,
		maintenanceCostPerYear: 3,
		combatStrength: 0,
		seaworthiness: 6,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: ['nat_thule', 'nat_dorset'],
		minYear: 0,
		maxYear: null,
		notes:
			"Le kayak permet la chasse au phoque et à la baleine dans les eaux glaciales de l'Arctique.",
	},
	{
		id: 'veh_birch_canoe',
		name: "Canot d'écorce de bouleau",
		description:
			"Embarcation légère en écorce de bouleau, portative et idéale pour les portages entre cours d'eau.",
		domain: 'river',
		roles: ['trade', 'passenger', 'fishing'],
		requiredTechs: [],
		cargoCapacity: 8,
		passengerCapacity: 6,
		speedKmPerDay: 40,
		crewRequired: 2,
		buildCost: 10,
		maintenanceCostPerYear: 3,
		combatStrength: 0,
		seaworthiness: 2,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: ['nat_mikmaq', 'nat_beothuk', 'nat_dene'],
		minYear: 0,
		maxYear: null,
		notes:
			"Le canot d'écorce permet de naviguer les réseaux fluviaux immenses d'Amérique du Nord.",
	},
	{
		id: 'veh_war_canoe',
		name: 'Pirogue de guerre',
		description:
			'Grande pirogue pouvant embarquer des dizaines de guerriers pour des raids côtiers ou fluviaux.',
		domain: 'coastal',
		roles: ['war', 'raid'],
		requiredTechs: [],
		cargoCapacity: 10,
		passengerCapacity: 30,
		speedKmPerDay: 50,
		crewRequired: 20,
		buildCost: 40,
		maintenanceCostPerYear: 5,
		combatStrength: 4,
		seaworthiness: 3,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: ['nat_haida', 'nat_fiji', 'nat_papuan'],
		minYear: 0,
		maxYear: null,
		notes:
			'Les pirogues de guerre haida transportent 40 guerriers pour les raids côtiers en Colombie-Britannique.',
	},
	{
		id: 'veh_fishing_boat',
		name: 'Barque de pêche',
		description:
			'Petit bateau côtier à rames ou voile, utilisé pour la pêche quotidienne.',
		domain: 'coastal',
		roles: ['fishing'],
		requiredTechs: [],
		cargoCapacity: 5,
		passengerCapacity: 4,
		speedKmPerDay: 30,
		crewRequired: 2,
		buildCost: 15,
		maintenanceCostPerYear: 3,
		combatStrength: 0,
		seaworthiness: 3,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			'La barque de pêche est universelle — de la Méditerranée aux fjords scandinaves.',
	},
	{
		id: 'veh_galley_war',
		name: 'Galère de guerre',
		description:
			'Navire de combat à rames avec éperon, plateforme de combat et archers embarqués.',
		domain: 'coastal',
		roles: ['war'],
		requiredTechs: ['tech_basic_sailing', 'tech_iron_working'],
		cargoCapacity: 10,
		passengerCapacity: 120,
		speedKmPerDay: 60,
		crewRequired: 100,
		buildCost: 350,
		maintenanceCostPerYear: 40,
		combatStrength: 7,
		seaworthiness: 4,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: ['nat_fatimid', 'nat_cordoba', 'nat_venice'],
		minYear: 0,
		maxYear: null,
		notes:
			"La galère reste le navire de guerre dominant en Méditerranée jusqu'à Lépante (1571).",
	},
	{
		id: 'veh_cog',
		name: 'Cogue (Cog)',
		description:
			'Navire marchand à fond plat, coque à clins, et château arrière. Ancêtre des navires européens.',
		domain: 'coastal',
		roles: ['trade'],
		requiredTechs: ['tech_basic_sailing', 'tech_basic_construction'],
		cargoCapacity: 80,
		passengerCapacity: 20,
		speedKmPerDay: 60,
		crewRequired: 12,
		buildCost: 150,
		maintenanceCostPerYear: 15,
		combatStrength: 3,
		seaworthiness: 5,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: ['nat_hre', 'nat_england', 'nat_denmark'],
		minYear: 900,
		maxYear: 1400,
		notes:
			"La cogue sera le navire-type de la Hanse. En l'an 1000, elle émerge dans les ports de la mer du Nord.",
	},

	// ========================================================================
	// NAVIRES CÉRÉMONIELS
	// ========================================================================
	{
		id: 'veh_royal_barge',
		name: 'Barge royale',
		description:
			"Embarcation d'apparat richement décorée, utilisée pour les processions fluviales et cérémonies.",
		domain: 'river',
		roles: ['ceremony', 'passenger'],
		requiredTechs: ['tech_basic_sailing'],
		cargoCapacity: 5,
		passengerCapacity: 30,
		speedKmPerDay: 30,
		crewRequired: 20,
		buildCost: 300,
		maintenanceCostPerYear: 20,
		combatStrength: 0,
		seaworthiness: 3,
		allowedTerrains: [],
		oceanCapable: false,
		riverCapable: true,
		culturalOrigins: ['nat_song', 'nat_khmer', 'nat_byzantine'],
		minYear: 0,
		maxYear: null,
		notes:
			'Les barges royales du Khmer, de la Chine Song et de Byzance projettent la puissance impériale.',
	},

	// ========================================================================
	// TRANSPORT TERRESTRE — CHARIOTS & VÉHICULES
	// ========================================================================
	{
		id: 'veh_ox_cart',
		name: 'Chariot à bœufs',
		description:
			'Charrette lourde tirée par des bœufs, principale logistique terrestre pour le grain et les matériaux.',
		domain: 'land',
		roles: ['trade'],
		requiredTechs: ['tech_basic_agriculture'],
		cargoCapacity: 30,
		passengerCapacity: 2,
		speedKmPerDay: 15,
		crewRequired: 1,
		buildCost: 20,
		maintenanceCostPerYear: 5,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'steppe', 'hill'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			'Le chariot à bœufs est le camion du Moyen Âge. Lent mais fiable sur les routes pavées.',
	},
	{
		id: 'veh_horse_cart',
		name: 'Chariot à cheval',
		description:
			"Charrette plus rapide tirée par des chevaux, nécessitant le collier d'épaule pour être efficace.",
		domain: 'land',
		roles: ['trade', 'passenger'],
		requiredTechs: ['tech_horse_collar'],
		cargoCapacity: 20,
		passengerCapacity: 4,
		speedKmPerDay: 30,
		crewRequired: 1,
		buildCost: 30,
		maintenanceCostPerYear: 8,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'steppe', 'hill'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			"Le collier d'épaule (tech_horse_collar) multiplie par 4 la force de traction du cheval.",
	},
	{
		id: 'veh_war_chariot',
		name: 'Char de guerre',
		description:
			'Véhicule de combat léger tiré par des chevaux, en déclin mais encore utilisé dans certaines régions.',
		domain: 'land',
		roles: ['war'],
		requiredTechs: ['tech_cavalry'],
		cargoCapacity: 2,
		passengerCapacity: 2,
		speedKmPerDay: 50,
		crewRequired: 2,
		buildCost: 80,
		maintenanceCostPerYear: 15,
		combatStrength: 5,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'steppe'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: 1000,
		notes:
			"Le char de guerre est largement supplanté par la cavalerie lourde en l'an 1000.",
	},
	{
		id: 'veh_siege_tower',
		name: 'Tour de siège',
		description:
			"Tour mobile en bois permettant aux assaillants d'atteindre le sommet des murailles.",
		domain: 'land',
		roles: ['siege'],
		requiredTechs: ['tech_siege_warfare', 'tech_basic_construction'],
		cargoCapacity: 0,
		passengerCapacity: 30,
		speedKmPerDay: 3,
		crewRequired: 20,
		buildCost: 100,
		maintenanceCostPerYear: 0,
		combatStrength: 6,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'hill'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			"Construite sur place lors des sièges, la tour d'assaut est un outil tactique éphémère.",
	},
	{
		id: 'veh_battering_ram',
		name: 'Bélier de siège',
		description:
			'Poutre lourde suspendue sous un abri mobile, utilisée pour enfoncer les portes.',
		domain: 'land',
		roles: ['siege'],
		requiredTechs: ['tech_siege_warfare'],
		cargoCapacity: 0,
		passengerCapacity: 10,
		speedKmPerDay: 3,
		crewRequired: 15,
		buildCost: 50,
		maintenanceCostPerYear: 0,
		combatStrength: 5,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'hill'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			'Le bélier couvert (vinea) protège ses servants des projectiles ennemis.',
	},
	{
		id: 'veh_trebuchet_mobile',
		name: 'Trébuchet mobile',
		description:
			'Engin de siège à contrepoids capable de lancer des projectiles de 100 kg à 300 mètres.',
		domain: 'land',
		roles: ['siege'],
		requiredTechs: ['tech_trebuchet'],
		cargoCapacity: 0,
		passengerCapacity: 0,
		speedKmPerDay: 5,
		crewRequired: 15,
		buildCost: 150,
		maintenanceCostPerYear: 10,
		combatStrength: 8,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'hill'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			'Le trébuchet à contrepoids apparaît au XIIe siècle en Europe, mais des versions à traction existent en Chine depuis le Ve siècle.',
	},

	// ========================================================================
	// TRANSPORT TERRESTRE — BÊTES DE SOMME & CARAVANES
	// ========================================================================
	{
		id: 'veh_horse_rider',
		name: 'Cavalier / Messager à cheval',
		description:
			'Le cheval monté est le moyen de transport rapide par excellence pour les messages et les personnes.',
		domain: 'land',
		roles: ['courier', 'passenger'],
		requiredTechs: ['tech_animal_husbandry'],
		cargoCapacity: 3,
		passengerCapacity: 1,
		speedKmPerDay: 60,
		crewRequired: 1,
		buildCost: 15,
		maintenanceCostPerYear: 10,
		combatStrength: 3,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'steppe', 'hill', 'forest', 'desert'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			'Un cavalier de relais peut couvrir 150 km/jour (système postal mongol, cursus publicus romain).',
	},
	{
		id: 'veh_horse_pack',
		name: 'Cheval de bât',
		description:
			'Cheval chargé de bâts, capable de franchir des terrains impraticables aux chariots.',
		domain: 'pack',
		roles: ['trade'],
		requiredTechs: ['tech_animal_husbandry'],
		cargoCapacity: 10,
		passengerCapacity: 0,
		speedKmPerDay: 25,
		crewRequired: 1,
		buildCost: 12,
		maintenanceCostPerYear: 8,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'steppe', 'hill', 'forest', 'mountain'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			'Le cheval de bât est essentiel sur les sentiers de montagne et dans les forêts denses.',
	},
	{
		id: 'veh_camel_caravan',
		name: 'Caravane de chameaux',
		description:
			'Convoi de dromadaires ou de chameaux de Bactriane, transportant marchandises à travers déserts et steppes.',
		domain: 'pack',
		roles: ['trade'],
		requiredTechs: ['tech_animal_husbandry'],
		cargoCapacity: 150,
		passengerCapacity: 10,
		speedKmPerDay: 30,
		crewRequired: 10,
		buildCost: 80,
		maintenanceCostPerYear: 20,
		combatStrength: 1,
		seaworthiness: 0,
		allowedTerrains: ['desert', 'steppe', 'plain'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [
			'nat_fatimid',
			'nat_ghaznavid',
			'nat_karakhanid',
			'nat_tuareg',
			'nat_ghana',
		],
		minYear: 0,
		maxYear: null,
		notes:
			'La caravane de chameaux est le pilier de la Route de la Soie et des routes transsahariennes.',
	},
	{
		id: 'veh_donkey_pack',
		name: 'Âne de bât',
		description:
			'Animal de somme robuste et économique, adapté aux terrains escarpés.',
		domain: 'pack',
		roles: ['trade'],
		requiredTechs: [],
		cargoCapacity: 6,
		passengerCapacity: 0,
		speedKmPerDay: 20,
		crewRequired: 1,
		buildCost: 5,
		maintenanceCostPerYear: 3,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: [
			'plain',
			'hill',
			'mountain',
			'desert',
			'steppe',
			'forest',
		],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			"L'âne est le compagnon du pauvre. En montagne, il surpasse le cheval en endurance.",
	},
	{
		id: 'veh_llama_caravan',
		name: 'Caravane de lamas',
		description:
			'Convoi de lamas transportant marchandises dans les Andes. Le seul animal de bât des Amériques.',
		domain: 'pack',
		roles: ['trade'],
		requiredTechs: ['tech_animal_husbandry'],
		cargoCapacity: 30,
		passengerCapacity: 0,
		speedKmPerDay: 15,
		crewRequired: 3,
		buildCost: 20,
		maintenanceCostPerYear: 5,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: ['mountain', 'hill', 'plain', 'steppe'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: ['nat_wari', 'nat_chimu'],
		minYear: 0,
		maxYear: null,
		notes:
			"Le lama porte 30 kg à 4000 m d'altitude. Les Andes n'ont pas de roue ni de cheval.",
	},
	{
		id: 'veh_elephant_transport',
		name: 'Éléphant de transport',
		description:
			'Éléphant domestiqué portant un howdah (palanquin), servant au transport de prestige et à la guerre.',
		domain: 'pack',
		roles: ['war', 'ceremony', 'passenger'],
		requiredTechs: ['tech_animal_husbandry'],
		cargoCapacity: 25,
		passengerCapacity: 4,
		speedKmPerDay: 25,
		crewRequired: 2,
		buildCost: 200,
		maintenanceCostPerYear: 30,
		combatStrength: 7,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'forest', 'jungle'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [
			'nat_chola',
			'nat_chalukya',
			'nat_pala',
			'nat_khmer',
			'nat_srivijaya',
		],
		minYear: 0,
		maxYear: null,
		notes:
			"L'éléphant de guerre inspire la terreur. Les Chola et les Khmer en alignent des centaines.",
	},
	{
		id: 'veh_yak_pack',
		name: 'Yack de bât',
		description:
			"Animal d'altitude adapté aux conditions extrêmes du plateau tibétain et de l'Himalaya.",
		domain: 'pack',
		roles: ['trade'],
		requiredTechs: ['tech_animal_husbandry'],
		cargoCapacity: 8,
		passengerCapacity: 0,
		speedKmPerDay: 15,
		crewRequired: 1,
		buildCost: 10,
		maintenanceCostPerYear: 4,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: ['mountain', 'hill', 'steppe', 'tundra'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: ['nat_tibet'],
		minYear: 0,
		maxYear: null,
		notes:
			"Le yack est indispensable sur les cols himalayens à plus de 5000 m d'altitude.",
	},
	{
		id: 'veh_dog_sled',
		name: 'Traîneau à chiens',
		description:
			'Attelage de chiens tirant un traîneau sur la neige et la glace. Transport vital en terres arctiques.',
		domain: 'land',
		roles: ['trade', 'passenger', 'courier'],
		requiredTechs: [],
		cargoCapacity: 10,
		passengerCapacity: 2,
		speedKmPerDay: 40,
		crewRequired: 1,
		buildCost: 15,
		maintenanceCostPerYear: 5,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: ['tundra', 'ice', 'steppe'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: ['nat_thule', 'nat_dorset', 'nat_chukchi', 'nat_sami'],
		minYear: 0,
		maxYear: null,
		notes:
			'Le traîneau à chiens est le seul moyen de transport terrestre efficace dans le Grand Nord.',
	},
	{
		id: 'veh_reindeer_sled',
		name: 'Traîneau à rennes',
		description:
			'Rennes attelés à un traîneau ou montés directement, pour les peuples de la taïga et de la toundra.',
		domain: 'land',
		roles: ['trade', 'passenger'],
		requiredTechs: ['tech_animal_husbandry'],
		cargoCapacity: 8,
		passengerCapacity: 2,
		speedKmPerDay: 35,
		crewRequired: 1,
		buildCost: 12,
		maintenanceCostPerYear: 4,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: ['tundra', 'steppe', 'forest'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: ['nat_sami', 'nat_chukchi'],
		minYear: 0,
		maxYear: null,
		notes:
			'Les Sami et les Tchouktches dépendent du renne pour le transport, la nourriture et le vêtement.',
	},
	{
		id: 'veh_sedan_chair',
		name: 'Palanquin / Litière',
		description:
			"Siège fermé porté par des porteurs, réservé à l'élite et au clergé.",
		domain: 'land',
		roles: ['passenger', 'ceremony'],
		requiredTechs: [],
		cargoCapacity: 1,
		passengerCapacity: 1,
		speedKmPerDay: 15,
		crewRequired: 4,
		buildCost: 30,
		maintenanceCostPerYear: 5,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: ['plain', 'hill', 'forest'],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			"Le palanquin est un symbole de statut social de la Chine à l'Europe en passant par l'Inde.",
	},
	{
		id: 'veh_porter_team',
		name: 'Équipe de porteurs',
		description:
			'Groupe de porteurs humains transportant des charges sur les routes impraticables.',
		domain: 'pack',
		roles: ['trade'],
		requiredTechs: [],
		cargoCapacity: 20,
		passengerCapacity: 0,
		speedKmPerDay: 15,
		crewRequired: 10,
		buildCost: 0,
		maintenanceCostPerYear: 15,
		combatStrength: 0,
		seaworthiness: 0,
		allowedTerrains: [
			'plain',
			'hill',
			'mountain',
			'forest',
			'dense_forest',
			'jungle',
			'swamp',
		],
		oceanCapable: false,
		riverCapable: false,
		culturalOrigins: [],
		minYear: 0,
		maxYear: null,
		notes:
			'En Afrique subsaharienne et en Mésoamérique (sans animaux de bât), les porteurs sont le transport principal.',
	},
]
